### ISSUE TITLE
Getting blocks prior to 2784001

### ISSUE THREAD

**Issue by kardolus** [osmosis-labs/osmosis#1000]
Hi there! 

This is more of a question than an issue. 

I spun up a node the other day using a `default` snapshot from [quicksync.io](https://quicksync.io/osmosis.json). 

However when I try to get an "older" block I get this error:
```
{"error":"height 1000 is not available, lowest height is 2784001"}
```

How can I get all the blocks? I'm looking to index osmosis in full starting at block 1. Do I need to restore an `archive` node instead of a `default`? Do I need to find a different snapshot?

Thanks!

**Comment by faddat** [comment]
That is correct-- you'd restore an archive node, and then you'd start it like:

osmosisd start --pruning nothing

**Comment by kardolus** [comment]
@faddat thank you so much!
