### ISSUE TITLE
"osmosisd start" startup error,why?

### ISSUE THREAD

**Issue by shizhiqiang007** [osmosis-labs/osmosis#1003]
panic: internal

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x25f0828, 0xc000128000}, {0x261dae0, 0xc00015f980}, {{0x0, 0x0}, {0xc0012760d0, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/genutil/gentx.go:113 +0x274
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x25f0828, 0xc000128000}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/genutil/module.go:99 +0x15e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x25f0828, 0xc000128000}, {0x261dae0, 0xc00015f980}, {{0x0, 0x0}, {0xc0012760d0, 0x9}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:310 +0x49d
github.com/osmosis-labs/osmosis/v6/app.(*OsmosisApp).InitChainer(_, {{0x25f0828, 0xc000128000}, {0x261dae0, 0xc00015f980}, {{0x0, 0x0}, {0xc0012760d0, 0x9}, 0x0, ...}, ...}, ...)
        github.com/osmosis-labs/osmosis/v6/app/app.go:490 +0x1d2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000039380, {{0x0, 0xed85ec810, 0x0}, {0xc0012760d0, 0x9}, 0xc0002808c0, {0x3725f40, 0x0, 0x0}, ...})
        github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000219380, {{0x0, 0xed85ec810, 0x0}, {0xc0012760d0, 0x9}, 0xc0002808c0, {0x3725f40, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.15/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xad, {{0x0, 0xed85ec810, 0x0}, {0xc0012760d0, 0x9}, 0xc0002808c0, {0x3725f40, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.15/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1c6e2e6, 0x7}}, {0xc0012760d0, 0x9}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.15/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00f511e20, {0x261ef48, 0xc000df41a0})
        github.com/tendermint/tendermint@v0.34.15/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1c6e2e6, 0x7}}, {0xc0012760d0, 0x9}, 0x1, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.15/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00001adc0, {0x25ca960, 0xc00126dcc0}, 0xc001257e40, {0x25aa520, 0xc0002281e0}, 0x0, 0x0, 0xc001257fa0, {0x25f1708, ...}, ...)
        github.com/tendermint/tendermint@v0.34.15/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x262fcf8, 0xc00002e960}, {0x0, 0x0}, {0x25fa1d0, 0xc001125ab0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/server/start.

**Comment by ValarDragon** [comment]
Looks like your making your own testnet, and you didn't provide a genesis file or gentxs?

**Comment by shizhiqiang007** [comment]
> 看起来你正在制作自己的测试网，但你没有提供 genesis 文件或 gentxs？

I'm trying to join the mainnet by following this tutorial (https://docs.osmosis.zone/developing/network/join-mainnet.html#install-osmosis-binary), but when I run osmosis start I get the following error, as for genesis is the genesis.json downloaded in the tutorial

**Comment by ValarDragon** [comment]
Looks like your trying to start the chain from genesis, but aren't using the genesis version of the software
