### ISSUE TITLE
[Epic] Deployment Automation

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#1014]
## Background

Currently, we do not have auto-deployment enabled. It is useful to have an always running node version of the main branch so that we can be more confident about the reliability of the latest changes. The scope of this epic is to have a node deployed to an ansible configured digital ocean droplet with every update to the main branch. In the future, we can extend this work to allow engineers from the team to auto deploy their branch from their GitHub job.

## Stories

**Story 1**: Auto-deployed node on every commit to the main branch
> As an engineer, I want to have an auto-deployed node on commit to the main branch so that I can always have a running version of the current state.

This can be accomplished with our existing terraform setup and Ansible configuration. To spin up a node with all dependencies installed, we should be able to use the starport setup suggested by Bez.

Resources:
- https://github.com/marketplace/actions/run-ansible-playbook
- https://github.com/osmosis-labs/osmosis-infra
- https://github.com/osmosis-labs/infrastructure
- https://github.com/osmosis-labs/osmosis/issues/1123
   * Startport liveness/e2e test configuration that can be used for starting the node

**Story 2**: Auto-deployed osmosis-monitor on the same node with the node
> As an engineer, I want to have the Promethus + Grafana [osmosis-monitor](https://github.com/osmosis-labs/osmosis-monitor) set up and deployed with the node so that I can effectively analyze the latest changes

**Story 3**: Correctly configured permissions
> As an engineer, I want to make sure that Digital Ocean and GitHub permissions are configured correctly so that I do not delete the main node accidentally while using Digital Ocean

## Future Plans
To be addressed in a future epic:
- Manual Gitlab job from branch to be able to test a branch worked in progress
- Introduce telemetry/observability and alerts

## Acceptance Criteria
- Story 1: Auto-deployed node on every commit to the main branch
- Story 2: Auto-deployed osmosis-monitor on the same droplet with the node
- Evaluate "Future Plans" and create new epic

## Tracked Issues
- https://github.com/osmosis-labs/osmosis/issues/1412

**Comment by daniel-farina** [comment]
@p0mvn & @daniel-farina  to setup meeting to discuss further.

**Comment by p0mvn** [comment]
This epic needs to be groomed more, creating an issue to plan the development process:
- [ ] [Deployment Automation] - create a plan and issues
