### ISSUE TITLE
State Export Init Time

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1023]
When creating state exported testnets, what we at first thought was a Tendermint P2P bug was in reality the new genesis file being initialized prior to creating new blocks. This process instantly maxes 32GB of RAM and goes to swap, which is likely the reason this process takes over an hour. If we can find a way to limit physical memory usage, this process can probably be completed much quicker. To recreate this, simply sync to osmo-test-4 from genesis. After you hit the first block, the initialization process will begin and will not hit further blocks until ~1 hour has passed. 

https://github.com/osmosis-labs/networks/tree/main/osmo-test-4#sync-from-genesis-guide-osmo-test-4

**Comment by daniel-farina** [comment]
@ValarDragon  to add description

**Comment by ValarDragon** [comment]
Closing in favor of #1413
