### ISSUE TITLE
enable more linters

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1024]
While working on the SDK 46 upgrade for wasmd, I've found linters really useful.  I'd like to invert the way we've got that configured now.  (mainly enabled by default instead of disabled)

**Comment by ValarDragon** [comment]
Sweet, would very much appreciate getting more linters! If you want to list out the ones you want to enable here before doing it, we could agree on any we think should be included prior to the bulk of the work needed to doing the switch

**Comment by ValarDragon** [comment]
Closed by subsequent PRs you made!
