### ISSUE TITLE
Bring back release binaries

### ISSUE THREAD

**Issue by mdyring** [osmosis-labs/osmosis#1027]
It would be great to bring back release binaries for the 7.x.x releases.

I realise that arm64 is not supported at present, but I imagine it would be doable to provide amd64 binaries for now?

Building the binaries locally seems fragile at present: 
1. Builds sometimes fail when fetching dependencies.
2. The addition of WASM support seems to have introduced some weirdness in the build process (good old "make build" produces non-working binaries)

Thanks for your consideration.

**Comment by nikever** [comment]
Released binaries introduced again from `v8`.
Closing
