### ISSUE TITLE
backport IAVL to v3.1.0 and v4.2.0

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1044]
**Background**

We would like to backport the fast storage IAVL changes to v3.x and v4.x

Being able to do this is important safety-wise and for future features. We shouldn’t be only relying on a centralized server to download archive nodes all the time.

Basically, these IAVL changes backported would allow us to sync from gen way faster from the first block. It is also important if we want to transition to a different database since we would have to replay the entire state.

**Notes**
- we skip v5.x because it is state-compatible with v6.x.
- we skip v2.x because there was an SDK issue
- we skip v1.x because it is not state-compatible with itself 

**Acceptance  Criteria**
- [ ] #3518
- [ ] #3519

**Comment by faddat** [comment]
Hi, I'm on this, currently working on updating the cosmos sdk stuff needed for it.

**Comment by faddat** [comment]
I am midway through making a rocks archive node automatcially.  Right. now the main holdup is that I haven't automated it yet, pretty sure that with automation it is less than 24h total sync time.

**Comment by ValarDragon** [comment]
Lets close, and target this via IAVL v1
