### ISSUE TITLE
Juno Withdraws do not show up in Kelper Wallet

### ISSUE THREAD

**Issue by DylanCkawalec** [osmosis-labs/osmosis#1047]
this is a small report; 

When withdrawing from Juno on Osmosis, the withdraw lost the funds and do not show up in the Kelper wallet. 
juno180rpvx356ms6snkpyd0ykzjre7y9srq7szgsan

Here's the transaction 

https://www.mintscan.io/juno/txs/1BFF5D16314D750B7C4F0E12FCCE6A0E2B4672C0AD2FA49B19E01BF01164241E

**Comment by mattverse** [comment]
Thanks for submitting this issue! 
Per issues for Keplr connection on Osmosis, please reach out to chadmins in Telegram group or Discord!
