### ISSUE TITLE
Regarding RPC for block & Historical queries

### ISSUE THREAD

**Issue by FeurJak** [osmosis-labs/osmosis#1075]
I'm not 100% sure how I can query a block or get historical data. 

OSMOSIS doc (https://docs.osmosis.zone/developing/structure/transaction.html#retrieving-a-block) states that I can retrieve a block via RPC but there's no given RPC example aside from using the osmosisd client ["osmosisd query block 2836990"]. 

I've checked the gRPC swagger and couldn't find what endpoint I should call to retrieve blocks. 

Also, how do I query for historical data? For example, getting Pool data at block x? I know how to query Pool data but not sure how to specify the block height (if that is possible?).

**Comment by FeurJak** [comment]
Okay looks like I figured out querying blocks. Just needed to use "github.com/cosmos/cosmos-sdk/client/grpc/tmservice". 

Though still not sure about querying for historical data.

**Comment by ValarDragon** [comment]
From the CLI I believe you should be able to use `--height` to achieve this. I don't know how to query old heights from REST, or GRPC, not sure if others do.

`abci_query` allows one to query old heights, but to be honest I don't know how grpc query interacts with abci query.

**Comment by FeurJak** [comment]
@ValarDragon let me know if you want me to forward you an example code. Happy to share.

**Comment by ValarDragon** [comment]
oh interesting, could you please add an example of what you did!

**Comment by FeurJak** [comment]
@ValarDragon  

Make you sure you can access the Tendermint Node (same address as your Osmosis Node, but port: 26657). Update the client.toml Tendermint RPC node to  "tcp://0.0.0.0:26657"  so it's accessible to outside the Host computer.

Then conect to the client: 

`
func InitTenderMintNode(nodeAddr string) (*TenderMintNode, error) {
	cl, err := cosmosClient.NewClientFromNode(nodeAddr)
	if err != nil {
		log.Printf("[InitTenderMintNode] error connecting to Tendermint node %s, err: %s", nodeAddr, err.Error())
		return nil, err
	}
	log.Println("[InitTenderMintNode] Successfully connected to Tendermint Node at Addr: ", nodeAddr)
	client := TenderMintNode{client: cl}
	err = client.startSubscriber() // Start Subscriber
	if err != nil {
		log.Printf("[InitTenderMintNode] subscriber error addr: %s, err: %s", nodeAddr, err.Error())
		return nil, err
	}
	return &client, nil
}
`

And then you can query for a block or many blocks: 
`
func (cl *TenderMintNode) TxSearch(ctx context.Context, query string, prove bool, page *int, perPage *int, orderBy string) (*ctypes.ResultTxSearch, error) {
	_res, err := cl.client.TxSearch(context.Background(), query, prove, page, perPage, orderBy)
	if err != nil {
		log.Println("[Tx] Unable to query Tx, err: ", err)
		return nil, err
	}
	return _res, nil
}
`

Example :

`
_query := fmt.Sprintf("tx.height=%d", _startAt) // default query
_results, err := b.AppClient.GetTenderMintNode().TxSearch(b.AppClient.GetAppCtx(), _query, false, nil, nil, "")
`
