### ISSUE TITLE
Broken query for `x/superfluid` total_superfluid_delegations

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1080]
Current superfluid module does not delete intermediary accounts that are not being used(intermediary accounts without any delegations for superfluid).

Meanwhile, https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/keeper/grpc_query.go#L290-L319 `TotalSuperfluidDelegations` iterate through all intermediary accounts, and omits and error if there aren't delegations for the intermediary account. 

Quick fix I propose: simply do not omit an error if delegation not found and pass, we might want further discussions on if we want to keep intermediary accounts or not in the future

**Comment by ValarDragon** [comment]
The proposed quick fix sounds great to me!

We'll have to think through edge cases around rounding before we can delete the intermediate account entirely in a future state machine change
