### ISSUE TITLE
GetRewardEst iterates all over the locked tokens

### ISSUE THREAD

**Issue by mconcat** [osmosis-labs/osmosis#109]
`GetRewardsEst`(which is called in `RewardsEst` grpc query) calls `FilteredLocksDistributionEst`, which iterates all over the locked tokens(https://github.com/osmosis-labs/osmosis/blob/main/x/incentives/keeper/pot.go#L164). This causes issues on performance side, as it need to recalculate the reward every time when the query happens.

The suggested solution is limit the lockup period to the epoch, and make the lockup module updates the total amount when there is lock related event happens. The incentive module will read the cached state when queried. 

ref @Thunnini

**Comment by ValarDragon** [comment]
`GetRewardsEst` is for a single address, so we should be able to determine the rewards for that address without iterating over all locks. We just need to get the locks associated with that address, and the total amount of shares for each pot that the lock contributes to. Then we can calculate the reward going to that address

**Comment by mconcat** [comment]
Adding a lock reference for the owner address and adding total share for a pot(which is updated by lock hook) would work.
