### ISSUE TITLE
Authz doesn't work with some osmosis-specific messages

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#1093]
## Summary of Bug

Trying to grant a generic authorization via authz doesn't work for `/osmosis.lockup.MsgLockTokens`. Other messages may potentially be affected as well.

## Version

Current Production (osmosisd 7.0.3)

## Steps to Reproduce

`export $granter=osmo...`
`export $grantee=osmo...`

The following auth grant tx works:
`osmosisd tx authz grant $granter generic --msg-type=/osmosis.gamm.v1beta1.MsgJoinSwapExternAmountIn --from=$grantee`

The following fails:
`osmosisd tx authz grant $granter generic --msg-type=/osmosis.lockup.MsgLockTokens --from=$grantee`

An example of the failing transaction can be seen in https://www.mintscan.io/osmosis/txs/C407AA9A2631A6A159EDA5632F761A096DCBC8ABDDF0AC2CF0257B2C6D81D718

The grenerated transaction (with the addresses redacted) is:

```
{"body":{"messages":[{"@type":"/cosmos.authz.v1beta1.MsgGrant","granter":"osmo...","grantee":"osmo...","grant":{"authorization":{"@type":"/cosmos.authz.v1beta1.GenericAuthorization","msg":"/osmosis.lockup.MsgLockTokens"},"expiration":"2023-03-13T19:21:27Z"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"350000","payer":"","granter":""}},"signatures":[]}
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ValarDragon** [comment]
Ah I found the bug

All of our modules have to register a message server. Here is how its done for staking: https://github.com/osmosis-labs/cosmos-sdk/blob/v0.45.0x-osmo-v7/x/staking/module.go#L138

Here is where its not done for lockup (and presumably more of our modules): https://github.com/osmosis-labs/osmosis/blob/main/x/lockup/module.go#L144

**Comment by george-aj** [comment]
FYI "/osmosis.superfluid.MsgLockAndSuperfluidDelegate" also doesn't work, producing the exact same error.

**Comment by ValarDragon** [comment]
Lockup module, superfluid module and creating gauges won't work at the moment.

Amm swaps and LP'ing should work right now

Should get fixed in v8, not much we can do to get it fixed until then unfortunately :(

**Comment by Vinitowinit** [comment]
If this gets fixed in v8, what is the timeline then? 2-4 weeks. Is this just another sprint?

**Comment by ValarDragon** [comment]
v8's targetted to get on chain first week of April at the moment. The big goal is:
* Stability improvements to Superfluid
* larger refactor of the AMM module
* Stableswap
* Further IAVL stability

And then bug fixes. (The PR I just opened should fix this on main, v8 is just the next upgrade on chain that'll happen)

**Comment by nicolaslara** [comment]
Thanks for the quick fix!

**Comment by giansalex** [comment]
fyi. 
This issue also affects cosmwasm.

**Comment by Vinitowinit** [comment]
Why does this matter if it affects cosmwasm? Does this delay the fix?

**Comment by ValarDragon** [comment]
Not yet unfortunately, mainnet upgrade hasn't happened yet

**Comment by ValarDragon** [comment]
Yeah I think you can plan for it landing by then. The v8 release is still under development unfortunately, but its written in that erlease

**Comment by Vinitowinit** [comment]
Thanks that is helpful. Last question, how do you track the v8 release and whether it is deployed or not? Is there some place to check this? The v8 is huge. Includes your stableswap, superfluid stability, and new AMM module lol... that is a lot

**Comment by ValarDragon** [comment]
You can track progress here! #1141 

We;re working on keeping that more up to date. The signal for it being ready is going to be governance proposal on Osmosis + github releases, etc
