### ISSUE TITLE
Sync full node failed! How to solve？

### ISSUE THREAD

**Issue by shizhiqiang007** [osmosis-labs/osmosis#1096]
erro info:
Error: error during handshake: error on replay: wrong Block.Header.AppHash. Expected 5E4C28EE6A4A55F6377DB9F768A7F9E67AF4C3ACCE245186235CD89A03E61F37, got AA57874C0A7F6F8CE5F4CB2237087E6293419D485697E4015124BF1C45654C2B

**Comment by ValarDragon** [comment]
I think you have to retry the sync :/ 

I ran into this issue last night as well. Were working trying to figure out the root cause. cref #1090
