### ISSUE TITLE
Tracking issue: Crashes

### ISSUE THREAD

**Issue by leezijie** [osmosis-labs/osmosis#1097]
Why are nodes so unstable and crash every few days.

**Comment by ValarDragon** [comment]
Theres some concurrency bug with the IAVL speedup changes we did. We're trying to figure out where the latest one is coming from :/

Heres the tracking issue #1016

**Comment by leezijie** [comment]
> Theres some concurrency bug with the IAVL speedup changes we did. We're trying to figure out where the latest one is coming from :/
> 
> Heres the tracking issue #1016 , and mostly like the one your running into #1090

Yes, I've been updating to the latest version recently, but it still crashes. I hope it can be solved as soon as possible.Thanks.

**Comment by faddat** [comment]
I had a silent crash on my validator today.  v7.0.4

now upgraded to v7.1.0

**Comment by faddat** [comment]
closing since we have a tracking issue
