### ISSUE TITLE
Synchronizing the full node, the hard fork of 712000 has the following error, how to solve it, my osmosis version is 1.0.1

### ISSUE THREAD

**Issue by shizhiqiang007** [osmosis-labs/osmosis#1119]
6:43AM INF ABCI Replay Blocks appHeight=712000 module=consensus stateHeight=712000 storeHeight=712001
6:43AM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 5E4C28EE6A4A55F6377DB9F768A7F9E67AF4C3ACCE245186235CD89A03E61F37, got AA57874C0A7F6F8CE5F4CB2237087E6293419D485697E4015124BF1C45654C2B

**Comment by czarcas7ic** [comment]
If you are syncing from genesis, you actually need to start with v3.1.0. If you use the installer at https://get.osmosis.zone, it predownloads the proper binaries for you so you don't run into this issue. 

With that being said, depending on what you are trying to do you probably dont need to sync from genesis and can probably get away with downloading a snapshot instead.

**Comment by shizhiqiang007** [comment]
Thank you for your answer， The version has been updated to 3.1.0, but another error was reported when updating to block 450000, “Error: failed to initialize database: file missing”

**Comment by shizhiqiang007** [comment]
> If you are syncing from genesis, you actually need to start with v3.1.0. If you use the installer at https://get.osmosis.zone, it predownloads the proper binaries for you so you don't run into this issue.
> 
> With that being said, depending on what you are trying to do you probably dont need to sync from genesis and can probably get away with downloading a snapshot instead.
Thank you for your answer， The version has been updated to 3.1.0, but another error was reported when updating to block 450000, “Error: failed to initialize database: file missing”

**Comment by alexanderbez** [comment]
> Thank you for your answer， The version has been updated to 3.1.0, but another error was reported when updating to block 450000, “Error: failed to initialize database: file missing”

Sounds like your environment is corrupted. I'd suggest just starting from scratch if you haven't done so already 👍

**Comment by ValarDragon** [comment]
Going to go ahead and close this. Can you retry using the installer from get.osmosis.zone, which has cosmovisor configured for syncing from genesis?
