### ISSUE TITLE
Auto-swap non-osmo tx fees to osmo

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1121]
Currently when a transaction fee is paid in a valid non-OSMO token, the token is collected and distributed as-is to stakers. While this doesn't affect the core user flow since gas fees are zero for the time being anyway, it causes confusing UX around claiming staking rewards (since epochs with too many additional denoms used as tx fees breach the auto set gas limit on Keplr) and dust for random denoms showing up in wallets. The goal of this change would be to implement the following logic:

- For osmo, do whatever it currently does (send to distribution module)
- For not osmo, send to a module account $FOO in txfees module
- On epoch, auto-swap the funds in module account $FOO and distribute that osmo to stakers.

More specifically, one relatively clean way of implementing this would be to take the following steps:

1. Create a second module account in the TxFees module to send non-OSMO fee tokens to
2. Add a check in the DeductFees function (sends tokens from fee payer to module account) that checks if the paid fee denom is OSMO and if not, make sure they are supported on the DEX (with enough liquidity) and send the tokens to the second module account
3. At the end of each epoch, iterate through all the denoms in the second module account, swapping each into OSMO and then transferring the total amount to the first module account to be distributed like normal

**Comment by ValarDragon** [comment]
- [ ] Move DeductFeesAnteHandler code into txfeeskeeper
- [ ] Make new module account in txfees
- [ ] Send all non-native fee coins to that module account

- [ ] On epoch code, swap all non-native tx fees in that module to osmo, move that osmo to distribution for staking rewards

- [ ] Upstream the deduct fees keeper (no swap code) to mainline SDK to fix their gas problems

**Comment by danwt** [comment]
Hi,

I was just wondering why the epoch part of this is important? Would it still be important even if the fees were not distributed to stakers?

Thanks a lot

**Comment by czarcas7ic** [comment]
Its run at epoch in order for the fees that got transformed into osmo to the be distributed. It could happen at faster or slower intervals, but just makes sense to run at epoch prior to distribution.

**Comment by danwt** [comment]
Thanks @czarcas7ic I understand it needs to be transformed into osmo, but I was just curious why the need to do this at epoch and not on the fly? thanks!

**Comment by AlpinYukseloglu** [comment]
> Thanks @czarcas7ic I understand it needs to be transformed into osmo, but I was just curious why the need to do this at epoch and not on the fly? thanks!

The main reason is gas efficiency for users. If every transaction included an additional swap to settle fees, users would have to pay much more in gas to compensate. This approach amortizes the cost across many users.

Keep in mind that it would be fully secure even if we never swapped to OSMO, so there's no security risk with this parameter. Doing this at epoch just happened to be both very effective and very convenient.

**Comment by danwt** [comment]
Ok thanks!
