### ISSUE TITLE
proposal: use starport for CI liveness tests

### ISSUE THREAD

**Issue by alexanderbez** [osmosis-labs/osmosis#1123]
I propose we use starport to test basic liveness of osmosis instead of the current docker-compose approach. Unless there is a strong reason to use docker-compose along with all the ad-hoc tooling and scripting needed for it to work, I think Starport is much cleaner approach, requiring only a single file and make target.

If there is consensus on this, I'll be happy to tackle it.

**Comment by ValarDragon** [comment]
I haven't really worked with starport for this. Do you have any links for the liveness tests using Starport? (Also @daniel-farina have you looked into starport for this before?)

**Comment by alexanderbez** [comment]
Yes, it's very simple!

1. Just define a config file ([example](https://github.com/umee-network/umee/blob/main/starport.ci.yml))
2. Have GH actions run the job ([example](https://github.com/umee-network/umee/blob/main/.github/workflows/tests.yml#L98-L125)

That's it :)

**Comment by ValarDragon** [comment]
Oh cool, this is for single chain liveness tests. Sounds great to me!

**Comment by alexanderbez** [comment]
Yeah, I think they compliment each other. In fact, I often use the liveness test framework for quick iterative and rapid testing.

e.g

1. start network
2. query API/CLI
3. make changes (starport automatically rebuilds)

**Comment by ValarDragon** [comment]
Oh sweet, sounds great to me!
