### ISSUE TITLE
proposal: introduce an e2e test suite

### ISSUE THREAD

**Issue by alexanderbez** [osmosis-labs/osmosis#1124]
I propose we introduce a programatic e2e integration test suite that allows us to test functionality from the most basic operations like IBC transfers and native sends, to AMM operations.

Examples of this can be found here:

- https://github.com/cosmos/gaia/tree/main/tests/e2e
- https://github.com/umee-network/umee/tree/main/tests/e2e

If there is consensus on this, I'll be happy to tackle it or guide others on the approach used :)

**Comment by ValarDragon** [comment]
This sounds awesome! Its something @nikever @czarcas7ic and @daniel-farina have been looking into

I think we should be really happy to use something that already exists! Is there some docs for how these end to end tests work? (Like how end-to-end are they? Is it starting a single node testnet, and then posting txs & running queries to it?)

**Comment by alexanderbez** [comment]
Yeah, so in each implementation I've done, there is a `doc.go` that outlines what's going on, but I never spent that much time on that file/doc, but we totally could make it very elaborate.

The basic gist of it is:

- Setup data and files (in tmp dirs)
- Build and/or pull docker images (via dockertest)
- Run containers (via dockertest)
- Write your tests in Go! You have access to all gRPC, API and RPC endpoints.

**Comment by ValarDragon** [comment]
Ah sweet, just checked the file! This sounds awesome, it even does IBC tests. I think we should totally use this

**Comment by daniel-farina** [comment]
@czarcas7ic to investigate further with @alexanderbez.
