### ISSUE TITLE
Balancer: Consider storing normalized pool weight in state

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1131]
At the moment, balancer pools store an unnormalized weight for every asset, and re-computes the normalized weight on ~every action.

We should consider storing the normalized weight for each pool asset. At the moment, this would look like the following field going in PoolAsset, but the abstraction for how weights are handled should improve in the future as well.

```
  // Weight that is normalized s.t. the sum of all pool assets' weights
  // equals 1. If the user provides this value, it is ignored. This should only
  // ever be set by the state machine. This is left as a TODO for a future PR.
  // string normalizedWeight = 3 [
  //  (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
  //  (gogoproto.moretags) = "yaml:\"normalized_weight\"",
  //  (gogoproto.nullable) = true
  // ];
```

**Comment by p0mvn** [comment]
The changes in #1343 helped us see that there aren't many cases where normalized weights are needed. Therefore, decided not to pursue this change
