### ISSUE TITLE
Make every module use apptesting for its test suites

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1148]
We made the apptesting helper package, so we dont have modules re-implementing each others test scaffolding. We need to propogate this change to all of our existing modules.

Right now its being a painpoint for a lot of the GAMM updates I'm working on. (Modules like pool-incentives & txfees have copy paste methods of setup code from gamm)

**Comment by catShaark** [comment]
so there's differences between each module's `KeeperTestSuite`, for example some modules use `keeper.Querier` for grpc query test, while some others use `types.queryClient` for grpc query test. Should we have a standard for `KeeperTestSuite` that every modules has to follow.
