### ISSUE TITLE
Sync full node ,Error: failed to initialize database: file missing

### ISSUE THREAD

**Issue by shizhiqiang007** [osmosis-labs/osmosis#1152]
Sync full node ,Error: failed to initialize database: file missing

**Comment by ValarDragon** [comment]
This needs far more info

**Comment by shizhiqiang007** [comment]
> This needs far more info

When I upgraded from osmosis 1.0.3 to 3.1.0 to synchronize the full node to a height of 450,000 blocks, I only saw this error reported. Is there any way to see the detailed error?


root@datalake:~# osmosisd start
1:33AM INF starting ABCI with Tendermint
Error: failed to initialize database: file missing
