### ISSUE TITLE
got Issues when start a new node from state-sync 

### ISSUE THREAD

**Issue by liangping** [osmosis-labs/osmosis#1159]
```
11:51AM INF Found local state with non-zero height, skipping state sync
11:51AM INF ABCI Handshake App Info hash="��\x15�\x10K\v���#\x11\x1b�^ͬ���LoTK���E�)2�" height=3755000 module=consensus protocol-version=0 software-version=7.0.4
11:51AM INF ABCI Replay Blocks appHeight=3755000 module=consensus stateHeight=3755000 storeHeight=3755001
11:51AM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.Version. Expected {11 0}, got {11 1}
```
version:  7.0.4

**Comment by faddat** [comment]
The bad thing is This means that you are getting further than me.

If you are getting the above result then you should use the script in the scripts folder and that will use a modified version of tendermint to correctly set the app version

**Comment by liangping** [comment]
I tried that as well.

**Comment by faddat** [comment]
@liangping did the script work?

It no longer works for me :cry:

**Comment by liangping** [comment]
I tried yesterday. It works

**Comment by liangping** [comment]
Sorry, I did NOT use that script.  the approach is:

-  state-sync normally. you will halt after it's done, because of the block version.
-  clone tendermint patch.  run it manully.

**Comment by ValarDragon** [comment]
Closing in favor of #1805
