### ISSUE TITLE
Update max_age_num_blocks to reflect Osmosis bonding period

### ISSUE THREAD

**Issue by moniya12** [osmosis-labs/osmosis#1160]
Osmosis has 14 days bonding period and so genesis should only force 14 days of data when validators/nodes enable pruning. When pruning is enabled, minimum height to retain is calculated based on multiple configurations but can never go above max_age_num_blocks defined in genesis. 

In Osmosis genesis forces 30 days of blocks, as max_age_num_blocks is set to 403200. While max_age_duration is set to 14 days (1209600000000000 nanoseconds). Due to configuration (max_age_num_blocks), our state.db and blockstore.db holds 30 days of data even when we are pruning. 

Configuration should be updated to 186092. 

@ValarDragon Can you please take care of this in next release?

**Comment by alexanderbez** [comment]
I believe `max_age_num_blocks` is related to evidence and indeed it should generally line up with the unbonding period. However, this is an on-chain parameter so to change it, it'd have to go through governance, either by a param change proposal or via the next chain upgrade.

**Comment by moniya12** [comment]
@alexanderbez Thanks for the response. Yes, max_age_num_blocks are part of evidence and we don't want people updating them without param change proposal. 

As our bonding period is 14 days we should be able to change it via param change or as you said in next chain upgrade. 

As TM will never prune anything within max_age_num_blocks we are carrying 16 days of extra data today (in pruned nodes).

**Comment by alexanderbez** [comment]
Yup, makes sense. Idk when we plan on the next v8 upgrade (cc @ValarDragon), but if it's pretty far out, I say we just submit a `ParamChangeProposal`.

**Comment by ValarDragon** [comment]
Thanks for finding this! 

I'm supportive of doing this change, and doing it as one component in the v8 release. Its targetted to ideally get proposed on chain April 8th ish.
