### ISSUE TITLE
Make superfluid staking stakers get direct governance votes

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1161]
To give SFS stakers direct voting power in votes, we need to pass in the superfluid staking keeper as the staking keeper to the governance keeper.

The governance keeper requires the following methods defined in order to be a staking keeper: https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/types/expected_keepers.go#L16-L27
```golang
	IterateBondedValidatorsByPower(
		sdk.Context, func(index int64, validator stakingtypes.ValidatorI) (stop bool),
	)
	TotalBondedTokens(sdk.Context) sdk.Int // total bonded tokens within the validator set
	IterateDelegations(
		ctx sdk.Context, delegator sdk.AccAddress,
		fn func(index int64, delegation stakingtypes.DelegationI) (stop bool),
	)
```

So we should add a staking_keeper.go file in `x/superfluid/keeper/` and add these three methods. `IterateBondedValidatorsByPower` and `TotalBondedTokens` can just return data from the underlying staking keeper.

IterateDelegations needs to basically just return the staking keepers delegations and then construct delegations from the existing superfluid delegations from this address.  Looking at the [Tally code](https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/keeper/tally.go#L51) it appears that it should be fine to return multiple delegation structs for each validator, making this even simpler to integrate.

We should make golang tests for this, by making a validator vote, a superfluid delegator override it, and see that it works.

**Comment by mconcat** [comment]
How are the stakingkeeper and superfluidkeeper combined inside the gov module? Is there already a feature for merging multiple staking keepers?
