### ISSUE TITLE
Communicating with integrators to ensure they still work over the GAMM refactor

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1165]

**Comment by czarcas7ic** [comment]
Posted in integrators channel in Discord with instructions on how to connect to the new temporary testnet based off main as of yesterday. Will continue to follow up with current integrators to ensure they are aware of the breaking changes.

**Comment by czarcas7ic** [comment]
Utilized localosmosis to give integrators a v9 testnet to test on. No issues heard for the last couple of weeks.
