### ISSUE TITLE
use Quicksync , ERR WARNING: Attempt to allocate proposer rewards to unknown proposer

### ISSUE THREAD

**Issue by shizhiqiang007** [osmosis-labs/osmosis#1171]
ERR WARNING: Attempt to allocate proposer rewards to unknown proposer osmovalcons1upk6m66p8q54trmuj5eel7mpfxw95xaerwyxsy. This should happen only if the proposer unbonded completely within a single block, which generally should not happen except in exceptional circumstances (or fuzz testing). We recommend you investigate immediately. module=x/distribution
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by alexanderbez** [comment]
What block did this happen on? Is this on mainnet? Could you provide more info?

**Comment by ValarDragon** [comment]
This is likely some sort of db corruption? Can you retry your node with v7.1.0, we believe most db corruptions are sorted out on that release.
