### ISSUE TITLE
[x/gamm][Misc improvements] Msg defined twice in different proto files

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/osmosis#1185]
I'm working on a workflow to produce TS definitions and using `protoc` to generate them. In this process, I'm getting an error 

```
osmosis/gamm/v1beta1/tx.proto:9:9: "osmosis.gamm.v1beta1.Msg" is already defined in file "osmosis/gamm/pool-models/balancer/tx.proto".
```

https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/pool-models/balancer/tx.proto#L9

https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/tx.proto#L9

Seems that the `Msg` identifier is being used twice. Maybe not an issue in go, but in generating via `ts-proto` it seems to not be happy.

**Comment by pyramation** [comment]
for more context, here is the command I'm running in the repo w all protobufs: https://github.com/pyramation/osmosis-protobufs/blob/master/bin/run-proto.sh

**Comment by pyramation** [comment]
I saw the progress on the PR and tested out the protoc gen — the current PR works  🙌🏻

**Comment by ValarDragon** [comment]
Matt had a good point: https://github.com/osmosis-labs/osmosis/pull/1208#discussion_r843559703

We should change the txs to be defined under the correct package, and just leave the balancer pool defined under the wrong proto package (which won't cause conflicts)

**Comment by pyramation** [comment]
great, I like the idea of `osmosis.gamm.pool-models.BalacerMsg` or a path that makes sense 🙌🏻
