### ISSUE TITLE
x/gamm: JoinSwapExactAmountIn/ExitSwapShareAmountIn Share Inconsistency Investigation

### ISSUE THREAD

**Issue by alexanderbez** [osmosis-labs/osmosis#1196]
The `TestJoinSwapExactAmountInConsistency` test has a case there is an expected number of resulting "out" amount number of tokens returned from `ExitSwapShareAmountIn` after calling `JoinSwapExactAmountIn`. The current theory is the swap fee is being applied incorrectly and that the no-swap variants of these calls should be tried out to test this theory and further understand why this is happening.

ref: https://github.com/osmosis-labs/osmosis/pull/1174

cc @ValarDragon

**Comment by p0mvn** [comment]
I will try to investigate this. Should help me understand gamm better
