### ISSUE TITLE
enable markdown linter

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1210]
Context

nit: we should have a markdown liner enabled 

```suggestion

* [#1203](https://github.com/osmosis-labs/osmosis/pull/1203) cleanup Makefile and ci workflows
```

_Originally posted by @alexanderbez in https://github.com/osmosis-labs/osmosis/pull/1203#discussion_r844068886_

**Acceptance Criteria**
- markdown linter is enabled and runs on all READMEs

**Comment by alexanderbez** [comment]
For reference, see what I did for Umee:

- Config: https://github.com/umee-network/umee/blob/main/.markdownlint.yml (we can add rules others to disable if we want)
- GH action job: https://github.com/umee-network/umee/blob/main/.github/workflows/lint.yml#L27-L43

**Comment by ValarDragon** [comment]
Here was the old issue I had lol: https://github.com/osmosis-labs/osmosis/issues/88

If people want to retry it, I'm happy to do so. But its definitely the sort of thing I don't think we should feel too attached to / isn't really that helpful.

I think the only ones I found helpful before were `links`. I found the newlines after header, and line length ones really cumbersome to fight against personally.

**Comment by p0mvn** [comment]
Drafted out a PR with this in #1317 to see how this works

Tried running the linter and there were hundreds, maybe thousands of issues. Unfortunately, the linter doesn't auto-fix them all. After auto-fix, it still seems like a few hours worth of work to fix them all manually.

One thing I also noted is that it would require further customization. For example, it complains about having headings with the same name in CHANGELOG

What is the consensus on this? Should I keep working? I would like to make sure that the team wants this before I spend time

Personally, I'm in support of encouraging consistency across the codebase but not sure if it's worth the time effort

**Comment by ValarDragon** [comment]
The only markdown lints I've found useful in the past limiting line lengths to 120 characters, and reminders for correct link syntax. I've otherwise found every other one counter-helpful.

I'm happy to adapt if other people want to use it, I'm generally not enthused about them though
