### ISSUE TITLE
Add PokePool function to AMM interface

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1213]
Copied from a slack discussion:

I have a feeling the AMM refactor broke LBP's, by not calling PokeTokenPoolWeights on GetPool . Our tests didn't catch this, because at the moment they call Poke directly, whereas they should call it from GetPool on the keeper method

Theres two ways that come to my mind for how to fix this:
* Add pool.PokeTokenWeights at the beginning of every pool interface function in balancer.go
* Add a PokePool function in the pool interface, that then gets called in keeper.GetPool()

I like the second approach better, what do others think? The first seems more brittle,

@mconcat : PokePool is equivalent with getting the newest version of the pool, so second makes more sense

@alexanderbez : I like the 2nd option too

**Comment by alexanderbez** [comment]
@ValarDragon can I pick this up?

**Comment by ValarDragon** [comment]
Sure!
