### ISSUE TITLE
port bytes size iavl cache to v6.x to mitigate RAM issues

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1239]
**Background**

There are RAM issues on v6.x with rocks db. It is likely to be caused by iavl fast storage. Once [this PR](https://github.com/osmosis-labs/iavl/pull/40) is merged, it should be backported to v6.x.

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/issues/1140#issuecomment-1096782206_

**Acceptance Criteria**
- bytes size cache is backported to `v6.x`

**Comment by faddat** [comment]
sir, you have your ear close to the metal, and thank you.

I'd meant to open just this issue.

**Comment by ValarDragon** [comment]
Closing for now, only affects archive nodes and there are better ideas to do now (e.g. IAVL v1)
