### ISSUE TITLE
Make CI for testing generated proto correctness

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1256]
We should have a CI job that does `make proto-all`,and returns an error if there is a diff betrween the post `make proto-all` output, and any `.proto` or `.pb.go` file. This will help us catch whenever make proto-all wasn't ran

**Comment by alexanderbez** [comment]
Great idea!

**Comment by catShaark** [comment]
so we should check if .proto files is different, if so .pb.go files must be also different right

**Comment by ValarDragon** [comment]
We need to check differences in both `.pb.go` files, and `.proto` files

**Comment by ValarDragon** [comment]
Someone want to see if we can just copy what Tendermint's workflow here is: https://github.com/tendermint/tendermint/blob/mjf/unsocketing/.github/workflows/check-generated.yml

**Comment by xBalbinus** [comment]
May be closed by [#1892](https://github.com/osmosis-labs/osmosis/pull/1892)
