### ISSUE TITLE
Why can't I use RPC to query historical block data for data synchronized with snapshots?

### ISSUE THREAD

**Issue by shizhiqiang007** [osmosis-labs/osmosis#1258]
Why can't I use RPC to query historical block data for data synchronized with snapshots?

**Comment by faddat** [comment]
Most of the snapshots are "state synced" -- this means that they contain the tip of the blockchain only.  

If you want the whole thing, you'll need the 3.1tb archive image, available here:

https://quicksync.io/networks/osmosis.html
