### ISSUE TITLE
enrich existing PR template to smooth the review process

### ISSUE THREAD

**Issue by jlbit** [osmosis-labs/osmosis#1261]
As discussed with @ValarDragon, currently Osmosis's existing [pr template](https://github.com/osmosis-labs/osmosis/blob/main/.github/pull_request_template.md) is a bit over simplified with only "Description" field required.

I'd like propose adding a bit more templating to help smooth the review process, as well as fostering a engineering habit of emphasizing documentations, e.g. when a new feature released or user-facing behavior changed, PR submitters should always keep in mind updating the docs at the same time in https://github.com/osmosis-labs/docs.

**Comment by jblbit** [comment]
on the other hand, the template should not be overcomplicated like the one in cosmos SDK, which has too many checkboxes that makes it unreadable and thus no one taking it seriously anymore

**Comment by jblbit** [comment]
this should be a very similar one to which I proposed in osmosis's doc repo https://github.com/osmosis-labs/docs/pull/68
