### ISSUE TITLE
add CONTRIBUTING.md rather than using gaia's

### ISSUE THREAD

**Issue by jlbit** [osmosis-labs/osmosis#1263]
currently [Osmosis' PR request template](https://github.com/osmosis-labs/osmosis/blame/main/.github/pull_request_template.md#L20) is referencing the [branching model in gaia](https://github.com/osmosis-labs/osmosis/blame/main/.github/pull_request_template.md#L20) rather than having its own one, which seems a bit strange.

We can add a branching model page in Osmosis by borrowing gaia's content, and point our pr template to use the new one.

**Comment by alexanderbez** [comment]
Yes, this is much needed. Thank you so much! While we're at it, it should really be simplified.

**Comment by daniel-farina** [comment]
- If this is a feature request, please use the feature-request repo (with a link to it)
- Delete as much text as possible
- Try to make it so that instructions fit within the textbox when you open an issue, avoid infinite scrolling of instructions :smile:

Thank you so much for working on this!

**Comment by jlbit** [comment]
@daniel-farina do you actually mean to leave this comment under https://github.com/osmosis-labs/osmosis/issues/1339 ?

**Comment by ValarDragon** [comment]
Why was this closed? Theres no contributing.md here

**Comment by xBalbinus** [comment]
Oh shoot my bad I thought the contributing.md was created with the other PR. I'll finish this today with a PR.

**Comment by xBalbinus** [comment]
https://github.com/osmosis-labs/docs/pull/107 This should fix the contributing.md request - we put contributing.md for the chain repo onto the docs, let me know @ValarDragon if you think we should also include a contributing.md on the chain repo.

**Comment by ValarDragon** [comment]
It should absolutely be in the chain dev repo
