### ISSUE TITLE
Improve help command examples for CLI to show required flags

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#127]
Currently just says `osmosisd tx lockup lock-tokens [flags]`

Should have examples of required flags

**Comment by ValarDragon** [comment]
Lets get a lot of @czarcas7ic work in documentation to propogate into updating CLI flags.

**Comment by czarcas7ic** [comment]
@ValarDragon Once I complete all the module docs I can create a specified list of which commands did not have examples of required flags in the CLI

**Comment by ValarDragon** [comment]
TYSM, that'd be amazing 🙏
