### ISSUE TITLE
Stableswap: Createpool logic

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1276]
We need to add CreatePool logic to the gamm keeper for stableswap. This has a few steps:
- [x] Implement the msg.CreatePool logic https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/pool-models/stableswap/msgs.go#L86-L88 , see Balancer logic for an example of how to do it
- [x] Add a new function to the message server, similar to https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/msg_server.go#L34-L37
- [x] Add stableswap to relevant register functions here; https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/module.go

**Comment by alexanderbez** [comment]
@ValarDragon are you going to add a description to the issue? :)

**Comment by ValarDragon** [comment]
Thanks for the reminder! This came up during a call today, forgot to come back and add descriptions
