### ISSUE TITLE
Remove gofumpt

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1309]
Gofumpt doesn't have fix-on-save integration with the golang language server `pls` as far as I can tell. This makes formatting workflows for gofumpt annoying in many editors and acts as an extra hurdle for newer contributors. I'm locally mitigating this with a git pre-commit hook, but I don't know of any way to automate the installation of that for anyone cloning the project. (Nor do I think a pre-commit hook that has to download a go tool is great to be standardizing on -- will cause hard to debug errors for people without internet access at time of commit)

I recommend we disable gofumpt, and do not enforce any sort of linting in package import order. We can add back gofumpt once theres lint on save.

Perhaps we can add gofumpt'ing the entire code to a script that we execute pre-releases and prior to making new major release branches?

What do others think? cref @alexanderbez @faddat

**Comment by faddat** [comment]
I think that makes sense, definitely want to make osmosis as easy to contribute to as possible, and the script you just described would take care of the formatting/consistency issues pretty well.
