### ISSUE TITLE
Query Pools Faulty Tokens

### ISSUE THREAD

**Issue by Sen-Com** [osmosis-labs/osmosis#1324]
Hey, I just noticed that the "osmosis.gamm.v1beta1.Query/Pools" query gives incorrect results back. The query response contains tokens that are not in the pool.

Here is a part of the response. As per https://www.mintscan.io/osmosis/account/osmo1c9gj5nwxhuh2gz7wwg4r8e8tw8v7ggy9lh2hu7kkdgh0t450754qh9cpvd
, it should contain only "uosmo" and "1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4", however it contains a whole bunch more:
`{
  "address":"osmo1c9gj5nwxhuh2gz7wwg4r8e8tw8v7ggy9lh2hu7kkdgh0t450754qh9cpvd",
  "id":3,
  "pool_params":{
    "swapFee":"0.001000000000000000",
    "exitFee":"0.000000000000000000"
  },
  "future_pool_governor":"24h",
  "total_weight":"1073741824000000.000000000000000000",
  "total_shares":{
    "denom":"gamm/pool/3",
    "amount":"161290322580645161290"
  },
  "pool_assets":[
    {
      "token":{
        "denom":"ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
        "amount":"8396525282594"
      },
      "weight":"536870912000000"
    },
    {
      "token":{
        "denom":"uosmo",
        "amount":"35832549179743"
      },
      "weight":"536870912000000"
    },
    {
      "token":{
        "denom":"uion",
        "amount":"1368577798"
      },
      "weight":"858993459200000"
    },
    {
      "token":{
        "denom":"uosmo",
        "amount":"247115648733"
      },
      "weight":"214748364800000"
    },
    {
      "token":{
        "denom":"ibc/1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4",
        "amount":"3197335581355"
      },
      "weight":"536870912000000"
    },
    {
      "token":{
        "denom":"uosmo",
        "amount":"704732731126"
      },
      "weight":"536870912000000"
    }
  ]
}`

**Comment by Sen-Com** [comment]
I'd be happy to help with the reproduction & fixing.

**Comment by ValarDragon** [comment]
That'd be really helpful! Do you have a command / URL for this?

On quick check the CLI output looks correct to me. Its definitely possible that there could be something inconsistent / wrong between the CLI query code and the grpc_query code. 

https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/grpc_query.go#L70-L73

**Comment by Sen-Com** [comment]
It appears that I made a silly mistake here. I individually marshaled elements of the response list into a pool while not using a fresh struct for each decoding. Thus, the result was off. So there's nothing of with the grpc query. Thanks and sorry for the false alarm.
