### ISSUE TITLE
consider adopting github issue template for better project management

### ISSUE THREAD

**Issue by jlbit** [osmosis-labs/osmosis#1339]
Consider fully leverage github issue template for better ticket (github issue) management and organization,  and thus better project management and prioritization

e.g. separate bug reports v.s. feature 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#issue-templates
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates

cc @ValarDragon @daniel-farina

**Comment by alexanderbez** [comment]
Great idea!

**Comment by ValarDragon** [comment]
Yeah, we should definitely use issue templates!

**Comment by p0mvn** [comment]
I would like to pick this up if this is not being worked on by anyone

**Comment by alexanderbez** [comment]
Check out the SDK's templates or some that I [worked](https://github.com/umee-network/umee/tree/main/.github) on for inspiration :)

**Comment by p0mvn** [comment]
Re-assigning this to @xBalbinus since he has done a lot of great work in https://github.com/osmosis-labs/osmosis/pull/1399

@xBalbinus please keep this issue updated. Thank you!

**Comment by xBalbinus** [comment]
Will do! thanks for the great work as well on the addition of more templates @p0mvn !

**Comment by xBalbinus** [comment]
Added templates to [docs](https://github.com/osmosis-labs/docs/tree/stage) and [frontend](https://github.com/osmosis-labs/osmosis-frontend/pull/473)
