### ISSUE TITLE
Add tests for stableswap calc methods and spot prices

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1349]
https://github.com/osmosis-labs/osmosis/pull/1287, https://github.com/osmosis-labs/osmosis/pull/1345 both need additional test cases for stable swap spot price and calc methods.

**Comment by p0mvn** [comment]
@mattverse suggested to address the following comment here: https://github.com/osmosis-labs/osmosis/pull/1345/files#r858187443
