### ISSUE TITLE
Add binary build test for pre-Monterey Mac OS

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1352]
Current binary build test (CI) is running without build test on Mac OS, as it was removed after the cosmwasm inclusion. 

With cases like https://github.com/osmosis-labs/osmosis/pull/1351, where binary build could possibly fail even if it succeeds on Linux, we should re-add the Mac OS binary tests to github actions.

**Comment by ValarDragon** [comment]
Looks like it was never disabled, my bad: https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/build.yml#L18-L22

Maybe it was just an OS version? Can we add OS versions to these matrices?
