### ISSUE TITLE
Uncomment an off-by-one test case in TestCalcSingleAssetInAndOut_InverseRelationship

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1359]
**Background**

One of the tests in currently commented out because it is off-by-one.

#1345 might fix it. Once it is merged, uncomment the test case and make sure it passes

**Acceptance Criteria**
- uncomment the test case in TestCalcSingleAssetInAndOut_InverseRelationship
- ensure all testcases pass

**Comment by alexanderbez** [comment]
Thanks for tracking this @p0mvn 🙏
