### ISSUE TITLE
Add initial pool liquidity validation to stableswap msg.ValidateBasic function

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1364]
Add a check in stabelswap's msg.ValidateBasic() function that makes sure the input initialLiquidity is appropriate.

The check should go here: https://github.com/osmosis-labs/osmosis/blob/e9b9804bcef341a2b22fa90d7722a2fadb738d7e/x/gamm/pool-models/stableswap/msgs.go#L46

**Comment by mattverse** [comment]
NOTE: this issue also has dependency with https://github.com/osmosis-labs/osmosis/pull/1354, where we would need additional checks for ensuring that `poolLiquidity` and `scalingFactors` are by the same index

**Comment by mattverse** [comment]
@AlpinYukseloglu Are you currently on this? If not, would you mind if I start this?

**Comment by AlpinYukseloglu** [comment]
@mattverse The specific addition was quick so I went ahead and did it myself and requested a review from you

**Comment by mattverse** [comment]
Ah, I was also talking about adding checks to ensure scaling factors and pool liquidity have the same index(since both PRs were both open at the time this issue was opened). Since `CreatePool` is now implemented, I guess we could create a separate issue for adding scaling Factors and `validate`!
