### ISSUE TITLE
[x/gamm][StableSwap] Figure out LP share amount out derivation for stableswap

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1368]

**Comment by catShaark** [comment]
Can you provide more description for this issue ?

**Comment by AlpinYukseloglu** [comment]
### General formula
<img width="150" alt="Screen Shot 2022-09-19 at 1 51 47 AM" src="https://user-images.githubusercontent.com/62043214/190982091-4a755e0e-db1a-4224-8217-3f430c0e0faa.png">

The general formula is: **`c^(4+j) * k`**, where c is the factor we scale the total liquidity by (e.g. increasing pool liquidity by 10% would make c = 1.1), and j is the number of assets in the pool _that aren't being traded against_. 

**Examples:**
* Two asset pool, increasing liquidity by 15% (c = 1.15, j = 0): k increases to k*(1.15^4)
* Six-asset pool, decreasing liquidity by 4% (c = 0.96, j = 4): k decreases to k*(0.96^8)

### Derivation
**Two-asset CFMM:**

<img width="447" alt="Screen Shot 2022-09-19 at 1 31 49 AM" src="https://user-images.githubusercontent.com/62043214/190981554-78d9e57b-377b-4caf-9e24-ee3e7538f1eb.png">

**Multi-asset CFMM (derived example from 4-asset pool with assets x, y, m, and n):**

<img width="833" alt="Screen Shot 2022-09-19 at 1 47 33 AM" src="https://user-images.githubusercontent.com/62043214/190981631-e95b777d-6d52-4032-91ed-f45c84bbb911.png">
