### ISSUE TITLE
[x/gamm][StableSwap] multi-asset swap / LP equations, and tests

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1369]
The current CFMM equation we use for stableswap is `xy(x^2 + y^2) = k`. 

To extend this to many assets, we use the natural generalization, e.g. for 4 assets, `xyzw(x^2 + y^2 + z^2 + w^2)`. To implement this, we seek to have a single CFMM equation for swaps that works for all numbers of assets. We achieve this via a variable substitution. Let `u = zw` and `v = z^2 + w^2`. Then the stableswap equation for a swap is the same for all numbers of assets, taking the natural generalization of the two. Namely:

`xyu(x^2 + y^2 + v)`

And we just make our swap CFMM algorithms relative to this.

**Comment by p0mvn** [comment]
More work need to be done to get all the AMM logic use multi asset rliqudiity. @ValarDragon please provide more context

**Comment by AlpinYukseloglu** [comment]
Update: the only remaining part for this issue (tests for higher-level pool joining logic) is covered by #2346, so we can close this issue
