### ISSUE TITLE
[x/gamm][Testing] generalize TestCalculateAmountOutAndIn_InverseRelationship

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1371]
**Background**

The following PRs contributed to `TestCalculateAmountOutAndIn_InverseRelationship` in `balancer` package:
- #1254 - tests with zero swap fee
- #1344 - tests with non-zero swap fee

From "Gamm Refactor", `CalcInAmtGivenOut` and `CalcOutAmtGivenIn` are defined on the [`PoolI`](https://github.com/osmosis-labs/osmosis/blob/69811b3f40367a162f093cc437a4a95cd504ab9e/x/gamm/types/pool.go#L14) interface.

There are 2 pool implementations for `PoolI`: `balancer` and `stableswap`. The previously added tests only test `balancer` at the moment. However, since the inverse relationship applies to both `balancer` and `stableswap`, these tests can be generalized to apply to all possible implementations.

**Suggested Design**
- create a test file in `x/gamm/pool-models`
- extract `TestCalculateAmountOutAndIn_InverseRelationship` test from `x/gamm/pool-models/balancer` to `x/gamm/pool-models`
- generalize the test to apply to both `balancer` and `stableswap` pool implementations

**Acceptance Criteria**
- `TestCalculateAmountOutAndIn_InverseRelationship` tests both pool implementations
- the test is easily extensible to add more implementations if we have any in the future
- all new and existing unit tests pass

**Comment by p0mvn** [comment]
@xBalbinus would you be interested in working on this? Thanks for offering to help with the tests

**Comment by xBalbinus** [comment]
Yo @p0mvn ! Of course! Taking a look.

**Comment by p0mvn** [comment]
From @ValarDragon :

Recently, great tests have been added that test certain invariants (in the tests called "inverse relations") that are expected to hold trrue for any pool: https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/pool-models/balancer/amm_test.go#L89-L216

We should make code reuse possible for using the same core logic in stableswap tests. Theres a couple ways this can be done:

I suggest we do the following:
* Make a general function, perhaps in `pool-models/internal/test_helpers` that defines a testcase struct, which takes in a `PoolI` and some input to try the invariant relation on
* Define testcases in amm_test.go (in the case of balancer, adapt the existing tests, to use a single function call to generate the pool)
  * This should not increase the length of testcase definition notably. Ideally its a one or two liner.
* Add the invariant relation tests to stableswap

There are alternative approaches if for some reason this produces extra overheads though.

**Comment by xBalbinus** [comment]
^ Huge shoutout to @mattverse for helping with this PR, I also fixed a small thing to keep the linter running. All tests are passing & ready for merge upon approval.
