### ISSUE TITLE
unable to connect  gRPC server. "ResourceExhausted desc = grpc: received message larger than max (3 vs. 0)"

### ISSUE THREAD

**Issue by superpdm** [osmosis-labs/osmosis#1377]
I tried to connect for gRPC service with grpcurl:
       grpcurl -plaintext  "127.0.0.1:9190" list
I got the message "Failed to list services: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (3 vs. 0)"
osmosis version tested: v7.0.3, v7.2.1. 

grpclog prints the following when I start osmosisd node:

INFO: 2022/04/30 10:00:30 [core] Subchannel Connectivity change to CONNECTING
INFO: 2022/04/30 10:00:30 [core] Subchannel picks a new address "127.0.0.1:9190" to connect
INFO: 2022/04/30 10:00:30 [core] pickfirstBalancer: UpdateSubConnState: 0xc0014ea340, {CONNECTING <nil>}
INFO: 2022/04/30 10:00:30 [core] Channel Connectivity change to CONNECTING
WARNING: 2022/04/30 10:00:30 [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:9190 127.0.0.1:9190 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9190: connect: connection refused". Reconnecting...
INFO: 2022/04/30 10:00:30 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2022/04/30 10:00:30 [core] pickfirstBalancer: UpdateSubConnState: 0xc0014ea340, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9190: connect: connection refused"}
INFO: 2022/04/30 10:00:30 [core] Channel Connectivity change to TRANSIENT_FAILURE
INFO: 2022/04/30 10:00:33 [core] Subchannel Connectivity change to CONNECTING
INFO: 2022/04/30 10:00:33 [core] Subchannel picks a new address "127.0.0.1:9190" to connect
INFO: 2022/04/30 10:00:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc0014ea340, {CONNECTING <nil>}
INFO: 2022/04/30 10:00:33 [core] Channel Connectivity change to CONNECTING
INFO: 2022/04/30 10:00:33 [core] Subchannel Connectivity change to READY
INFO: 2022/04/30 10:00:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc0014ea340, {READY <nil>}
INFO: 2022/04/30 10:00:33 [core] Channel Connectivity change to READY
INFO: 2022/04/30 10:01:31 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2022/04/30 10:01:57 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2022/04/30 10:02:08 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"

**Comment by superpdm** [comment]
It turns out to be wrong config file

**Comment by kobrien** [comment]
also running into this issue, what was the config fix?

**Comment by czarcas7ic** [comment]
@kobrien I recommend generating the config.toml file via the newest release (v8.0.0) and this issue will go away

**Comment by superpdm** [comment]
> config.toml file via the newest release (v8.0.0) and this issue will go

I'm runing terrad and osmod at the same machine while I used the same port number for both deamons.
