### ISSUE TITLE
App version mismatch

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1381]
The app version mismatch has severely impacted database testing.  

Things work fine with gaia for example.

Since improving performance also improves developer experience and relay coverage, I think that it's best that we try to fix the app version issue, even if that means a fork of tendermint into osmosis-labs

We should be trying to match this experience:

https://twitter.com/notionaldao/status/1520646639756914689

(video in that tweet)

Gaia is running this:

https://github.com/faddat/gaia/tree/badger3

**Comment by ValarDragon** [comment]
Do you know how we'd fix it?

**Comment by faddat** [comment]
Sort of.

but not exactly.

**Comment by ValarDragon** [comment]
AppVersion is a consensus param? Should be easy to update that in end block then

**Comment by faddat** [comment]
More context in #642

**Comment by ValarDragon** [comment]
Closing in favor of tracking in #1805
