### ISSUE TITLE
[x/gamm][TWAP] Architecture

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1386]
## Introduction

We currently have a need for exposing on-chain time weighted average prices (TWAPs) for pools. This can be done in a way that's independent of the pool type, and thus can be done quite modularly.

Twaps work by maintaining a rolling accumulator value. The exact equation within the accumulator depends upon what is the type of TWAP you are taking. (How do you weight older prices vs newer prices) So someone who wants to get the price the TWAP of a pool between time A and time B does: `calc_twap(accumulator_time_A, accumulator_time_B, interval_size) price`.

A twap at a high level thinks of the pool as having a certain price between blocks. On the first trade in a pool within a block, it records the last spot price the pool had, scales it by the time since last update to this pool, and adds that into the twap value. Basically running `record_twap_entry(last_time, cur_time, cur_price, last_accumulator) new_accumulator`. When `last_time = cur_time` its a no-op. This is because we view blocks as the discretization of execution times. Thus the prior price was held for no time interval.

## Design considerations

There are two main twap algorithms used in crypto right now, arithmetic mean twap, and geometric mean twap. These are both well documented elsewhere. I propose that we make our current TWAP design assume that we want all pools to implement all useful TWAPs. Later on, if we run into a situation where we may only want certain TWAP types on a subset of pools, we re-assess then. I believe this should be handle-able with no migration, using optional fields in a proto, but will be sub-optimal. The buffer between state machine logic and clients via cosmwasm APIs & grpc_query should hopefully mitigate this becoming problematic.

Its a feature to keep this logic decoupled from the core AMM work, in its own package.

## Proposed Architecture

Keep all of the relevant TWAP code in `x/gamm/twap`. Make the proto struct:
```
message twap_record {
  option (gogoproto.equal)            = true;
  option (gogoproto.goproto_stringer) = false;

  uint64 pool_id = 1;
  string asset_in_denom = 2;
  string asset_out_denom = 3;
  uint64 height = 4 [(gogoproto.moretags) = "yaml:\"record_height\"", (gogoproto.jsontag) = "record_height"];
  // This field should only exist until we have a global registry in the state machine, mapping prior block heights within {TIME RANGE} to times.
  google.protobuf.Timestamp time = 5
      [(gogoproto.nullable) = false, (gogoproto.stdtime) = true, (gogoproto.moretags) = "yaml:\"record_time\""];
  
  string arithmetic_twap_accumulator = 6 [(gogoproto.customtype) = "[github.com/cosmos/cosmos-sdk/types.Dec](http://github.com/cosmos/cosmos-sdk/types.Dec)", (gogoproto.nullable) = false];
  string geometric_twap_accumulator = 7 [(gogoproto.customtype) = "[github.com/cosmos/cosmos-sdk/types.Dec](http://github.com/cosmos/cosmos-sdk/types.Dec)", (gogoproto.nullable) = false];
}
```

We should maintain 1 twap record per pool asset pair / block. Ideally we would use ORM to index this in state. And then have primary indices, pool_id, and a secondary index on asset_in / asset_out / height. 

I suggest we store TWAP entries for the last (say) week, and prune on daily epochs.

**Comment by alexanderbez** [comment]
So we'd have `num_blocks_day * 14 * num_pools` records at any given time?

**Comment by mattverse** [comment]
Can we close this issue with this TWAP Architecture having been implemented to main?
