### ISSUE TITLE
Unable to fetch large blocks via RPC: I/O timeout

### ISSUE THREAD

**Issue by mdyring** [osmosis-labs/osmosis#1391]
Fetching block_results for large blocks results in IO timeouts, making it impossible to properly index the blocks.

It seems like the RPC server will kill the connection if fetching data from the block store takes longer than 30 seconds.

Example using curl to fetch block
```
$ time curl -vs localhost:29657/block_results?height=3711555
*   Trying 127.0.0.1:29657...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 29657 (#0)
> GET /block_results?height=3711555 HTTP/1.1
> Host: localhost:29657
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact

real	0m31.817s
user	0m0.005s
sys	0m0.010s
```

Log output from osmosisd (which logs the entire 100+ mb response to stderr):
```
6:29AM ERR failed to write response err="write tcp 127.0.0.1:29657->127.0.0.1:41328: i/o timeout" module=rpc-server res={"begin_block_events":[{"attributes":[{"index":true,"key":"ZXBvY2hfbnVtYmVy","value":"Mjc4"}],"type":"epoch_e
nd"},{"attributes":[{"index":true,"key":"c3BlbmRlcg==","value":"b3NtbzFrcnh3ZjVlMzA4am1jbHloZmQ5dTkya3AzNjlsMDgzd2VxdWdlNg=="},{"index":true,"key":"YW1vdW50","value":"Njk4Mzg3MjBpYmMvMEVGMTVERjJGMDI0ODBBREUwQkI2RTg1RDlFQkI1REFFQTI4MzZEMzg2MEU5Rjk3RjlBQURFNEY1N0EzMUFBMCw
2OTQxOTk5OTM0MGliYy8zMDdFNUM5NkM4RjYwRDFDQkVFMjY5QTlBODZDMDgzNEUxREIwNkYyQjM3ODhBRTRGNzE2RURCOTdBNDhCOTdELDExMTExMTEwOTc5NGliYy8zNDY3ODZFQTgyRjQxRkU1NUZBRDE0QkY2OUFEOEJBOUIzNjk4NTQwNkU0M0YzQ0IyM0U2QzQ1QTI4NUE5NTkzLDU1NTU2NjYwMjRpYmMvNDZCNDQ4OTkzMjJGM0NEODU0RDJENDZERUVGO
...
```

**Comment by mdyring** [comment]
@alexanderbez yeah we're querying Tendermint RPC directly, e.g. /block_results?height=3711555, but have been unable to find any clues in the Tendermint code/config that would solve it.

Since we have only encountered this issue on Osmosis so far (due to yuuuge epoch blocks), I was thinking you guys might have a better chance of reproducing and diagnose the root cause compared to Tendermint team.

**Comment by alexanderbez** [comment]
Unfortunately, Tendermint does not expose these in their RPC configuration block. I'd advise closing this issue and moving it to the Tendermint repo. The RPC timeout is entirely handled in Tendermint since you're querying the RPC directly. The only other approach would be to add this request as a proxy to the SDK like we do for some other requests, so that way you'll be able to utilize the app.toml RPC timeout configs.

But to be honest, I feel like Tendermint adding these configs is a cleaner and more sustainable approach.

**Comment by ValarDragon** [comment]
Do we know where we'd update these timeouts? I'm not opposed to maintaining a tendermint fork with this change until it gets into an upstreamed tendermint release.

**Comment by mdyring** [comment]
> Do we know where we'd update these timeouts? I'm not opposed to maintaining a tendermint fork with this change until it gets into an upstreamed tendermint release.

That would be great as I haven't observed this yet on other chains.

Being able to export full block state seems like a must-have. 👍

**Comment by alexanderbez** [comment]
> Do we know where we'd update these timeouts? I'm not opposed to maintaining a tendermint fork with this change until it gets into an upstreamed tendermint release.

It's super trivial to implement. Let's open an issue in the Tendermint repo. I would really try and avoid forking whenever possible.

**Comment by alexanderbez** [comment]
https://github.com/tendermint/tendermint/issues/8465

**Comment by tyrion70** [comment]
Cross posting here, it looks like the `timeout_broadcast_tx_commit` actually sets the global http write timeout on the http server. I just tested it and we're now able to download these large blocks without any issues.

**Comment by ValarDragon** [comment]
Awesome! Lets update our default config generation code, to up this default value

**Comment by alexanderbez** [comment]
Yes, but setting `timeout_broadcast_tx_commit` is a hack. Tendermint should support providing explicit configurations in it's `config.toml` for the RPC settings.

**Comment by ValarDragon** [comment]
I think this has been fixed? Lets re-open if this is still affecting folks
