### ISSUE TITLE
x/pool-incentives: Make FundCommunityPoolFromModule call distr.FundCommunityPool

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1401]
The current [FundCommunityPoolFromModule](https://github.com/osmosis-labs/osmosis/blob/main/x/pool-incentives/keeper/distr.go#L14-L22) function in pool-incentives should either be upstreamed to the SDK's distribution module, or we should derive the SDK address for this, and call `distr.FundCommunityPool`.

We derive the SDK address from a module name via:
```
addr := k.accountKeeper.GetModuleAddress(moduleName)
if addr == nil {
  error or panic
}
```

**Comment by alexanderbez** [comment]
@ValarDragon what exactly are you proposing we upstream to `x/distribution`?

**Comment by ValarDragon** [comment]
The `FundCommunityPoolFromModule` function as a whole. The problem we faced was we wanted to send coins to the community pool from a module account, and in this code we basically hackily did updates to the `Distr.FeeTokens` struct to handle this.

**Comment by alexanderbez** [comment]
Got it!

**Comment by ValarDragon** [comment]
Oh true. I guess its a yak shaving question of do we want to get this into the SDK, versus just use more black box functionality  here. (converting sending address to a normal address rather than module address)
