### ISSUE TITLE
[x/gamm][StableSwap]  two asset swap / LP equations and tests

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1406]

**Comment by p0mvn** [comment]
Hi @ValarDragon 

Created this issue from the epic in #1050 to make sure that we don't have non-issue bullet points.

Please fill in the description, labels, priority, and size when you have time

**Comment by AlpinYukseloglu** [comment]
Update: the only remaining part for this issue (tests for higher-level pool joining logic) is covered by #2346, so we can close this issue
