### ISSUE TITLE
Auto-derive Arithmetic Mean TWAP and Geometric Mean TWAP accumulators on pools after each swap

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1410]

**Comment by p0mvn** [comment]
@ValarDragon ,

Created this issue from the epic in https://github.com/osmosis-labs/osmosis/issues/1050 to make sure that we don't have non-issue bullet points.

Please fill in the description, labels, priority, and size when you have time

**Comment by ValarDragon** [comment]
Closing in favor of #1386

**Comment by p0mvn** [comment]
Thanks, replaced it in the epic

**Comment by zmanian** [comment]
It would be really helpful to use cases with interchain queries if these values are written to the store.

**Comment by ValarDragon** [comment]
Our plan is to have old accumulator values written in state, and maintain them 7 days worth of accumulators per pool by default
