### ISSUE TITLE
[Import Genesis] Speeding up the import genesis time

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1413]
**Background**

We need to understand what is happening during the import genesis and come up with a solution to improve time.

**Acceptance Criteria**
- Import genesis time is well understood
- A plan to mitigate the problem is created

**Comment by p0mvn** [comment]
Hi @moniya12 . Are you on this? If yes, what is the status? Thanks!

**Comment by catShaark** [comment]
@p0mvn, I did some work on this and so far I've reduced the importing time by maybe a half. I did the profiling by running [this test file] (https://github.com/notional-labs/osmosis/blob/1fdff279e3a2ad816f56bb0fd1b4e4662ba2f55e/simapp/sim_test.go#L39) which contains the code needed for importing genesis used in the `osmosisd start` cmd.

**Comment by czarcas7ic** [comment]
@catShaark out of curiosity, how much time does it now take compared to what it did before? What changes did you make to achieve this?

**Comment by catShaark** [comment]
Changes I did :
- [Improve](https://github.com/cosmos/cosmos-sdk/pull/12170) the `DelegatorSharesInvariant` invariant check in the sdk. It reduces runtime from 241 to 161 sec in one of my computer.
- makes the unmarshaling of modules' genesis state parallel, before we unmarshal modules' genesis sequentially. This reduces runtime for about 30-40 sec.

**Comment by czarcas7ic** [comment]
@catShaark So just to give you some more context, this issue was in reference to state exported testnets. Basically, when we take a state export, modify the values, then start a new testnet off this new genesis the following happens:
1. Init genesis starts, this process takes roughly 15 minutes
2. We hit the block after the snapshot was taken
3. We then pause on this block for about an hour and a half, using a large amount of RAM (almost 64GB) 
4. After we hit the next block, we hit blocks like normal

I think your changes will help with number 1, but number 3 is where the most time is spent. @moniya12 was working on some database changes to potentially help with this.

**Comment by catShaark** [comment]
take a state export = running osmosisd export right ?

**Comment by czarcas7ic** [comment]
@catShaark correct! That takes ~5-10 mins max

**Comment by catShaark** [comment]
I import a 1.8G genesis file ( exported from an osmosis mainet node ) and it takes only 200-300 sec. Do I do something wrong ?

**Comment by czarcas7ic** [comment]
In our scenario, we are modifying the genesis the mint new coins to a wallet, change a validator's consensus key to the one that we have locally, and give it 99 percent of the voting power. You can read a little more about the process here https://github.com/osmosis-labs/osmosis/tree/main/tests/localosmosis#localosmosis-with-mainnet-state and see the python script being used to modify the genesis here https://github.com/osmosis-labs/osmosis/blob/main/cmd/osmosisd/cmd/testnetify/testnetify.py

Tomorrow I can provide you with a modified one with the required consensus key if desired

**Comment by catShaark** [comment]
thanks, I'd love to work on this to improve our test runtime overall
also, can you tell me what you think happened on step 3, why is it taking so long

**Comment by catShaark** [comment]
> * Import genesis time is well understood


![here is a pprof graph for importing genesis on a different computer of mine](https://user-images.githubusercontent.com/50263489/172289263-df190ff1-9216-4c5b-b1dc-5398edc28a62.svg), this is importing a 1.8G genesis file, I run in [this test file](https://github.com/notional-labs/osmosis/blob/75a458caf7e71163a7b885e8ee8d230e75cc3cf1/simapp/sim_test.go#L39).

**Comment by p0mvn** [comment]
@catShaark thanks for the pprof. From what I remember, we had a specific case where our pprof was taking more than an hour, halting for over 40 minutes due to processing data. 

@czarcas7ic do you happen to remember how to reproduce this?

**Comment by catShaark** [comment]
ohh thank you guys, this is something I really want to put my hand on.

**Comment by czarcas7ic** [comment]
Yeah honestly the more eyes on this the better. While it started off being just an annoying side problem, its gotten in the way a lot more than one would expect

**Comment by catShaark** [comment]
@czarcas7ic, this is still relevant right ? now that the incident is over, should we continue working on this ?

**Comment by czarcas7ic** [comment]
Yes very relevant, will get back to it tomorrow, thanks for the ping

**Comment by ValarDragon** [comment]
Closing this for now. We've temporarily mitigated the problem by pruning IBC state.

Further improvements should come from IAVL improvements and better atomicity structure in the SDK's usage of the database
