### ISSUE TITLE
[E2E - Upgrade Testing] automate the creation of older e2e chain initialization images

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1415]
**Background**

We need a way to automate the creation of chain initialization images. Currently, these have to be manually created and pushed to the Docker hub

**Acceptance Criteria**
- the previously released branch is auto-detected
- the image for initializing latest released version is auto-built and uploaded to docker hub without the need for manual intervention

**Comment by nikever** [comment]
Possible inspiration: 
https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/docker.yml

**Comment by p0mvn** [comment]
Closing in favor of: https://github.com/osmosis-labs/osmosis/issues/4070
