### ISSUE TITLE
Add table-driven tests to x/tokenfactory

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#1418]
Currently, most of the tests for x/tokenfactory are "story-driven tests", but we should use more table driven tests with more edge cases to maximize code coverage.

**Comment by ValarDragon** [comment]
I don;t think they are story driven tests at the moment either. (At least not for common definitions of story driven testing / acceptance criteria testing)

**Comment by ValarDragon** [comment]
To consider this issue complete, we should have tests for:
* MsgCreateDenom
  * Try with subdenom too long
  * Subdenom having invalid characters
  * Subdenom & creator pair already exists
  * Success case
* MsgMintDenom
  * Denom does not exist
  * Mint is not by the admin
  * Try to overflow int limits with mint
  * Success
(Same as above for burn)
* MsgChangeAdminDenom
  * After setting to "", creator / prior admin can't mint
  * non-admins can't change the existing admin
  
There are more edge cases, but I think we can add them separately
