### ISSUE TITLE
[x/gamm][Misc Improvements] Making balancer and stableswap pool model folders more aligned

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1420]
We currently use a different code structure for the balancer and stableswap packages. We should align these.

I think we should make the balancer package follow more of the standards of the stableswap package namely:
* Move API satisfaction functions from amm.go to pool.go
* Make the publicly exported method do basic input validation / output wrapping, and call out to a separate private 'mathy' method within amm.go
* Rename balancer_pool.go -> pool.go

In stableswap, we should delete stableswap_pool.go, and move that relevant code to pool.go

**Comment by p0mvn** [comment]
Hi @ValarDragon and @mconcat 

Could one of you please add "T:task" label to this and include it in the description of https://github.com/osmosis-labs/osmosis/issues/1453 story so that this issue is tracked?

Thanks in advance!

**Comment by ValarDragon** [comment]
Closed by Bez' recent PR!
