### ISSUE TITLE
investigate and test: balancer.CalcTokenInShareAmountOut should be inverse of balancer.CalcJoinPoolShares

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1426]
**Background**

`JoinSwapShareAmountOut` was attempted to be implemented in the following way https://github.com/osmosis-labs/osmosis/pull/1307#discussion_r857177513. Once we calculate `tokenInAmount` with `CalcTokenInShareAmountOut`, we should be able to call `JoinPool` (that in turn calls `CalcJoinPoolShare`). to update liquidity under the hood. 

If we do so, `sharesCreated` by `JoinPool` should be equal to `shareOutAmount` received by `JoinSwapShareAmountOut`. However, they do not match.
```
test panicked: {824636220864} shares created is not equal to the requested amount of {824633847808}
```

On initial investigation, `v7.x` receives the same `tokenInAmount` as this implementation so `CalcTokenInShareAmountOut` is **likely** to be correct.

On the other hand, `JoinPool` is missing any unit tests. Thererefore, it is a **more likely** source of problems, if any.

We should add the inverse unit test for `balancer.CalcTokenInShareAmountOut` and `balancer.CalcJoinPoolShares` once #1307 is merged.

Referenced code:
```
func (k Keeper) JoinSwapShareAmountOut(
	ctx sdk.Context,
	sender sdk.AccAddress,
	poolId uint64,
	tokenInDenom string,
	shareOutAmount sdk.Int,
	tokenInMaxAmount sdk.Int,
) (tokenInAmount sdk.Int, err error) {
	pool, err := k.getPoolForSwap(ctx, poolId)
	if err != nil {
		return sdk.Int{}, err
	}

	extendedPool, ok := pool.(types.PoolAmountOutExtension)
	if !ok {
		return sdk.Int{}, fmt.Errorf("pool with id %d does not support this kind of join", poolId)
	}

	tokenInAmount, err = extendedPool.CalcTokenInShareAmountOut(ctx, tokenInDenom, shareOutAmount, pool.GetSwapFee(ctx))
	if err != nil {
		return sdk.Int{}, err
	}

	if tokenInAmount.GT(tokenInMaxAmount) {
		return sdk.Int{}, sdkerrors.Wrapf(types.ErrLimitMaxAmount, "%d resulted tokens is larger than the max amount of %d", tokenInAmount.Int64(), tokenInMaxAmount.Int64())
	}

	tokenIn := sdk.Coins{sdk.NewCoin(tokenInDenom, tokenInAmount)}

	sharesCreated, err := extendedPool.JoinPool(ctx, tokenIn, pool.GetSwapFee(ctx))
	if sharesCreated != shareOutAmount {
		panic(fmt.Sprintf("%d shares created is not equal to the requested amount of %d", sharesCreated, shareOutAmount))
	}

	err = k.applyJoinPoolStateChange(ctx, pool, sender, shareOutAmount, tokenIn)
	if err != nil {
		return sdk.ZeroInt(), err
	}
	return tokenInAmount, nil
}
```

**Acceptance Criteria**
- inverse unit tests for `balancer.CalcTokenInShareAmountOut` and `balancer.CalcJoinPoolShares`
- determine if this is an actual problem or a logical error
- if error exists, it is fixed

**Comment by nicolaslara** [comment]
I see the status of this is "Done. Can we close it?
