### ISSUE TITLE
Include PR #11224 from cosmos-sdk to fix Ledger/Amino authz signing

### ISSUE THREAD

**Issue by george-aj** [osmosis-labs/osmosis#1434]
Hi,

Would it be possible to include the following PR https://github.com/cosmos/cosmos-sdk/pull/11224 into the next release? This would fix the Ledger/Amino authz MsgGrant signing issues that are currently impacting all Ledger users.

Geo

**Comment by p0mvn** [comment]
Hi @george-aj . Taking a look... The desired PR related to this seems to be: https://github.com/cosmos/cosmos-sdk/pull/11680

As a side note, this article was helpful for understanding the context: https://medium.com/confio/authz-and-ledger-signing-an-executive-summary-8754a0dc2a88

**Comment by ValarDragon** [comment]
@alexanderbez thoughts on whether this is a good idea to add directly to next release, vs wait until a subsequent release with SDK v0.46 ?

i don't understand whats happening with RegisterLegacyAminoJson being added into every module (vs just Authz)

**Comment by alexanderbez** [comment]
I think @p0mvn's PR introduces the changes we need, but also introduces some API breaking changes. We can get it into v8.
