### ISSUE TITLE
Make gotests template for cosmos keeper & message tests

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1444]
The gotests tool is really nice for automatically generating go tests for a given function: https://github.com/cweill/gotests/

Its been ~2 years since I last used it, but I remember it working quite well for doing the boilerplate of a table driven test setup, for "normal" golang code. Its possible to make custom templates for it, we should add custom templates for desired table driven keeper test patterns and message test patterns.

It has vscode integrations already

We should investigate this, and if template configuration is easy / sufficient, use it to help speed up test writing in the way we want =)

**Comment by stackman27** [comment]
would this be a vscode plugin to use or just a general testing template?

**Comment by ValarDragon** [comment]
gotests is already a go tool, that has native integration into the vscode `go` package already!

This template would be a file we add to the root directory, that go tests would automatically read and use.

**Comment by AlpinYukseloglu** [comment]
Seems like `Go: Generate Unit Tests For Function` routes to [this file](https://github.com/cweill/gotests/blob/develop/templates/testify/function.tmpl) in `gotests`, which should be pretty straightforward to edit to fit our testing standards, but I'm struggling to figure out:
1. How to edit/run this locally
2. How to set it up with our repo so no additional IDE setup is required for it to work as intended

Any ideas/guidance @ValarDragon?

**Comment by ValarDragon** [comment]
It may require some IDE setup in vscode to point to it, but thats doable via https://github.com/osmosis-labs/osmosis/blob/main/.vscode/settings.json

I haven't tried editing templates before
