### ISSUE TITLE
[x/gamm][StableSwap - Post V8] Add stableswap `scaling factor governor`

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1460]
There is a desire to use stableswaps with yield accumulating assets. There are a few designs for how you could do this, but the simplest one seems to be to utilize the 'scaling factors' present in the Stableswap algorithm. If someone wanted to adjust the scaling factors according to yield, then this would achieve altering the price that its being stable around.

We should add a new field in the stableswap proto message, called `scaling_factor_governor`, which can be either blank, or an osmo address.

We should also add a new message called "MsgStableSwapAdjustScalingFactors", that can only be sent from the `scaling_factor_governor` address for the respective poolID. (if the address is blank, noone can send this message for the given poolID). This message adjusts the scaling factors to the provided ones.

It is intentioned that cosmwasm contracts could be used to set these in the future. There should also be a query for this, as it will be important for front-ends / users to know about a governor risk prior to LP'ing.

This is a post v8 feature

**Comment by vuong177** [comment]
Could i try doing that ?
