### ISSUE TITLE
download genesis automatically with ipfs

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1489]
## Background

We can't make enough RPC nodes.  It is impossible.  Plus, we want to make "the signal" unstoppable.  This means that eventually, Osmosis and its related DAOs need to ship onto user machines, as desktop apps.

Currently those of us on the "technical side" of the house have all shared the experience of guiding someone through hunting down genesis and seeds.

In fact, many of us have spent days of our lives doing the same.  This is counter-productive and bad.  

## Suggested Design

Osmosis should download its own genesis state by default, and state sync by default, using addresses from the cosmos chain registry. Here's the code:

```go
import "github.com/notional-labs/get"

get.Get(filepath, cid)
```

## Acceptance Criteria

* State sync needs to work
* Users should approve of downloading genesis state as a part of the chain binary
* It should work seamlessly, hundreds of times
* `osmosisd init` should no longer be necessary except for validators and others doing "fancy things" with their nodes
* Need to communicate with Keplr team about wallet security in the context of an electron app.
* Teams developing applications on Osmosis should be contacted and alerted to the infrastructure-free deployment option

**Comment by ValarDragon** [comment]
why isn't get.osmosis.zone the goal we target here?

**Comment by faddat** [comment]
...where get.osmosis.zone gives you a .dmg ;)

**Comment by faddat** [comment]
Unfortunately, this is blocked by this:

https://github.com/cosmos/cosmos-sdk/pull/11414
