### ISSUE TITLE
[v9 RC Blocker] Upgrade Main to Cosmwasm v0.27.0.rc3

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1502]
## Background

We need to upgrade main from wasmd 0.24 to either 0.26 or 0.27. This is a blocker for RC0 release of v9. This change should be competed by tomorrow, Tuesday May 17th. 

## Acceptance Criteria

- wasmd upgraded
- all existing and new tests should pass

**Comment by p0mvn** [comment]
I'm trying `0.26` since `0.27` is an rc release. It also introduced breaking changes when `0.26` doesn't seem to

**Comment by p0mvn** [comment]
Having a problem with upgrading wasmd. Osmosis depends on cosmos-sdk from our own fork while wasmd utilizes the upstream.

When I bump up the version for wasmd to 0.26 it complains about needing to depend on our fork. As I've done before, I tried to just switch wasmd 0.26 to depend on our own fork and tag it. However, that broke some tests. Seems that the new wasmd relies on some updates from the latest v0.45.4 release of the sdk upstream.

Any suggestions on how to deal with this?

**Comment by p0mvn** [comment]
The problem is resolved. Went with `v0.26.0` because `v0.27.x` is rc still

**Comment by czarcas7ic** [comment]
Could it have something to do with us still requiring wasmvm? According to that compatibility chart, 0.26 no longer uses this.

**Comment by faddat** [comment]
hey, I would like to recommend:

* 27
* ibc v3

Happy to help with either

**Comment by faddat** [comment]
I am intimately familiar with these dockerfile issues. 

I recommend:

ghcr.io/faddat/cosmos

it is designed specifically as the solution to the docker issues mentioned.

**Comment by faddat** [comment]
@p0mvn I am hopping onto the wasmd issue.

27 gets us state sync

**Comment by p0mvn** [comment]
@faddat thanks. I'm concerned that 0.27 is an rc though. Has it been used by other chains?

**Comment by p0mvn** [comment]
Also, the wasmd problem is solved for 0.26 on this branch:

https://github.com/osmosis-labs/wasmd/tree/v0.26.0-osmo

I suspect that the fix for v0.27 would require similar changes

**Comment by faddat** [comment]
actually reading through that branch now.  v27 hasn't been tested on other chains, but -- wait-- yes it has.it is on juno (not quite v27 but very close) and (pieces of it?) are on scrt I think

**Comment by faddat** [comment]
We shouldn't cut an osmosis release with it as an rc, though it's worth noting that Juno hasn't had issues.

We needed sudo for the implementation of prop 16 iirc

**Comment by p0mvn** [comment]
> Also, the wasmd problem is solved for 0.26 on this branch:
> 
> https://github.com/osmosis-labs/wasmd/tree/v0.26.0-osmo
> 
> I suspect that the fix for v0.27 would require similar changes

Essentially, what's done on the linked branch of wasmd is making it use the same SDK and IAVL as Osmosis. Once go.mod is changed accordingly, there will be a few places requiring manual code changes

**Comment by faddat** [comment]
yep -- in fact I just used your commit :)

but need to update our SDK it seems, would you like me to?

**Comment by p0mvn** [comment]
> We shouldn't cut an osmosis release with it as an rc, though it's worth noting that Juno hasn't had issues.
> 
> 
> 
> We needed sudo for the implementation of prop 16 iirc
> 
> 
> 
> I'll prep 27, you proceed with the other pieces, @p0mvn ?

Yeah I'll keep trying to figure out the Docker images issue. Will try the images you shared. Thanks

**Comment by faddat** [comment]
awesome :D.  

I'll check back when progress or computer has exploded

**Comment by faddat** [comment]
ah, I almost forgot -- here's the source for those docker images:

https://github.com/faddat/archlinux-docker

`osmosis` is `cosmos` but it also has genesis.json at /

**Comment by p0mvn** [comment]
> yep -- in fact I just used your commit :)
> 
> 
> 
> but need to update our SDK it seems, would you like me to?

Why do you need to update the SDK? When we update the version of SDK in go.mod of wasmd, there will be some issues post-update. I think wasmd needs to be updated to match our SDK fork API

**Comment by faddat** [comment]
I might not-- I found your work on osmosis-labs/cosmos-sdk `main`

:)

**Comment by alexanderbez** [comment]
So wait...are we using 0.26 or 0.27

**Comment by faddat** [comment]
My thoughts:

We should prep with v0.26.0

If I can finish v0.27.0 we should consider it.  Currently getting snapshots over the line, I think.  There were changes to the wasm snapshots, which would affect our cosmos-sdk. 

Also, if we would like to go fast fast-- might as well use v0.26 + ibc v2.2.0 as - is, and come back to this at a later time.

**Comment by p0mvn** [comment]
Also, I switched to trying to integrate `v0.27.0.rc3`. Trying to backport https://github.com/cosmos/cosmos-sdk/pull/11267 to our fork to make it work with Osmosis

**Comment by p0mvn** [comment]
Created:

https://github.com/osmosis-labs/wasmd/releases/tag/v0.27.0.rc3-osmo

Next, need to upgrade Osmosis to ibc-go/v3 and wasmd to v0.27.0.rc3-osmo
