### ISSUE TITLE
[v9] Add Superfluid Governance

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1504]
## Background

Review and merge #1191 

## Acceptance Criteria

- PR #1191 is merged
- test if governance works as expected on a testnet
- all existing and new tests should pass

**Comment by mattverse** [comment]
Hey @czarcas7ic do you know if we ever got to test this on a test net?

**Comment by czarcas7ic** [comment]
Tested and added to e2e tests, will close now, thanks!
