### ISSUE TITLE
[v9] Token Factory

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1505]
## Background

Token factory should be fully implemented and tested for v9 release.

## Acceptance Criteria

- Review of token factory code
- Create a [more detailed spec](https://github.com/osmosis-labs/osmosis/blob/main/x/tokenfactory/README.md)
- Test token creation on a testnet
- Add a gov parameter to charge a set fee per new denom created
- (optional) Test Cosmwasm binding API for token factory

**Comment by mattverse** [comment]
Assigning myself for creating detailed spec for token factory

**Comment by ValarDragon** [comment]
Turns out the gov parameter already exists on main, and we have the queries we need!
