### ISSUE TITLE
[v9] Cosmwasm Binding API Review

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1507]
## Background

As mentioned in #1505, we need to familiarize ourselves with the cosmwasm API, its relation to osmosis, and if there are any issues with its implementation.

## Acceptance Criteria

- general dev consensus that cosmwasm API bindings are properly implemented

**Comment by ValarDragon** [comment]
We basically want to look at the API / usage from within cosmwasm. Not sure if theres an example cosmwasm contract using the bindings in the bindings repo

**Comment by p0mvn** [comment]
I can work on that and document my findings

**Comment by daniel-farina** [comment]
I think this is key as mentioned by @iboss-ptk in Slack.

https://github.com/osmosis-labs/osmosis/pull/1135

**Comment by p0mvn** [comment]
TODO for this issue: find or create a sample contract and document it

**Comment by ValarDragon** [comment]
Done!
