### ISSUE TITLE
[v9] Different Voting Period Per Gov Type

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1508]
## Background

The current "one-size-fits-all" gov period has shown its flaws in light of recent events. We need to have the ability to set a shorter gov period for certain proposal types.

Also to detail in future issues, ideas to handle emergency proposals with 2/3rds expidted approving.

## Acceptance Criteria

- Can set a different voting period per proposal type
- proposer can choose emergency option to reduce gov voting time
- @alexanderbez can put further ideas here as he has a current mental model of how he believes it should be implemented

**Comment by alexanderbez** [comment]
ref: https://github.com/osmosis-labs/osmosis/issues/1517
