### ISSUE TITLE
[v9] Contract Upload Process

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1509]
## Background

We need a clear guide that steps users through the entire contact upload process.

## Acceptance Criteria

- guide created and uploaded to documentation website

**Comment by daniel-farina** [comment]
Several guides uploaded and a few more to come.

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/13665117/169334824-c58aacc2-d123-48b7-98e3-8db661332e97.png">
