### ISSUE TITLE
Make  `Add new issues to project` only run on PRs that are not from a fork

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1529]
## Background

Make  `Add new issues to project` only run on PRs that are not from a fork. Its currently erroring on every PR from a fork.

## Suggested Design

Add a check in the github actions flow for this. An alternative design would be to make github tokens work in a fork, idk if thats possible though. Another design would be for it to not be an action that shows in PRs

## Acceptance Criteria

- [ ] Add new issues to project github action doesn't error when coming from a fork.

**Comment by ValarDragon** [comment]
See https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363 for how we'd do it

**Comment by ValarDragon** [comment]
cc @xBalbinus is this something you'd be down to take on?

Will help everyone working on forks to not have constant errors on their PRs

**Comment by xBalbinus** [comment]
Yep! Got it, down to take this on
