### ISSUE TITLE
Too Many Snapshots In Data Folder

### ISSUE THREAD

**Issue by lightiv** [osmosis-labs/osmosis#1531]
#### System information

Osmosis version: `Osmosis version`: v8.0.0
OS & Version: Windows/Linux/OSX: Linux
Commit hash: 16e3b51f19a58f815a4eabcbcee11886eb33e026

#### Expected behaviour

For there to be 2  snapshots folders under ~/.osmosisd/data to correspond with the state_sync setting in app.toml.  The default is to retain 2 of these images.  

#### Actual behaviour

Osmosis has 4 despite having the same settings. (My other chains all have 2 )

#### Steps to reproduce the behaviour

I was spot checking with `osmosisd du -h .` in the ~/.osmosisd/data folder

Maybe this is why Osmosis nodes are so huge?  I have custom pruning at 60K in app.toml

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by alexanderbez** [comment]
Could it be possible that 2 are from the previous version of Osmosis and 2 are from the current? Where the current version will not prune or remove snapshots it doesn't understand or know about (i.e. v7)...? Thoughts @p0mvn?

**Comment by lightiv** [comment]
This was a fresh setup that I noted this on.

**Comment by p0mvn** [comment]
Hi @lightiv . Has this been a problem on your end? Is this still needing investigation?

**Comment by czarcas7ic** [comment]
@p0mvn come to think of it I have actually noticed this too

**Comment by alexanderbez** [comment]
Did anything change with regards to that? AFAIU, this is managed by the snapshot manager, right @p0mvn? Where there any changes in that for v8?

**Comment by lightiv** [comment]
Looking at czarcas7ic response above it appear he is having the issue.  I have disable snapshots on my boxes so I am not sure if it is resolved or not.  It has been a while but i think the problem did resolve on my end.  So please close as you see fit.  Thanks

**Comment by czarcas7ic** [comment]
@lightiv We will be keeping this issue open since it does still exist, however are giving it a lower priority at the moment. Thanks for reporting!

**Comment by the-smooth-operator** [comment]
We are also experiencing this same issue. Even with `snapshot-keep-recent = 2` defined in app.toml snapshots keep piling up. 
Disabling them completely works, but this is not good for the network.

**Comment by ValarDragon** [comment]
I believe this has been fixed, please comment re-open if it has not been
