### ISSUE TITLE
test: e2e test superfluid gov voting

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1556]
## Background

We should convert this manual test case to an e2e test: https://github.com/osmosis-labs/osmosis/discussions/1543#discussioncomment-2786650

## Suggested Design

- introduce `func (s *IntegrationTestSuite) TestSuperfluidGovVoting() {...}
- Reproduce the listed commands by calling them via Docker test in e2e_test.go
- add a test where there is no SF delegation and assert that only validator has voted
- add a test where a non-superfluid (regular) staker votes and ensure that the vote is overridden

## Acceptance Criteria

- the manual test is fully converted to e2e
- similar test with no SF delegation is added and passes
- similar test with a regular staker added
- all new and existing tests pass

**Comment by czarcas7ic** [comment]
Closed via https://github.com/osmosis-labs/osmosis/pull/1586
