### ISSUE TITLE
Error: error during handshake,how to solve this problem！

### ISSUE THREAD

**Issue by sznariOsmosis** [osmosis-labs/osmosis#1562]
May 23 12:41:35 datalake cosmovisor[2388114]: 12:41PM INF Starting IndexerService service impl=IndexerService module=txindex
May 23 12:41:35 datalake cosmovisor[2388114]: 12:41PM INF ABCI Handshake App Info hash="4\x01\"��U�\x10H�s\aX-\x0f}�tM \v�`#Ra\x1a���q�" height=2383300 module=consensus protocol-version=0 software-version=6.4.1
May 23 12:41:35 datalake cosmovisor[2388114]: 12:41PM INF ABCI Replay Blocks appHeight=2383300 module=consensus stateHeight=2383300 storeHeight=2383301
May 23 12:41:35 datalake cosmovisor[2388114]: 12:41PM INF Replay last block using real app module=consensus
May 23 12:41:35 datalake cosmovisor[2388114]: Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 340122B3C355CA1048E07307582D0F7DB6744D200B8C602352611A92C7DD71DE, got 67366325F099CABB1667AB169584B746EFF7D83777EA3C6B845B470DF1B519BA
May 23 12:41:35 datalake cosmovisor[2388109]: 12:41PM ERR  error="exit status 1" module=cosmovisor
May 23 12:41:35 datalake systemd[1]: cosmovisor.service: Main process exited, code=exited, status=1/FAILURE

**Comment by ValarDragon** [comment]
Do we need to backport more db / snapshot related fixes to the v6.x line?

cc @p0mvn

**Comment by p0mvn** [comment]
Yes, I'll work on this and get back once `v6.x` is updated and released

**Comment by sznariOsmosis** [comment]
> Yes, I'll work on this and get back once `v6.x` is updated and released

Is it a bug of osmosis? , if it's a bug, when will this be fixed?

**Comment by sznariOsmosis** [comment]
> Do we need to backport more db / snapshot related fixes to the v6.x line?
> 
> cc @p0mvn



> Do we need to backport more db / snapshot related fixes to the v6.x line?
> 
> cc @p0mvn

Is it a bug of osmosis? , if it's a bug, when will this be fixed?

**Comment by czarcas7ic** [comment]
This happened at height 2383300 which is the v5 upgrade. This just means they didn't change their binary at the correct height

**Comment by sznariOsmosis** [comment]
> This happened at height 2383300 which is the v5 upgrade. This just means they didn't change their binary at the correct height

Thank you for replying to me so quickly, if this happens, how can I fix it, because it took me a few months to sync to 2383300, I don't want to sync data from 0 anymore, can you tell me how to fix it, thank you very much!

**Comment by czarcas7ic** [comment]
Can I ask why you are syncing from genesis? Firstly, it's very odd that it took months to do and secondly, if you just need the chain data you can download a archive snapshot from chainlayer instead. 

But to answer your question, you need to set the upgrades in this order:
V3,V4,V6,V8

This is due to the hardforks that took place. When you get an app hash error, the DB is corrupt and there is nothing you can do about it AFAIK

**Comment by sznariOsmosis** [comment]
> V3,V4,V6,V8

The archive snapshot file currently has a size of 4.0T. I can't download it in a limited time. I have tried downloading it, but it is updated every time it is halfway through the download, which causes the download to fail every time.

And I used the osmosis-install.py provided by you for the full node synchronization. There is no configuration cosmovisor in it. Will it automatically upgrade V3, V4, V5, V6, V8? Because the memory is only 16G, when upgrading V5 An error was reported, so I set the swap memory to 32G, and reduced 6.4.1 in V5 to V5.0.0. Could it be the database confusion caused by my downgraded version?

**Comment by czarcas7ic** [comment]
Yes that's correct, it should have been left at V6. If you did use the get.osmosis.zone tool, it would do all these upgrades for you. With that being said, I highly don't recommend running an archive node with 16GB base memory. I would say it would require 32GB base and that's a hard minimum. I'd be more inclined to say 64GB min for archive node

**Comment by sznariOsmosis** [comment]
> 是的，没错，它应该留在V6。如果您确实使用了 get.osmosis.zone 工具，它会为您完成所有这些升级。话虽如此，我强烈不建议运行具有 16GB 基本内存的存档节点。我会说它需要 32GB 的基础，这是一个很难的最低要求。我更倾向于说存档节点最少 64GB

Understand, I saw your reply last time, I was going to set the swap memory to 64G, but this error occurred later, but I have seen your upgrade document V5 version can use V5.0.0? , let's not talk about this, now that this situation has happened, is there any way to remedy it, I'm going to go crazy all over again

**Comment by sznariOsmosis** [comment]
> Yes that's correct, it should have been left at V6. If you did use the get.osmosis.zone tool, it would do all these upgrades for you. With that being said, I highly don't recommend running an archive node with 16GB base memory. I would say it would require 32GB base and that's a hard minimum. I'd be more inclined to say 64GB min for archive node

Understand, I saw your reply last time, I was going to set the swap memory to 64G, but this error occurred later, but I have seen your upgrade document V5 version can use V5.0.0? , let's not talk about this, now that this situation has happened, is there any way to remedy it, I'm going to go crazy all over again

**Comment by czarcas7ic** [comment]
I'm really sorry but once you hit app hash you have to resync. So here's the things: you can upgrade in order (v3,v4,v5,v6,v7,v8), but then you risk corruption which is what happened to you. Instead, if you follow the order I showed (3,4,6,8). Also to clarify, the installer used cosmovisor with this order. We don't use 5 and 7 since that would risk corruption

**Comment by sznariOsmosis** [comment]
> I'm really sorry but once you hit app hash you have to resync. So here's the things: you can upgrade in order (v3,v4,v5,v6,v7,v8), but then you risk corruption which is what happened to you. Instead, if you follow the order I showed (3,4,6,8). Also to clarify, the installer used cosmovisor with this order. We don't use 5 and 7 since that would risk corruption

Where can I download the snapshot data of 2 million heights?

**Comment by ValarDragon** [comment]
https://quicksync.io/networks/osmosis.html

There are some folks (valnodes) working on tooling that could potentially lower some of the replication factor of data in the archive nodes, but that won't really help you either.

Whats your goal in having an archive node? Can maybe suggest ways to tune your syncing to improve it. But I would just recommend getting everything to sync from genesis done via cosmovisor as get.osmosis.zone does.
