### ISSUE TITLE
Make pool-incentives queries show % of incentives

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1569]
## Background

Make pool incentives query show % of incentives going to that gauge ID

## Acceptance Criteria

- [ ] Either an existing query is amended, or a new query is added, to show % of total incentives going towards a particular gauge

**Comment by stackman27** [comment]
Hi @ValarDragon, i can work on this

**Comment by ValarDragon** [comment]
Awesome, ty!

**Comment by stackman27** [comment]
Hi @ValarDragon @mattverse is "% of incentives" the same as gauge_size? If so how do i calculate it? 

Also, how do i test whether the query returns the % incentives or not? Do i run `starport chain serve` and test the query or is there an alternate way?

**Comment by mattverse** [comment]
By % of incentives, it would probably be `gauge_size / total_incentive_amount *100`

per testing, you can use starport, or I usually use [local osmosis](https://stage-docs.osmosis.zone/developing/tools/localosmosis.html#what-is-localosmosis), create the necessary environment I need and then test if queries return output I'm expecting
