### ISSUE TITLE
[v10] Expedited Proposals

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1596]
## Background

In addition to variable vote times based on proposal type that is getting added to v9, we would like to add an expedited option for all proposals in the event of emergency situations.

## Suggested Design

A majority of this work has already by completed by @p0mvn in [#240](https://github.com/osmosis-labs/cosmos-sdk/pull/240)

## Acceptance Criteria

- [ ] Go through review process of [#240](https://github.com/osmosis-labs/cosmos-sdk/pull/240)
- [ ] Review [comments from commonwealth](https://commonwealth.im/osmosis/discussion/5035-governance-module-upgrade-twothirds-majority-emergency-voting-periods-24hr) on this feature
- [ ] #1687
- [x] #1688
- [ ] Include in v10 upgrade

**Comment by mattverse** [comment]
We need to discuss on the timeline we want to put up a text proposal for this since the feature itself is getting close to merge.

**Comment by p0mvn** [comment]
The only remaining item for this is manually / e2e testing. I am going to create a separate issue for this
