### ISSUE TITLE
[v10] Thirdening Testing

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1597]
## Background

While there is no reason to be suspicious of the code in place to reduce token emissions by 1/3rd every year (the thirdening), since this is a fairly significant event, it should get extensively tested prior to it happening.

## Suggested Design

Prior to June 18th
- [x] Spin up a state exported testnet
  - [x] Expedite the daily epoch to happen every 60 seconds
  - [x] Take note of emissions prior to thirdening
  - [x] Take note of emissions after thirdening
 - [x] Check osmo supply pre & post thirdening

## Acceptance Criteria

Actions related to thirdening are reviewed for any odd behaviors. If odd behavior is noted, a plan is put into action to address prior to June 18th

**Comment by czarcas7ic** [comment]
Epoch 364: 
- Start Height: 4642252
- Epoch Provisions: 821917808219.178082191780821917

Epoch 365:
- Start Height: 4642313
- Epoch Provisions: 821917808219.178082191780821917

Epoch 366:
- Start Height: 4642375
- Epoch Provisions: 821917808219.178082191780821917

Epoch 367:
- Start Height: 4642438
- Epoch Provisions: 547945205479.452054246575342465

Epoch provisions are now 2/3rds what it was, as expected. The thirdening will happen on epoch 367. This translates to the epoch that occurs on Monday, June 20th on mainnet.

**Comment by czarcas7ic** [comment]
I wanted to query to community pool and note the differences, but for some reason I think the state export broke this connection since the account I know to be the community pool does not increase at all (both pre and post thirdening).

**Comment by czarcas7ic** [comment]
My numbers weren't adding up for community pool, so this is my attempt at getting them to work for a dev reward wallet. Should be less varying factors. Doing it on this address osmo14kjcwdwcqsujkdt8n5qwpd8x8ty2rys5rjrdjj with 0.288700000000000000 weight

Epoch 364: 
- Start Height: 4642252
- Epoch Provisions: 821917808219.178082191780821917
  - Goes to dev rewards: 205479452054.79452054794520547925
  - Goes to specific wallet: dev rewards*0.2887=59321917808.219178082191780821859475
- Wallet Bal: 21533856163941

Epoch 365:
- Start Height: 4642313
- Epoch Provisions: 821917808219.178082191780821917
  - Goes to dev rewards: 205479452054.79452054794520547925
  - Goes to specific wallet: dev rewards*0.2887=59321917808.219178082191780821859475
  - Add rewards to previous wallet balance to get expected wallet bal
    - 59321917808.219178082191780821859475 + 21533856163941 = 21593178081749.219178082191780821859475
- Actual Wallet Bal: 21593178081748
- Dif is -1.21917808219 less osmo than expected

Epoch 366:
- Start Height: 4642375
- Epoch Provisions: 821917808219.178082191780821917
  - Goes to dev rewards (25%): 205479452054.79452054794520547925
  - Goes to specific wallet: dev rewards*0.2887=59321917808.219178082191780821859475
  - Add rewards to previous wallet balance to get expected wallet bal
    - 59321917808.219178082191780821859475 + 21593178081748 = 21652499999556.219178082191780821859475
- Actual Wallet Bal: 21652499999555
- Dif is -1.21917808219 less osmo than expected

Epoch 367:
- Start Height: 4642438
- Epoch Provisions: 547945205479.452054246575342465
  - Goes to dev rewards: 136986301369.86301356164383561625
  - Goes to specific wallet: dev rewards*0.2887 = 39547945205.479452015246575342411375
  - Add rewards to previous wallet balance to get expected wallet bal
    - 39547945205.479452015246575342411375 + 21652499999555 = 21692047944760.479452015246575342411375
- Actual Wallet Bal: 21692047944760
- Dif is -0.479452015 less osmo than expected

**Comment by czarcas7ic** [comment]
Spun up another testnet to check total supply

Epoch 364: 
- Start Height: 4694728
- Epoch Provisions: 821917808219.178082191780821917
- Total Supply
  - 2581482187359696

Epoch 365:
- Start Height: 4694784
- Epoch Provisions: 821917808219.178082191780821917
- Total Supply
  - 2582304105167908
- Epoch 365 supply - epoch 364 supply should equal epoch provisions
  - 2582304105167908 - 2581482187359696 = 821917808212
  - 821917808219.178082191780821917 - 821917808212 = 7.178082191780821917
  - ~7.18 osmo unaccounted for

Epoch 366:
- Start Height: 4694841
- Epoch Provisions: 821917808219.178082191780821917
- Total Supply
  - 2583126022976120
- Epoch 366 supply - epoch 365 supply should equal epoch provisions
  - 2583126022976120 - 2582304105167908 = 821917808212
  - 821917808219.178082191780821917 - 821917808212 = 7.178082191780821917
  - ~7.18 osmo unaccounted for

Epoch 367:
- Start Height: 4694896
- Epoch Provisions: 547945205479.452054246575342465
- Total Supply
  - 2583673968181593
- Epoch 367 supply - epoch 366 supply should equal epoch provisions
  - 2583673968181593 - 2583126022976120 = 547945205473
  - 547945205479.452054246575342465 - 547945205473 = 6.452054246575342465
  - ~6.45 osmo unaccounted for

**Comment by czarcas7ic** [comment]
Are we happy with the above tests? If so, I will close this issue

**Comment by ValarDragon** [comment]
Yeah,thanks! We can just keep an eye on the total supply query on mainnet as a final sanity check
