### ISSUE TITLE
[v10] Make a Cosmwasm query to query the admin of a denom

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1603]
## Background

Make a cosmwasm binding to query the admin of a denom

## Suggested Design

If a token is not a factory denom return "". Otherwise make a straightforward binding for just querying the keeper.  

## Acceptance Criteria

- [ ] Its easy for a cosmwasm contract to find the current admin of a denom

**Comment by alexanderbez** [comment]
I would like to get my hands dirty with wasm and bindings. Mind if I tackle this (might need a bit of guidance but I'll try to figure it out on my own).

**Comment by ValarDragon** [comment]
Absolutely go for it!

**Comment by p0mvn** [comment]
This query would be useful for unit testing contracts. Right now, in the example contract: https://github.com/osmosis-labs/osmosis-bindings/pull/9 , after unit testing "change admin" there is no way to query and verify the correctness of the admin change.

Once this query is implemented, we should come back to the example contract and add some logic utilizing the query in unit tests
