### ISSUE TITLE
Enable mainnet-only upgrades 

### ISSUE THREAD

**Issue by joeabbey** [osmosis-labs/osmosis#1612]
## Background

From time to time, balances are adjusted, or parameters are changed but only need to be performed on the mainnet (currently `osmosis-1`) 

The ChainID can change, during an upgrade, or someone could create another chain using the osmosis code, etc.

We need a way in upgrade handlers to determine if sections of code should run or not.

## Suggested Design

Add a new config in genesis to apply mainnet state specific upgrades.

**Comment by ValarDragon** [comment]
Very agreed, needs to be a config so that state export testnets for simulating the upgrade can easily do it.

On first pass, I'm thinking the easiest way to do this would be adding a new param to the upgrade module, does that seem like the right abstraction here? I think we have this parameter default to "false"

I guess that would suck in that it won't help old software versions, but do we care about that? There shouldn't really be testnets starting from genesis?

**Comment by joeabbey** [comment]
> I guess that would suck in that it won't help old software versions, but do we care about that? There shouldn't really be testnets starting from genesis?

old software versions would have to adapt to the presence of this new configuration... which I suppose could be backported (to older versions and upgrade handlers)

personally, i'd go with the LLVM model of just supporting latest

**Comment by ValarDragon** [comment]
Came up in call with @czarcas7ic earlier today, a binary setting is likely insufficient. Theres at least three options we'd like to distinguish between:
1) mainnet state / state export
2) No custom state migration
3) testnet limited state (so we can test the upgrade in CI)

for limited state, it'd be like limiting the pool IDs. 

Is there a clean way to do enums with the params module atm? If not I guess we just make this parameter in the upgrades module a string, and validate the 3 values it can have. (cc @alexanderbez )

**Comment by ValarDragon** [comment]
How does this sound:

* Make a new param in the upgrades keeper of type `bool`, called "IsMainnetState"

Then we just do testing of limited state on clean testnets ad-hocly.

**Comment by alexanderbez** [comment]
@ValarDragon so `x/params` is being deprecated in favor of the module itself managing its own params. However, that won't be out in the SDK until the next major release (hopefully soon).

In the meantime, in our fork of the SDK we can add a string parameter, that is enumerated, in `x/upgrade` and use that in the upgrade handler to execute certain flows (which is what I think you're getting at). So yeah, ACK.
