### ISSUE TITLE
Make module dependency graph

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1635]
## Background

_Originally posted by @ValarDragon in https://github.com/osmosis-labs/osmosis/pull/1621#discussion_r885540815_

We should make a visual dependency graph of the Osmosis modules in the `x/README.md` file. 

## Suggested Design

I suggest using graphviz to do this, and we label the edges with some brief description of what it depends on it for.  https://stackoverflow.com/questions/46872521/draw-a-program-dependence-graph-with-graphviz

Perhaps graphviz isn't best, relative to like google draw or something though. Thoughts? I wonder what the ICS specs do

## Acceptance Criteria

- [ ] Dependency diagram exists somewhere, showing at a glance how our modules interact with one another.

**Comment by mattverse** [comment]
Hey @xBalbinus  mind if I take over this real quick?

**Comment by xBalbinus** [comment]
Hey Matt, I’ve already started some work on it, could you help feedback
this? Im sending it to you over slack
