### ISSUE TITLE
x/lockup: Enable users to elongate the lockup period for locked tokens

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#164]
Suppose a user has locked up 10 tokens for 2 days. We should allow them to increase the lockup period to 1 week, without having to unlock and relock. This will probably require a new message type in x/lockup to do this, as we need the user to specify which initial lockup time duration they want to increase.

(E.g. if they have 10 tokens locked for 2 days, 20 tokens locked for 4 days, and want to move the 20 tokens to a lockup of 1 week)

Also this should only support increasing the lockup duration, not decreasing it

**Comment by ValarDragon** [comment]
Prelaunch we should just ensure that this will be easy to upgrade in the future / double check how we handle state / implicit assumptions around this.

**Comment by mconcat** [comment]
Adding `MsgEditLockup` would work and we can check that lockup duration change is positive in `ValidateBasic`. This would be extensible in the future for other modifications too.
