### ISSUE TITLE
Documentation for adding wasm module into osmosis

### ISSUE THREAD

**Issue by jatinder116** [osmosis-labs/osmosis#1659]
Hi, Could you pelase suggest me how can I add wasm module into the custom blockchain.  Suggest me a some path how can I do this?

**Comment by ValarDragon** [comment]
If your looking for how to add cosmwasm into your own blockchain, look at https://github.com/CosmWasm/wasmd/tree/main/app, basically take any reference to wasm there and do it on your chain as well.
(Feel free to look at Osmosis' app folder for how we think about better structuring app folder code) It is unfortunate that this is a part of the SDK that is awful to work with, its going through active improvement right now.

It may also be in the cosmwasm docs.

Unfortunately, this repo is not the right place to discuss problems you have in integration of the wasm into your own blockchain. If you have more specific questions about Osmosis instantiation please re-open or make a new issue!
