### ISSUE TITLE
Minor bug: docs/core/proto-docs.md is not updated to proto change

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [osmosis-labs/osmosis#1660]
Ever since the decision to move to tendermintdev/sdk-proto-gen:v0.7 in makefile, proto-docs.md is not generated even if proto is changed. I have tried this changing proto and proto-docs.md is not generated.

This is contributed to:
1. no rule for protoc-gen-doc like this in bug.gen.gogo.yaml
![Screenshot from 2022-06-03 13-14-30](https://user-images.githubusercontent.com/23058164/171797605-1526291f-b665-4526-b3eb-de14833ee0a2.png)

2. if we decide to include generating proto-docs.md feature again, we should move to tendermintdev/sdk-proto-gen:v0.3

cc @alexanderbez

**Comment by ValarDragon** [comment]
Closed by #2834
