### ISSUE TITLE
Move wasm-bindings code out of app

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1667]
## Background

Currently the `wasm` package for bindings is in a package within `app`. I think it stands on its own as a `wasm-bindings` package in the top level directory.

I feel like it being in the app package is a different structure than I would a-priori expect coming into the repository.

## Suggested Design

Refactor `/app/wasm` to `/wasm-bindings`

**Comment by ValarDragon** [comment]
<!-- < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < ☺
v                               ✰  Thanks for creating an issue! ✰    
☺ > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >  --

## Background

Currently the `wasm` package for bindings is in a package within `app`. I think it stands on its own as a `wasm-bindings` package in the top level directory.

I feel like it being in the app package is a different structure than I would a-priori expect coming into the repository.

## Suggested Design

Refactor `/app/wasm` to `/wasm-bindings`

**Comment by vuong177** [comment]
Hi @ValarDragon, could I work on this ?

**Comment by ValarDragon** [comment]
Sure!
