### ISSUE TITLE
[Story][Dockerfile Improvements] Generalize and reduce the number of Dockerfiles

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1679]
## Background

> As an Osmosis engineer, I would like our Dockerfiles to be reusable and modular so that I don't have to make changes in many files and avoid the images going out of sync

Our Dockerfiles share a lot of the same logic. On one side of the issue, some folks update all Dockerfiles, wasting time for no reason. On the other side, other folks only update some, letting the images go out of sync. 

First, we should remove images that are not used. Second, we should investigate the rest.  Some can be generalized to be used as a base, and the rest import that base.

- #1684 
- #1685

## Status
- June 6 - WIP: Defining Scope

**Comment by niccoloraspa** [comment]
At the time of the issue we had the following Dockerimages:

```bash
❯ find . -iname "*dockerfile*"

./Dockerfile
./tests/localosmosis/Dockerfile
./tests/localosmosis/mainnet_state/Dockerfile-stateExport
./tests/e2e/initialization/init.Dockerfile
./contrib/images/osmobuilder/Dockerfile
./contrib/images/rbuilder/Dockerfile
```

Fixing https://github.com/osmosis-labs/osmosis/issues/2482, we removed the `contrib` folder and the following images:

```bash
./contrib/images/osmobuilder/Dockerfile
./contrib/images/rbuilder/Dockerfile
```

**Comment by niccoloraspa** [comment]
Removed also:

```bash
./tests/localosmosis/Dockerfile
./tests/localosmosis/mainnet_state/Dockerfile-stateExport
```

**Comment by ValarDragon** [comment]
Seeing that theres only two dockerfiles remaining, can we close this issue?

**Comment by niccoloraspa** [comment]
Yes. Closing
