### ISSUE TITLE
[Story][Dockerfile Improvements] Reduce size and improve compatibility

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1681]
## Background

> As an Osmosis engineer, I would like images to be lightweight and compatible with any environment so that they work on any platform I happen to work on

Oftentimes, I find that our images and/or binaries might work on some OS/VM and not others. When my environment changes, I happen to spend the majority of my time debugging our Docker images instead of focusing on a task.

#### Task 4.1 -  Allow Images to be Built as Non-root
The major bottleneck in this category is that our images are built as a root. This has caused me issues numerous times. For example, when we create files in a container mounted on a volume, these files cannot be removed from the host unless the host is root. While this is not an issue locally, it is troublesome in CI.

This issue was fixed [earlier for our release scripts](https://github.com/osmosis-labs/osmosis/pull/1286) but it seems to be broken again. Our main image and any other image that creates files on a volume (a lot of them are in e2e tests) should have the ability to be built as non-root.

#### Task 4.2 
`RUN`, `COPY`, and `ADD` directives add additional layers, contributing to bigger image size. We should minimize these.

For example, these `RUN`s could probably be on one line:
https://github.com/osmosis-labs/osmosis/blob/d5cd03329b7edc028f2793f95d4c4e85e62060fb/Dockerfile#L11-L14

##### Resources
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers

## Status
- Blocked by: #1679

**Comment by ValarDragon** [comment]
Closed by https://github.com/osmosis-labs/osmosis/pull/2876
