### ISSUE TITLE
[Story][Dockerfile Improvements] Reduce image build times

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1682]
## Background

> As an Osmosis engineer, I would like to reduce image build times so that I don't waste time or focus on waiting for no reason. 

This is a huge impediment to productivity where every time a developer makes a change to an image, they have to wait for around 4 minutes, and, as a result, lose the flow. The image build times should be minimized by structuring the steps and stages optimally and removing redundant steps.

#### Task 3.1 - Remove stale or redundant steps

Investigate all our images to remove stale or redundant steps that may have become such due to the repository evolving over time.

An example:
https://github.com/osmosis-labs/osmosis/blob/d5cd03329b7edc028f2793f95d4c4e85e62060fb/tests/e2e/chain_init/chain-init.Dockerfile#L17-L20
We don't need to have `ADD` and `RUN` for both architectures in most Dockerfiles. Instead, we should provide architecture as an argument to the Dockerfile and only `ADD` and `RUN` wasm libraries for the desired one.

#### Task 3.2 - Leverage Build Cache

We should leverage build-cache by structuring the steps in each Dockerfile in such a fashion as so to minimize the rebuild frequency. 

One example relevant to this issue is evident here:
https://github.com/osmosis-labs/osmosis/blob/d5cd03329b7edc028f2793f95d4c4e85e62060fb/Dockerfile#L17-L23

`COPY` directive requires updates **much** more frequently than the subsequent `ADD`s and `RUN`s. As a result, every time we make a change to the codebase and attempt to rebuild an image, it will redundantly repeat `ADD` and `RUN` steps simply because these are located after `COPY`

##### Resources
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache
- See `Tip #1`: https://www.docker.com/blog/intro-guide-to-dockerfile-best-practices/

## Status
- Blocked by: #1679

**Comment by ValarDragon** [comment]
Closed by https://github.com/osmosis-labs/osmosis/pull/2876
