### ISSUE TITLE
[Story][Dockerfile Improvements] Documentation and QA

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1683]
## Background

> As an Osmosis engineer, I would like to have a document about best practices with Dockerfiles and requirements for Osmosis so that I can QA changes easily during review and maintain an excellent condition of our Docker files long-term. 

It is challenging to onboard on Docker while easy to forget the details when switching contexts. Therefore, we should document the best practices and Dockerfiles requirements for Osmosis. New contributors should use these to understand what changes may be done to our Dockerfiles. Maintainers and reviewers can use these to QA in pull request reviews. 

## Status
- Blocked by:
   * #1679
   * #1680
   * #1682
   * #1681

**Comment by ValarDragon** [comment]
All done
