### ISSUE TITLE
[Task][Dockerfile Improvements] Remove stale or unused Dockerfiles

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1684]
## Background

Currently, we have the following Dockerfiles:
- https://github.com/osmosis-labs/osmosis/blob/main/Dockerfile
- https://github.com/osmosis-labs/osmosis/blob/main/tests/localosmosis/Dockerfile
- https://github.com/osmosis-labs/osmosis/blob/main/contrib/images/rbuilder/Dockerfile
- https://github.com/osmosis-labs/osmosis/blob/main/contrib/images/osmobuilder/Dockerfile
- https://github.com/osmosis-labs/osmosis/blob/main/contrib/images/simd-env/Dockerfile
- https://github.com/osmosis-labs/osmosis/blob/main/tests/e2e/chain_init/chain-init.Dockerfile

Investigate which files can be removed. Communicate with the team if needed. In particular, `rbuilder` and `osmobuilder` Dockerfiles are probably duplicates.

## Status
- June 6: TBD - Needs to be prioritized

## Acceptance Criteria
- Investigate the purpose and use of each Dockerfile
- Document the findings by commenting in this issue in the following format:

> < Link to Dockerfile >
< Short description about how the file is used, why it should be kept or removed >
< Final decision about whether to keep the file (Keep / Remove), link PR if to remove >

Example:
> Link: https://github.com/osmosis-labs/osmosis/blob/main/Dockerfile
Description: Main Dockerfile used to build the Osmosis project. It should be kept as it is in use...
Decision: Keep

- All stale and redundant Dockerfiles are removed

**Comment by ValarDragon** [comment]
Closed by @niccoloraspa 's recent PRs I believe / being tracked in #1685
