### ISSUE TITLE
[Task][Dockerfile Improvements] Generalize Docker files and reuse them where applicable

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1685]
## Background

Most, if not all of our Dockerfiles share the same lines of code at the beginning:
https://github.com/osmosis-labs/osmosis/blob/d5cd03329b7edc028f2793f95d4c4e85e62060fb/Dockerfile#L9-L28

This can be extracted into its own base image and reused across the rest.

## Status
- June 6 - WIP: Defining Scope
- Blocked by: #1684

## Acceptance Criteria
- TBD

**Comment by ValarDragon** [comment]
I believe this has been done?
