### ISSUE TITLE
Rebase our SDK fork onto SDK `release/v0.45.x`

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1686]
## Background

We should rebase our SDK `osmosis-main` branch onto `release/v0.45.x`. It has a number of chain operator UX wins, and dev UX wins / bug mitigations that we want to take advantage of.

This will help us save a lot of time in getting some of these UX wins into Osmosis and reducing the incompatibility complexity we have with SDK release lines.

If this is taken up after the `SDK v0.45.5` release is made, use that instead

## Suggested Design

Try
```
git checkout osmosis-main
git pull
git checkout -b {yourname}/{osmosis-main-rebase}
git rebase -i release/v0.45.x
```

If rebasing doesn't work, then we have to just cherry-pick each of our commits directly onto this fork. (And we should write a bit about the process, to see how we can better automate steps in the future)

There are a few commits we should drop, due to them getting upstreamed as well.

Then we do a detailed manual review of the branch before we swap out `osmosis-main`.

## Acceptance Criteria

**Comment by alexanderbez** [comment]
Ohh boy. Ok, I can give this a shot. What sprint do we want this for?

**Comment by ValarDragon** [comment]
Can be current sprint if you have time, or next sprint

Not super urgent, but generally better to have sooner rather than later
