### ISSUE TITLE
Put up text proposal for enabling expedited proposals

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1688]
This issue is about drafting up a text proposal for enabling expedited proposals.

**Acceptance Criteria**
- A draft is created and approved
- The proposal is put on chain

**Comment by alexanderbez** [comment]
Que?

**Comment by p0mvn** [comment]
Updated description, I'm working on this

**Comment by p0mvn** [comment]
The draft is created and approved. What is our plan for this?

**Comment by p0mvn** [comment]
This is on chain
