### ISSUE TITLE
Snapshot manager

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1697]
#### System information

v9
all
#### Expected behaviour

snapshot manager should be configured

#### Actual behaviour

it isn't 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by p0mvn** [comment]
This should be fixed in https://github.com/osmosis-labs/cosmos-sdk/pull/236. Going to backport to v9 and release

**Comment by p0mvn** [comment]
Going to keep this open until https://github.com/osmosis-labs/osmosis/pull/1698 gets in

**Comment by faddat** [comment]
Since I've reviewed #1708 and feel it is best to get that on testnet, I'll complete #1698 now

❤️
