### ISSUE TITLE
Finalize exit fee logic for Osmosis v1

### ISSUE THREAD

**Issue by Thunnini** [osmosis-labs/osmosis#171]
https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/pool_service.go#L336

As described in the code comments, the current x/gamm module can set the exit fee, but there is no logic to process the exit fee. Since we're very close to launch, we need to finalize how to handle this.

I think there are three options:
1. Remove the exit fee entirely
2. Send the exit fee to the community pool
3. Send the exit fee to the fee pool and distribute it to delegators as rewards

**Comment by ValarDragon** [comment]
If we assume there exists a pot with lockup time of `< 1s` for each pool, we can send the exit fee to that. I think this fee should be going to the existing pool LPs, not the chain as a whole

**Comment by sunnya97** [comment]
Is it not possible to just leave the fee amount in the pool?  Wouldn't that give it to the remaining LPs?

**Comment by Thunnini** [comment]
@ValarDragon Sounds good. It would be nice for the pool incentives module to be fixed and merged, then discuss how to implement it.
@sunnya97 Right now, the distribution can only handle pool assets. Because exit fee is not included as a pool asset, the current implementation doesn't support it.
