### ISSUE TITLE
Validate updates to numShares and newLiquidity in  `CalcJoinPoolShares`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1722]
Unit tests for `CalcJoinPoolShares` validating that these updates happen should be added in  a separate PR

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/1721#discussion_r893043336_

**Comment by mattverse** [comment]
We need https://github.com/osmosis-labs/osmosis/pull/1732/files merged to push this foward

**Comment by mattverse** [comment]
Currently on getting #1713 getting merged by adding test cases with different ratio

**Comment by mattverse** [comment]
https://github.com/osmosis-labs/osmosis/pull/1767 closes this
