### ISSUE TITLE
v10 Replace Mintscan Links

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1744]
Update mintscan links (one example here https://github.com/osmosis-labs/osmosis/commit/2bf34ddb229d43620622263f1882ac4e3001d8d8#diff-27f66338b65628440c075318651b24c6df974603549d69c1530b1aae1ce54d0dR52) with the new txs that change out community pool verbiage for multi sig account

**Comment by ValarDragon** [comment]
Irregular state change removed.
