### ISSUE TITLE
Make separate methods for single vs multi tokensIn calc.

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1745]
This is not specific to this PR. I just kept thinking about this while working on this method over these past few days. Basically, I think that we should have separate methods for single tokenIn calc and multi tokensIn calc.

The way it is done currently is violating the "Single responsibility principle" in SOLID where the method does 2 things.
It makes it less testable and less abstract IMO. We should consider addressing this post v10. Please create an issue if you agree. If not, please ignore

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/1737#discussion_r894140370_

**Comment by AlpinYukseloglu** [comment]
We should wait until #1721 is merged until we do this or work directly off that branch to avoid conflicts
