### ISSUE TITLE
Try buildjet CI for faster CI times

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1748]
## Summary

Propose that we use buildjet.io

We'd need to pay a very reasonable price to use it:

https://buildjet.com/for-github-actions/pricing

And then, we can take all of our current jobs running on ubuntu-latest, and change that to to one of the models in this table

https://buildjet.com/for-github-actions/docs/runners

<img width="612" alt="Screen Shot 2022-06-10 at 5 16 11 PM" src="https://user-images.githubusercontent.com/7142025/173044637-8ede58f5-3dcb-4d5d-9d31-26b7638eaafc.png">

Penumbra got a huge speed boost this way, and I understand it's affordable too. 

## Problem Definition

Our CI jobs take too long to complete right now. 

## Proposal

A repository admin would need to install buildjet on this repo.  Then a developer (I propose myself) can modify only the runs-on line of the github actions.  Then we will have vastly faster CI.

**Comment by alexanderbez** [comment]
Thoughts @ValarDragon?

**Comment by ValarDragon** [comment]
Im extremely down

**Comment by alexanderbez** [comment]
I guess we just need to setup billing and then what else do we do @faddat?

**Comment by ValarDragon** [comment]
@faddat can you take a look / a stab at it? My first attempt doesn't have any speedup on the go test either, but could be some odd cache effects:

before: https://github.com/osmosis-labs/osmosis/runs/6848775384?check_suite_focus=true
after: https://github.com/osmosis-labs/osmosis/runs/6848775384?check_suite_focus=true

it actually got 20 seconds slower!

**Comment by faddat** [comment]
hey, worrying thing-- I may have similar results elsewhere. 


I am doing this / working on this for pylons, but may even remove it. 

Having decent servers can be an easy massive sppeedup, but I am not sure that this is going to get us there.

**Comment by ValarDragon** [comment]
We tried this without success, so closing for now
