### ISSUE TITLE
fix: Change `PowApprox` to return one when exponent is 0

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1752]
## Background

`PowApprox` currently returns zero when the exponent is zero, whilst imo should be returning 1 when the exponent over is zero.
https://github.com/osmosis-labs/osmosis/blob/main/osmomath/math.go#L86-L88

We should change this to return `sdk.OneDec()`

## Acceptance Criteria

> Goals & criteria for success

- [ ] confirm that this `PowApprox` should be returning `1` instead of `0` in the case of having zero exponent. 
- [ ] create test cases for this specific case

**Comment by ValarDragon** [comment]
oof, can you PR a fix. Lets get this backported.
