### ISSUE TITLE
Improve backport bot

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1772]
## Background

We should make our backport bot able to make a commit to fix any import version mismatches / conflicts when backporting a PR.

## Suggested Design

TODO: if theres no merge conflict, its easy, not sure how to best do it in presence of merge conflicts.

**Comment by alexanderbez** [comment]
What's a "import version mismatches / conflicts"?

**Comment by ValarDragon** [comment]
A commit to main uses the "github.com/osmosis-labs/osmosis/v7" import path, the commit in the backport needs  "github.com/osmosis-labs/osmosis/v9"
