### ISSUE TITLE
Update import paths from v9 to v10 on v10.x

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1785]
**Context**

v10.x branch has outdated import paths ([example](https://github.com/osmosis-labs/osmosis/blob/e1babbdbe480b04ed1c0b80c07dbfe884420b902/x/epochs/abci.go#L7)). We need to update them with v10 by doing search and replace

**Acceptance Criteria**
- all import paths are updated to v10 on `v10.x` branch
- all tests continue to pass

**Comment by xBalbinus** [comment]
May be closed by #2000 (draft atm)
