### ISSUE TITLE
test: investigate and document all methods that use exit fee to futher unit-test

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1788]
## Background

Most of our test cases use 0 exit fees. We should ensure that we also test with non-zero where applicable.

## Acceptance Criteria

- Compile a list of all methods that use/take exit fee. That includes all pools in `x/gamm/pool-models`
- Create issues for unit testing each

**Comment by mattverse** [comment]
Also add tests for hand derived values

**Comment by p0mvn** [comment]
Exit fee is now disabled. This task is obsolete
