### ISSUE TITLE
Log Message - ERR no delegation distribution info

### ISSUE THREAD

**Issue by chris-remus** [osmosis-labs/osmosis#1797]
## Background

During the network restart using ``v10.0.0`` our logs displayed only the following message immediately after restarting ``osmosisd``.

```ERR no delegation distribution info```

Upon [reporting this](https://discord.com/channels/798583171548840026/842550346865180682/985578355648774174) to the Osmosis Validators discord channel, @ValarDragon [explained ](https://discord.com/channels/798583171548840026/842550346865180682/985578461596880947)the message was due to "no swaps in that pool" and asked me to create this issue so the log messaging could be improved.

## Suggested Design

TBD

## Acceptance Criteria

TBD

**Comment by SlingshotCade** [comment]
I too have run into this problem after upgrading to Osmosisd 10.0.0.    Once this issue shows up in the logs then the API stops responding (port 26657).    A couple times I restarted cosmovisor and it started to work again.   But then the "ERR no delegation distribution info"  shows up and then the server stops working.  Is there any more information on this?

**Comment by ValarDragon** [comment]
The API is down generally due to epoch time, which is a more a longstanding problem with queries aren't available during block execution.

**Comment by mattverse** [comment]
After investigation, noticed that we had this error not because the pool didn't have any swaps in between epochs, it's because we don't delete intermediary accounts. Working on a PR with the fix

**Comment by ValarDragon** [comment]
Hrmm, don't we need to be careful wrt when we need to delete intermediary accounts? (IIRC theres something in the spec about this)

**Comment by effofxprime** [comment]
Regarding this issue, since I also face the same error, is it possible that it's causing a performance hit that I've described here in this ticket (https://github.com/osmosis-labs/osmosis/issues/2173) ?

**Comment by mattverse** [comment]
Epoch has performance hit mainly because of distribution logic and internal logics that's happening in epoch time, shouldn't have relation with the error log we see here

**Comment by ValarDragon** [comment]
I believe this has been fixed
