### ISSUE TITLE
Make panic be wrapped to show block height

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1798]
## Background

Current panic does not leave any information on the block height it panicked, we'd love to have the panic be wrapped around block height for better logging.

## Acceptance Criteria

-  make panic log panic height

**Comment by alexanderbez** [comment]
What panics in specific?

**Comment by mattverse** [comment]
basically anything that panics: we want to add the paniced blocked height along with the panic log

**Comment by ValarDragon** [comment]
Wouild be nice for anything panic. What we observed in chain relaunch was in `osmoutils.ApplyFuncIfNoError`

**Comment by mattverse** [comment]
tbh, along with adding a wrapper to show panic height, I think we should strictly restrict the usage of `osmoutils.ApplyFuncIfNoError`, they can turn out to be super gnarly

**Comment by ValarDragon** [comment]
Can you expand a bit more on what you mean by "we should strictly restrict the usage of osmoutils.ApplyFuncIfNoError, they can turn out to be super gnarly" ?

**Comment by ValarDragon** [comment]
Closing for now, actually not that clear how to action on the very particular logging issue.
