### ISSUE TITLE
Update to IBC-go v3.1.0

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1808]
## Background

We should update to IBC-go v3.1

It requires a state migration to fix IBC'ing of assets with a slash in them (LP shares)

## Suggested Design

I'd suggest this be blocked until a decision is reached for https://github.com/cosmos/ibc-go/issues/1542 , would prefer the full function's complexity not have to be in our repo. 

## Acceptance Criteria

- [ ] Upgrade to IBC v3.1.x
- [ ] State migration exists for allowing transferral of denoms with a `/` in them.

**Comment by alexanderbez** [comment]
> would prefer the full function's complexity not have to be in our repo.

Totally agree here.
