### ISSUE TITLE
Distribution events not displaying for external gauges

### ISSUE THREAD

**Issue by IbrarMakaveli** [osmosis-labs/osmosis#1814]
#### System information

Osmosis version: `10.0.0`
OS & Version: Windows/Linux/OSX
Commit hash: 

#### Expected behaviour

Display `"distribution"` event in the json block BeginBlock/EndBlock that displays the distribution external rewards for each address, which worked before the v9 upgrade

#### Actual behaviour

Download block_result : https://cloud.digitalocean.com/spaces/osmosis-halt-data?i=c27b8c&path=block_result%2F

If we take the address `osmo1dfxf4nchfzzrmqk7pedgckz46yagg700cn449t` for example :
I can see on `4667584.json` there are 2 `"type": "distribution"` : one with external and partial-OSMO rewards for this epoch and one with partial-OSMO user rewards for this epoch
I can see on `4727047.json` there are 1 `"type": "distribution"` : one with partial-OSMO user rewards for this epoch

Calculation take into account this 2 distribution before v9, it was simply make sum of the 2 distributions (group by address and denom) and I get the user rewards for that epoch

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by mattverse** [comment]
This is interesting in the sense that we haven't changed any of the distribution code pre and post v9

**Comment by ValarDragon** [comment]
This has been fixed sometime in v12, apologies for the headache this caused
