### ISSUE TITLE
Idea: add property-based testing to Osmosis via QuickCheck

### ISSUE THREAD

**Issue by pwang00** [osmosis-labs/osmosis#1818]
## Background

I'm not sure if this is a good idea or applicable for Osmosis, but I was thinking we could also use https://pkg.go.dev/testing/quick in the future for writing tests in addition to what we currently have.  This is Go's version of Haskell's QuickCheck (https://hackage.haskell.org/package/QuickCheck).

QuickCheck essentially allows a programmer to test particular properties / invariants of programs by allowing them to specify predicates to be tested and generators for test cases.  At runtime, QuickCheck will generate hundreds of test cases and check that all of them satisfy the specified predicate.  I think the main benefit of QuickCheck is that it forces developers to focus on writing invariants that all test cases of a particular form should satisfy, instead of individual test cases for a particular invariant.  Here is a simplified example of what I mean:

Suppose we had a fractional type with constructor `Frac(num, denom)` that we would like to test performs addition correctly--that is: Frac(a, b) + Frac(c, d) = Frac(ad + bc, bd); normally, we would have to write individual test cases such as 

```
assert FractionalAdd(Frac(1, 2), Frac(1, 3)) = Frac(5, 6) 
assert FractionalAdd(Frac(1, 2), Frac(1, 2)) = Frac(3, 3)
```

With QuickCheck, we can instead specify a generator for Fractional types--a fraction is of the form a/b where a and b are integers, so a generator for `Frac` instances should generate 2 random integers for numerators and denominators and construct a `Frac` instance from them.  We can then specify the property: Frac(a, b) + Frac(c, d) = Frac(ad + bc, bd), and at runtime, QuickCheck would use our defined generator to automatically generate `Frac` instances and check that each one satisfies the above property.  Note that division by zero is not defined, so we can further add a constraint in our predicate that discards all generated cases whose denominator is zero.  Since QuickCheck can generate hundreds of test cases, we can be reasonably certain (much more so than if we were to just test using the two cases above) that if the tests pass, our fractional type does indeed implement addition correctly.  

I think using QuickCheck might help condense testing code in Osmosis, make more obvious what properties are being tested, and decrease the possibility of bugs occurring due to missed edge cases.

Resource for those interested: https://mayank0403.github.io/assets/pdf/CR18-PPT.pdf

## Suggested Design

- Add / test properties for Osmosis's Decimal type

## Acceptance Criteria

- QuickCheck integration succeeds
- All existing and new tests should pass

**Comment by mattverse** [comment]
oh intereseting, is this a fuzzing testing method?

**Comment by mattverse** [comment]
oh intereseting, is this a fuzzing testing method?

**Comment by p0mvn** [comment]
This sounds like a great suggestion. I'm also wondering - what are the benefits that QuickCheck provides over 1.18 [Go Fuzzing](https://go.dev/doc/fuzz/)?

**Comment by pwang00** [comment]
> oh intereseting, is my understanding correct that the library fuzzes to check certain assertions are true or not? I wonder how this is different from fuzzing introduced in go 1.18

Yeah that's kind of what property-based testing aims to accomplish; there are distinctions between property-based testing (what QuickCheck does) and fuzzing though, which https://www.tedinski.com/2018/12/11/fuzzing-and-property-testing.html explains in more detail--in particular, this excerpt:

---

But the two techniques are best applicable in different circumstances:

 - Because property testing involves the programmer describing “interesting” inputs to test, bizarre (and security-critical) inputs may not be considered. Fuzzing is therefore the tool of choice for ensuring software is robust to attacks, as it bakes in no such assumptions.

- Because fuzzing requires so much time to run, it cannot act as a replacement for example-based unit testing, while property testing can. When it comes to testing almost any property outside of security, property testing will generally be superior.


The QuickCheck library was just a suggestion (I only know of it from Haskell)--I think the fuzzing library may also work for our purposes, though it does seem kind of restrictive in what can be fuzzed:

---

The fuzzing arguments can only be the following types:
```string, []byte
int, int8, int16, int32/rune, int64
uint, uint8/byte, uint16, uint32, uint64
float32, float64
bool```

**Comment by ValarDragon** [comment]
Closing this! Using fuzz testing tooling would be great!

Just looks like go fuzz replaces quickcheck for golang! (Where it built on the quickcheck features)
