### ISSUE TITLE
Add section to Contributing.md detailing our desired pre-release code auditing process

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1830]
## Background

We should add a section to the contributing.md labeled "Major release" and detail:
* The actual release workflow #1663 
* The pre-release internal auditing process we've discussed

## Suggested Design

The pre-release audit process we discussed last thursday was:
* For every module with notable changes, assign someone who was not a primary author of those changes to review the entire module
* Deliverables of review are:
  * PR's with in-line code comments for things they had to figure out (or questions)
  * tests / test comments needed to convince themselves of correctness
  * spec updates
  * Small refactors that helped in understanding / making code conform to consistency stds / improve code signal-to-noise ratio welcome
  * (As with all PRs, should not be a monolithic PR that gets PR'd, even though that may be the natural way its first formed)
* Find a tool that lets us statically figure out every message that had something in its code path that changed
  * Until a tool is found, we must do this manually
* Test in testnet & e2e testnet behaviors about every message that has changed
* Communicate with various integrators if they'd like release-blocking QA testing for major releases
  * Chainapsis has communicated wanting a series of osmosis-frontend functionalities to be checked for correctness on a testnet as a release blocking item

## Acceptance Criteria

- [ ] This is all documented in contributing.md

**Comment by xBalbinus** [comment]
May be closed by [#1848](https://github.com/osmosis-labs/osmosis/pull/1848)
