### ISSUE TITLE
Internal auditing of our codebase

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1831]
## Background

We should go through an internal audit of every module in our codebase over this sprint, aiming to hit our new documentation standards as a component of this.

- Document all "entry points"
  - Proto messages, public keeper methods, hooks that we listen onto
  - Review the logic for these, add comments for things took time to grok
  - Ensure functionality that seems relevant is covered in tests
  - Consider making public methods private / changing or reworking API's to be more clear

## Modules

- [x] #1834
- [x] #1835
- [x] #1837
- [x] #1838
- [ ] #1839
- [ ] #1840
- [x] #1836
- [ ] #1955
- [x] x/tokenfactory
- [x] x/txfees

**Comment by stackman27** [comment]
Hi @ValarDragon can i do internal auditing for txfees?
