### ISSUE TITLE
[Placeholder] Simulator epic

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1832]
## Background

Epic for simulator, TODO to write this up in more detail

## Suggested Design

> Here, you can put concrete steps as to what to do next
> e.g.
> - create test file in...

## Acceptance Criteria

> Goals & criteria for success
> e.g.
> - all existing and new tests should pass

**Comment by p0mvn** [comment]
Duplicate of https://github.com/osmosis-labs/osmosis/issues/1851
