### ISSUE TITLE
x/incentives - internal audit

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1837]

**Comment by czarcas7ic** [comment]
The following are the remaining TODOs from the first pass. Would like to decide which of these we want to tackle as part of this audit and which we should just create issues for:

- [ ] Fixed rewards estimation to work sometimes, but other times it panics [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r909126390)
- [ ] Optimize getToDistributeCoinsFromGauges [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910382317)
- [ ] Fix hack here getLocksToDistributionWithMaxDuration [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910382971)
- [ ] Have doDistributionSends have way more re-use with distribute internal [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910384227)
- [ ] Need further explanation of checkFinishDistribution previous TODO [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910384852)
- [ ] Make TestGetModuleToDistributeCoins TDD [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911416017)
- [ ] Make TestGetModuleDistributedCoins TDD [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911416142)
- [ ] Do we need to be concerned with case where this should be ActiveGauges? [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910385386)
- [ ] Figure out what this number should be [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911417161)
- [ ] Make TestGRPCToDistributeCoins table driven, or simpler [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911417335)
- [ ] Clean up AfterEpochEnd [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910385724)
- [ ] Switch more code to use userLocks and perpGaugeDesc [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r910385884)
- [ ] Delete all usages of this method (why?) [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911417528)
- [ ] Why reset to 2 after postlaunch? Only 0 and 1 exist, and 1 is no longer used [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911297840)
- [ ] Delete this comment if the below code satisfies the above request [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911298031)
- [ ] x/epochs/simulation/genesis.go doesn't exist, what was this comment trying to say? [Discussion](https://github.com/osmosis-labs/osmosis/pull/1885/files#r911298244)
