### ISSUE TITLE
x/lockup - internal audit

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1838]
To be done in three seperate PR
- [ ] #1828 
- [ ] https://github.com/osmosis-labs/osmosis/pull/1900
- [ ] https://github.com/osmosis-labs/osmosis/pull/1936
- [ ] https://github.com/osmosis-labs/osmosis/pull/1937
- [ ] https://github.com/osmosis-labs/osmosis/pull/1951
- [ ] #1968 
- [ ] https://github.com/osmosis-labs/osmosis/pull/1979

**Comment by mattverse** [comment]
To be done in three seperate PR

- [ ] One PR for deleting unused methods, renaming methods, and the documentations cleanup
- [ ] One PR for refactoring `Lock` method.
- [ ] One PR for ensuring API safety for `ExtendLock`, where we used to take lock of pointer references as parameter. This is bad for ensuring API safety, now it takes in lockID as parameter.

**Comment by mattverse** [comment]
All the other components are finished as well in the branch `mattverse/audit-lockup`, but holding on those until #1900 gets closed since likely to cause too much merge conflicts
