### ISSUE TITLE
x/pool-incentives: Internal audit & cleanup

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1840]
- [x] Adding detailed docs for every proto message / struct in the pool incentives module
- [x] Reviewing what API's are exported to other modules
- [x] Seeing how is taking in other modules / does it make sense / can it be clarified better
- [x] Check that the tests cover everything, and are well structured + understandable
- [x] Comment any confusing logic in the code in detail
- [x] If there is availability, making a much less buggy input format (oneof https://github.com/osmosis-labs/osmosis/issues/368 https://github.com/osmosis-labs/osmosis/issues/267 , or perhaps a new idea)

Also any needed code refactors / etc. should ideally be split out into a couple PRs

**Comment by xBalbinus** [comment]
May be closed by https://github.com/osmosis-labs/osmosis/pull/2248
