### ISSUE TITLE
Make a daily workflow to check that every link isn't broken

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1850]
## Background

A common problem is that links to other sites in the code / documentation break. We should have a daily CI action that can scan every markdown file, and report on breaking links in a github issue / slack bot

## Acceptance Criteria

- Automated reporting of link breakage {exists}

**Comment by MasterPi-2124** [comment]
that's a coincidence that I was also working on this a few minutes ago. I created a workflow in notional fork and here is the run: https://github.com/notional-labs/osmosis/actions/runs/4498700168/jobs/7915641640
