### ISSUE TITLE
docs: all module README.mds are located in module root 

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1864]
## Background

Sometimes, our `README.md`s for each module are located in `< module >/spec/README.md`. Sometimes, there are 2 READMEs per module in a different location.

## Suggested Design

For each module, we should have a README in the module's root.

For example, for `tokenfactory` module, we would have a **single** README.md in `x/tokenfactory/README.md`

## Acceptance Criteria

- For every module, ensure that the README is located in module's root
- Consolidate 2 READMEs into 1 if needed
- For all modules, there is no `x/< module name >/spec/README.md`
- Update  https://github.com/osmosis-labs/docs to point to the new locations
- Ensure that the `docs.osmosis.zone` is pointing to the correct locations and is functional

**Comment by p0mvn** [comment]
This issue is blocked by: https://github.com/osmosis-labs/osmosis/issues/1831

We should do this once all audits are complete to avoid conflicts

**Comment by xBalbinus** [comment]
This should also not be merged until the according docs fixes are linked - merging the docs and this one at the same time is critical to docs not breaking.

**Comment by xBalbinus** [comment]
May be closed by https://github.com/osmosis-labs/osmosis/pull/2171
