### ISSUE TITLE
testnet faucet is not working !

### ISSUE THREAD

**Issue by ItsFunny** [osmosis-labs/osmosis#1875]
I want to take some testnet tokens ,but there has something wrong about testnet ! ,please fix this

**Comment by ItsFunny** [comment]
This is my address : osmo10whr2tvcxmveces87kdrwp6xl42h02e8ah2ac9 ,  Send me some testnet tokens If it is available for you ~

**Comment by DevOpsFarina** [comment]
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/39111451/175916997-982e9167-0c4c-4823-a8b0-11c05263a954.png">

Thank you for reporting. The issue has been fixed. I tested by sending some tokens to you and you now have a balance. 

Cheers!

**Comment by daniel-farina** [comment]
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/39111451/175916997-982e9167-0c4c-4823-a8b0-11c05263a954.png">

Thank you for reporting. The issue has been fixed. I tested by sending some tokens to you and you now have a balance.
Cheers!
