### ISSUE TITLE
x/gamm: Charge gas for computation in swaps instead of just I/O

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1903]
Swaps currently only charge gas for I/O, regardless of the amount of computation they take up. One minor but useful change would be to make it so that gas is also charged for computation in swaps.
[
](https://github.com/osmosis-labs/osmosis/pull/1858)

**Comment by AlpinYukseloglu** [comment]
> What exactly do you have in mind @AlpinYukseloglu? Some fixed cost per specific operation?

Yes, some fixed cost for now with a TODO to turn it into a param later (since making it a param now would require migration code and it's too small of a change to be worth it for that)

**Comment by ValarDragon** [comment]
Agreed, lets add a fixed cost for now.

**Comment by rrrliu** [comment]
@AlpinYukseloglu is anyone working on this right now? If not, happy to take this!

**Comment by AlpinYukseloglu** [comment]
> @AlpinYukseloglu is anyone working on this right now? If not, happy to take this!

Nope, feel free to take it!
