### ISSUE TITLE
x/gamm: Consider deleting IsActive and related checks

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1904]
## Background

Consider deleting `IsActive` and related checks, including `getPoolForSwap()`. These checks were introduced for a feature that no longer exists (namely, letting people add/remove liquidity from a pool while disallowing swaps in it). Currently, `IsActive` is [hard-coded to return true](https://github.com/osmosis-labs/osmosis/blob/85529c76683f2d2f2ffb2121125baf0e39463f84/x/gamm/pool-models/balancer/balancer_pool.go#L473-L475), and every check it is used in never fails. In the spirit of not keeping code that doesn't do anything in our codebase, I think it's worth considering removing this check and its related functions.

https://github.com/osmosis-labs/osmosis/blob/85529c76683f2d2f2ffb2121125baf0e39463f84/x/gamm/pool-models/balancer/balancer_pool.go#L473-L475

## Suggested Design

- Remove `IsActive` and `getPoolForSwap()`
- Replace uses of `getPoolForSwap()` with `GetPoolAndPoke()`

## Acceptance Criteria

- All existing tests pass[
](https://github.com/osmosis-labs/osmosis/pull/1858)

**Comment by AlpinYukseloglu** [comment]
> Following up on the discussion offline:
> 
> * Can we add a comment for the method spec explaining what the method does and why we are keeping it while it always returns true? (e.g. for emergency situations to have an ability to quickly change the logic about when a pool is active)
> * Can we have a simple unit test where we expect `IsActive` to always return true for now? This is to ensure that even such a basic function is covered by tests so that if anyone accidentally flips the flag, the unit test would immediately catch it

Agreed for both. I think we also discussed adding a test that would cover the "flipping" functionality – @ValarDragon you briefly mentioned mock testing as an option. Do we have any examples of something like that in our codebase/how did you envision it would look?

**Comment by ValarDragon** [comment]
Mocks refer to making a sample implementation of an interface, satisfying the minimal testing needs wanted at that spot.

[This](https://github.com/golang/mock) is a tool that can help generating such an interface stub, but it may be easier to just make a struct in place that implements the Pool interface.

**Comment by AlpinYukseloglu** [comment]
> Mocks refer to making a sample implementation of an interface, satisfying the minimal testing needs wanted at that spot.
> 
> 
> 
> [This](https://github.com/golang/mock) is a tool that can help generating such an interface stub, but it may be easier to just make a struct in place that implements the Pool interface.
> 
> 
> 
> I think its fine to leave the latter as a future issue, and for now just having a test for the IsActive functionality that roman noted sounds good to me.

Sounds good!
