### ISSUE TITLE
x/gamm: Consider renaming CalcExitPoolShares to CalcExitCoinsFromShares

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1905]
## Background

`CalcExitPoolShares` calculates the expected tokens output by a pool given some number of shares. With the current name, it's not clear whether or not the function calculates the number of shares from output tokens or output tokens from the number of shares, so I think it might be worth considering renaming it to something like `CalcExitCoinsFromShares` (or something else that better specifies what the function does).

https://github.com/osmosis-labs/osmosis/blob/85529c76683f2d2f2ffb2121125baf0e39463f84/x/gamm/pool-models/balancer/amm.go#L501

## Suggested Design

- `CalcExitPoolShares` -> `CalcExitCoinsFromShares`

## Acceptance Criteria

- All existing and new tests pass[
](https://github.com/osmosis-labs/osmosis/pull/1858)

**Comment by p0mvn** [comment]
I like the idea. Suggest even being more verbose for clarity: `CalcExitPoolCoinsFromShares`

**Comment by AlpinYukseloglu** [comment]
cc: @ValarDragon @alexanderbez thoughts?
