### ISSUE TITLE
x/gamm: Consider removing DeletePool from GAMM keeper

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1907]
## Background

Since we do not support pool deletion, `DeletePool` is entirely unused code, so I suggest we delete it for now. If we decide to implement pool deletion in the future, it will require a more robust implementation than the current version anyway, so I don't see why we should keep this function around.

https://github.com/osmosis-labs/osmosis/blob/85529c76683f2d2f2ffb2121125baf0e39463f84/x/gamm/keeper/pool.go#L96

## Suggested Design

- Delete `DeletePool`

## Acceptance Criteria

- All existing and new tests should pass[
](https://github.com/osmosis-labs/osmosis/pull/1858)

**Comment by p0mvn** [comment]
I agree we should not have unused code. If we decide to bring back the ability to delete pools, there is always `Git` history

**Comment by ValarDragon** [comment]
Closing this, lets discuss in #1925 , its the same discussion.
