### ISSUE TITLE
Minor release testing workflow

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1911]
## Background

We should make a workflow for testing minor releases against mainnet for state compatibility. The goal would be that on a branch thats in a PR to v10.x, there is some manual thing I could easily run to check a node against it. In case of app hash failure, being given the last {say} thousand lines of logs would be helpful

## Suggested Design

* We sync a new node against mainnet, using the relevant branch / commit
  * Where do we start the sync from?
    - [x] Snapshot?
    - [ ] State sync?
* Sync {X} blocks
  * Ideal if it syncs through a full day /  an epoch, this also informs where the start of our sync is from

## Acceptance Criteria

* Theres a github workflow or simple command we can execute to test minor releases, with the guarantee that that code syncs & correctly executes the last {day} of mainnet

**Comment by ValarDragon** [comment]
Per discussion: We have a snapshot service, maybe we set it to some time before epoch each day, and then sync some number of blocks from there.

We have to figure out how to trigger it exactly, and report on results (is it a slackbot? Comment on a PR? )

**Comment by nikever** [comment]
Implemented in https://github.com/osmosis-labs/osmosis/pull/2083 and https://github.com/osmosis-labs/osmosis/pull/2178
