### ISSUE TITLE
Make validateEpochIdentifier a function defined by x/epochs

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#192]
Its currently duplicated in every module who calls it (e.g. https://github.com/osmosis-labs/osmosis/pull/189/files#diff-ab83f6f773690e81db9bb8b1adb169983c955d5782f61ba2aaff49eba48a303aR131)

**Comment by ValarDragon** [comment]
So we should move that validate function into x/epochs, and search for all other usages of that function in the codebase.

**Comment by mattverse** [comment]
Issue solved in PR https://github.com/osmosis-labs/osmosis/pull/398
