### ISSUE TITLE
x/mint: make all fixtures in keeper package use `KeeperTestSuite`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1920]
#### Background

Currently, there are 2 test suites in `mint` `keeper`:
- [`KeeperTestSuite`](https://github.com/osmosis-labs/osmosis/blob/d34df6ecbdf15dc8bbc597045f357935b92f1341/x/mint/keeper/keeper_test.go#L23)
- [`MintTestSuite`](https://github.com/osmosis-labs/osmosis/blob/d34df6ecbdf15dc8bbc597045f357935b92f1341/x/mint/keeper/grpc_query_test.go#L13)

The only difference between them is that `MintTestSuite` has `queryClient`. These should be consolidated into 1 test suite since the overhead from creating the query client in setup for every test is not that high. At the same time, having 2 test suites per package feels confusing.

Additionally, some tests in `keeper_test` use the suite while others don't. We should convert all of them to utilize the suite for consistency.

##### Suggested Design

Consolidate a single `KeeperTestSuite` with all the relevant set up code in `suite_test.go`.
Make all test fixtures in `keeper_test` utilize this test suite.

**Acceptance Criteria**
- `keeper_test` test suites are consolidated into one
- all test fixtures in `keeper_test` utilize the only suite
- all tests continue to pass

**Comment by stackman27** [comment]
Hi @p0mvn is this in the works already? If not i can take a shot

**Comment by p0mvn** [comment]
Hi @stackman27 . No, this is available. Please feel free to take it. Thank you
