### ISSUE TITLE
x/gamm: Delete the height < v10forkheight { use broken code } check

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1935]
## Background

During v10 we added height gating, to make the v10 binary compatible with v9 until the fork height.

Now that were on v10, we should delete this code off of main.

## Suggested Design

Delete logic introduced in this commit: https://github.com/osmosis-labs/osmosis/pull/1792

cc @AlpinYukseloglu

**Comment by AlpinYukseloglu** [comment]
Agreed – we should probably delete all related broken functions as well right?
