### ISSUE TITLE
lint: investigate and fix errcheck linter

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1940]
## Background

Our `errcheck` linter does not seem to be working.

Two occurrences where it did not fail when should have:
- https://github.com/osmosis-labs/osmosis/blob/2007babdee01e9bb7743ccadeff097cdab9b7236/x/gamm/keeper/pool_service.go#L222
- https://github.com/osmosis-labs/osmosis/pull/1936#discussion_r911973832

Running `golangci-lint linters` shows it as enabled. We need to investigate why it is failing to detect problems, maybe an update is needed?

## Acceptance Criteria
- root cause of the linter not working figured out
- if taking more than 30 minutes and unclear, a new issue created in: https://github.com/kisielk/errcheck, linking this issue

**Comment by ValarDragon** [comment]
I think whats happening is errcheck only checks if an error is returned and you don't assign a variable to it. I suspect its not actually checking that the error was used for something (assumes golang unused var elimination would do that for you)

**Comment by p0mvn** [comment]
I think you're correct.

This false positive seems to occur when we declare an `err` variable and reuse it by many calls:

For example, the following case would go uncaught:
```
var err error

err = doA()
if err != nil {
    return err
}

err = doB()
// not handle
```
- Although we do not handle it for B, the `err` ends up being read by error checking `doA`. So, it is not caught by the `unused` (or similar) linters. At the same time, the assignment of the result of `doB()` to `err` makes `errcheck` also pass. 

From a brief look, there used to be a linter that could detect error handling: https://stackoverflow.com/questions/43898074/is-there-a-way-to-find-not-handled-errors-in-go-code . However, it was deprecated.

I think we can close this issue for now
