### ISSUE TITLE
x/gamm: Make all internal set functions private

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#1945]
## Background

I believe these functions were only public because they needed to be for an older SDK version. I think it would be appropriate to make them private now so that they aren't exposed to other modules.

cc: @ValarDragon @alexanderbez @p0mvn for discussion

## Suggested Design

- Convert all the following public GAMM set functions to private:
`SetParams`
`SetPool`
`SetNextPoolNumber`
`SetTotalLiquidity`
`SetDenomLiquidity`

## Acceptance Criteria

- All existing tests pass

**Comment by AlpinYukseloglu** [comment]
@ValarDragon it seems as though a bunch of our gamm tests use the gamm keeper set up in `suite.App`, which is only allowed to use public keeper methods. For example, if we make `SetParams` private, the following call has no way to access it:
https://github.com/osmosis-labs/osmosis/blob/8f018a6c638b64912c1b22c7df04f84abe667ba0/x/gamm/keeper/pool_service_test.go#L212-L213

Any ideas on how we can get around this?

**Comment by mattverse** [comment]
use `export_test.go` if there's need to test private functions!
