### ISSUE TITLE
test/devux: helper function for assertions conditional on error

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1946]
**Background**

We tend to use a common pattern for asserting on the results in table-driven tests:
```
err := systemUnderTest(...)

if tc.expectedErr {
    require.Error(t, err)
    return
}

require.NoError(t, err)

```

We should make a helper for this pattern. e.g. `osmoutils.ConditionalPanics(suite, expPanic, func)`

_Originally posted by @ValarDragon in https://github.com/osmosis-labs/osmosis/pull/1872#discussion_r911602155_

**Acceptance Criteria**
- helper is created
- skim our tests and replace / refactor to use the helper where applicable

**Comment by stackman27** [comment]
Hi @p0mvn I can work on this!

**Comment by p0mvn** [comment]
Awesome, thank you
