### ISSUE TITLE
x/superfluid - internal audit

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1955]
- [ ] #1991 
- [ ] #2027 
- [ ] #2059
  - [x] #1797 
- [ ] Consolidate usage and remove code duplication between `SuperfluidDelegation` and `IncreaseSuperfluidDelegation`

**Comment by mattverse** [comment]
Do folks have ideas or preferences on fixing the test setup logic?

**Comment by ValarDragon** [comment]
TODO investigate /explain how https://github.com/osmosis-labs/osmosis/pull/2010/files#diff-35d0a46dfd79324de14abc663cbf0cd00b7511be18ae04109b613facce9126cbR66-R69 happens (validate is that message actually true)
