### ISSUE TITLE
x/gamm: PoolAsset.ValidateWeight - enable overflow validation

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1958]
## Background

There is currently dead code here:
https://github.com/osmosis-labs/osmosis/blob/1517e651c8af8417009f6a2392833265106b7d64/x/gamm/pool-models/balancer/pool_asset.go#L21-L24

This seems to be a valid check that we should enable and unit test

## Acceptance Criteria
- the check is enabled
- unit test added

**Comment by catShaark** [comment]
@p0mvn, we have this [GuaranteedWeightPrecision](https://github.com/osmosis-labs/osmosis/blob/f0270d04bd77cc5e1c23f7913118b3c2ba737e97/x/gamm/pool-models/balancer/constants.go#L19) here that's used to scale up the weight provided by user. Since GuaranteedWeightPrecision = 1 << 30 already, maybe we should increase our 1 << 32 threshold ?

**Comment by catShaark** [comment]
@p0mvn, what do you think ?

**Comment by p0mvn** [comment]
I suggest erring on the side of caution and keeping the suggested limit. I'm not sure where the choice of this value is coming from but I'm afraid that it might be related to the max size of a 32-bit int in some way.

Also, please note that the scale-up happens after validation. So we only validate the de-scaled weight value one time. Then, we scale it up for internal purposes

**Comment by catShaark** [comment]
thanks for the clarification

**Comment by ValarDragon** [comment]
I think that comment is obsolete, we check for too much precision here: https://github.com/osmosis-labs/osmosis/blob/1517e651c8af8417009f6a2392833265106b7d64/x/gamm/pool-models/balancer/amm.go#L70-L82

That occurs at the validate basic for the pool creation

**Comment by catShaark** [comment]
if `ValidateUserSpecifiedWeight` already did the job of overflow validation then `validateWeight` shouldn't do the same thing right ?
