### ISSUE TITLE
x/pool-incentives : refactor test in pool-incentives keepers to be properly table-driven

### ISSUE THREAD

**Issue by vuong177** [osmosis-labs/osmosis#1961]
## Background
 - This issue is following #1840 
 - Now some test in pool-incentives keeper is complex and unintelligible. We need to refactor it to better structure.

## Suggested Design
- Group test cases in `distr_test.go` and `grpc_query_test.go` .

## Acceptance Criteria

 - All existing and new tests should pass

**Comment by catShaark** [comment]
I think this makes sense

**Comment by vuong177** [comment]
Yep! My idea is to use driven-table test instead of the current test for more readable.
