### ISSUE TITLE
refactor: remove legacy `handler.go` files

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1972]
**Background**

From each module, we should remove legacy `handler.go` files.

A similar refactor was don in the SDK that can be referenced: https://github.com/cosmos/cosmos-sdk/pull/9650

**Acceptance Criteria** 
- all `handler.go` logic is removed and refactored according to https://github.com/cosmos/cosmos-sdk/pull/9650
- all new functionality is covered by unit tests

_Originally posted by @alexanderbez in https://github.com/osmosis-labs/osmosis/pull/1956#discussion_r913264144_

**Comment by alexanderbez** [comment]
literally just code deletion haha. I can tackle this
