### ISSUE TITLE
lint(md): consider enforcing asterisk rule in our markdown files

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1993]
**Background**

There is a desire to have the asterisk being used for bullet points. We should configure our [markdown CI](https://github.com/igorshubovych/markdownlint-cli#readme) linter to be aware of this rule.

**Acceptance Criteria**
- The rule is applied to our markdown linter
- The CI passes for all files with the new rule

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/1983#discussion_r915944653_

**Comment by ValarDragon** [comment]
Closing in favor of cref #2287 

In general, I think lints like this are larger time sucks than wins.
