### ISSUE TITLE
ux(e2e): Makefile steps to run e2e test suite locally

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2002]
## Background

Currently, there is a pre-requisites to get e2e working locally. This step includes building `osmosis:debug` image to be pre-built for testing the upgrades. This setup introduces a barrier to entry for developers new to e2e.

We should have 2 makefile steps that run e2e "out of the box" while installing everything needed in the background:
- `make test-e2e` - installs dependencies and runs a full e2e suite
- `make test-e2e-short` - installs dependencies and runs short e2e test suite with upgrade and IBC tests off
   * `OSMOSIS_E2E_SKIP_IBC` environment variable must be true
   * `OSMOSIS_E2E_SKIP_UPGRADE` environment variable must be true

## Acceptance Criteria
- 2 suggested make file steps are introduced
- Documentation added to the e2e README that Docker should still be installed manually (link added)
- each step can be run multiple times locally without issues with no extra setup

**Comment by czarcas7ic** [comment]
100%, sometimes I even find myself forgetting to build the debug image locally when working on a new VM (or not rebuilding the debug image when working with a newer version)

**Comment by p0mvn** [comment]
@czarcas7ic Do you think `osmosis:debug` image should be rebuilt every time `make test-e2e` is run?

I think there is a trade-off. If rebuild every time, it makes you wait for results longer. If not every time (only the image is not present), easy to forget to rebuild it and run e2e on an old Osmosis version.

I'm leaning towards only building it on the first run to avoid waiting but curious to know what anyone else prefers

**Comment by czarcas7ic** [comment]
@p0mvn I for sure do not think it should be rebuild on ever run. I think we should just check for the images existence and if it doesn't exist we build it. Would also be neat if we can check for the age of the osmosis:debug image and if it is greater than x days we rebuild it. Just the first idea that came to my mind, could be much better ideas. Will think more about it

**Comment by ValarDragon** [comment]
What is in the `osmosis:debug` image? Why would we not just rebuild it every time relevant source has a change?

**Comment by czarcas7ic** [comment]
@ValarDragon we do rebuild this in CI every time it is run. The problem is when someone is running the e2e test suite locally, it is possible they already built the osmosis:debug image and instead of rebuilding it could just utilize this same image for multiple runs. The osmosis debug image is just osmosis build off all local changes.

@p0mvn what we could do is just have two separate makefile cmds, where make test-e2e will reuse your local image and make test-e2e-rebuild will remove your local image and rebuild

**Comment by czarcas7ic** [comment]
Logic is sound to me! Will either get with @nikever or do some basic searching to see how to determine if a docker image matches what is there locally without having to rebuild
