### ISSUE TITLE
x/incentives: index synthetic lockups by denom

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2006]
## Background

Synthetic lockups aren't indexed by denom as expected

https://github.com/osmosis-labs/osmosis/blob/fb0de8c1f7131d5e95ee8e98f93c432eefb682c6/x/incentives/keeper/distribute.go#L91-L109

## Suggested Design

Will need to come back to this to figure out a suggested design. 

## Acceptance Criteria

- Synthetic lockups are indexed by denom
- Hack no longer required in getLocksToDistributionWithMaxDuration

**Comment by stackman27** [comment]
Hi @czarcas7ic is this issue being worked on? can i take a shot at it? Will follow up with @ValarDragon  regarding the design

**Comment by czarcas7ic** [comment]
@stackman27 please do, I will assign it to you!

**Comment by ValarDragon** [comment]
Hey, just saw this issue. I think we should not index these, and instead be planning to delete the synthetic locks entirely.

Rather than maintain the current state, would rather put such energy into getting it deleted :muscle:

**Comment by stackman27** [comment]
Are we trying to make it a part of period locks?

**Comment by ValarDragon** [comment]
This is the design we should go towards imo https://github.com/osmosis-labs/osmosis/pull/942

**Comment by ValarDragon** [comment]
Were not going to pursue this.
