### ISSUE TITLE
refactor(x/gamm): move errors in balancer pool to `x/gamm/types/errors.go`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2034]
## Background

Many recently added errors were defined in the balancer package. Instead, we might want to have them in `types/errors.go` for consistency.

## Suggested Design

Move:
https://github.com/osmosis-labs/osmosis/blob/3be2640a842394e962e323e9ad1885019e4e4229/x/gamm/pool-models/balancer/pool.go#L20-L27

to `types/errors.go`

Also, remove `//nolint:deadcode` and delete the unused errors

## Acceptance Criteria
- balancer pool errors are moved to `x/gamm/types/errors.go`
- balancer pool and tests are refactored to use errors from types
- `//nolint:deadcode` is removed together with unused errors
- potentially duplicate errors are consolidated

**Comment by stackman27** [comment]
I can do this
