### ISSUE TITLE
refactor(x/mint): move errors in mint keeper to `x/mint/types/errors.go`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2035]
## Background

Many recently added errors were defined directly in the mint keeper. Instead, we might want to have them in `types/errors.go` for consistency and to make them exposed to the clients

## Suggested Design

Move:
https://github.com/osmosis-labs/osmosis/blob/3be2640a842394e962e323e9ad1885019e4e4229/x/mint/keeper/keeper.go#L31-L43

to `types/errors.go` for consistency with other modules and to make them exposed to the clients.

## Acceptance Criteria
- mint keeper errors are moved to `x/mint/types/errors.go`
- mint keeper and tests are refactored to use errors from types
- potentially duplicate errors are consolidated

**Comment by stackman27** [comment]
I can do this. Sorry i keep pinging, i cannot self assign

**Comment by p0mvn** [comment]
Closed by #2067
