### ISSUE TITLE
Add tests for the denom -> active pot ID map 

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#204]
Currently in #200 this was only indirectly tested. We should add direct tests for this map being correct

**Comment by antstalepresh** [comment]
Is this correct to add an iterator by denom for active gauges and test it?

**Comment by ValarDragon** [comment]
That'd work. Another alternative would be to make a set of pots in a test, and an expected denom -> active ID map, and then test that the function returns the same thing for every denom.
