### ISSUE TITLE
proposal: implement the ability to print out container logs when e2e fails waiting on node to reach a certain height

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2042]
## Background

Currently, it is challenging to debug e2e upgrades and setup both in CI and locally because, when a node container fails, its logs are not printed to stdout.

We need to be able to print the logs from a failing container to the host's stdout.

## Story
>As an Osmosis engineer, I would like to be able to easily identify the source of e2e node container failures so that I can avoid debugging our tooling and focus at being efficient at fixing the actual failures

## Example

This is an example of what we see in the CI logs when node fails to produce blocks:
https://github.com/osmosis-labs/osmosis/runs/7312134568?check_suite_focus=true

Not much useful information is available.

## Suggested Design

We should be able to achieve this by adding logic to [the following branch](https://github.com/osmosis-labs/osmosis/blob/3e449625e06fe8d86ad320d1a2989c19075fea3b/tests/e2e/configurer/chain/chain.go#L117) of `WaitUntil` method of `chain.Config` module.

`chain.Config` has `containerManager` embedded as [its field](https://github.com/osmosis-labs/osmosis/blob/3e449625e06fe8d86ad320d1a2989c19075fea3b/tests/e2e/configurer/chain/chain.go#L30). Therefore, it should be possible to get access to the node's container by calling [`GetValidatorResource(...)`](https://github.com/osmosis-labs/osmosis/blob/3e449625e06fe8d86ad320d1a2989c19075fea3b/tests/e2e/containers/containers.go#L245)

Once we have the container resource, we can access its `LogPath`. Next, read the last 100-200 files of the [`LogPath`](https://github.com/ory/dockertest/blob/4d608dbb348c52b3f719f3631aae6008cafefcb5/docker/container.go#L462) file directly and try to output it to the host's stdout.

I propose implementing a method on `containers.Manager`:
 ```
// ExtractLogs extracts logs from a container dedicated to a node running on chainId and identified by nodeIndex. It 
// returns the last 100 lines of the container logs, if available. Returns error if not available or if a container does not exist.
func (m *Manager)  ExtractLogs(chainId string, nodeIndex) ([]byte, error)
```
This method should be called from [this branch](https://github.com/osmosis-labs/osmosis/blob/3e449625e06fe8d86ad320d1a2989c19075fea3b/tests/e2e/configurer/chain/chain.go#L117) in `WaitUntil`

Then, the result ican be used to log the bytes to the host's stdout.

## Acceptance Criteria
- `ExtractLogs` is implemented
- Logs are printed to the host's stdout
- Debugging e2e container failures is convenient

**Comment by p0mvn** [comment]
CC: @czarcas7ic what do you think about the suggested design?

Something I'm currently unsure about is how the `dockertest.Container`'s `LogPath` file is updated. Need to investigate this further

**Comment by czarcas7ic** [comment]
Your suggestion sounds good to me. If that doesn't work, something less elegant we could try is to export the container ID that fails as an env var. Then have a following GH action that, if previous tests failed, it simply runs `docker logs EXPORTED_CONTAINER_ID` which should give us everything we need!

**Comment by p0mvn** [comment]
I went with a simpler solution in #2385 where we always print the logs, at most 3 times per CLI command. However added an environment variable to disable the extra logs if wanted
