### ISSUE TITLE
e2e: Wrap Eventually() into query logic

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2045]
## Background

This is a really simple issue that anyone looking to start out (especially on e2e testing) should take on!

As Dev pointed out, we call Eventually() many times throughout our E2E tests, and this should be abstracted into the query command itself to make reading the tests even simpler.

## Suggested Design

Here is one example:

https://github.com/osmosis-labs/osmosis/blob/e383d32c6e7fdd27f2d3d6dd5fd07aa56d834ee1/tests/e2e/e2e_test.go#L82-L98

Instead of calling Eventually() here, we should move it into the QueryIntermediaryAccount function itself. This abstraction makes reading the actual tests much simpler

## Acceptance Criteria

- All Eventually() logic is removed from the primary testing files and placed into the function itself
- E2E test suite still passes

**Comment by p0mvn** [comment]
I don't think we should be moving this logic to `QueryIntermediaryAccount` because this is more involved than just a query. 

However, I think it's a good idea to potentially encapsulate this somewhere. A new method in `chain.go` could work. Any other ideas where?

Also, can we specify other examples as well, please?

**Comment by ValarDragon** [comment]
I'm confused why this require even exists. Its Query's job to ensure its finished executing when it returns. And query already does this, in the GRPC gateway value.

This require seems redundant / like it should just be deleted.

**Comment by czarcas7ic** [comment]
The eventually statements were included in almost all queries/txs when we were initially debugging issues. They for sure need to exist on txs since we are not hardcoding sequence numbers, but can probably be taken off of queries without any problems. I can close this issue and we can work on a separate issue the get rid of all unnecessary eventually statements.
