### ISSUE TITLE
x/gamm: Make gas cost per swap a param

### ISSUE THREAD

**Issue by rrrliu** [osmosis-labs/osmosis#2058]
## Background

Follow up to https://github.com/osmosis-labs/osmosis/issues/1903#issuecomment-1173907587, make this fixed gas fee into a pool-level param for more customizability.

Right now we use a `BalancerGasFeeForSwap` fixed constant, we'll need to update that logic when we swap.

## Suggested Design

Add a new field to `PoolParams` for balancer and stableswap pools, use this field to consume gas during `applySwap`.

## Acceptance Criteria

- `PoolParams` struct updated, prepare for contract migration
- Unit tests in `pool_test.go` and updated tests in `swap_test.go`

**Comment by alexanderbez** [comment]
Per chain-dev call, we decided to keep this as a static-hard coded value.
