### ISSUE TITLE
Helper functions for handling sdk.Coins in osmosutil

### ISSUE THREAD

**Issue by catShaark** [osmosis-labs/osmosis#2060]
## Background

We need functions to do division and multiplication of sdk.Coins and a number. For example 
DivCoin( 88stake, 2 ) -> 44stake, this will be a useful helper function for our tests

## Suggested Design

- Create function for division and multiplication of sdk.Coin in osmosutil.

**Comment by ThanhNhann** [comment]
Hey @ValarDragon, I saw you coded the division of sdk.Coins, what about multiplication? if not, I will handle it
