### ISSUE TITLE
test(gov): manually / e2e test expedited proposals

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2087]
## Background

We need to manually and/or e2e test expedited proposals. This issue is blocked on me providing a description about the plan
## Suggested Design

TBD

## Acceptance Criteria
- verified that expedited proposals work as expected and can be released

**Comment by p0mvn** [comment]
This issue is blocked by the parameter migrations in: https://github.com/osmosis-labs/osmosis/issues/2249

**Comment by czarcas7ic** [comment]
Issue unblocked, I am now working on this
