### ISSUE TITLE
Attacking

### ISSUE THREAD

**Issue by Halimao** [osmosis-labs/osmosis#2093]
## Background
https://www.mintscan.io/osmosis/account/osmo173pu4mkx8lx30c4e38cy2z29dy2qrrma55e5kc
this guy is attacking osmosis nodes all the time

I saw this acount's balance is only 0.001osmo, but it is sending 6,810,000SMO swapping in pool 1

osmo1yqzfnppugtw0tn33ev2zy2jwhn98h8256rqgxk and osmo18aynruwqhesgllqsah2vdc3vdtrns8vvfvdyjc and osmo1hs8c2lemgvmeshzk9mpyufu5ngds9vffn98hqy and so on are doing the same thing
"osmo173pu4mkx8lx30c4e38cy2z29dy2qrrma55e5kc" sent osmo to a lot of accounts, and those accounts is attacking now)

## Suggested Design
ban these accounts
## Acceptance Criteria
is this guy attacking osmosis nodes all the time?
I saw this acount's balance is only 0.001osmo, but it is sending 6,810,000SMO swapping in pool 1
osmo1yqzfnppugtw0tn33ev2zy2jwhn98h8256rqgxk and osmo18aynruwqhesgllqsah2vdc3vdtrns8vvfvdyjc and osmo1hs8c2lemgvmeshzk9mpyufu5ngds9vffn98hqy are doing the same thing
"osmo173pu4mkx8lx30c4e38cy2z29dy2qrrma55e5kc" sent osmo to a lot of accounts, and those accounts is attacking now

**Comment by p0mvn** [comment]
Hi @Halimao 

Thank you for this report.

I just checked all the accounts and they seem to be now inactive for over a day.

Can we close this for now?

Thank you again for reporting this

**Comment by czarcas7ic** [comment]
Validators have moved up min fee for the most part, which makes this spam less prominent. We can close this issue for now. Also thank you for reporting! 😄
