### ISSUE TITLE
Support for adding liquidity in cosmwasm

### ISSUE THREAD

**Issue by hskang9** [osmosis-labs/osmosis#2095]
## Background

Hackatom 2022's osmosis challenge requires a cosmwasm contract on 
Futures or options on a token using the AMM for settlement, but I cannot find a binding that add/ remove liquidity in single-side or both side.

## Suggested Design

Support add/remove liquidity message in `OsmosisMsg` in `osmo_bindings`.

## Acceptance Criteria

- OsmosisMsg adding two functions for liquidity

```Rust
impl OsmosisMsg {
    /// Basic helper to define a swap with one pool
    pub fn simple_swap(
        pool_id: u64,
        denom_in: impl Into<String>,
        denom_out: impl Into<String>,
        amount: SwapAmountWithLimit,
    ) -> Self {
        OsmosisMsg::Swap {
            first: Swap::new(pool_id, denom_in, denom_out),
            amount,
            route: vec![],
        }
    }
    
    pub fn add_liquidity(
        pool_id: u64,
        denom_in: Option<impl Into<String>>,
        denom_out: Option<impl Into<String>>,
        amount_in: Amount,
        amount_out: Amount,
        single_sided: bool
    ) -> Self {
       // Code that returns a message
        ...
    }
    
    pub fn remove_liquidity(
        pool_id: u64,
        denom_in: Option<impl Into<String>>,
        denom_out: Option<impl Into<String>>,
        amount_in: Amount,
        amount_out: Amount,
    ) -> Self {
       // Code that returns a message
        ...
    }
}
```

**Comment by ValarDragon** [comment]
We'd like to be having folks use stargate message for this. cc @iboss-ptk , do we have an example of stargate messages for cosmwasm?

**Comment by iboss-ptk** [comment]
yes, here you go https://github.com/iboss-ptk/osmosis-cosmwasm-stargate-example

**Comment by hskang9** [comment]
Even if one use stargate message for this, I have not seen any stargate message for adding liquidity. Maybe care to see the subject of the issue?

**Comment by ValarDragon** [comment]
Stargate message is generic execution for any SDK message. Re: liquidity message not being included, see:

> Will provide all generated types from proto similar to osmo_msg.rs soon

**Comment by iboss-ptk** [comment]
@hskang9  In 1-2 days, I should be able to launch `v0.0.1` for the lib but for now, if you want to try things out quickly, you can use

```rs
/// ===================== MsgJoinPool
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgJoinPool {
    #[prost(string, tag="1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub pool_id: u64,
    #[prost(string, tag="3")]
    pub share_out_amount: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="4")]
    pub token_in_maxs: ::prost::alloc::vec::Vec<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgJoinPoolResponse {
}
/// ===================== MsgExitPool
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgExitPool {
    #[prost(string, tag="1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub pool_id: u64,
    #[prost(string, tag="3")]
    pub share_in_amount: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="4")]
    pub token_out_mins: ::prost::alloc::vec::Vec<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgExitPoolResponse {
}
```
And implement `CosmosMsg` conversion [similar to this ](https://github.com/iboss-ptk/osmosis-cosmwasm-stargate-example/blob/fb165cfd93759a6536a30152e6d3bc8e3383fa06/contracts/tokenfactory/src/osmo_msg.rs#L20)

**Comment by hskang9** [comment]
Thank you

**Comment by iboss-ptk** [comment]
@hskang9 pls check this out https://github.com/osmosis-labs/osmosis-rust/tree/main/packages/osmosis-std

**Comment by hskang9** [comment]
Can you teach me on what does `share_in_amount` and `token_in_maxs` mean?

**Comment by hskang9** [comment]
Also I need to convert `cosmwasm_std::Coin` to `osmosis_std::cosmos_sdk_proto::cosmos::base::v1beta1::Coin`

**Comment by iboss-ptk** [comment]
> Also I need to convert cosmwasm_std::Coin to osmosis_std::cosmos_sdk_proto::cosmos::base::v1beta1::Coin to use this stargate message.

Good point! Will add convenient conversion for that, if you want one now, you can add the following (untested but you ge the idea)

```rs
impl From<cosmwasm_std::Coin> for osmosis_std::cosmos_sdk_proto::cosmos::base::v1beta1::Coin {
  fn from(coin:cosmwasm_std::Coin) -> Self {
      Self {
        denom: coin.denom,
        amount: coin.amount.to_string()
      }
  }
}
```

**Comment by iboss-ptk** [comment]
> Can you teach me on what does share_in_amount and token_in_maxs mean?

From [gamm spec](https://github.com/osmosis-labs/osmosis/tree/47a2366c5eeee474de9e1cb4777fab0ccfbb9592/x/gamm/spec)

For [Join Pool](https://github.com/osmosis-labs/osmosis/tree/47a2366c5eeee474de9e1cb4777fab0ccfbb9592/x/gamm/spec#join-pool)

> Add liquidity to a specified pool to get an exact amount of LP shares (`share_out_amount`) while specifying a maximum number tokens willing to swap to receive said LP shares (`token_in_maxs`).

For [Exit Pool](https://github.com/osmosis-labs/osmosis/tree/47a2366c5eeee474de9e1cb4777fab0ccfbb9592/x/gamm/spec#exit-pool)

> Remove liquidity from a specified pool with an exact amount of LP shares (`share_in_amount`) while specifying the minimum number of tokens willing to receive for said LP shares (`token_out_mins`).
