### ISSUE TITLE
Fork cosmwasm to re-enable queries

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2098]
## Background

For our next release, I believe that we want to fork wasmd to re-enable stargate queries. We eventually want to move to a whitelist approach, so we can control which queries were making state machine compatability guarantees about. Until they are added back, it must be part of contract review to ensure that all approved contract queries are fine. 

To be more precise:
* A query that is exposed should not have any fields deleted, otherwise it will be state machine breaking
* When gas tracking is added, it should not be changed within a minor version.

And we should have a beaker test doing this.

As part of this, we should also scope how hard would it be to build a whitelist. (hopefully not much, seeing as we already have a string description of the query type)

## Suggested Design

We need to investigate how stargate queries were removed, so that we can add them back.

## Acceptance Criteria

- [ ] It is possible to use stargate queries in forked cosmwasm.

**Comment by alexanderbez** [comment]
The queries should be deterministic too, i.e. no map encoding or anything like that. And if they do, ensure that the output is deterministic.

**Comment by mattverse** [comment]
https://github.com/osmosis-labs/osmosis/pull/2190

**Comment by mattverse** [comment]
https://github.com/osmosis-labs/osmosis/pull/2353
