### ISSUE TITLE
Ensure all messages work with Authz

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2099]
## Background

Apply API breaking changes from https://github.com/cosmos/cosmos-sdk/pull/11224 into the Osmosis code. This is already in osmosis main from: https://github.com/osmosis-labs/cosmos-sdk/pull/224 , so we just need to apply it to our code and check that it works / nothing broke.

## Suggested Design

Apply API changes from aforementioned PR
Check that existing txs still work signed via CLI, ledger, authz CLI and authz ledger. (Can we get a golang test for this? A golang test would also help with mutation testing's highlight of a testing gap here0

## Acceptance Criteria

- [ ] API changes done
- [ ] Golang test Txs signed in ledger format, normal format, and Authz still work. (Pass in an SDK.Msg with signer field filled)
- [ ] Manual test to sanity check

**Comment by vuong177** [comment]
@ValarDragon can I close this issue ?

**Comment by p0mvn** [comment]
Hi @vuong177 

You can take this if you'd like. This is an important issue. However, I would like to warn you that there is a lot of uncertainty with this. As a result, guidance and help might be limited.

The goal is to have this before the end of the current sprint (end of next week). 

So if you'd like to work on something open-ended while having these constraints in mind, feel free to take this.

Please let me know if you are planning on working on this

**Comment by vuong177** [comment]
@p0mvn yes. I'd love to take this work.
