### ISSUE TITLE
Investigate e2e test execution time

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2100]
## Background

E2E execution time takes very long. Often takes 8+ minutes, adding notable delay to CI (and thus developer flow). Roman's made a series of very helpful issues for mitigating build times. This issue is for investigating whats happening in our test execution time. CI run copy/paste for reference

```
--- PASS: TestIntegrationTestSuite (431.08s)
    --- PASS: TestIntegrationTestSuite/TestCreatePoolPostUpgrade (5.42s)
    --- PASS: TestIntegrationTestSuite/TestIBCTokenTransfer (94.79s)
    --- PASS: TestIntegrationTestSuite/TestSuperfluidVoting (77.14s)
```

## Ideas

Ideas I have for why this could be taking so long (in sequence of what I'd try / check):
* What are block times in e2e? For e2e test, we should be setting `precommit_timeout_wait` to be negligible. I'd even suggest `5ms`, we gain nothing by having delay in these tests. We don't need every validator signing every block either. 
  * Lets just adjust this config parameter and see what happens?
* Whats the blocking behavior for subsequent txs and subsequent queries?
  * Are we getting blocked in this? Can we add a "time trace'" to our ExecCLI & ExecQuery commands to learn more?
* Are relayers getting stuck in getting things onto both chains?

## Acceptance Criteria

We have some understanding of where time is getting stuck, via "guess and check", metrics / hacky log file, or otherwise

**Comment by ValarDragon** [comment]
Some things that strike out to me with adding some basic time logging in https://github.com/osmosis-labs/osmosis/pull/2103 is that:
* We are running all tests / actions in sequence. When we have more tests post-upgrade, they should be able to run in parallel if they use different accounts
* IBC test is really slow (looks like 1.5 minutes, and is ran twice)
* Superfluid voting - we should be doing votes across nodes in parallel. Maybe we can make a helper method for doing the same action, on all node configs, in parallel?

**Comment by ValarDragon** [comment]
update from #2103, most of the time was in require.Eventually tick timers. Changing those brought execution time to 3min 30 sec! Once we can get the test config propogated to lower block times, we'll probs be fine for now in terms of execution time

**Comment by p0mvn** [comment]
Most of the items in this issue are tracked separately so I'm going to close this. Open an issue for parallelizing tests
