### ISSUE TITLE
mutation testing: Automated github action to generate issue

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2114]
## Background

We should automate the routine mutation testing issue creation (cref #2069 #2105 ).

This should be pretty straightforward:
- [ ] Make github action that runs once per week
- [ ] It runs make test-mutation
- [ ] Takes mutation_test_result.txt, and creates a github issue. (with some formatting. Perhaps only parse out failures, and split them up with a number and separate code block)

The mutation test issue should also include next steps. (Going from the workflow noted before):

 - We then manually "group" these issues and sort into buckets:
        {errors that are legit}
        {errors that are noise}

Then for legit bucket, further sort errors legitimate errors by testing strategy that will hit it, and make new issues for that testing strategy into follow-up issues. These should be solved within the week, or otherwise be looped into a larger plan.

For the noise bucket, make a new github issue detailing the noise error type. We should aim to get a fork of gomuttest / try disabling noise / finding a strategy to mitigate noise.

**Comment by stackman27** [comment]
@ValarDragon should i create individual issues or put all the failed cases in one issue like you did [here](https://github.com/osmosis-labs/osmosis/issues/2105)?

**Comment by stackman27** [comment]
So i've thought about two approaches for formatting mutation_test_result.txt to generate github issues 
1. modify mutation-test.sh to generate a mutation_test_result_fails.tx and create github issue 
2. Run a python script within mutation-test.yml file that formats the mutation_test_result_fails.tx (probably with regex) and generate issues

**Comment by ValarDragon** [comment]
I'd probably just write a python script for formatting it (And do something more structured than a regex)
