### ISSUE TITLE
mutation test: Amend line deletion mutator to not delete errcheck or panic

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2116]
## Background

Currently the go mutation tester has false positives wrt unkilled mutations, because it will delete:
`panic(err)` and `return err` in the following examples:
```
if err != nil {
    panic(err)
}
```
```
if err != nil {
    return err
}
```

## Suggested Design

We should amend the mutator for line deletion in go-mutation testing, to handle these two special cases. Namely if I have an `IfExpression` that specifically checks if an object of type `error` is `not equal to` the value `nil`, and the Body of the IfExpression is a single `panic call` or a single `ReturnExpression`, then do not muitate.

## Acceptance Criteria

- [x] Go mutation test does not atempt to delete panic lines or error returns

**Comment by ValarDragon** [comment]
Leaving this open until we use our fork correctly on osmosis main

**Comment by alexanderbez** [comment]
1. Update `tools/tools.go` to use the Osmosis fork
2. Update the `scripts/mutation-test.sh` script to use the Osmosis fork
