### ISSUE TITLE
Update to Cosmos SDK v0.42.5 properly

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#212]
In #200 we upgraded cosmos-sdk in go.mod from 0.42.4 to 0.42.5:  https://github.com/osmosis-labs/osmosis/pull/200/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R31

However, this didn't do anything because we replace cosmos-sdk with the osmosis-labs version on L31 of go.mod:  https://github.com/osmosis-labs/osmosis/blob/main/go.mod#L31

We need to rebase our osmosis-specific cosmos sdk branch on top of 0.42.5.

**Comment by sunnya97** [comment]
I'm undoing the bump in the go.mod in #203, so that it's clear when seeing the go.mod file that we're based on a derivative of 0.42.4.

**Comment by ValarDragon** [comment]
Is this now done @sunnya97 ?

**Comment by sunnya97** [comment]
Yes

**Comment by sunnya97** [comment]
Yes, closed by #222
