### ISSUE TITLE
Install on OSX M1 not working

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#2121]
#### System information

Osmosis version: latest from cloning repo
OS & Version: OSX - Monterrey 12.3 (21E230)

#### Expected behaviour
```
make build
make install
```
should install the binary from `build/osmosisd` to `/usr/local/bin`

#### Actual behaviour
Build runs but install fails to copy file

#### Steps to reproduce the behaviour
```
#remove your osmosisd binary
sudo rm /usr/local/bin/osmosisd
git clone https://github.com/osmosis-labs/osmosis.git
make build
make install
osmosisd version
```
Output: command not found: osmosisd

#### Alternative solution

```
git clone https://github.com/osmosis-labs/osmosis.git
make build
sudo cp build/osmosisd /usr/local/bin
```

This currently breaks installations from source and also from the official installer.

**Comment by ValarDragon** [comment]
Is this still applicable? I remember some discussion on the problem / solutions for it, but idk if we ended up fixing what was needed

**Comment by czarcas7ic** [comment]
I don't have this issue on my M1

**Comment by ValarDragon** [comment]
ok, going to close for now then!
