### ISSUE TITLE
v10.1 release

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2123]
# Background

We should probably cut a v10.1 soon, we've already accumulated a notable number of changes on v10.x. We are also planning to backport many of the accumulated main changes to v10.x, and would be good to incrementally test commits to date first.

- [x] Refactors
- [x] TokenFactory InitGenesis fixes
- [x] Update v10.x SDK import
  - Which has the store hash logging update, to reduce log spam

# Suggested Design

Once the minor test commit workflow is merged & we have updated v10.x SDK import:
- [x] Run the commit workflow on v10.x
- [x] See if we can extend workflows, to make binaries from a manually created releas

Also we need to cleanup the changelog prior to release

# Acceptance Criteria

- [x] v10.1 tag and release exists
- [x] Has an automated test for state machine compatability
- [x] Binaries exist on release

**Comment by nikever** [comment]
I think we can close this issue.

- State compatibility check was added in https://github.com/osmosis-labs/osmosis/pull/2178
- Release workflow can be triggered via `osmosis-ci` repository. It was used to create: https://github.com/osmosis-labs/osmosis/releases/tag/v10.1.0
