### ISSUE TITLE
Measure and lower overhead of KeeperTestHelper.Setup()

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2148]
## Background

Locally, KeeperTestHelper takes about 20ms, which adds up over the hundreds of invokations around osmosis tests, to tens of seconds of delay. More importantly, this appears to contribute a minute to CI test time. 

I added a micro-benchmark in #2143 , and it shows that 75% of this time is in heap. Its a nice / useful project for someone to investigate memoryprofiling that benchmark, and to see where we can lower heap allocation to improve our CI time.

NOTE: I'm just filing as I noticed this recently, not saying its something thats a priority

## Suggested Design

- Look into why the following functions need to allocate so much RAM:
![image](https://user-images.githubusercontent.com/6440154/179847310-2bc16c2a-5774-4577-8007-d864f13674b8.png)
- See if theres small fixes to reduce this in our CI setting
- Methods for ease of CTRL+F:
  - modulemanager.InitGenesis (on default genesis)
  - iavl.LoadVersion
  - app.MakeEncodingConfig()
    - Its all in RegisterLegacyAminoCodec
    - Presumably this can be cached / globally init once, and then copied from that?
  - app.NewDefaultGenesisState
    - This one seems basic, presumably we can just cache this and only compute it once

## Acceptance Criteria

- [ ] We understand allocation overhead root causes
- [ ] We've reduced allocation in the test setup logic

**Comment by ValarDragon** [comment]
* iavl.LoadVersion likely coming from us forcing GC within iavl. We should probably remove that logic that forces garbage collection, and only make that trigger if memory usage is above some number. This is almost certainly the big root cause of slowness of our golang tests
* InitGenesis overhead seems to 75% come from JSON unmarshalling, surely theres ways we can improve these.

**Comment by RusAkh** [comment]
I'd like to look into this

**Comment by p0mvn** [comment]
@RusAkh Sweet, thanks!

**Comment by ValarDragon** [comment]
Just fixed two of these in #7902 , gonna close for now. Lets re-open with some new benchmarks.
