### ISSUE TITLE
Add scaling factor to stableswap pool creation

### ISSUE THREAD

**Issue by catShaark** [osmosis-labs/osmosis#2166]
## Background

Stable swap pool needs its `ScalingFactor` set in order to do basic operation like `CalcInAmtGivenOut`.

Right now, `NewStableswapPool` doesn't include `ScalingFactor` in its params so any pools crated from `NewStableswapPool` will not be usable.

`MsgCreateStableswapPool` also doesn't include `ScalingFactor` and doesn't set `ScalingFactor` to any default value, this means the pool created will also not be usable until a `MsgStableSwapAdjustScalingFactors`, is this intended ?

## Suggested Design

Include `ScalingFactor` in `NewStableswapPool`
Include `ScalingFactor` in `MsgCreateStableswapPool`

**Comment by ValarDragon** [comment]
Definitely not intended, this is needed.

**Comment by stackman27** [comment]
closely relates to #1470
