### ISSUE TITLE
Full Node - Epoch block, Gauge and Delegation info issue

### ISSUE THREAD

**Issue by effofxprime** [osmosis-labs/osmosis#2173]
## Background

I've been running an Osmo full node for a couple of weeks now.  Version is `v10.0.1`.
When the Epoch block is reached, the server "stops working" but the daemon is running and continuing to do peer gossip.  Prior to this, even when the network is under a heavier load, the node keeps up with the chain(I saw this when we had that small spam attack on the network the other day).

Below is a log snippet.  I have a lot of the no delegation distribution info errors and then it pauses on distribute superfluid gauges.
```
Jul 20 12:01:48 horace systemd[1]: Started Osmosis Node.
Jul 20 12:01:48 horace osmosisd[724498]: 12:01PM INF starting ABCI with Tendermint
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting multiAppConn service impl=multiAppConn module=proxy
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting localClient service connection=query impl=localClient module=abci-client
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting EventBus service impl=EventBus module=events
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting PubSub service impl=PubSub module=pubsub
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Starting IndexerService service impl=IndexerService module=txindex
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF ABCI Handshake App Info hash="S>ƿ��[oU��\u007f��'�n3���}EA\r�\f{7��e" height=5238498 module=consensus protocol-version=9 software-version=10.0.1
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF ABCI Replay Blocks appHeight=5238498 module=consensus stateHeight=5238498 storeHeight=5238499
Jul 20 12:01:53 horace osmosisd[724498]: 12:01PM INF Replay last block using real app module=consensus
Jul 20 12:02:30 horace osmosisd[724498]: 12:02PM INF minted coins from module account amount=547945205479uosmo from=mint module=x/bank
Jul 20 12:02:30 horace osmosisd[724498]: 12:02PM INF burned tokens from module account amount=136986301369uosmo from=mint module=x/bank
Jul 20 12:02:30 horace osmosisd[724498]: 12:02PM INF Starting epoch with identifier day epoch number 397 module=x/epochs
Jul 20 12:02:31 horace osmosisd[724498]: 12:02PM INF Move delegation rewards to gauges
....
....  Lots of errors "ERR no delegation distribution info"
....
.... 
Jul 20 12:02:34 horace osmosisd[724498]: 12:02PM ERR no delegation distribution info
Jul 20 12:02:34 horace osmosisd[724498]: 12:02PM ERR no delegation distribution info
Jul 20 12:02:34 horace osmosisd[724498]: 12:02PM ERR no delegation distribution info
Jul 20 12:02:34 horace osmosisd[724498]: 12:02PM INF Distribute Superfluid gauges
```

Server hosting specs:
Linode Dedicated VPS - 8core 16GBram, 57G swap(swap drive is a 3x NVME strip LVM with striped size of 4M).

While the daemon sits and does whatever it's doing behind the scense right now, htop reports that my `PSI FULL IO` is around 40%-60%.  So I am not currently maxing out my IO AFAIK.

## Expectations ##
I don't expect the swap drive to be too limiting on the performance here with how I've configured it in LVM.
Unsure why I am getting the `no delegation distribution info` and the long pause on completing the epoch block.

I searched and think that I am suffering from the same issue as here:  https://github.com/osmosis-labs/osmosis/issues/1797

Please let me know what other info you'd like me to get.  Looking forward to understanding this better as well.
Thank you

**Comment by czarcas7ic** [comment]
Your node is just processing epoch, there is nothing out of the ordinary happening here. The delegation distribution info log is getting fixed in another release. If it is down longer than ~8 minutes, I suspect this is due to your low RAM, as 32GB is the recommended value.

**Comment by effofxprime** [comment]
> Your node is just processing epoch, there is nothing out of the ordinary happening here. The delegation distribution info log is getting fixed in another release. If it is down longer than ~8 minutes, I suspect this is due to your low RAM, as 32GB is the recommended value.

Regarding the delegation distribution log errors, would they have any impact on performance?  Esp. the performance of completing the epoch block?

What I have noticed is, if the server doesn't get rebooted at the time of the epoch, it will never move beyond that block time.  However it will continue to do peer gossip.  I've chalked this up to the distribution errors but wanted to confirm to be sure.

**Comment by czarcas7ic** [comment]
@effofxprime if you are caught up to the head, there is no way you can process the epoch block faster than it takes the network to reach 67% consensus. This is usually ~8 minutes. If its taking you much longer (like, 15 or 20 minutes) its likely you have to have more RAM. The err logs have nothing to do with the performance
