### ISSUE TITLE
Make tests for osmoutils/store_helper

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2179]
## Background

In #2175  we added a utils package for `osmoutils/store_helper.go`, These don't have tests associated with them, we should add tests. (They have tests of the functionality in the TWAP logic PR #2168 )

We need to add unit tests for the store_helper file, and then look into if we can more generally use these

## Suggested Design / Acceptance criteria

- [ ] Write unit tests for functions in `store_helper.go`
- [ ] See if they can be reused for other iterators in the codebase

**Comment by p0mvn** [comment]
I will also cover `osmoutils.MustSet`. The rest of the methods are still available
