### ISSUE TITLE
refactor(osmoutils): make ReverseSlice mutative 

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2181]
**Background**

`ReverseSlice` can be made mutative and reverse in place, achieving O(n/2) time and no extra space by maintaining a pointer to the beginning and to the end of the slice

Example: https://stackoverflow.com/questions/44452668/how-to-reverse-string-in-place-in-java

Original Discussion: https://github.com/osmosis-labs/osmosis/pull/2175#discussion_r926150035

**Acceptance Criteria**
- the suggested algorithm is implemented
- table-driven tests added

**Comment by sehyunc** [comment]
Hey @p0mvn! Is anyone working on this, and if not could I be assigned it?

**Comment by p0mvn** [comment]
Hey @sehyunc . Seeing that you're already assigned but yes, please go for it! Thank you
