### ISSUE TITLE
Create a fee for Gauge Creation

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2191]
## Background

We should make a fee for creating a gauge for a new locked denom (e.g. 50 osmo).

This fee should be based off of the msg_server message, rather than the keeper. We want the pool-incentives hook to not make a cost.

## Suggested Design

Make a new param for gauge creation fee, add it as a cost to the msg_server.

Ensure that pool creation still works with the hooks

## Acceptance Criteria

- [ ] Create gauge requires a cost from the sender
- [ ] pool incentives does not add a cost

**Comment by czarcas7ic** [comment]
@vuong177 hey, I am just ensuring that you are aware @p0mvn and I are working on this right now. If you are looking to also do this to double check our work that is fine, I just wanted to make sure that you knew!

**Comment by vuong177** [comment]
@czarcas7ic Oh,  I don't know you're working on this. ! Thank you so much for letting me know, and please continue your work.
