### ISSUE TITLE
[Epic] Quality assurance for events

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2195]
## Background

During the internal audit, we discovered that the tests and documentation for events across all modules are limited. This is an epic to track work across modules

## Stories
- https://github.com/osmosis-labs/osmosis/issues/1942
- https://github.com/osmosis-labs/osmosis/issues/2194
- TBD: `epochs`
- https://github.com/osmosis-labs/osmosis/issues/2270
- TBD: `mint`
- TBD: `pool-incentives`
- TBD: `tokenfactory`
- TBD: `txfees` 

## Acceptance Criteria
- events are tested and documented across all modules
- the design is consistent across modules

**Comment by p0mvn** [comment]
We should investigate if events are emitted correctly in other modules and create issues for them, if applicable

**Comment by stackman27** [comment]
I can try looking into x/lockup as i'm pretty familiar with that module

**Comment by p0mvn** [comment]
> I can try looking into x/lockup as i'm pretty familiar with that module

That would be awesome! Would you like to create an issue to track this? Similar to #1942 and #2194

**Comment by p0mvn** [comment]
Synched offline - will not pursue this further unless asked for guarantees by integrators. Will wait for more event improvements from the SDK and/or code gen what's possible
