### ISSUE TITLE
Twap: Integrate into mutation testing

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2210]
## Background

We should integrate TWAP into our mutation testing flow.

## Acceptance Criteria

- [ ] Twap integrated into mutation testing
- [ ] Only mutations we don't catch are attempts at deleting errors or panics

**Comment by czarcas7ic** [comment]
Closing in favor of https://github.com/osmosis-labs/osmosis/issues/2426!
