### ISSUE TITLE
x/incentives: refactor create gauge and add to gauge fees to use txfees denom

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2236]
## Background

In #2227, we hard coded the fee denom for create gauge and add to gauge fees. This was done to minimize the changes for a smooth and expedited v11 release.

However, the hard-coded denom causes issues with the simulator. Simulator assumes "stake" denom for majority of its tests by default. As a result, no account has the hard coded "uosmo" denom to pay the fee.

We had to disable simulator in the [incentives tests](https://github.com/osmosis-labs/osmosis/pull/2227/commits/87dd1fe8423b4b680826375138ddfd4d2337489d) for now.

## Suggested Design

We should revert the following 3 commits separately and avoid backporting them to `v11.x`:
- https://github.com/osmosis-labs/osmosis/pull/2227/commits/100b693c51cb28e2da6e23954f7960b881485546
- https://github.com/osmosis-labs/osmosis/pull/2227/commits/915e9ff99a4a615ee4a5de2c74a06bf6368dc94a
- https://github.com/osmosis-labs/osmosis/pull/2227/commits/87dd1fe8423b4b680826375138ddfd4d2337489d

## Acceptance Criteria
- create gauge and add to gauge fee uses denom from the `txfees` keeper
- simulator incentives tests function correctly

**Comment by stackman27** [comment]
Hi @p0mvn is this being worked on?

**Comment by p0mvn** [comment]
Hi @stackman27 . No, please feel free to take this if you'd like
