### ISSUE TITLE
Set up epochs start time in `KeeperTestHelper.App`

### ISSUE THREAD

**Issue by catShaark** [osmosis-labs/osmosis#2241]
## Background

So the epoch time in `KeeperTestHelper.App`  is set to be empty. It should not be empty since in modules' test suite we often set values related to time to be Time.Now(). For example, in incentives' test suite,
we set all the gauges start time to be Time.Now(). This in turn causes unexpected behavior in our tests, like `BeginNewBlock` (with `executeNextEpoch` equals true) won't trigger gauge distribution in incentives' test suite. Specifically, `BeginNewBlock` (with `executeNextEpoch` equals true) will set the suite.Ctx.BlockTime() to be = epoch start time + 5 sec ( = time.Time{} + 5 sec) , because block time (time.Time{} + 5 sec) is way before all the gauges start time (time.Now()) in the tests suite, gauge distribution won't happen

## Suggested Design

- Set epoch time in  `KeeperTestHelper.App`  to be time.Now()

## Acceptance Criteria

- all existing and new tests should pass

**Comment by catShaark** [comment]
@ValarDragon, plz tell me if this is good or not

**Comment by ValarDragon** [comment]
Oh interesting, this is a good point. Yes lets do this!
