### ISSUE TITLE
Node setup using docker - node start failing

### ISSUE THREAD

**Issue by sankararaok** [osmosis-labs/osmosis#2247]
Hi ,
I have used the below command to initialize the node and for starting, 
Initialization is fine , but after that  i have changed the genesis file that generated and used the one mentioned in the github and tried to start the node
But getting error.
11:16AM INF Done init genesis
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

Please guide me on this. please share some docs on how to setup node using osmosis docker.

sudo docker run -it -p 26657:26657 -p 26656:26656 -v /disk/node-osmosis/osmosis/.osmosisd:/osmosis/.osmosisd osmolabs/osmosis:10 init osmosisnode --chain-id osmosis-1 --home /osmosis/.osmosisd
sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-osmosis/osmosis/.osmosisd:/osmosis/.osmosisd  osmolabs/osmosis:10  start --pruning nothing --home /osmosis/.osmosisd

**Comment by ValarDragon** [comment]
A lot of the docker issues have recently been fixed, closing this for now. Please re-open if the issue presents itself
