### ISSUE TITLE
refactor(x/gov): expedited proposals parameter migrations

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2249]
## Background

For expedited proposals we added 2 new parameters:
- [`MinExpeditedDeposit`](https://github.com/osmosis-labs/cosmos-sdk/blob/51bfa90799eee0ca476792955a33acdac88754be/x/gov/types/gov.pb.go#L382)
- [`ExpeditedVotingPeriod`](https://github.com/osmosis-labs/cosmos-sdk/blob/51bfa90799eee0ca476792955a33acdac88754be/x/gov/types/gov.pb.go#L426)
- [`ExpeditedThreshold`](https://github.com/osmosis-labs/cosmos-sdk/blob/51bfa90799eee0ca476792955a33acdac88754be/x/gov/types/gov.pb.go#L472)

However, these parameters have not been set / migrated to. We need to implement the migrations to set the parameters to the desired values according to: https://wallet.keplr.app/chains/osmosis/proposals/278 and its respective common wealth thread.

When the migrations are implemented in the SDK fork, we need to upgrade our `go.mod` in `Osmosis`. As long as the e2e upgrade test passes, the migrations are done correctly and this change is complete. 

## Suggested Design

For reference how the migrations can be done, it is possible to reference:
- https://github.com/osmosis-labs/cosmos-sdk/pull/296
- https://github.com/osmosis-labs/cosmos-sdk/pull/298

From #296, we need a similar change to `x/gov/legacy/v3` package. This time, we need to make a new `v4` package. Additionally. we need to increase the gov module's consensus version to v4

From #298, we need similar boilerplate to enable migrations. The two PRs were split because the changes in #298 were missed and caught in tests. Ideally, these should have been a single PR.

This is a [Cosmos-SDK fork change](https://github.com/osmosis-labs/cosmos-sdk). Openining up issue here because it needs to be updated with this change to unblock https://github.com/osmosis-labs/osmosis/issues/2087.

## Acceptance Criteria
- expedited proposal parameter migrations are implemented in the SDK fork
- parameters are set to the desired values from the gov prop
- the upgraded sdk change is integrated into Osmosis
- e2e upgrade tests continue to pass

**Comment by p0mvn** [comment]
@xBalbinus would you like to work on this? This is a pre-requisite to #2087 that you were interested in picking up

**Comment by xBalbinus** [comment]
Yeah you got it! For sure. I can pick this up early next week - I'm trying to wrap up some inline docs with the pool-incentives audit (and just general things on that end) atm

**Comment by xBalbinus** [comment]
May be closed by https://github.com/osmosis-labs/cosmos-sdk/pull/303
