### ISSUE TITLE
desmos | Transaction Failed when trying to withdraw or deposit on Osmosis

### ISSUE THREAD

**Issue by lorenzomenegon** [osmosis-labs/osmosis#2256]
#### System information

Osmosis version: `10.1.1`
OS & Version: OS Monterey 12.4

#### Expected behaviour
The transaction should be correctly broadcasted.

#### Actual behaviour
A lot of Keplr users are facing this issue when trying to submit a transaction between Keplr and Osmosis with Desmos chain. The error message is the following:

`Transaction Failed: you have too many concurrent txs going on! Try resending after your prior tx lands on chain. (We couldn't send the tx with sequence number 0)`

#### Steps to reproduce the behaviour
To Reproduce
Steps to reproduce the behavior (not happening to every account):

1. Go to https://app.osmosis.zone/assets.
2. Click on Deposit button.
3. Sign the transaction.
4. See the error message posted in the description.

#### Backtrace

This was marked as an Osmosis frontend issue: #https://github.com/chainapsis/keplr-wallet/issues/468

![Screen_Shot_2022-07-06_at_9 21 37_AM](https://user-images.githubusercontent.com/106406454/181766489-0aa13302-7ec4-4849-bee8-6bbf1f7d045f.png)

**Comment by p0mvn** [comment]
Hi @lorenzomenegon Thanks for reporting this.

Since this is a frontend issue I would like to request to please open it in [osmosis-frontend](https://github.com/osmosis-labs/osmosis-frontend). This repository is concerned with chain-dev only and folks don't have the context about the frontend.

cc: @jonator

**Comment by lorenzomenegon** [comment]
Ok, thank you.
