### ISSUE TITLE
fix: backport labels are not working when applied more than once

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2273]
## Background

It is common for us to attach a backport label to a PR. Once Mergify opens it, we might decide to close it and reopen it later.

However, it would not work. Additionally, applying a label to backport to another branch does not work either.

To reproduce, try to backport this PR to v11 by removing and reattaching a backport lable: https://github.com/osmosis-labs/osmosis/pull/2141. Note, that Mergify does not open a backport PR.

## Acceptance Criteria
- backport labels can successfully be reapplied so that Mergify opens a backport PR

**Comment by czarcas7ic** [comment]
@p0mvn says is fixed, closing

**Comment by ValarDragon** [comment]
Cannot replicate
