### ISSUE TITLE
Turn off all markdown lints by default, make explicit whitelist

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2287]
## Background

Lets turn off all markdown lints, and then one by one enable markdown lints. Imo the markdown linter has generally been a huge waste of time, providing very little quality guarantees, and tons of quality flow time burned.

From multiple conversations, theres _very few_ markdown lints we care about. Lets specifically only enable those, and ensure that every single file in this repo passes those lints, 

## Suggested Design

Explicitly disable every markdown lint, make markdown lint apply to every single file, and then one by one re-enable things.

## Acceptance Criteria

- [ ] all but whitelist of Markdown lints disabled in all prior branches
- [ ] Markdown lint is set in GH to apply to every single file
- [ ] If anyone likes particular lints, must one by one PR re-adding it

**Comment by alexanderbez** [comment]
Agree with the proposal!

>  Imo the markdown linter has generally been a huge waste of time, providing very little quality guarantees, and tons of quality flow time burned.

Don't necessarily agree with this though. The linter should guarantee consistency in style across markdown files :)

**Comment by p0mvn** [comment]
What are you proposing to whitelist?

**Comment by ValarDragon** [comment]
I personally only find URL lints, and codeblocks should have language specified useful.

**Comment by p0mvn** [comment]
I haven't had any issues with the markdown lints besides some already disabled so I would say that all are fine with me.

I find heading levels, indentations, and line limits for non-code blocks, particularly useful.

I also would like to second Bez here that the main benefit I see is consistency and. I'm afraid that with the majority of the linters disabled, we would have a variety of styles in our markdowns, making them more challenging to follow. 

To me, the major cause of frustration with markdownlints occurs when someone merges a broken markdown CI lint PR. It doesn't break the CI for the next immediate pull request. However, It then breaks linter CI for someone else working on the same file in the future. 

We could mitigate that by turning [this](https://github.com/osmosis-labs/osmosis/blob/e33e776f4f45d63d4d9c8fa50e09992d80b36d4c/.github/workflows/lint.yml#L58) to true and fixing all existing issues. Then, if someone breaks the markdown linter - it is trivial to `git blame` and resolve the problem. That would help to prevent another person from dealing with issues they didn't cause in the future and remove a lot of frustration about the markdown lints.

What do you think?
