### ISSUE TITLE
feat(twap): create a prune epoch identifier parameter

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2289]
## Background

Currently, we are returning a hardcoded constant for prune epoch identifier in twap. Ideally, this should be a parameter.

https://github.com/osmosis-labs/osmosis/blob/1592bb89a2b13dbedaa8ea63cbe83bf63ea31f1d/x/gamm/twap/keeper.go#L24

The author can reference a similar parameter in the mint module to use it as guidance:
https://github.com/osmosis-labs/osmosis/blob/1592bb89a2b13dbedaa8ea63cbe83bf63ea31f1d/proto/osmosis/mint/v1beta1/mint.proto#L79-L81

## Acceptance Criteria
- prune epoch identifier parameter is created
- tests added to ensure that is it set and used correctly

**Comment by catShaark** [comment]
should this prune epoch identifier parameter be in gamm params ?

**Comment by p0mvn** [comment]
Since twap has its own keeper, I think it might make sense to let it have its own params as well.
