### ISSUE TITLE
CI: Minor releases should sync through more blocks pre-release

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2295]
## Background

Currently we have a CI workflow that runs epoch block + 1000 blocks on every commit to latest release branch. This is great for testing!

We should also have a CI flow that we can use pre-release that syncs through every available block on that branch. (So we make a snapshot of state at a height slightly after upgrade or upgrade directly)

This will increase our pre-release mainnet sync's battery of tests, from 1000 blocks (+ simulator after #2267 ) to all available blocks. The degree to which we can depend on this will depend on whats the syncing advantage factor, what degree we can parallelize the syncs, etc. 

## Suggested Design

Make a CI workflow we can use to try syncing a node with a given branch, from pre-configured start height for that release (e.g. first block of v11 based on a snapshot) to some set end block OR latest block.

This can be something we manually require before tagging any minor or patch version

**Comment by niccoloraspa** [comment]
Hey @ValarDragon, thanks for the issue. I like the idea of running the check for longer periods before a release.
I had simpler approach to address this problem:

What I had in mind was to have a CI that would spin up a node from the **latest** snapshot and leaving it up for a certain amount of time (e.g. 24h hours) setting an `halt-time` in `config.toml`. 

This is simpler to implement as it's only a small variation of our current CI and we wouldn't need to have post upgrade snapshot. At the same time:
- it would only process a portion of the blocks and not only the `vX` blocks
- it would "freeze" the release for the testing time

What I like about this it's this **node-as-service** approach can be generalized to any branch / commit and not necessarily limited to a release

If it's okay with you we can't with this solution first and then modifying to start from from earlier heights.
The main reason for adding this intermediate step it's that we would need to extend our own self-hosted architecture to allows node to run for long period of time.

**Comment by faddat** [comment]
https://github.com/osmosis-labs/osmosis/pull/3507


Does anyone other than myself have a state sync script?

I favor Dev's approach, and use it widely on other chains.  It is a safe way to check for app hash errors.  It requires linking a physical machine into ci because otherwise it takes forever and a day.

**Comment by czarcas7ic** [comment]
@niccoloraspa is there any updates on the path we are looking to go with this?

**Comment by niccoloraspa** [comment]
It's tracked here for reference: https://github.com/osmosis-labs/osmosis-ci/issues/13
