### ISSUE TITLE
Make sure poolincentives can only add OSMO incentives to a perpetual pot

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#230]

**Comment by ValarDragon** [comment]
Governance should catch this, so this should be pretty low priority / ok if we don't get to

**Comment by sunnya97** [comment]
@antstalepresh oh sorry, wasn't well explained.  The key part of this was about making sure it only goes to a perpetual pot.  Because a non-perpertual pot can be deleted after it's run is over, and so we don't want to be distributing to a pot that doesn't exist.  Perpetual pots don't get deleted.
