### ISSUE TITLE
e2e testing should clear existing containers automatically

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#2315]
## Background

When running e2e tests locally, if the tests have already run (and failed) the old containers aren't removed. This leads to 

```
    e2e_setup_test.go:96:
        	Error Trace:	/Users/nicolas/devel/osmosis/tests/e2e/e2e_setup_test.go:96
        	            				/Users/nicolas/devel/osmosis/tests/e2e/suite.go:132
        	            				/Users/nicolas/devel/osmosis/tests/e2e/e2e_setup_test.go:40
        	Error:      	Received unexpected error:
        	            	container already exists

        	            	github.com/ory/dockertest/v3.(*Pool).RunWithOptions
        	            		/Users/nicolas/go/pkg/mod/github.com/ory/dockertest/v3@v3.9.1/dockertest.go:453
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e/containers.(*Manager).RunHermesResource
        	            		/Users/nicolas/devel/osmosis/tests/e2e/containers/containers.go:138
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e/configurer.(*baseConfigurer).runIBCRelayer
        	            		/Users/nicolas/devel/osmosis/tests/e2e/configurer/base.go:110
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e/configurer.(*baseConfigurer).RunIBC
        	            		/Users/nicolas/devel/osmosis/tests/e2e/configurer/base.go:77
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e/configurer.withIBC.func1
        	            		/Users/nicolas/devel/osmosis/tests/e2e/configurer/setup.go:22
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e/configurer.withUpgrade.func1
        	            		/Users/nicolas/devel/osmosis/tests/e2e/configurer/setup.go:32
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e/configurer.(*UpgradeConfigurer).RunSetup
        	            		/Users/nicolas/devel/osmosis/tests/e2e/configurer/upgrade.go:134
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e.(*IntegrationTestSuite).SetupSuite
        	            		/Users/nicolas/devel/osmosis/tests/e2e/e2e_setup_test.go:95
        	            	github.com/stretchr/testify/suite.Run
        	            		/Users/nicolas/go/pkg/mod/github.com/stretchr/testify@v1.8.0/suite/suite.go:132
        	            	github.com/osmosis-labs/osmosis/v10/tests/e2e.TestIntegrationTestSuite
        	            		/Users/nicolas/devel/osmosis/tests/e2e/e2e_setup_test.go:40
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:1439
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1571
        	Test:       	TestIntegrationTestSuite
```

You can manually clear the containers by running `docker rm --force $(docker ps -a -f name=osmo-test -q)` and `docker rm --force $(docker ps -a -f name=hermes-relayer -q)`, but this is tedious and error prone. 

## Suggested Design

Make the tests clear the containers it needs to create before continuing.

## Acceptance Criteria

 - [ ] e2e tests can run without having to clear the containers each time

**Comment by p0mvn** [comment]
We are _suppossed_ to clean up resources in this function:
https://github.com/osmosis-labs/osmosis/blob/fd23552f94caf1df9dbeb6fb4784e9d0efded2a4/tests/e2e/containers/containers.go#L288-L299

On a quick look, it seems that the call to this function is [still there](https://github.com/osmosis-labs/osmosis/blob/fd23552f94caf1df9dbeb6fb4784e9d0efded2a4/tests/e2e/e2e_setup_test.go#L110).

Is there a chance that there is an environment variable set that [lets us avoid deleting the containers](https://github.com/osmosis-labs/osmosis/blob/fd23552f94caf1df9dbeb6fb4784e9d0efded2a4/tests/e2e/e2e_setup_test.go#L100)? We have that functionality for debugging locally

**Comment by ValarDragon** [comment]
I've had this issue locally with containers not getting cleared, and having background osmosisd eat all system CPU for days

**Comment by nicolaslara** [comment]
I wonder if something like this https://stackoverflow.com/a/45379980/989344 works here

**Comment by czarcas7ic** [comment]
Another things that should be added that should not increase the scope dramatically of this issue is clearing the docker network on completion as well. If I run the e2e test long enough, I eventually need to run `docker network prune` in order to remove all the IP reservations since it runs out of available IPs
