### ISSUE TITLE
Add Missing API Endpoints

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#232]
There's a number of important missing api endpoints

Some of them are brand new endpoints that don't exist in the GRPC_server but will be very helpful:

`x/claims`
- [x] Query Params (GRPC, CLI, REST) (completed in #235)

`x/epochs`
- [x] Query CurrentEpoch (GRPC, CLI, REST) (completed in https://github.com/osmosis-labs/osmosis/pull/258 except REST)

`x/gamm`
- [x] Query NumPools (GRPC, CLI, REST)  (completed in https://github.com/osmosis-labs/osmosis/pull/258 except REST)

---

There's also a number that have gRPC endpoints, but are missing associated CLI or REST endpoints.

`x/gamm`
- [ ] ~All REST Endpoints~

`x/claims`
- [x] All REST Endpoints  (completed in #235)

`x/epochs`
- [x] Query EpochsInfos (CLI, REST) (Completed in https://github.com/osmosis-labs/osmosis/pull/259 except REST)

`x/incentives`
- [ ] ~All REST Endpoints~
- [x] [Many CLI Queries left as TODO](https://github.com/osmosis-labs/osmosis/blob/main/x/incentives/client/cli/query.go#L76) (completed in  https://github.com/osmosis-labs/osmosis/pull/260)

`x/lockup`
- [ ] ~Many missing REST Endpoints~

`x/poolincentives`
- [x] All CLI queries (completed in https://github.com/osmosis-labs/osmosis/pull/261)
- [ ] ~All REST queries~

**Comment by antstalepresh** [comment]
> @antstalepresh this is finished?

Yes
