### ISSUE TITLE
Streamswap

### ISSUE THREAD

**Issue by robert-zaremba** [osmosis-labs/osmosis#2333]
## Background

Streamswap is a nove launchapd module providing price discovery, token sale and future integration into a swap pool.

## Subtasks

- [ ] proto definitions
- [ ] Spec and documentation
- [ ] Msg and Query server
- [ ] CLI implementation
- [ ] App wiring
- [ ] sim tests

**Comment by ValarDragon** [comment]
This was moved to cosmwasm!
