### ISSUE TITLE
Change `EstimateSwap` to not require assets

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2337]
## Background

Current `EstimateSwap` queries, namely `EstimateSwapExactAmountIn` and `EstimateSwapExactAmountOut` and the `EstimateSwap` API in the bindings query does not only estimate swaps but includes the actual process of swapping to calculate and estimate. IMO, an API for estimating should not include balance check for the account trying to do the query. Take the gas estimation query in the Cosmos SDK for example, it does not require the sender to have the designated amount of fee and balance as well. 

## Suggested Design

I suggest that we move towards supporting the `EstimateSwap` API so that swaps can be estimated without performing the actual performance of swaps. This can be possibly done by separating out some of the logic within `MultihopSwapExactAmountOut` and `MultihopSwapExactAmountIn`

**Comment by ValarDragon** [comment]
Closed by #3424 which got into v13!

We should update the queries accordingly as well
