### ISSUE TITLE
[x/gamm][stableswap]: Add tests for single-asset joins (`calcSingleAssetJoinShares`)

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2348]
## Background

Our current implementation of `calcSingleAssetJoinShares` is untested. We should make tests that cover similar cases to what we have in balancer.

## Suggested Design

- Create single-asset pool join tests that mirror what we have in balancer but with our stableswap CFMM

## Acceptance Criteria

- All tests pass and removing `updatePoolForJoin` through mutation testing doesn't break `calcSingleAssetJoinShares`

**Comment by RusAkh** [comment]
Is this issue available to work on?

**Comment by p0mvn** [comment]
@RusAkh Yes, please

You can get inspiration from [the existing test cases in balancer](https://github.com/osmosis-labs/osmosis/blob/3c7eab90146396d7cb5ee7f4580244be78bf44f6/x/gamm/pool-models/balancer/pool_suite_test.go#L67) there. However, they might not be exhaustive so if you think of any extra, please add them

**Comment by AlpinYukseloglu** [comment]
I actually covered a significant portion of this issue in #2905, so it might not be a great one to pick up if you don't have context (properly testing this functionality is actually a relatively complicated process)

**Comment by AlpinYukseloglu** [comment]
Update: single-asset joins are now tested (#2905) and can be further tested as part of #2900
