### ISSUE TITLE
Add make command for building binary w/ osmobuilder

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2362]
We use osmo-builder directly in a couple spots to build binaries. We should probably make this into a single make command right?

cref @niccoloraspa 

_Originally posted by @ValarDragon in https://github.com/osmosis-labs/osmosis/pull/2299#discussion_r942725835_

**Comment by niccoloraspa** [comment]
Yes, I think it can be used to replace the various `build-reproducibile-{arm,amd}` in the Makefile.

I also propose that we dismiss: https://github.com/osmosis-labs/osmosis/tree/main/contrib/images/rbuilder

**Comment by niccoloraspa** [comment]
We should also backport the building process to previous `v*.X` branches.

State compatibility check on previous `v*.X` branches is failing because it can't find the `osmo-builder`

**Comment by ValarDragon** [comment]
We can directly PR the latest osmobuilder code to those branches (up to fixing cosmwasm version), since backporting all PRs will probably be a pain
