### ISSUE TITLE
Add wasm update that includes Juno fix

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2368]

**Comment by mattverse** [comment]
- [ ] https://github.com/osmosis-labs/wasmd/pull/8
- [ ] https://github.com/osmosis-labs/wasmd/pull/9

**Comment by faddat** [comment]
very

**Comment by czarcas7ic** [comment]
Decided to move our wasmd to v0.28 (or whatever is latest)

**Comment by p0mvn** [comment]
Created custom branch off of `v0.28.0`: https://github.com/osmosis-labs/wasmd/tree/v0.28.0-osmo-v12 that depends on the osmosis SDK and iavl forks
