### ISSUE TITLE
Figure out a strategy for deffered accrued developer rewards

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#237]
We may want to be able to have developer rewards accrue in another address, that can be one-time transferred via governance sometime post-launch.

Will reply more with thoughts on architecture later. My initial thoughts are having it pay to a module account managed by mint, and then making a new governance proposal type to one-time move those funds into a different address, but this seems like a lot of work prelaunch.

Though if we decide to go with this approach, the governance proposal could come post-launch in the first upgrade.

**Comment by ValarDragon** [comment]
Plan: Undistributed tokens all start in a module account, which then transfers to dev address per the existing procedure

**Comment by ValarDragon** [comment]
Ok so the plan is to:
1) Have unvested developer tokens begin in a module account (so that they exist)
2) Have it pay out to a governance-changeable, weighted list of addresses, whose weights sum to 1.

Furthermore for (2), it should be able to payout to an address such that if the address is a vesting account, it adds to the unvested total. We only need this for DelayedVestingAccounts https://github.com/cosmos/cosmos-sdk/blob/cb66c99eab17d0763ea900d8d7bf2d970e4add22/x/auth/spec/05_vesting.md#delayeddiscrete-vesting-accounts

We should change our fork of the cosmos-sdk to add a SendVestedCoins function to delayed discrete vesting accounts, which will increment the OriginalVesting tokens.

**Comment by antstalepresh** [comment]
For 2, we should have a new module right?

**Comment by ValarDragon** [comment]
```
func (dva DelayedVestingAccount) AddToOriginalVestedCoins(coins sdk.Coins) dva {
    newOriginalVesting := dva.OriginalVesting.Add(coins)
    return DelayedVestingAccount{OriginalVesting: newOriginalVesting}
}
```

On the bank keeper, I think we need to add `SendToOriginalVestedCoins`
```
func (bk BankKeeper) SendFromModuleToAccountOriginalVesting(sdk.Coins) Coins {
   {Existing bank keeper logic for SendFromModuleToAccount, except the recipient account should have its original vesting increment if its a vesting account. If recipient is a regular account, just do a normal send}
}
```

**Comment by sunnya97** [comment]
> For 2, we should have a new module right?

No, we should just change the developer address param in mint to be a weighted list of addresses.
