### ISSUE TITLE
feat(twap): pruning "time to keep records" is configured via parameter

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2371]
## Background

In #2294 , we introduced twap pruning. Currently, the period for which the records are kept is hardcoded:
https://github.com/osmosis-labs/osmosis/blob/62aa54e894b501a7e8ce8866c3f755a187a8429e/x/twap/listeners.go#L31-L32

Instead, this should be set via parameter. 

The implementation should be similar to #2289 

## Acceptance Criteria
- pruning "time to keep records" is configured via parameter
- tests added to ensure that it is set and used correctly

**Comment by stackman27** [comment]
@vuong177 are you working on this?

**Comment by vuong177** [comment]
Yes. I'm waiting for p0mvn's PR will to be merged.
