### ISSUE TITLE
[x/gamm][stableswap] Implement `JoinPoolNoSwap` and `CalcJoinPoolNoSwapShares` abstractions

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2376]
## Background

Our implementation for issue https://github.com/osmosis-labs/osmosis/issues/2128 left out the relevant changes for stableswap for the sake of time. We should implement and test this abstraction asap for stableswap to prevent it from breaking future work as we pick stableswap work back up.

## Suggested Design

- Should be implemented in a similar fashion to what we have in balancer: https://github.com/osmosis-labs/osmosis/pull/2133

## Acceptance Criteria

- All existing and new tests pass

**Comment by p0mvn** [comment]
@AlpinYukseloglu FYI, I'm on this
