### ISSUE TITLE
osmo routed half swap fees

### ISSUE THREAD

**Issue by hleb-albau** [osmosis-labs/osmosis#2406]
## Background

There is passed [proposal](https://www.mintscan.io/osmosis/proposals/187) and [its first implementation attempt](https://github.com/osmosis-labs/osmosis/pull/1069). Should we implement it, or it is abandoned idea?

## Suggested Design

The same as in PR, but implemented on top of current main branch.

## Other

I am ready to impl that.

**Comment by hleb-albau** [comment]
Hey @ValarDragon could you please just drop a line - yes or no :)

**Comment by ValarDragon** [comment]
We should implement this!

**Comment by hleb-albau** [comment]
took it
