### ISSUE TITLE
TWAP: Overflow

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2412]
In TWAP we need to handle overflow of accumulator values, and a strategy for dealing with large spot prices. This issue details (1) how we handle large spot prices, and (2) options for handling overflow that we should decide between.

## How to handle large spot prices

Currently the `GetSpotPrice` function will panic if the spot price is too large or any intermediate term hits some upperbound. Investigation on the upperbound frontier is happening within #2207 .
The guarantees we should get from this PR are:
- GetSpotPrice should never panic (panic's caught)
- Return some "errorOverflow" type and "errorUnderflow" type, depending on internal value
- All pools always support results up to spot prices of some max bound, e.g. 2^128
  - May not be possible for weighted balancer pools right away

**Comment by ValarDragon** [comment]
@nicolaslara and I went through this in some more detail last week. 

Max Accumulator value today is `2**256`

We can upperbound the value in it as `MaxPoolSpotPrice * {time interval}`

MaxPoolSpotPrice is set at `2^119` in https://github.com/osmosis-labs/osmosis/pull/2508/files#diff-d77d97fd9b8bc65f96ceb1cb6a6e8cbbe208b5838691047f8097f3a8560272abR28, but we can change this to be more convenient. For right now, lets abstract as `2^160`.

Then if time interval is measured in nanoseconds, the max time interval would be `2**256 / (2**160) = 2**96 ns = 2.5 * 10^12 years = 2.5 Gyear`

Hence we should have no concern of overflow.

**Comment by czarcas7ic** [comment]
Create a test case that tests out of bounds time, then issue can be closed from there
