### ISSUE TITLE
Make testing suite to ensure queries never alter state

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2457]
## Background

Similar to how we made a test battery for `messages` to check things like encoding, we should make a battery of tests for queries.

One thing in the battery, should be ensuring that all queries do not alter state. (perhaps attempting to commit the block and check app hash, or iterating over every state entry)

## Acceptance Criteria

- [ ] We have a test in AppTesting to ensure that queries aren't state altering
- [ ] We make tests in client/* that are table driven where we make a proto input, run the query, and check that no state changed

**Comment by vuong177** [comment]
Hi @ValarDragon could I do this work? It is related to my PR about estimate swap.

**Comment by ValarDragon** [comment]
Sure!
