### ISSUE TITLE
Small changes/chores for IBC rate limiting contract

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#2485]
This issue tracks the changes/chores left for https://github.com/osmosis-labs/osmosis/pull/2408.

 - [x] Add a readme
 - [ ] Calculate how the rate limit would behave in the two different scenarios from [these comments](https://github.com/osmosis-labs/osmosis/pull/2408#discussion_r949369768) (base limit on current value vs value at the beginning of the period) and adapt the code for the best option 
 - [x] Use Uint256 internally for amounts ([comment](https://github.com/osmosis-labs/osmosis/pull/2408#discussion_r947722594))
 - [x] Upgrade to cosmwasm 1.1
 - [x] Add a schema

**Comment by nicolaslara** [comment]
Should probably also upgrade to cosmwasm 1.1 so that we get nice Uint256 math

**Comment by ValarDragon** [comment]
Closing this tracking issue!
