### ISSUE TITLE
wasm files missing for starting with docker with datafolder dump?

### ISSUE THREAD

**Issue by jun0tpyrc** [osmosis-labs/osmosis#2492]
- data folders obtained from https://www.quicksync.io/networks/osmosis.html
- image quickstarter  from osmolabs/osmosis:11

```
10:58AM INF starting ABCI with Tendermint
failed initialize pinned codes Error calling the VM: Cache error: Error opening Wasm file for reading: No such file or directory (os error 2): pinning contract failed
```

**Comment by niccoloraspa** [comment]
Hey!

Can you paste all the commands you are running to replicate the problem please?

**Comment by czarcas7ic** [comment]
youll need to ensure you are extracting both the data and wasm folder, otherwise this error will occur

**Comment by jun0tpyrc** [comment]
Yes, thanks 
We confirmed the snapshot we got initially was corrupted (without wasm/ folder intact),  extracted the wasm/ folders from another pruned datadir to resume
