### ISSUE TITLE
Domain separate event types by module name Overlaps

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2497]
## Background

While doing mutation tests on tokenfactory, I realized BurnDenom was emitting two events. After looking into this with Roman, we realized that this was due to overlap between the sdk's bank "burn" message and the tokenfactory "burn" message. To fix this, I changed the tokenfactory message name from "burn" to "tf_burn".

## Suggested Design

As Roman suggested, it would probably be best for all module messages to have a module name prefix to prevent overlaps like this in the future. This is especially true for messages that might exist between multiple modules (such as burning and minting)

## Acceptance Criteria

TBD

**Comment by hieuvubk** [comment]
Is anyone working on this issue?? I could close it

**Comment by czarcas7ic** [comment]
@hieuvubk no one is working on this! I will assign you now, thanks!

**Comment by hieuvubk** [comment]
@czarcas7ic  With the `tokenfactory` module, we use TypeMsg to emit events and msg names both, but unlike other modules which have their own msg name, their own event name. With such modules, should we just change the events name

**Comment by czarcas7ic** [comment]
@hieuvubk sorry I am not following, can you explain further?

**Comment by hieuvubk** [comment]
> @hieuvubk sorry I am not following, can you explain further?

https://github.com/osmosis-labs/osmosis/blob/main/x/tokenfactory/keeper/msg_server.go#L67-L72
Here use msg type to emit events.

And the difference:
https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/keeper/internal/events/emit.go#L23-L27

https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/types/events.go#L7
https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/types/msgs.go#L12

So I mean we just need to change the TypeEvt right?
