### ISSUE TITLE
x/twap: track pool state changes after exit pool hooks

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2540]
## Background

Our current TWAP implementation only tracks pool state changes for pool joins and swaps, but not for exits. This should not cause issues in most cases as the swap portions of `ExitSwapShareAmountIn` and `ExitSwapExternAmountOut` are still tracked by the swap listeners, but there are still possible edge cases where pool exits might be able to change spot price due to rounding changes.

## Suggested Design

- Call `trackChangedPool` in our `AfterExitPool` listener in `x/twap/listeners.go`
https://github.com/osmosis-labs/osmosis/blob/0240c650f441d55872311e315d573d4a289cdb9d/x/twap/listeners.go#L52-L53

## Acceptance Criteria

- Changes are tested and all existed & new tests pass

**Comment by hieuvubk** [comment]
@AlpinYukseloglu Could u pls take a look at above pr.
Also I have a questtion: There are 2 funcs call AfterSwap( SwapExactAmountOut, SwapExactAmountAmountIn), but currently we just test SwapExactAmountIn( inside apptesting.RunBasicSwap). Should we add more test for the remaining function or keep as currently.
Same issue with AfterSwap hook.

**Comment by AlpinYukseloglu** [comment]
> @AlpinYukseloglu Could u pls take a look at above pr.
> 
> Also I have a questtion: There are 2 funcs call `AfterSwap` hook( `SwapExactAmountOut`, `SwapExactAmountAmountIn`), but currently we just test `SwapExactAmountIn`( inside `apptesting.RunBasicSwap`). Should we add more test for the remaining function or keep as currently.
> 
> Same issue with `AfterSwap` hook.

Thanks for the PR!

I believe both `SwapExactAmountOut` and  `SwapExactAmountAmountIn` tie back to the same actual swap logic/functions (just with different methods to calculate input/output) so the current setup should be sufficient.
