### ISSUE TITLE
Make KeeperTestHelper constructor, with a no-op suite.Sute

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2554]
## Background

@iboss-ptk is working on CGO bindings to allow testing cosmwasm contracts against live state machine. One issue is that a lot of convenience methods are needed that are the same as what we do in keeper test helper. This can't currently be imported due to issues with suite.Suite depending on testing.T.

## Suggested Design

Make a constructor for KeeperTestHelper that has a no-op for testing suite

## Acceptance Criteria

- [ ] We can make a KeeperTestHelper struct and use all existing methods, without needing testing.T

**Comment by hieuvubk** [comment]
Is anyone working on this issue? I think removing the suite from `KeeperTestHelper` and moving to `KeeperTestSuite` will solve this problem.
Pls lmk what u think
