### ISSUE TITLE
V12: properly update and release fork dependencies

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2566]
## Background

Currently, we have our core repository depending on tags that are in development.

`osmosis-labs/osmosis` depends on `osmosis-main` of `osmosis-labs/cosmos-sdk`

Additionally, `osmosis-labs/wasmd` will temporarily depend on `osmosis-main` `osmosis-labs/cosmos-sdk` in https://github.com/osmosis-labs/osmosis/issues/2368

## Suggested Design

Before v12 release, we should:

1.Kick off a `v045.0x-osmo-v12` `osmosis-labs/cosmos-sdk` branch.
- Make a tag off of that branch.

2. Kick off a `v0.28.0x-osmo-v12` `osmosis-labs/wasmd` branch
- Update the `osmosis-labs/cosmos-sdk` dependency
- Make a tag off of that branch with SDK updated

3. Update `osmosis-labs/osmosis` to depend on the above tags

## Acceptance Criteria
- `osmosis-labs/cosmos-sdk`
    * created v12 release branch (`v045.0x-osmo-v12`)
    * release tag created from release branch
- `osmosis-labs/wasmd`
   * created v12 release branch off of upstream `v0.28.0` tag (`v0.28.0x-osmo-v12`)
   * release tag created from release branch
- `osmosis-labs/osmosis`
   * `osmosis-labs/cosmos-sdk` dependency is updated
   * `osmosis-labs/wasmd`  dependency is updated

**Comment by p0mvn** [comment]
This should be done right before code freeze and is currently blocked on more v12 changes being merged across the stack

**Comment by p0mvn** [comment]
@mattverse what is the decision on wasmd? are we going to use the updated upstream or our fork?

**Comment by mattverse** [comment]
Apologies, I just saw this, both ways work we don't have preference over one another, I think it'd be fine we use wasmd upstream?

**Comment by p0mvn** [comment]
This has been resolved
