### ISSUE TITLE
fix(e2e): decouple tests to allow running them in isolation

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2569]
## Background

Currently, we have the following dependencies between tests:

- ["pool creation test"](https://github.com/osmosis-labs/osmosis/blob/ffccf80f995e70d67f24b22350214af53bc8449f/tests/e2e/e2e_test.go#L21) depends on either the [pre upgrade logic ](https://github.com/osmosis-labs/osmosis/blob/ffccf80f995e70d67f24b22350214af53bc8449f/tests/e2e/configurer/upgrade.go#L108)or [IBC token transfer](https://github.com/osmosis-labs/osmosis/blob/ffccf80f995e70d67f24b22350214af53bc8449f/tests/e2e/e2e_test.go#L33).

- ["superfluid test"](https://github.com/osmosis-labs/osmosis/blob/ffccf80f995e70d67f24b22350214af53bc8449f/tests/e2e/e2e_test.go#L47) depends on the above "pool creation test"

## Suggested Design

We should be able to run each test in isolation for faster debugging and to be able to have shorter makefile steps that can meaningfully run e2e tests without executing the long upgrade logic.

1. To decouple pool creation tests from IBC and upgrade, send IBC tokens inside `TestCreatePoolPostUpgrade` prior to calling `node.CreatePool(...)` with IBC denoms.

2. To decouple superfluid tests from pool creation, create a separate superfluid-specific pool in `TestSuperfluidVoting`

## Acceptance Criteria
- IBC test can be run in isolation
- pool creation test can be run in isolation
- superfluid voting test can be run in isolation

**Comment by p0mvn** [comment]
This is relevant to all tests that we have in `e2e_test.go` today, not just the ones listed in acceptance criteria of this issue

**Comment by ThanhNhann** [comment]
I think all the tests are running independently now, I have tested each of them (just one test at a time) with adjust env in `launch.json` and see that they were all passed, below are images of tests

- TestAddToExistingLock
![TestAddToExistingLock](https://user-images.githubusercontent.com/28915032/215688409-b6f26a46-1325-4f8a-ad41-82e64d731d08.png)

- TestAddToExistingLockPostUpgrade
![TestAddToExistingLockPostUpgrade](https://user-images.githubusercontent.com/28915032/215688416-c02e193a-87d2-48e8-ac43-764ca4b2cf31.png)

- TestArithemeticTWAP
![TestArithemeticTWAP](https://user-images.githubusercontent.com/28915032/215688419-b675aa72-a35b-4bec-9fd2-1de906909921.png)

- TestConcentratedLiquidity
![TestConcentratedLiquidity](https://user-images.githubusercontent.com/28915032/215688425-affd7569-7f74-4072-aec9-d556b1ac0381.png)

- TestExpeditedProposals
![TestExpeditedProposals](https://user-images.githubusercontent.com/28915032/215688430-e507e1b8-41d2-43c8-aa03-34341d453e35.png)

- TestGeometricTWAP
![TestGeometricTWAP](https://user-images.githubusercontent.com/28915032/215688432-4c3611b6-77cd-4273-9d45-421809e53ae6.png)

- TestGeometricTwapMigration
![TestGeometricTwapMigration](https://user-images.githubusercontent.com/28915032/215688435-a06ec3fa-9e60-4a0f-a8a7-6db99fd270da.png)

- TestIBCTokenTransferAndCreatePool
![TestIBCTokenTransferAndCreatePool](https://user-images.githubusercontent.com/28915032/215688438-96ec0c81-3207-4d28-b0ca-0748970c53b1.png)

- TestIBCTokenTrasferRateLimiting
![TestIBCTokenTrasferRateLimiting](https://user-images.githubusercontent.com/28915032/215688440-15c60046-0338-4d64-9963-a1a767653d52.png)

- TestIBCWasmHooks
![TestIBCWasmHooks](https://user-images.githubusercontent.com/28915032/215688442-7ff8dfde-ffc4-4482-b4f1-72837830897e.png)

- TestStateSync
![TestStateSync](https://user-images.githubusercontent.com/28915032/215688444-34d2e9fb-3b34-4137-bd3a-288bcf407f61.png)

- TestSuperfluidVoting
![TestSuperfluidVoting](https://user-images.githubusercontent.com/28915032/215688446-d030c82a-e238-48b4-b786-4c5283e11619.png)

**Comment by p0mvn** [comment]
Great work @ThanhNhann .

Thank you for your thoroughness in verifying this. It will help us to be certain that we can safely start attempting to work on  #4101
