### ISSUE TITLE
feat(release): automate post-upgrade tasks by code generating upgrade handler and auto-increasing e2e version

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2609]
## Background

The post-release process in https://github.com/osmosis-labs/osmosis/issues/2608 can be fully automated.

## Suggested Design

- Once a release a created, we can trigger the post-release GitHub Action
- The GitHub Action runs a script to generate an empty "next version" upgrade handler in `app/upgrades`
   - Some earlier code gen examples can be found here: https://github.com/osmosis-labs/osmosis/blob/roman/twap-e2e/cmd/querygen/README.md#L0-L1
- The e2e upgrade version is increased by the script
- Pull request with the changes is automatically created
   - Our import paths action can be a helpful reference: https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/import_paths.yml

## Acceptance Criteria
- the script is tested on a personal fork
- Proof PR from personal fork is attached
- E2E test is passing
- E2E test is testing the post-release upgrade handler

**Comment by RusAkh** [comment]
hello @p0mvn is this available to work on?

**Comment by p0mvn** [comment]
Yes, please go ahead. Thank you
