### ISSUE TITLE
x/gamm: make balancer `JoinPool` empty return value on error consistent with that of `CalcJoinPoolShares`

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2615]
## Background

Note: this is a minor code hygiene change

Our current balancer implementation for `JoinPool` returns `sdk.Int{}` as `numShares` upon hitting an error, while all of its subsidiary functions return `sdk.ZeroInt()`. `sdk.Int{}` looks really messy in error messages and in general we want consistent error returns along a chain of function calls, so I think this would be a worthwhile change to make.

cc: @ValarDragon would this break anything?

## Suggested Design

- Replace balancer `JoinPool`'s empty return value on error with `sdk.ZeroInt()`
https://github.com/osmosis-labs/osmosis/blob/0b260495245c77d1967d5ef1379387357350d226/x/gamm/pool-models/balancer/pool.go#L656

## Acceptance Criteria

- All existing tests pass

**Comment by hieuvubk** [comment]
@AlpinYukseloglu @ValarDragon should we close this issue, I can work on it

**Comment by AlpinYukseloglu** [comment]
Feel free to pick this up!

**Comment by AlpinYukseloglu** [comment]
Looks like we aren't going to be implementing this – thanks for taking a crack at it anyway @RusAkh!

https://github.com/osmosis-labs/osmosis/pull/2820#issuecomment-1256620893
