### ISSUE TITLE
Update Whitelist for Stargate Query to use Inferred value

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2627]
## Background

Currently Stargate Querier Whitelist keeps a hard coded map of whitelist, using query path as keys, and the actual response proto struct as the value for the map. 

For those queries we do want to whitelist, we have to go through the process of hard coding the whitelist map manually. 

## Suggested Design

The values we are hard coding right now should be able to be inferred using the auto generated proto files, we can create a method to extract the query path and the correct proto struct from the query.pb.go files. The implementation of this might differ depending on how we extract and infer values from the query.pb.go files, it'd be best IMO if we can infer the query path when we simply have a list of response structs.

**Comment by ThanhNhann** [comment]
Does this issue have been assigned sir @mattverse

**Comment by mattverse** [comment]
@ThanhNhann  Please go ahead!

**Comment by ValarDragon** [comment]
I believe this was fixed?
