### ISSUE TITLE
test(e2e): parallelize tests to improve CI times

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2646]
## Background

Since our tests are now independent, we can parallelize them to improve CI times

## Suggested Design

Add `s.T().Parallel()` to the following:
- `TestIBCTokenTransferAndCreatePool`
- `TestSuperfluidVoting`
- `TestAddToExistingLockPostUpgrade`
- `TestAddToExistingLock`
- `TestTWAP`
- `TestExpeditedProposals`

Note:
`TestStateSync` cannot be parallelized

## Acceptance Criteria
-  tests are parallelized
- benchmark CI time improvement
- ensure that the following still work locally:
    * `make test-e2e-debug`
    * `make test-e2e-short`

**Comment by p0mvn** [comment]
ref: https://github.com/osmosis-labs/osmosis/issues/2100

**Comment by p0mvn** [comment]
Might not be as simple as adding `s.T().Parallel()` due to the need for synchronizing some shared variables.

**Comment by ValarDragon** [comment]
I also am suspicious that this is where the big speedup will come from, vs block time changes

Its a bit hard to see right now due to #2653 , but my recollection from before was that the time from traces looked to mostly be in waiting for blocks to occur.
