### ISSUE TITLE
tests/e2e: Stop double building docker images

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2652]
## Background

If you look at the logs for e2e tests, it currently appears that its double-building docker images: https://github.com/osmosis-labs/osmosis/runs/8249355310?check_suite_focus=true

They're being built in both the testing step, and the prior step.

This adds 3.5 more minutes to the e2e test time in CI, which increases developmetn friction.

**Comment by alexanderbez** [comment]
yikes! Seems like a simple job fix. Looking at the job, I wonder if we need the following step?

https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/test.yml#L112-L123

@p0mvn
