### ISSUE TITLE
Setup once a day CI flow to try upgrading to latest upgrade handler on recent mainnet state export

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2675]
## Background

We should have a CI job that can regularly test upgrading a recent mainnet state export from latest mainnet version to the next upgrade handler off of main.

(And ideally output total migration time OR timeout after 4 hours)

This can help us tighten our feedback loop, for knowing if main is safe for upgrades, and should help us reduce at least 1 day from the release timeline.

## Suggested Design

- [x] Daily CI job that:
  - [x] grabs recent mainnet state export
  - [x] adjusts it for being a single val testnet
  - [x] starts network on latest mainnet release
  - [ ] upgrades network
  - [ ] Measures upgrade time and reports it
  - [ ] Scans logs for any errors / panics / early chain halts, makes github issues if they exist

Its possible that this can entirely be done via the e2e test suite, with changing the genesis + being on a sufficiently well resourced machine.

**Comment by czarcas7ic** [comment]
@niccoloraspa Sorry for all the pings, just grooming issues. Is there any updates on this?

**Comment by niccoloraspa** [comment]
We completed the first 3 items and currently working on the 4th.
I didn't think about items 5 and 6, but they sound like a great addition.

I will migrate this issue to the osmosis-ci repository so we can close this here.
