### ISSUE TITLE
test(twap): multi-asset tests for `updateRecords`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2688]
## Background

We should add multi-asset pool tests to `updateRecords`

## Suggested Design

In #2687, we added comments specifying the test cases needed:
https://github.com/osmosis-labs/osmosis/blob/6edfbefcfa5548530126c40144833373606ea473/x/twap/logic_test.go#L900-L902

#2670 adds some useful helpers for multi-asset pool twaps so it's best to wait for it to be merged

## Acceptance Criteria
- specified test added
- helpers from #2670 are reused

**Comment by hieuvubk** [comment]
@p0mvn should we separate the second one into 3 individual test cases?
