### ISSUE TITLE
Different value from abci pool query then from grpc query

### ISSUE THREAD

**Issue by schnetzlerjoe** [osmosis-labs/osmosis#2699]
#### System information

If you abci direct store query using /store/gamm/key vs abci query via grpc with /osmosis.gamm.v1beta1.Query/Pool the results are different by 3 bytes it seems. Check it out here https://replit.com/join/lvdyneppxb-joeschnetzler.

For example pool 9 responses in base64:

/store/gamm/key:
Chovb3Ntb3Npcy5nYW1tLnYxYmV0YTEuUG9vbBKyAgo/b3NtbzEzanIzcDVwMDcwaDRwdTdzeGh0bGRhZzk4OTlzZXY5cHd4MHIydmx2cGt5cmF2cHhscXNzbnpzdXE5EAcaFQoQMjAwMDAwMDAwMDAwMDAwMBIBMCIDMjRoKioKC2dhbW0vcG9vbC83Ehs5MDc5Njk5NjM3MzA3NjY4Mjg1ODc2OTIwMjMyaQpWCkRpYmMvN0M0RDYwQUE5NUU1QTc1NThCMEEzNjQ4NjA5NzlDQTM0QjdGRjhBQUYyNTVCODdBRjlFODc5Mzc0NDcwQ0VDMBIOMjYyNjE1OTE3MjAwMzESDzUzNjg3MDkxMjAwMDAwMDIoChUKBXVvc21vEgwyMzM2ODc1OTQxNjASDzUzNjg3MDkxMjAwMDAwMDoQMTA3Mzc0MTgyNDAwMDAwMA==

/osmosis.gamm.v1beta1.Query/Pool:
CtECChovb3Ntb3Npcy5nYW1tLnYxYmV0YTEuUG9vbBKyAgo/b3NtbzEzanIzcDVwMDcwaDRwdTdzeGh0bGRhZzk4OTlzZXY5cHd4MHIydmx2cGt5cmF2cHhscXNzbnpzdXE5EAcaFQoQMjAwMDAwMDAwMDAwMDAwMBIBMCIDMjRoKioKC2dhbW0vcG9vbC83Ehs5MDc5Njk5NjM3MzA3NjY4Mjg1ODc2OTIwMjMyaQpWCkRpYmMvN0M0RDYwQUE5NUU1QTc1NThCMEEzNjQ4NjA5NzlDQTM0QjdGRjhBQUYyNTVCODdBRjlFODc5Mzc0NDcwQ0VDMBIOMjYyNjE1OTE3MjAwMzESDzUzNjg3MDkxMjAwMDAwMDIoChUKBXVvc21vEgwyMzM2ODc1OTQxNjASDzUzNjg3MDkxMjAwMDAwMDoQMTA3Mzc0MTgyNDAwMDAwMA==

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ValarDragon** [comment]
This is something interesting, but is intended. It relates to how interface encoding is done in cosmos.

People should not be relying on raw KV store queries for Osmosis, there are no guarantees given for stability of this.

**Comment by schnetzlerjoe** [comment]
> This is something interesting, but is intended. It relates to how interface encoding is done in cosmos. The query returns a protobuf any.
> 
> People should not be relying on raw KV store queries for Osmosis, there are no guarantees given for stability of this across upgrades.
> 
> Closing unless theres more we should investigate! Here is the line https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/grpc_query.go#L63

Interesting. For someone using interchain accounts and/or interchain queries that would be tough as you would not be able to prove the data using grpc (no proof returns). Plus the provable value is the raw KV store. Any suggestions?
