### ISSUE TITLE
[stableswap]: Resolve large inaccuracies that arise from solver approximations

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2702]
## Background

Our CFMM solver has many terms that are heavily approximated, mainly due square root approximations. This leads to an ever-increasing inaccuracy in the output of the CFMM that scales with the number of tokens in pool reserves. We need to find a way to minimize or bound these inaccuracies if we want to be able to accommodate pools with large amounts of assets.

The simplified solver implemented in #2697 reduces these inaccuracies by around 3x for our current tests, but they still fall outside of our intended thresholds and, importantly, still scale with the number of assets in the pool. We can continue trying to simplify the solver, but I believe this path will have significantly diminishing returns.

## Suggested Design

- Interpolate the output value given the difference in k values between the beginning and end of the solver
- If there is a clear overestimate, truncate the output to minimize security risks in the short term

## Acceptance Criteria

- Trades of all sizes against pools with $100M in each asset fall within our expected thresholds

**Comment by ValarDragon** [comment]
I feel like the binary search approach is probably the move.

Also we really need to raise the fractional exponentiation precision bound, for the cubic root.

**Comment by AlpinYukseloglu** [comment]
Closed by #2845
