### ISSUE TITLE
Queries should return an error if the data at the requested height is not available

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#2710]
## Background

Queries with `--height` on pruned state return the default values. Example:
```
❯ osmosisd query bank total --denom uosmo --height 5977650
amount: "0"
denom: uosmo
```

## Suggested Design

Check if the IAVL and see if the version is stored. If it isn't, return an error. 

## Acceptance Criteria

 * Queries on pruned state return errors instead of defaults

**Comment by mattverse** [comment]
Yeah this was a known tech debt that we need to come back to to fix in the sdk side.

From a brief investigation, I wonder why this is happening, where this error should be caught and returned as stated in
https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/abci.go#L634-L641

**Comment by mattverse** [comment]
Ah it's from how we handle CacheMultiStore, assigning myself for this issue for further investigation

**Comment by ValarDragon** [comment]
This has been fixed
