### ISSUE TITLE
Add Swagger docs for x/ibc

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis#273]
Currently, there is no endpoint documentation for IBC related queries on Swagger.

While users could reference other chain's IBC endpoint information (like [Cosmos Hub](https://v1.cosmos.network/rpc/v0.41.4)), it'd greatly improve dev experience if IBC endpoint docs were provided for Osmosis Swagger as well.

**Comment by Thunnini** [comment]
Fixed in #278
