### ISSUE TITLE
Global fee module

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#2732]
## Background

The global fee module is a convenient way of setting fees for the entire chain. Instead of setting them by governance and dinging validators for non-compliance through social channels or somewhat imaginary future governance channels, it may make sense to implement the global fee module in Osmosis version 12 or 13. 

## Suggested Design

We recently implemented the global fee module for Eve and I believe that it should be pretty easy to implement in osmosis.

## Acceptance Criteria

* need default fee setting
* Global fee module should be integrated with osmosis tests and updated to match osmosis style if needed.

**Comment by faddat** [comment]
This issue should be closed if the txfee module does what I think it does.

**Comment by ValarDragon** [comment]
I'd like to write an EIP-1559 module instead, aiming to write up a github issue for it by next week
