### ISSUE TITLE
x/gamm: Make a `PoolType()` query, that returns a string type name

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2739]
## Background & suggested design

We should make a `PoolType()` query, so users & contracts can easily know the type of a pool, between Balancer and Stableswap pools. This can be done via the `pool` query, but thats intended for clients as a fallback if they need the raw representation. We don't want that to be the stable API people are depending upon, and hence don't want that to be contract-accessible.

**Comment by RusAkh** [comment]
I think it would be good to add a method to PoolI interface for example .Type() so we won't need to use typecasting to access type
```
_, ok := pool.(*balancer.Pool)
if ok {
      return &types.QueryPoolTypeResponse{Type: "Balancer"}, nil
} 
return &types.QueryPoolTypeResponse{Type: "Stableswap"}, nil
```
