### ISSUE TITLE
apptesting: Switch BeginBlocker and EndBlocker calls to be ABCI calls

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2740]
## Background

The SDK baseapp has a very undocumented / hard to understand dependence on new Ctx generations, that are needed for App.DeliverTx to work with the same go ctx we use in test code. This is something we reverse engineered to be correct within the simulator, and just painstakingly did for osmosis-rust.

Our go tests currently work off of a ctx that is distinct from what would be used for DeliverTx's if we used both. In #2575 we fixed one of the problems.

It remains that we need to fix the `s.App.BeginBlocker(ctx, req)` and `s.App.EndBlocker(Ctx, req)` calls, to instead be the ABCI calls `s.App.BeginBlock(req)` and `s.App.EndBlock(req)` . We likely need to ensure that the entire begin block / endblock / (optional commit) flow is happening correctly in tests. (And were exposing the sensible API's from our code)

## Suggested Design

- [ ] Change the beginblock + endblock calls to be ABCI method
- [ ] Map the flow were doing in failing tests, understand if we have API issues or more changes that need to happen, etc.

## Acceptance Criteria

- [ ] We only call ABCI calls for begin/endblock in apptesting

**Comment by hieuvubk** [comment]
I got a problem when changing `BeginBlocker` to `BeginBlock`, especially in `upgrades_test`. The `LastBlockHeight` from the previous block's commit is required to start a new block.
Looks like we are just changing the context Header without committing

**Comment by ValarDragon** [comment]
Lets close for now, we have to revisit anyway when we ugprade to SDK's runtime module
