### ISSUE TITLE
Revert fixed gas costs for swaps

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2758]
## Background

Revert https://github.com/osmosis-labs/osmosis/pull/2016 for v12

## Suggested Design

TBD

## Acceptance Criteria

TBD

**Comment by hieuvubk** [comment]
Can I ask a question about why we need to revert it? 🤔🤔

**Comment by czarcas7ic** [comment]
@hieuvubk increases testing requirements, for now we are reverting and can implement this in the future.

**Comment by hieuvubk** [comment]
> @hieuvubk increases testing requirements, for now we are reverting and can implement this in the future.

Thank you for letting me know. I'll work on this issue

**Comment by p0mvn** [comment]
Closed by https://github.com/osmosis-labs/osmosis/pull/2808
