### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#276]
We should update the project README

We should include things about the general vision, and whats done thus far.

**Comment by p0mvn** [comment]
This is outdated, closing

**Comment by ValarDragon** [comment]
Its still actually appllicable,. in that the github readme is pretty bad / basically irrelevant to what we currently do

**Comment by p0mvn** [comment]
Let me reopen for now so that this doesn't get lost but I agree about the need for a new issue

**Comment by ValarDragon** [comment]
Closing in favor of more recent issues
