### ISSUE TITLE
fix(build/ux): unable to build localnet with state export due to broken dockerfile

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2760]
## Background

`make localnet-build-state-export` is broken:

```
COPY failed: file not found in build context or excluded by .dockerignore: stat tests/localosmosis/testnet_genesis.json: file does not exist
make: *** [Makefile:367: localnet-build-state-export] Error 1
```

The problem is that the following file does not exist:
https://github.com/osmosis-labs/osmosis/blob/d9bfe9432a4a6f94ae8ab6ab168f4fad7f19178f/tests/localosmosis/mainnet_state/Dockerfile-stateExport#L39

## Acceptance Criteria
- fix the makefile step

**Comment by p0mvn** [comment]
I'm not sure if anyone uses this. Seems that it has been broken for a while. If unused, maybe we can consider removing all this logic instead of spending time fixing it.

CC: @czarcas7ic

**Comment by czarcas7ic** [comment]
It is not broken, see step 5 https://github.com/osmosis-labs/osmosis/tree/main/tests/localosmosis#localosmosis-with-mainnet-state

If you do not do step five, then step 7 (running that command) wont work because it will have no input file to modify

**Comment by p0mvn** [comment]
Will try, thanks
