### ISSUE TITLE
x/incentives: Delete ModuleDistributedCoins query

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2766]
## Background

I don't understand the use case of this, with permissionless gauge creation. I think we should delete this query, and logic that exists solely for this query to exist.

Its possible that this could be helpful for tests, but we should still be deleting the query in this case.

## Acceptance Criteria

- [x] Grpc query for x/incentives `ModuleDistributedCoins` is deleted

**Comment by faddat** [comment]
So, I did this by **only** deleting the query, but not the messages.
