### ISSUE TITLE
Cleanup Balancer Pools

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2791]
## Background

We currently have many unimportant pools, that were created before pool creation fees were created.
This burdens front end developers and node operators, causing high network fees in the pools query.

## Suggested Design

Proposed way of doing this is referencing https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/pool.go#L115, and including it in V13. 

The code snippet we've created back in the days. (We need a sincere review on this (maybe rewrite the entire function since most of the pool APIs are now outdated) as this was created long time ago). 

## Acceptance Criteria

- Rewrite or have deep code review on `CleanupBalancerPool`
- Add test cases for `CleanupBalancerPool`

**Comment by JohnnyWyles** [comment]
Bumping this as it has been raised again.
We have governance approval for this from the early days of the chain.
https://www.mintscan.io/osmosis/proposals/85

**Comment by ValarDragon** [comment]
We have decided that this does not make sense to do on-chain given the current state of Osmosis. The goal can be achieved by making a new query that skips these pools.
