### ISSUE TITLE
State Export ICA Patch v11

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2800]
## Background

We need to merge this change to v11.x, otherwise anyone trying to state export a v11 height wont be able to state export

https://github.com/osmosis-labs/osmosis/commits/adam/v11-ica-export-patch

**Comment by ValarDragon** [comment]
Can you PR it to v11?

**Comment by czarcas7ic** [comment]
Yes, can do this Monday!

**Comment by czarcas7ic** [comment]
I believe so, see:

https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.45.0x-osmo-v9.3

and

https://github.com/osmosis-labs/osmosis/blob/v11.x/go.mod#L274-L275

Closing
