### ISSUE TITLE
Deprecate `docker-build-debug` in Makefile

### ISSUE THREAD

**Issue by niccoloraspa** [osmosis-labs/osmosis#2853]
## Background

https://github.com/osmosis-labs/osmosis/pull/2440 removed the `debug` osmosis image, but we still have some reference to it in the Makefile: https://github.com/osmosis-labs/osmosis/blob/c4f2cfc68ce9c731cd118c11fd6cc5a014dbe95b/Makefile#L292-L294

We should remove any reference to the `debug` osmosis image favoring the use of the  osmosis `-alpine` image.

## Suggested Design

- Replace `debug` osmosis image with `alpine` osmosis image 
- Update e2e to ensure that the changes don't break anything 

## Acceptance Criteria

No more references to the `debug` osmosis image

**Comment by p0mvn** [comment]
Not sure I'm following why we are removing this. It is used by e2e

https://github.com/osmosis-labs/osmosis/blob/811f922b10004ce16f2ee1255f0cb13cc211b8e3/.github/workflows/test.yml#L118

https://github.com/osmosis-labs/osmosis/blob/327a6d62550ea29110e78b046eae4ab01f951741/tests/e2e/containers/config.go#L21-L22

**Comment by p0mvn** [comment]
I see now, the alpine image is meant to be specifically local

**Comment by p0mvn** [comment]
I suggest the following:
- remove `docker-build-debug` in Makefile
- rename `docker-build-debug-alpine` Makefile step to `docker-build-debug`
