### ISSUE TITLE
[stableswap]: Add max pool asset check to ValidateBasic()

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2860]
## Background

Even with scaling factors and increased decimal precision, we still need to have a cap on the number of assets we can support in multi-asset pools.

This number should be somewhere between 4 and 8 assets per multi-asset pool and can be enforced by adding checks at pool creation. The simplest check we can add is in ValidateBasic(), although we should enforce this at lower levels as well as a guardrail.

## Suggested Design

- Expand the input asset length check in ValidateBasic() to include a maximum (currently only checks that there are min 2 assets)
- Add any other relevant checks to CreatePool etc.

## Acceptance Criteria

- All new and existing tests pass

**Comment by hieuvubk** [comment]
@AlpinYukseloglu As I read in the description, we don't allow pool with 3 assets right?

**Comment by hieuvubk** [comment]
Alright I had a little misunderstanding here. We don't have a conclusion about the specific cap yet, right?

**Comment by AlpinYukseloglu** [comment]
Yes we haven't finalized it yet! It will come down to a number of factors tied to current open issues/PRs (not a major decision just one I'd prefer not to spend too much time reverting/changing)
