### ISSUE TITLE
[stableswap]: Add scaling factor tests

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2861]
## Background

Scaling factors currently have a basic test skeleton commented out in the keeper tests that needs to be moved to our `pool_test.go` and filled with test cases for scaling/descaling pool assets

## Suggested Design

- Move commented tests from keeper tests to `pool_test.go`
- Add thorough test cases (even/uneven pools, even/uneven scaling factors, min and max scaling factors, overflow/underflow, panic catching etc.)

## Acceptance Criteria

- All new and existing tests pass

**Comment by AlpinYukseloglu** [comment]
@hieuvubk I saw that you self-assigned - I was working on this alongside a few other scaling factor changes so will unassign you for now (I hope you weren't too far into it!).

In general I will probably be picking up (or already have significant progress for) the stableswap-related issues I create unless I tag them as 'Good First Issue' :)

**Comment by hieuvubk** [comment]
Okay got it, thank you!
