### ISSUE TITLE
Upgrade to 12 startup error reported

### ISSUE THREAD

**Issue by leezijie** [osmosis-labs/osmosis#2862]
I started downloading osmod-12 binaries, but the boot failed.So I downloaded the latest snapshot, but it still booted incorrectly.
start: `/data/blockdata/osmo/osmosisd-12.0.0 start --home /data/blockdata/osmo/node`
logs:`INF starting ABCI with Tendermint
5:01PM INF service start impl=multiAppConn module=proxy msg={}
5:01PM INF service start connection=query impl=localClient module=abci-client msg={}
5:01PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
5:01PM INF service start connection=mempool impl=localClient module=abci-client msg={}
5:01PM INF service start connection=consensus impl=localClient module=abci-client msg={}
5:01PM INF service start impl=EventBus module=events msg={}
5:01PM INF service start impl=PubSub module=pubsub msg={}
5:01PM INF service start impl=IndexerService module=txindex msg={}
5:01PM INF ABCI Handshake App Info hash="�f��\vIj(�d�k!�$/Hq%{T��@\f�-�\x05�M�" height=6181763 module=consensus protocol-version=0 software-version=12.0.0
5:01PM INF ABCI Replay Blocks appHeight=6181763 module=consensus stateHeight=6181763 storeHeight=6181764
5:01PM INF Replay last block using real app module=consensus
5:01PM INF client state updated client-id=07-tendermint-1 height=4-12203514 module=x/ibc/client
5:01PM INF packet received dst_channel=channel-0 dst_port=transfer module=x/ibc/channel sequence=1327532 src_channel=channel-141 src_port=transfer
5:01PM INF minted coins from module account amount=9200000ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2 from=transfer module=x/bank
5:01PM INF acknowledgement written dst_channel=channel-0 dst_port=transfer module=x/ibc/channel sequence=1327532 src_channel=channel-141 src_port=transfer
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x2b5e588, 0xc0016a6ec0}, 0xc00020a400, {0x2b38790, 0xc0016f4f50}, {0x2b387e0, 0xc0016f5070}, {0xc00015eaf8, 0x7, 0x18}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/params/types/subspace.go:109 +0x307
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.MinSelfDelegation(...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/keeper/params.go:58
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.GetParams({{0x2b38790, 0xc0016f4f00}, {0x2b5e588, 0xc0016a6ec0}, {0x2b52620, 0xc001283440}, {0x2b5be78, 0xc000179b80}, {0x2b5f008, 0xc001323458}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/keeper/params.go:71 +0x6a8
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.ApplyAndReturnValidatorSetUpdates({{0x2b38790, 0xc0016f4f00}, {0x2b5e588, 0xc0016a6ec0}, {0x2b52620, 0xc001283440}, {0x2b5be78, 0xc000179b80}, {0x2b5f008, 0xc001323458}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/keeper/val_state_change.go:109 +0xbb
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.BlockValidatorUpdates({{0x2b38790, 0xc0016f4f00}, {0x2b5e588, 0xc0016a6ec0}, {0x2b52620, 0xc001283440}, {0x2b5be78, 0xc000179b80}, {0x2b5f008, 0xc001323458}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/keeper/val_state_change.go:27 +0x7d
github.com/cosmos/cosmos-sdk/x/staking.EndBlocker({{0x2b503c8, 0xc00012a000}, {0x2b60240, 0xc000718e40}, {{0xb, 0xa}, {0xc001426ad0, 0x9}, 0x5e5384, {0x2e2bf336, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/abci.go:26 +0xff
github.com/cosmos/cosmos-sdk/x/staking.AppModule.EndBlock(...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/module.go:175
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x2b503c8, 0xc00012a000}, {0x2b60240, 0xc000718e40}, {{0xb, 0xa}, {0xc001426ad0, 0x9}, 0x5e5384, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/types/module/module.go:502 +0x449
github.com/osmosis-labs/osmosis/v12/app.(*OsmosisApp).EndBlocker(_, {{0x2b503c8, 0xc00012a000}, {0x2b60240, 0xc000718e40}, {{0xb, 0xa}, {0xc001426ad0, 0x9}, 0x5e5384, ...}, ...}, ...)
	github.com/osmosis-labs/osmosis/v12/app/app.go:323 +0x78
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc001043500, {0x0?})
	github.com/cosmos/cosmos-sdk@v0.46.1/baseapp/abci.go:241 +0x1dd
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000714840, {0xc000714840?})
	github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:288 +0xdf
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0006de8a0?, {0xc000728000?})
	github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:89 +0x24
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2b51740?, 0xc0007152c0}, {0x2b57da0, 0xc004692e50}, 0xc000ffeb40, {0x2b5f9c0, 0xc000132330}, 0x5e5383?)
	github.com/tendermint/tendermint@v0.34.21/state/execution.go:327 +0x54e
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0xa}, {0xc00468e2e8, 0x7}}, {0xc00468e300, 0x9}, 0x1, 0x5e5383, {{0xc002c92b60, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0xa}, {0xc00468e2e8, 0x7}}, {0xc00468e300, 0x9}, 0x1, 0x5e5383, {{0xc002c92b60, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0xa}, {0xc00468e2e8, 0x7}}, {0xc00468e300, 0x9}, 0x1, 0x5e5383, {{0xc002c92b60, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc003dd3b28, {0x2b60a10, 0xc00059ca90})
	github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0xa}, {0xc00468e2e8, 0x7}}, {0xc00468e300, 0x9}, 0x1, 0x5e5383, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001305900, {0x2b4d230, 0xc0029c6000}, 0xc0028424d0, {0x2b33820, 0xc0029c42a0}, 0x1?, 0x0?, 0xc002842650, {0x2b51740, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2b67ab8, 0xc000ec7bf0}, {0x0, 0x0}, {0x2b55600, 0xc0012df720}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/server/start.go:262 +0x79b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001344000?, {0xc00138f0e0?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.46.1/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc001344000, {0xc00138f0c0, 0x2, 0x2})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc001276f00)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000357c98, 0x18})
	github.com/cosmos/cosmos-sdk@v0.46.1/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/osmosis-labs/osmosis/v12/cmd/osmosisd/main.go:16 +0x31`

**Comment by ValarDragon** [comment]
You shouldn't upgrade until after the upgrade height! Please see the upgrade instructions: https://www.mintscan.io/osmosis/proposals/335

> As always, we recommend validators utilize 64GB of RAM. Since state migration is relatively negligible in this upgrade, it is likely possible to get away with less, but still not recommended. If you are unable to have 64GB of RAM, at a minimum have a total of 64GB of swap set to prevent out of memory errors.
> 
> If using cosmovisor, manually build & copy the osmosisd binary to /cosmovisor/upgrades/v12/bin/.
> 
> If not using cosmovisor, wait for your node to halt at the upgrade height, then install and run the v12.0.0 binary.

How did you find out about the release? We should make the upgrade instructions more evident there.

**Comment by leezijie** [comment]
> As always, we recommend validators utilize 64GB of RAM. Since state migration is relatively negligible in this upgrade, it is likely possible to get away with less, but still not recommended. If you are unable to have 64GB of RAM, at a minimum have a total of 64GB of swap set to prevent out of memory errors.
> 
> If using cosmovisor, manually build & copy the osmosisd binary to /cosmovisor/upgrades/v12/bin/.
> 
> If not using cosmovisor, wait for your node to halt at the upgrade height, then install and run the v12.0.0 binary.

Thanks.
