### ISSUE TITLE
Discussion: Add pool type query to Pool Interface

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2868]
## Background
We've added a new query where it returns the pool type(string) given poolID. (https://github.com/osmosis-labs/osmosis/pull/2832)
For now, it's implemented as a go API, which would try type casting to each pool model type manually and then return which ever the pool model is. 

As per discussion within the PR,(https://github.com/osmosis-labs/osmosis/pull/2832#discussion_r979380401) we want further discussions and opinions on whether we should make a new exposed method in the Pool( the pool interface) which would return the pool type, or rather keep it as a go API.

## Suggested Design

Implementing it as s pool interface would look something like this: `GetPoolType() string`
where each pool would return a string which indicates the pool model name.

**Comment by mattverse** [comment]
I'm leaning towards leaving it as a go API, and the reason behind it is that I think if we're able to infer pool type from the keeper layer, not in each pool model package layer, why make it as a part of the pool interface?

Open to further ideas and discussions on this!

**Comment by ValarDragon** [comment]
That sounds quite reasonable to me, hadn't thought about that

**Comment by mattverse** [comment]
Closing this issue, with the conclusion that we're leaving the pool type query as is!
