### ISSUE TITLE
limit number of gauges per denom

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#289]
Currently the distribution code is slower than we expected, and runs in time `O(sum_{denoms} (#gauges for that denom) * (#lockups for that denom)`. We expected to instead have been `O(sum_{denoms} (#gauges for that denom) + (#lockups for that denom)`. This is something thats not hard to fix post-launch, its just that fixing it doesn't fit into our launch timeline.

In light of this, we've decided that the best way to proceed for launch is to limit the number of gauges for each denom.

We want to limit the creatable gauges to just be ones that have a DistrCondition based on `Duration` (so for now just rejecting ones with a StartTime based DistrCondition. We can work out deleting all that code post-launch)

Then we also want to limit the creatable durations for a denom to just be one of a small number of durations. Lets for now just make it the same set as used in pool-incentives (but the parameters being managed separately). We should also ensure that only one gauge for a `(denom, duration)` pair can be created.

**Comment by antstalepresh** [comment]
> We want to limit the creatable gauges to just be ones that have a DistrCondition based on `Duration` (so for now just rejecting ones with a StartTime based DistrCondition. We can work out deleting all that code post-launch)

What you mean by deleting all that code? @ValarDragon
