### ISSUE TITLE
[x/gamm][stableswap]: Make scaling/descaling logic also convert to and from `BigDec`

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2903]
## Background

Scaling/descaling can serve as a convenient place to convert inputs and outputs to/from `BigDec` for core stableswap math. Once we make this change, we should ensure that the only conversions to and from `BigDec` happen through the scaling functions.

## Suggested Design

- Make scaling functions do `SDKDec` -> `BigDec` and descaling do `BigDec` -> `SDKDec`

## Acceptance Criteria

- All conversions to and from `BigDec` happen under scaling functions
- All existing and new tests pass

**Comment by AlpinYukseloglu** [comment]
It just occurred to me that this might not be fully possible since we directly interact with the `PoolI` interface for single asset joins @ValarDragon 

Am I right in assuming that if we want to use scaling/descaling functions to gate `SDKDec` <-> `BigDec` conversions (and do all internal calculations with `BigDec`), we would have to create a `BigDecCoin` implementation and an internal pool interface that supports it?

**Comment by Stphill0** [comment]
Hi @AlpinYukseloglu kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)
