### ISSUE TITLE
State Export Logic Audit

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2940]
## Background

If it ever came down to needing a new genesis file for mainnet, we need to be certain that the current state export logic created a genesis file that replicated mainnet 1:1. As it stands, we have had to make many changes over the months after realizing things were left out or were incorrect in osmo-test-4 due to improper state export logic.

## Suggested Design

Go through every module and ensure state export logic is sound.

We can even make a new testnet (osmo-test-5) to be the new main testnet, and we can query various things on this testnet and see if there is anything off in terms of what should have been exported and what really was exported.

## Acceptance Criteria

Every module has been checked against a running testnet to verify all state export logic is sound.

**Comment by ValarDragon** [comment]
Unneeded due to in place testnet
