### ISSUE TITLE
About osmosis swap transactions

### ISSUE THREAD

**Issue by huzi0007** [osmosis-labs/osmosis#2948]
I want to implement  transaction of Osmosis through programming, 

For example：
    I have 2,000 JUNO tokens. I want to swap 1,000 JUNO tokens to OMOS tokens, and set the Slippage smaller than 3%.
    I have read all the documents of osmosis, but also don't know how to achieve it. Hope to get help, thank you!

**Comment by MayVictor** [comment]
Hello @huzi0007  A support ticket has been opened for you Talk to a Dev on the [Live support page](https://rebrand.ly/LiveChat-Support) so that your issue can be looked into. [CLICK HERE](https://rebrand.ly/LiveChat-Support)

**Comment by czarcas7ic** [comment]
I think you can achieve what you are looking to do using a swap router contract. See this workshop Roman and I gave last week!

https://github.com/p0mvn/swaprouter-workshop

**Comment by huzi0007** [comment]
> I think you can achieve what you are looking to do using a swap router contract. See this workshop Roman and I gave last week!
> 
> https://github.com/p0mvn/swaprouter-workshop

I'm sorry to say that I just know JavaScript and python，therefore I don't know how to use this docs.
Thank you all the same!
