### ISSUE TITLE
Make Export Less RAM Intensive (IAVL Changes)

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2953]
## Background

It currently takes VMs with 64GB of RAM to export/import full state exports. Some basic IAVL improvements can be done to improve this performance.

## Suggested Design

* Key format change
  * Replace all native maps with BTree maps
* We currently have atmoic writes at a per module scope, which is not efficient
  * We should lower the scope of atomic writes from the 100s of MBs to the 100s of KBs  

## Acceptance Criteria

* Import/Export does not take extraordinary amounts of RAM to work

**Comment by catShaark** [comment]
Can I have some questions ?
- What maps should we replace ? Maybe native maps like [this](https://github.com/cosmos/iavl/blob/3198de953ee62f0f83c7b8eb91acfbe36b0a07a4/cache/cache.go#L48) ?
- We should use https://github.com/tidwall/btree for BTree maps right ?
-

**Comment by catShaark** [comment]
> We currently have atomic writes at a per module scope

This refers to cms Store's Write() right ? Can you explain this more ?

**Comment by czarcas7ic** [comment]
I am going to have to have a separate conversation with Dev to get a better / more concrete understanding of the best way forward with this. This might have to happen later this week sadly

**Comment by catShaark** [comment]
seems like the non-atomic writes is explained [here](https://github.com/cosmos/cosmos-sdk/issues/6370#issuecomment-643226398)

**Comment by catShaark** [comment]
@czarcas7ic, do we have any update on this?

**Comment by czarcas7ic** [comment]
I sadly do not have context on this, @ValarDragon would you be able to write something out in order to allow @catShaark to pick up this task?

**Comment by ValarDragon** [comment]
> Key Format Changes

Basically make key formats we write to disk follow `write_version | path_to_node`

> Replace all native maps with BTree maps

This is entirely unrelated

> We currently have atmoic writes at a per module scope, which is not efficient 

Basically just change the batch.write usage in IAVL, to write in many smaller batches. E.g. write every 1MB atomically, don't keep growing the batches. We already have tooling for detecting when we've completed the final write, the whole thing should not be atomic, it should just be possible to safely automatically rollback.

**Comment by p0mvn** [comment]
@catShaark I would love to work with you on batch writing. Would you be interested in working together?

**Comment by catShaark** [comment]
yesss, just tell me what to do

**Comment by ValarDragon** [comment]
Unneeded due to in-place testnet
