### ISSUE TITLE
Change expectPass with bool fields in test cases to `expectedError` fields with error types

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2959]
## Background

Most of the current test cases have an `expectPass` or an `expectFail`, `expectError` with a boolean value set as its field. (ex. https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/msg_server_test.go). 

Although these test cases are still valid, these test cases sometimes can turn out to be inaccurate, as the test case itself can omit different errors from different parts of the code from different reasons, not exactly from the logic we're trying to test, and not exactly from the reason we're expecting it to error. 

## Suggested Design

Although we do have **alot** of these test cases with the test cases of having these expectPass boolean fields as test cases, we should move towards chagning these to `expectedError` with the type of `Error` and precisely check the Error that's happening to ensure that we're erroring for reasons that we're expecting. 

A good example to reference is https://github.com/osmosis-labs/osmosis/blob/main/x/mint/keeper/keeper_test.go#L136

For tracking:
- [x] [gamm](https://github.com/osmosis-labs/osmosis/pull/2968)
- [ ] [epoch]()
- [x] [incentives](https://github.com/osmosis-labs/osmosis/pull/2986)
- [x] [lockup](https://github.com/osmosis-labs/osmosis/pull/2981)
- [ ] [mint]()
- [x] [pool-incentives](https://github.com/osmosis-labs/osmosis/pull/2985)
- [x] [superfluid](https://github.com/osmosis-labs/osmosis/pull/2990)
- [ ] [tokenfactory]()
- [x] [twap](https://github.com/osmosis-labs/osmosis/pull/2987)
- [x] [txfees](https://github.com/osmosis-labs/osmosis/pull/2989)

**Comment by hieuvubk** [comment]
I think we should break this down by each module to make it easier to follow

**Comment by hieuvubk** [comment]
And is anyone working on? I can start with it

**Comment by mattverse** [comment]
@hieuvubk please go ahead! That'd be great! Might be almost impossible to do this in a single PR since the scope is too big, might want to do it by module to module scope.

**Comment by ValarDragon** [comment]
Wait I thought we decided not to do this

**Comment by czarcas7ic** [comment]
Correct, I am going to close these respective PRs and we can re address at another time.

**Comment by czarcas7ic** [comment]
Respective PRs closed, closing this issue. Still think we should discuss internally to get a shared understanding of what is the best endstate for tests is
