### ISSUE TITLE
osmosisd will not build on MacOS / M1

### ISSUE THREAD

**Issue by dffffffff** [osmosis-labs/osmosis#2969]
#### System information

Osmosis version: `v12.0.1`
OS & Version: MacOS 12.6 go1.19.2 darwin/arm64
Commit hash: 

#### Expected behaviour
Successful build 

#### Actual behaviour
# github.com/zondax/hid
In file included from ../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here

#### Steps to reproduce the behaviour
Build from source with an M1 Mac (In my case a Macbook Air M1 2020)

#### Fix
See https://github.com/Zondax/hid/issues/4

**Comment by ValarDragon** [comment]
Are you sure this is failing to build, and not just warnings?

**Comment by dffffffff** [comment]
@ValarDragon You are correct it is just a warning, i had local env issues which was causing the build to fail. I will pay more attention as to what is actually causing the the failed build before submitting a bug report. Apologies!

v12.2.0 builds successfully on 
MacOS 12.6 
go1.19.2 darwin/arm64
MacBook Air (M1 2020)

**Comment by ValarDragon** [comment]
Thanks! Glad its working, going to close for now!

I think were blocked on a ZondaX release to actually get rid of the warning
