### ISSUE TITLE
x/superfluid: Add tests for `cli_test.go`

### ISSUE THREAD

**Issue by hieuvubk** [osmosis-labs/osmosis#2971]
## Background

Currently module superfluid has no tests in `cli_test. We should complete this file instead of leaving it blank as it is now

## Suggested Design

Add tests for all tx & query cmds

## Acceptance Criteria

All tests pass

**Comment by ValarDragon** [comment]
Disagree, I want to get all of this CLI code auto-generated / run-time handled, and then we just have to test what the message created is.
