### ISSUE TITLE
`begin_unlock` event contains wrong lock info for partial unlocks

### ISSUE THREAD

**Issue by apollo-pacman** [osmosis-labs/osmosis#2993]
## Background

When `MsgBeginUnlocking` is called on the lockup module an event is emitted with information about the lock. When `MsgBeginUnlocking` is used to unlock an entire locked position the event contains information about the lock that is being unlocked (as expected). But when `MsgBeginUnlocking` is used to partially unlock a locked position a new `PeriodLock` is created with the amount of coins to unlock and `lock.EndTime = ctx.BlockTime().Add(lock.Duration)` and the EndTime of the original lock is left unchanged. In this case the event emitted still contains information about the original lock and not the newly created lock.

https://github.com/osmosis-labs/osmosis/blob/main/x/lockup/keeper/msg_server.go#L99-L10

## Suggested Design

Change `BeginUnlocking` function so that the `begin_unlock` event always contains information about the "unlocking lock" resulting from the message call.

**Comment by patriklaurell** [comment]
@p0mvn hi i was just testing against testnet (osmo-test-4). So haven't tested locally against any branch

**Comment by apollo-pacman** [comment]
hi! thanks for the fast response. I have just tested against testnet (osmo-test-4), so haven't tested locally against any branch @p0mvn
