### ISSUE TITLE
state export fail to extract wasm contract

### ISSUE THREAD

**Issue by Galadrin** [osmosis-labs/osmosis#2995]
#### System information

Osmosis version: `12.1.0`
OS & Version: Linux Debian 11
Commit hash: 8329e9e7dfdd232430602d7f6a2b7df0e4acc1bd

#### Expected behaviour
Generate an export json file without errors

#### Actual behaviour
export fail to extract wasm contract
wasm contract are present in the `.osmosisd/wasm` directory

#### Steps to reproduce the behaviour
`osmosisd export --height 6425579`

#### Backtrace
https://pastebin.com/sGk9yKjK

**Comment by ValarDragon** [comment]
This bug was fixed!
