### ISSUE TITLE
Create Gamm helper method to manipulate into given spot price

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3003]
## Background

We have alot of incidences where we want to modify pool so that it has a certain spot price for a specific asset. (e.g in the twap testing, we don't have a direct way of doing this, thereby using programmed AMMI for better modification). There are alot of other instances where we want to modify a pool to a given spot price for testing purposes.  

## Suggested Design

We create a helper method in the test helpers package, that takes in `poolId` and `targetSpotPrice`, and then within the logic of the method, we do the calculation for the swap that needs to be done to modify the pool to the given target spot price. A Pseudocode would look something like this

```
func (s *KeeperTestHelper) ModifySpotPrice(poolID uint64, targetSpotPrice sdk.Dec, baseDenom string) {
     1. Do calculation of how much more base asset is needed to match the target spot price, here we would call it amountA
     2. Create a dummy account, fund that account with amountA
     3. Perform swap of AmountA to modify the pool spot price to the targetspotprice
}
```

## Acceptance Criteria
- We have a helper method to modify pool spot price to the target spot price
- Replace existing tests to use this method

**Comment by ThanhNhann** [comment]
Did this assigned sir @maurolacy

**Comment by hieuvubk** [comment]
Is all about 2-assets pool? How about multi assets could u pls lmk?

**Comment by ThanhNhann** [comment]
hi @mattverse, I have done the implementation of this func, so can you point to me the file test using this implement then I can update the test?
