### ISSUE TITLE
[CL][Liquidity Provision]: investigate implementation of join pool / exit pool methods with hardcoded values

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3034]
## Background

For [Milestone 1](https://github.com/osmosis-labs/osmosis/milestone/11), out goal is to be able to provide liquidity with pre-computed hard-coded values.

This task is focused on analyzing, prototyping and documenting our existing pool interface methods defined on the concentrated liquidity pool

## Suggested Design

We need to have a direction for the following methods:
- `JoinPoolNoSwap` / `CalcJoinPoolSharesNoSwap`
- `ExitPool` / `CalcExitPoolShares`

Additionally, it seems that `JoinPool` is not valid for concentrated liquidity pools because we must always be adding liquidity proportional to the existing pool reserves.

> Recall that the proportion of current pool reserves tells the current spot price. Assume we added 1 ETH and 5000 USDC. So if we want to put more tokens into the pool and keep the same price, the amounts must be proportional, e.g.: 2 ETH and 10,000 USDC; 10 ETH and 50,000 USDC, etc.

Therefore we need to determine how we are going to go about `JoinPool` / `CalcJoinPoolShares` methods. Options are:
- Disable it by always erroring or panicking
- Move it into an extension interface
- Modifying the spec to be compatible with the new abstraction and verifying that balancer and stableswap implementation are still aligned with the spec

## Acceptance Criteria
- Summary of the subsequent steps for each of the above methods / potentially a prototype
- Summary of constraints that we need to tackle (e.g. logarithm implementation)
- New issues with the next steps created

**Comment by mattverse** [comment]
This is to be completed in milestone2, given that the current structure of pool-models is not suitable for stroing additional states

**Comment by p0mvn** [comment]
Agreed, moving to milestone 2. This is blocked by #3045 and #3044

**Comment by p0mvn** [comment]
The direction is clear now.

We will utilize the store logic from here: https://github.com/osmosis-labs/osmosis/blob/concentrated-liquidity/proto/osmosis/concentrated-liquidity/concentratedPool.proto

JoinPool logic is implemented on the keeper, swaps are routed directly into the concentrated liquidity pool defined here: https://github.com/osmosis-labs/osmosis/pull/3047
