### ISSUE TITLE
[Story][CL]: Pool Manager Module

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3042]
## Background

> As a user, I would like to have a unified entrypoint for my swaps regardless of the underlying pool implementation so that I don't need to reason about API complexity

#3041 has advocated for a separate module for concentrated liquidity implementation. As a result, we are planning to have 2 entrypoints depending on the underlying pool used:
- `balancer` -> entrypoint in gamm
- `stableswap` -> entrypoint in gamm
- concentrated-liquidity` -> entrypoint in ints own module

## Suggested Design

Instead of having separate swap messages for each, we should have a unified entrypoint for swaps. Namely, `swap-router` module that implements the following messages:
- `SwapExactAmountIn`
- `SwapExactAmountOut`

Depending on the underlying pool type swapped against, the swap is routed to the desired module.

Existing `SwapExactAmountIn` and `SwapExactAmountOut` messages are removed from `gamm` message server. However, any keeper logic is preserved.

## Tasks

- https://github.com/osmosis-labs/osmosis/issues/3049
- https://github.com/osmosis-labs/osmosis/issues/3064
- https://github.com/osmosis-labs/osmosis/issues/3066
- https://github.com/osmosis-labs/osmosis/issues/3087
- https://github.com/osmosis-labs/osmosis/issues/3097
- https://github.com/osmosis-labs/osmosis/issues/3130
- https://github.com/osmosis-labs/osmosis/issues/3129
- https://github.com/osmosis-labs/osmosis/issues/3131
- https://github.com/osmosis-labs/osmosis/issues/3236
- https://github.com/osmosis-labs/osmosis/issues/3237
- https://github.com/osmosis-labs/osmosis/issues/3238
- https://github.com/osmosis-labs/osmosis/issues/3241
- https://github.com/osmosis-labs/osmosis/issues/3644
- https://github.com/osmosis-labs/osmosis/issues/3881
- https://github.com/osmosis-labs/osmosis/issues/3921

## Acceptance Criteria
- new module is implemented
- folder structure similar to `twap` is used
- test coverage is maximized

**Comment by p0mvn** [comment]
TODO:
- create task for implementing barebones structure for milestone 2

**Comment by mattverse** [comment]
Closed by #3051

**Comment by p0mvn** [comment]
Reopening since we decided to implemented the swap-router component only (not the pool creation logic)

**Comment by p0mvn** [comment]
Swaprouter was renamed to pool manager, renaming the issue as well

**Comment by p0mvn** [comment]
I'm going to move the last issue here to #3030 and close this
