### ISSUE TITLE
[CL][Pool Manager Module]: implement foundational structure

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3048]
## Background

As part of milestone 2, we should implement the foundations of the new `pool-manager` module.

See #3043 for more details

## Suggested Design

The following keeper methods:
- `CreatePool`
- `JoinPool`
- `ExitPool`

## Acceptance Criteria
- follows `twap` folder structure
- both message server and keeper methods

**Comment by mattverse** [comment]
Closed by #3051
