### ISSUE TITLE
[CL][Swap Router Module]: implement foundational structure

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3049]
## Background

As part of milestone 2, we should implement the foundations of the new `swap-router` module.

See #3042 for more details

## Suggested Design

The following keeper methods:
- `SwapExactAmountIn`
- `SwapExactAmountOut`

## Acceptance Criteria
- follows `twap` folder structure
- both message server and keeper methods

**Comment by mattverse** [comment]
Closed by #3051

**Comment by p0mvn** [comment]
closed by #3060
