### ISSUE TITLE
[CL][Concentrated Liquidity Module]: Prototype Tick Bitmap

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3059]
## Background

Univ3 paper talks about using tick bitmap for tracking the presence / absence of initialized ticks. We need to investigate and prototype this bitmap in our concentrated-liquidity module

## Acceptance Criteria
- bitmap prototype is made

**Comment by p0mvn** [comment]
@alexanderbez FYI made this issue to track bitmap investigations

**Comment by mattverse** [comment]
Closing Per the original PR being closed
