### ISSUE TITLE
Block denoms to be traded until start time

### ISSUE THREAD

**Issue by mconcat** [osmosis-labs/osmosis#306]
Add a new governance parameter type on x/gamm, named "PoolDenomBanned", type of `[]struct{Bantype string, Denom string, Expiration time.Time}`. `Bentype` is one of `[]string{"match", "includes"}`(use enum in the actual impl). When creating or adding new pool assets, if they are banned, the transaction will be failed.

**Comment by ValarDragon** [comment]
We ended up deciding this is not the move
