### ISSUE TITLE
Add query for lockup params

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3092]
## Background

We need to add query for the lockup params that was added in https://github.com/osmosis-labs/osmosis/pull/2733

## Acceptance Criteria

- Follow the format of param query supported in other modules and create a query for it.

**Comment by hieuvubk** [comment]
Is anyone working on this issue? I can start with it

**Comment by mattverse** [comment]
@hieuvubk That'd be awesome! Thanks!

**Comment by hieuvubk** [comment]
> @hieuvubk That'd be awesome! Thanks!

Created a pr above could u pls check it out!
