### ISSUE TITLE
[CL][Swap Router Module]: Pool ID routing 

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3097]
## Background
 
The current design in the swap router has a boolean field in the keeper method for `RouteMultihopSwapExactAmountIn` and `MultihopSwapExactAmountOut`, that takes in the field `isGamm` as a boolean field, in which routes to the correct pool module: either the gamm module or the concentrated liquidity module. 

This implementation is a half implementation of the swap router module. 

We want to route the swap messages to the correct module given pool ID. 

## Suggested Design

There are two ways of doing this depending on which 

1. When Pool ID for concentrated liquidity is in a different form (ex. poolId = cl1 )

We are assuming two things in this case:
- Pool ID for concentrated liquidity is in a different form(ex. cl1) instead of being in a form of uint64
- Pool ID is kept across two different modules. 

This case should be easy, we simply route the swap message to the correct pool type by referencing to the pool Id format. 

2. Use interface

If preconditions mentioned above are not fulfilled, we need to use interfaces to find out which pool model it is given pool id. We can achieve this by using interfaces: traditional amms and concentrated amms has different APIs and methods - we can abstract them as interfaces to see if each pool fulfills this and find out which pool model it is to route to the correct pool 

3. Use `GetPoolById`

The last possible approach of doing this is using `GetPoolById`. We can try calling `GetPoolById` method from each pool model module and use the pool returned, if error returned assume that it's the other module. 

## Acceptance Criteria

- Have the message server or the keeper layer route to the correct pool module(either gamm module or the concentrated-liquidity module) given pool id

**Comment by p0mvn** [comment]
Adding this to milestone 4

**Comment by p0mvn** [comment]
We made the decision to move pool id management into the `swap-router` module. Investigation of the constraints is TBD

**Comment by p0mvn** [comment]
closed by #3238
