### ISSUE TITLE
[CL][Misc]: rename Mint and Burn abstractions

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3108]
## Background

For adding liquidity, we went with the "Mint" abstraction. For removing, it is likely to end up being "Burn".

## Suggested Design

I would like to propose renaming Mint and Burn abstractions to the following options:
- AddLiquidity and RemoveLiquidity
- CreatePosition and WithdrawPosition

The reason is that we already use mint / burn names in x/mint , x/tokenfactory and x/bank so I think it would make it easier to be precise what exactly we are talking about.

Leaving the final choice of the name up to the person working on this.

## Acceptance Criteria
- names changed
- ensure tests are updated to reflect the name change as well

**Comment by mattverse** [comment]
We don't have burning methods for now, burning could be addressed in the future PRs when the feature is introduced

**Comment by mattverse** [comment]
Done in https://github.com/osmosis-labs/osmosis/pull/3139
