### ISSUE TITLE
x/gamm: update position and make table driven tests for function getMaximalNoSwapLPAmount 

### ISSUE THREAD

**Issue by ThanhNhann** [osmosis-labs/osmosis#3120]
## Background
Base on this [issue](https://github.com/osmosis-labs/osmosis/issues/1908#issuecomment-1288373220), we should update position for func `getMaximalNoSwapLPAmount` and write some tests to make table driven 

## Suggested Design

- update position for func `getMaximalNoSwapLPAmount`

- make all test of this func in table-driven form

## Acceptance Criteria

All existing and new tests should pass

**Comment by czarcas7ic** [comment]
@ThanhNhann can this get revived? We will review and merge once open

**Comment by ThanhNhann** [comment]
hey @czarcas7ic, I'm waiting for Roman to check this if we still need it

**Comment by czarcas7ic** [comment]
@ThanhNhann we were on a call and agreed to ping you on this
