### ISSUE TITLE
`make install` may cause conflict with NodeJS's `node`

### ISSUE THREAD

**Issue by mikedotexe** [osmosis-labs/osmosis#3125]
#### System information

Osmosis version: `Osmosis version`
OS & Version: Mac M1 Monterey 12.6 as well as Macbook Pro with Catalina 10.15.7
Commit hash: tagged at 11.0.1 and 12.2.0

#### Expected behaviour

That my typical experience on my terminal will not be affected by installation of `osmosisd`.

#### Actual behaviour

There seems to be a clash with a Golang binary that's thrown into:

`~/go/bin/node`

<img width="1271" alt="Screen Shot 2022-10-24 at 10 50 21 AM" src="https://user-images.githubusercontent.com/1042667/197595461-e75c396e-7be8-4022-9404-ea4ae1e5a280.png">

and

<img width="1282" alt="Screen Shot 2022-10-24 at 10 57 27 AM" src="https://user-images.githubusercontent.com/1042667/197594693-5d8b6c97-2ddd-4e16-b43d-1fe3500c55cb.png">

#### Steps to reproduce the behaviour

Install the node version manager (nvm): https://github.com/nvm-sh/nvm#installing-and-updating

Follow directions here:
https://docs.osmosis.zone/osmosis-core/build#build-osmosis

Text version of the logs:

```
panic: data-dir is required

goroutine 1 [running]:
main.main()
	github.com/osmosis-labs/osmosis/v12/tests/e2e/initialization/node/main.go:47 +0x6b8
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v18.3.0` to unset it.
```

```
panic: data-dir is required

goroutine 1 [running]:
main.main()
	github.com/osmosis-labs/osmosis/v12/tests/e2e/initialization/node/main.go:47 +0x6b8
```

It seems like it might be the end-to-end testing, which is mentioned in this `Makefile`:
https://github.com/osmosis-labs/osmosis/blob/805f80ce945aab93bd2db2a534eea1af52bafddf/Makefile#L301-L302

---

Perhaps I am at fault for my `$PATH` having the golang binaries before the NodeJs/nvm ones, but thought I would report since I am seeing this on two of my machines, the newer one starting from scratch (not using Time Machine backups or whatever) so I probably won't be the last person to face this issue.

Overall, I'd say it might not a good move to have any binary called `node` and perhaps that could be renamed to `e2e-node` or something.

**Comment by czarcas7ic** [comment]
tagging @niccoloraspa who has most context with docker files

**Comment by niccoloraspa** [comment]
Thanks for the issue and the detailed explanation.
As you pointed out it is a name conflict due to a not-so-ideal name choice.

Fix is in pipeline.

**Comment by ValarDragon** [comment]
I'm confused as to why anything for e2e is getting built with make install

**Comment by ValarDragon** [comment]
Just checking in, did we figure this one out @niccoloraspa 

(Both why make build did this, and getting things renamed)

**Comment by ArtemAlagizov** [comment]
having the same issue, any update?

**Comment by 5iddy** [comment]
I have experienced this issue too. Confused the hell out of me. I have experienced it while setting up neovim-treesitter.
[Error That I encountered](https://imgur.com/lJrkhxF)

**Comment by mdyring** [comment]
Bumping into this as well. Also experienced this after doing a `make install` on latest release tag.

This looks like the source of the issue, but not sure I understand why e2e test binaries are being built for make install.

https://github.com/osmosis-labs/osmosis/blob/ebde7f11b846ce26859012f9c325d74c75d4e116/Makefile#L318

**Comment by migueldingli1997** [comment]
Also ran into this issue and it confused me quite a bit as well.

**Comment by czarcas7ic** [comment]
On our chain backlog call, Roman stated that there is an E2E script named "node", and we just have to rename it to solve this name clash issue.
