### ISSUE TITLE
[CL][Swap Router Module]: improve `TestMultihopSwapExactAmountIn` and `TestMultihopSwapExactAmountOut`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3131]
## Background

Desired test cases are listed here for `TestMultihopSwapExactAmountIn`:

https://github.com/osmosis-labs/osmosis/blob/d76deee64911cdd21ae3914ef2912ff633bb960a/x/swaprouter/router_test.go#L131-L140

and here for `TestMultihopSwapExactAmountOut`:

https://github.com/osmosis-labs/osmosis/blob/d76deee64911cdd21ae3914ef2912ff633bb960a/x/swaprouter/router_test.go#L131-L140

## Acceptance Criteria
- all proposed test cases are covered
- new test cases are added if applicable

**Comment by hieuvubk** [comment]
Hello anyone working on it? I would like to work with it

**Comment by p0mvn** [comment]
Hi @hieuvubk . I'm afraid it’s currently blocked on: https://github.com/osmosis-labs/osmosis/pull/3170

I’m planning to finalize that PR soon. Will lyk once this issue is unblocked. Thanks

**Comment by hieuvubk** [comment]
Yes thank u

**Comment by p0mvn** [comment]
This is now blocked on https://github.com/osmosis-labs/osmosis/issues/3238 since we need proper routing to work first

**Comment by p0mvn** [comment]
Some progress towards this has been done in: https://github.com/osmosis-labs/osmosis/pull/3490

However, there is still more to test. `swaprouter` module is currently on code-freeze until we finish merge to main

**Comment by p0mvn** [comment]
We still need to add a test with a concentrated liquidity pool, upon merging the module to main
