### ISSUE TITLE
osmomath(log/CL): implement and test natural logarithm, custom base logarithm and `1.0001` logarithm 

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3132]
## Background

With log base 2 implemented in https://github.com/osmosis-labs/osmosis/pull/2788, we should add more bases for logarithms.

### Natural logarithm

`ln x = \frac{log_{2}{x}}{log_{2}{1.0001}}`

- estimate `{log_{2}{e}` in WolframAlpha (add link to the estimate)
- hard code the estimate
- create a method `Ln` that utilizes `LogBase2` and hardcoded `e` value to solve the above

## Base 1.0001
This is what we need for concentrated liquidity
$$ln x = \frac{log_{2}{x}}{log_{2}{1.0001}}$$ 

- estimate `{log_{1.0001}{x}` in WolframAlpha (add link to the estimate)
- hard code the estimate
- create a method `LogBaseHundredthBasisPoint` that utilizes `LogBase2` and hardcoded `log_{1.0001}{x}` value to solve the above

## Custom Base

Implement `LogCustomBase` that utilizes similar idea to above

## Acceptance Criteria
- tests added for each method
- wolfram links with calculations
- benchmarks
- similar to https://github.com/osmosis-labs/osmosis/pull/2788 
- make PR against main with backport to `concentrated-liquidity-main`

**Comment by RusAkh** [comment]
I would like to work on it

**Comment by p0mvn** [comment]
Thank you. Please go ahead
