### ISSUE TITLE
chore: remove streamswap module

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3133]
## Background

According to latest product updates, streamswap is to be implemented in CosmWasm.

Therefore, we should remove the existing module.

## Acceptance Criteria
- delete contents of `x/streamswap`

**Comment by hieuvubk** [comment]
Is anyone working on this issue, we would like to close it. @ThanhNhann

**Comment by p0mvn** [comment]
That would be great. Please take it. Thanks
