### ISSUE TITLE
[CL][Misc]Create testcases for `GetIfFound`

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3138]
## Background

We recently added a helper method in the osmoutils, that would instead of pannicing if not found (which is what `MustGet` does), we return a boolean field and an error instead which looks like this:

```
func GetIfFound(store store.KVStore, key []byte, result proto.Message) (found bool, err error) {
	b := store.Get(key)
	if b == nil {
		return false, nil
	}
	if err := proto.Unmarshal(b, result); err != nil {
		return true, err
	}
	return true, nil
}

```

Actual implementation: https://github.com/osmosis-labs/osmosis/pull/3136/commits/016f27573a36b8b7dc1ffe1fe101a424bb36a43f#diff-b6d3bf142ce5c79530054885a752706a87726315c61bd5ff4a3abe8de0b275a9R129-R138
## Suggested Design
We want to come back to this method and eventually add test cases for this specific method. 
The PR itself could be made off of `concentrated-liquidity-main` branch until that branch is merged to main.

## Acceptance Criteria
We have a test case for `GetIfFound`

**Comment by hieuvubk** [comment]
I would like to work on this issue if no one on process
