### ISSUE TITLE
[CL][Liquidity Provision]: implement `withdrawPosition` method

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3143]
## Background

So far we have made decent progress on adding liquidity (`createPosition`) and swapping. However, there is nothing implemented for `withdrawPosition`

## Suggested Design

We should implement the following method in `lp.go`:

```go
// withdrawPosition withdraws a concentrated liquidity position from the given pool id in the given tick range and liquidityAmount.
// On success, returns an amount of each token withdrawn.
// Returns error if
// - there is no position in the given tick ranges
// - if tick ranges are invalid
// - if attemps to withdraw an amount higher than originally provided in createPosition for a given range
// TODO: implement and table-driven tests
func (k Keeper) withdrawPosition(ctx sdk.Context, poolId uint64, owner sdk.AccAddress, lowerTick, upperTick int64, liquidityAmount sdk.Int) (amtDenom0, amtDenom1 sdk.Int, err error) {
	panic("not implemented")
}
```

## Acceptance Criteria
- implement method
- at least one "happy path" test case added

**Comment by RusAkh** [comment]
hello @p0mvn is anyone working on this? I would like to help

**Comment by czarcas7ic** [comment]
@RusAkh im fairly certain Roman is working on this / has nearly completed

**Comment by p0mvn** [comment]
Implemented in: https://github.com/osmosis-labs/osmosis/pull/3459
