### ISSUE TITLE
Create testcases for `Inactive` Pool

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3154]
## Background

Adding a new Interface, namely the `traditionalAMMI`, we had to remove existing testing that uses mock pool to mock a pool that is inactive and ensure that if pool is inactive, we aren't able to do a swap.

https://github.com/osmosis-labs/osmosis/pull/3152/files#diff-b5cfd36f7b82ca1c172a606b4fd5c6978db0e6f9db3361dea89e2893ab843aeeL276-L327

## Suggested Design

We need to update the mock pool package or methods to be able to mock an inactive pool. Right now, the same test would fail, since doing a `GetPool` operation on a pool created via mock would error. 

## Acceptance Criteria

- Doing a `GetPool` operation on a pool created via mock package does not error
- We have test on (or we bring back test on) TestInactivePoolFreezeSwaps
- PRd against `concentrated-liquidity-main`

**Comment by RusAkh** [comment]
hello is anyone working on it?

**Comment by mattverse** [comment]
Nope! I don't think so!

**Comment by RusAkh** [comment]
cool, I would like to work on it

**Comment by p0mvn** [comment]
Please go for it
