### ISSUE TITLE
[CL][Swapping] Add Test cases for `CalcOutAmtGivenIn`

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3196]
## Background

Current `CalcOutAmtGivenIn` only has test cases for doing a swap within one price range. 

We want to add more test cases so that we have the following test cases for the swappings

## Suggested Design
The following are the test cases that are planned to be added:
- Swapping on two equal price ranges
- Swapping on consecutive price ranges
- Swapping on partially overlapping price ranges

## Acceptance Criteria

- [ ] Test cases listed above are added 
- [ ] In depth comment on the test cases are added(how we get the calculation and maths)

**Comment by czarcas7ic** [comment]
Closing as addressed in previous PRs
