### ISSUE TITLE
[CL][Swapping]: refactor and test `CalcInAmtGivenOut`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3198]
## Background

Currently, our `CalcInAmtGivenOut` has precision and, possibly, logic issues. We should investigate, refactor and test this method.

The issue stems from potentially needing a different equation from `CalcOutAmtGivenIn`. This equation needs to be investigated and documented.

## Acceptance Criteria
- refactor the method
- table-driven tests with Wolfram links

**Comment by czarcas7ic** [comment]
Closing as addressed in previous PRs
