### ISSUE TITLE
[CL][Swap] SwapOutAmtGivenIn

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3201]
## Background

Once CalcOutAmtGivenIn logic is sound, we need to implement SwapOutAmtGivenIn for the concentrated liquidity module.

## Acceptance Criteria

- Swap logic is properly implemented
- Table driven tests for SwapOutAmtGivenIn are created

**Comment by p0mvn** [comment]
Can we apply labels please and append this to a story?
