### ISSUE TITLE
[ValSet-Pref] Add query for `UserValidatorPreferences` 

### ISSUE THREAD

**Issue by stackman27** [osmosis-labs/osmosis#3204]
## Background
Returns the list of ValidatorPreferences for the user.

## Suggested Design

Use the TWAP query format 

## Acceptance Criteria

we can query a user's validator preference

**Comment by ValarDragon** [comment]
@stackman27 can this be closed

**Comment by stackman27** [comment]
yup! i'll close a lot of valset issues
