### ISSUE TITLE
feat(ci/e2e): create a CI job to test e2e related makefile steps on merge to `main`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3208]
## Background

We should add a CI job on merge to main that would attempt to build all relevant test images necessary for e2e testing. This should help with identifying problematic PRs.

Today we only tend to discover problems with e2e dependency builds when we need to rebuild something. These problems tend to have a cascading effect of discovering even more problems since we don't build these scripts/images frequently.

## Suggested Design

- Run `make docker-build-e2e-init-chain` on merge to `main`
- Run `make test-e2e-short` on merge to `main`
   * This in addition to `make test-e2e-ci`.
   * This is useful because `make test-e2e-short` is frequently used locally and runs non-upgrade tests
   * Since we currently don't test this in CI, it breaks often

## Acceptance Criteria
- CI jobs introduced
- Run on merge to main
- Fails if the makefile step breaks
- Test from personal fork added displaying both success and failure

**Comment by anhductn2001** [comment]
Hi @p0mvn, I am working on this issue. Everything is good except make test-e2e-short. It's failing both on my github action and on my local. 
![image](https://user-images.githubusercontent.com/62016666/200100255-c495ffda-78be-4890-8b46-2146569a89f1.png)

**Comment by anhductn2001** [comment]
Can you check this, plss..

**Comment by czarcas7ic** [comment]
@anhductn2001 did you run `e2e-setup` prior to this

**Comment by anhductn2001** [comment]
Yes!! I did. In 'make test-e2e-short' had e2e-setup. Have you tested it yet??

**Comment by anhductn2001** [comment]
My colleague ran it and got the same error!!

**Comment by anhductn2001** [comment]
I agree. But now this test is for non upgrade and i think this is a issue

**Comment by p0mvn** [comment]
The upgrade should be disabled for `make test-e2e-short`. This is the short makefile step to test locally without upgrade.

**Comment by czarcas7ic** [comment]
Right, I think for some reason the upgrade being disabled (on e2e-short) messes up that specific test. I haven't had time to look into it though

**Comment by anhductn2001** [comment]
We can create a new issue and I will spend time to check it

**Comment by anhductn2001** [comment]
Wait, should I wait for the PR to be merged before continue..

**Comment by czarcas7ic** [comment]
@anhductn2001 just merged it
