### ISSUE TITLE
[CL][Swapping]: refactor to use Strategy design pattern instead of `zeroForOne` boolean

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3218]
## Background

Currently, we use `zeroForOne` boolean within swapping logic that leads to code like this:

```go
func getNextSqrtPriceFromInput(sqrtPriceCurrent, liquidity, amountRemaining sdk.Dec, zeroForOne bool) (sqrtPriceNext sdk.Dec) {
	if zeroForOne {
		sqrtPriceNext = getNextSqrtPriceFromAmount0RoundingUp(sqrtPriceCurrent, liquidity, amountRemaining)
	} else {
		sqrtPriceNext = getNextSqrtPriceFromAmount1RoundingDown(sqrtPriceCurrent, liquidity, amountRemaining)
	}
	return sqrtPriceNext
}
```

This reduces readability and increases the likelihood of making a mistake by providing a wrong flag. Our functions and methods should be cohesive.

## Suggested Design

Instead, we should use a strategy design pattern. By doing so, we can initialize a specific "strategy" either `zeroForOne` or `oneForZero` at the beginning of the execution flow of the swap.

The concrete strategies have the same interfaces but different implementations. As a result, we should be able to call each strategy's implementation and avoid passing in the `zeroForOne` boolean throughout the codebase.

The previous example would turn into:

```go
type swapStrategy interface {
    getNextSqrtPriceFromInput(sqrtPriceCurrent, liquidity, amountRemaining sdk.Dec) (sqrtPriceNext sdk.Dec)
}
...

newSwapStrategy(zeroForOne bool) swapStrategy {
    if zeroForOne {
        return &zeroForOneStrategy{}
    }
    return &oneForZeroStrategy{}
}

func (s *zeroForOneStrategy) getNextSqrtPriceFromInput(sqrtPriceCurrent, liquidity, amountRemaining sdk.Dec) (sqrtPriceNext sdk.Dec) {
	return getNextSqrtPriceFromAmount0RoundingUp(sqrtPriceCurrent, liquidity, amountRemaining)
}

func (s *oneForZeroStrategy) getNextSqrtPriceFromInput(sqrtPriceCurrent, liquidity, amountRemaining sdk.Dec) (sqrtPriceNext sdk.Dec) {
	return getNextSqrtPriceFromAmount1RoundingDown(sqrtPriceCurrent, liquidity, amountRemaining)
}
```
- note that the interface and each strategy will have more methods defined

The clients would then simply call:
```go
func swap(...) ... {
    zeroForOne := ...
    swapStrategy := newSwapStrategy(zeroForOne)

    nextSqrtPrice := swapStrategy.getNextSqrtPriceFromInput(...)
}
```

## Acceptance Criteria
- strategy design pattern is integrated
- code duplication minimized
- avoid passing `zeroForOne` boolean
- all existing tests pass

**Comment by hieuvubk** [comment]
Hello is anyone in the process? I'm willing to work with it

**Comment by czarcas7ic** [comment]
@p0mvn I will assign @hieuvubk 

Thank you!

**Comment by p0mvn** [comment]
As part of the final check off for this issue, ensure that the problem in this discussion has been resolved:
https://github.com/osmosis-labs/osmosis/pull/4131#discussion_r1092794164

**Comment by p0mvn** [comment]
Closing in favor of: https://github.com/osmosis-labs/osmosis/issues/4427
