### ISSUE TITLE
[CL][Swap Router Module]: test `CreatePool`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3236]
## Background

We should cover the following test cases:
https://github.com/osmosis-labs/osmosis/blob/0c2fa2d14a153b50d5d97525556ad828d3af6344/x/swaprouter/creator_test.go#L37-L39

## Acceptance Criteria
- tests added
- all pass

**Comment by hieuvubk** [comment]
It's blocked by #3245 . I'm willing to work on this issue after `MsgCreateConcentratedPool ` is implemented.

**Comment by czarcas7ic** [comment]
Basic CL test was added as a drive by
