### ISSUE TITLE
[CL][Swap Router Module]: define `InitGenesis` and `ExportGenesis` tests on the suite

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3237]
## Background

Define the tests on the suite for consistency.

## Suggested Design

Follow TODOs:
- https://github.com/osmosis-labs/osmosis/blob/8653dd77354a19f23923fcd7d90ab01cefdcc39d/x/swaprouter/keeper_test.go#L44
- https://github.com/osmosis-labs/osmosis/blob/8653dd77354a19f23923fcd7d90ab01cefdcc39d/x/swaprouter/keeper_test.go#L60

## Acceptance Criteria
- `InitGenesis` is defined on the suite
- `ExportGenesis` is defined on the suite

**Comment by hieuvubk** [comment]
Hi could I work with it?

**Comment by p0mvn** [comment]
This is now complete
