### ISSUE TITLE
[CL][Misc]: consider removing "pool_count" index and `NumPools` query from `gamm` 

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3240]
## Background

It is questionable whether `NumPools` query in `x/gamm` has any use to clients.
Currently, we store an additional index to keep track of this count.

## Suggested Design

We should consider removing this query from `x/gamm` and the `pool_count` store index.

## Acceptance Criteria
- Decision is made
- If decided to remove, all of the store index, relevant methods, queries and CLI are deleted

**Comment by p0mvn** [comment]
If no argument for keeping the "NumPools" query in `x/gamm` is made in the next few days, I propose we remove it.

**Comment by hieuvubk** [comment]
Hi if we got final decision about this issue, I'm willing to work with it
