### ISSUE TITLE
[CL][Swap Router Module]: rename the module

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3241]
## Background

The original name was chosen with the assumption that only the swaps would be routed through the module.

Later, we decided to route pool creation and handle id management in the module as well.

## Suggested Design

Choose either:
- "Pool Router"
- "Pool Manager"

## Acceptance Criteria
- new name is chosen
- all references are updated in code
- updated GitHub user story issue: https://github.com/osmosis-labs/osmosis/issues/3042
- update mergify label configuration
- update labels
- update the spec: https://github.com/osmosis-labs/osmosis/pull/3233

**Comment by p0mvn** [comment]
Let's tackle this at the end to avoid naming confusion midway through implementing the feature.

Please feel free to suggest other names in the meantime

**Comment by p0mvn** [comment]
This is now available to be worked on. The latest name that was agreed upon is "Pool Manager".

The person working on this should check various case combinations of "swaprouter" and "swap router" being present in our codebase and replace it with "poolmanager" and "pool manager" respectively while preserving the correct case.

For example:
- `swapRouter` -> `poolManager`
- `SwapRouter` -> `PoolManager`
- `Swap router` -> `Pool manager`

**Comment by phamminh0811** [comment]
Could I work with it?

**Comment by p0mvn** [comment]
Hey. Yes, please. However, please wait for https://github.com/osmosis-labs/osmosis/pull/3880 to be merged before starting to work on this
