### ISSUE TITLE
[CL][Concentrated Liquidity Module]: create a separate file and folder for pool implementation

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3243]
## Background

Currently, we have keeper methods and pool methods both mixed up in `pool.go`.

We should separate pool methods from the keeper methods.

## Suggested Design

1. Create a `concentratedpool` package in the root of the module. 
2. Regenerate the `concentratedPool.pb.go` file to the above package
3. Move all pool method implementations from into the `concentratedpool` package
4. Port tests

## Acceptance Criteria
- design implemented
- keeper and pool implementations are separated

**Comment by RusAkh** [comment]
hello @p0mvn, need help on this?

**Comment by mattverse** [comment]
Hrrm, srry if Im missing something, but I don't understand the reason to have a separated out structure for the cl module if cl is the only pool model within the module. Also, this way, we can't access state for the ticks if its a pool method. Are you thinking of this design to be swap-router compatible?

**Comment by p0mvn** [comment]
> I don't understand the reason to have a separated out structure for the cl module if cl is the only pool model within the module

Do you mean having a separate pool model?

Pool-model is a separate component so I think it makes sense to encapsulate it into its own package. It would also work well with the abstractions in `x/gamm` where each pool model belongs to their own package.

> Also, this way, we can't access state for the ticks if its a pool method.

With the current API, what are the methods that would need to have access to ticks? We should be able to keep such methods on the keeper.

> Are you thinking of this design to be swap-router compatible?

What do you mean exactly by swaprouter compatible? If it implements `PoolI`, it is compatible with the swaprouter

**Comment by p0mvn** [comment]
This is complete in #3296
