### ISSUE TITLE
[x/gamm][stableswap]: Panic catch core operations at keeper level

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#3277]
## Background

We currently panic when there is an issue with the solver or core AMM math. We should catch these panics at the keeper level and return errors as we do with spot prices for balancer pools.

## Suggested Design

- Catch panics and turn into errors with appropriate error messages

## Acceptance Criteria

- All new and existing tests pass

**Comment by RusAkh** [comment]
hello @AlpinYukseloglu is this available to work on?
