### ISSUE TITLE
delete tag v1.0.4 or retract

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#3305]
## Background

For some time now, I keep forgetting to mention that this does not work.  v1.0.3-dev doesn't apphash, however. 

## Suggested Design

delete or retract osmosis v1.0.4

**Comment by ValarDragon** [comment]
So the first version people should use is v3.1.0 (source; https://github.com/cosmos/chain-registry/blob/master/osmosis/chain.json#L57-L98)

I'm not sure that we should be deleting older tags though. (Does github have a notion of retracting a tag?)

**Comment by faddat** [comment]
no, but go.mod does.  Thank you for reminding me about the version walking thing.  I'd forgotten.
