### ISSUE TITLE
test(stableswap): SetScalingFactors

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3329]
## Background

No tests `SetScalingFactors`

## Suggested Design

Add table-driven tests:

- [ ] https://github.com/osmosis-labs/osmosis/blob/bbd4d5bc496ecfbe8eaa98b294eab15c3c33d9d5/x/gamm/pool-models/stableswap/pool.go#L378
- [ ] https://github.com/osmosis-labs/osmosis/blob/2bd5f763ac59d26a75f0486e4fd2b568a5313e37/x/gamm/keeper/pool.go#L270

## Acceptance Criteria
- coverage is maximized

**Comment by ThanhNhann** [comment]
Hey @p0mvn, can I handle this task?

**Comment by p0mvn** [comment]
Hi @ThanhNhann . Yes please
