### ISSUE TITLE
Bugs Staging.osmosis.zone

### ISSUE THREAD

**Issue by LL-Cosmo** [osmosis-labs/osmosis#333]
Osmosis Hub AMM bugs after launch

**Comment by LL-Cosmo** [comment]
Bug 1. Too many Requests

**Comment by LL-Cosmo** [comment]
Bug 2. Transaction failed

**Comment by LL-Cosmo** [comment]
Bug 3. 
Airdrop tasks (incomplete, complete) do update to Osmo balance, do not update to Airdrop list

**Comment by ValarDragon** [comment]
Thanks, those were are all related to having our backend overloaded right at launch, those should all be resolved.
