### ISSUE TITLE
Github CI: Update deprecated go test cache work

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#3348]
## Background

We see this warning `GitHub Actions: Deprecating save-state and set-output commands` on every PR now, in the load from cache step, linking to: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Haven't read through yet, but seems like something we need to fix

**Comment by RusAkh** [comment]
id like to fix it

**Comment by RusAkh** [comment]
https://github.com/mheap/github-action-required-labels/issues/42#issuecomment-1315784425
