### ISSUE TITLE
chore: fix `make test-unit` permission error

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3384]
## Background

`make test-unit` is getting a permission error in one of the `.wasm` bytecode files.

This is what I'm getting when running `make test-unit` on `main`:
[test.log](https://github.com/osmosis-labs/osmosis/files/10008715/test.log)

## Suggested Design

We should fix these errors.

## Acceptance Criteria
`make test-unit` passes with no errors

**Comment by p0mvn** [comment]
CC: @nicolaslara could it be related to any of the wasm files we merged today?

**Comment by nicolaslara** [comment]
I don't think that's related, but I'll take a look.

It seems to be on the tests for the wasmbindings. My first guess is that something changed at the os level where the tests are run. I'll report back in a bit

**Comment by p0mvn** [comment]
@nicolaslara thanks for looking into it. Sounds like a machine-specific issue. I'll try debugging this locally

**Comment by ValarDragon** [comment]
Did this problem get fixed for you @p0mvn ?
