### ISSUE TITLE
fix: import paths CI job

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3399]
## Background

Import paths ci job is failing:
https://github.com/osmosis-labs/osmosis/actions/runs/3473319104/jobs/5805205259

We should update the relevant scripts to unblock the CI.

## Acceptance Criteria
- import paths CI job is working
- updates all relevant import paths correctly
- test on a personal fork added

**Comment by RusAkh** [comment]
I'll fix it
