### ISSUE TITLE
"keys parse" command runs forever

### ISSUE THREAD

**Issue by hydrogen18** [osmosis-labs/osmosis#342]
I downloaded the 'Release version' from github & compiled it. If I run the keys parse command like this

```
osmosisd keys parse aaa
```

It just runs forever, never printing any output or showing any error.

**Comment by ValarDragon** [comment]
Billy fixed that in #335, so it should be fixed in the next release

**Comment by hydrogen18** [comment]
Confirmed broken again in v3.1.0
