### ISSUE TITLE
Improve error message when trying to Exit 100% of a pool

### ISSUE THREAD

**Issue by joe-bowman** [osmosis-labs/osmosis#3427]
#### System information

Osmosis version: `v13.0.0-rc2`

#### Expected behaviour

The last user in a pool should be able to completely exit the pool.

#### Actual behaviour

The last user in a pool must leave 1 gamm token in the pool

#### Steps to reproduce the behaviour

- Create a pool
- Join pool
- Exit pool with 100% of shares
- Receive error "100000000000000 resulted shares is larger than the max amount of 100000000000000"

**Comment by ValarDragon** [comment]
This is expected behavior

**Comment by joe-bowman** [comment]
Then presumably the error message wants changing? because this is somewhat confusing:
`100000000000000 resulted shares is larger than the max amount of 100000000000000`.

**Comment by ValarDragon** [comment]
Ah yeah, lets change that error message! (Should just need to subtract one from the max amount displayed)

For context, it breaks some assumptions around other methods, and we are in undefined behavior if the last share exits.

The number of shares is sufficiently large, s.t. we believe that the last LP share is negligible

**Comment by ValarDragon** [comment]
Want to submit or update the PR, to fix the error message?
