### ISSUE TITLE
test(stableswap): validateScalingFactors function

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3434]
## Background

Test this:
https://github.com/osmosis-labs/osmosis/blob/6398733549c124cb973eaa20d7aaba0fe6915ab9/x/gamm/pool-models/stableswap/pool.go#L439

## Acceptance Criteria
- coverage maximized

**Comment by p0mvn** [comment]
Not v13 blocking but good to have

**Comment by hoangdv2429** [comment]
Seems open. Can I handle this ?
