### ISSUE TITLE
test(stableswap): `getLiquidityIndexMap` function

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3435]
## Background

https://github.com/osmosis-labs/osmosis/blob/6398733549c124cb973eaa20d7aaba0fe6915ab9/x/gamm/pool-models/stableswap/pool.go#L158

## Acceptance Criteria
- case with 2 assets, case with 4 assets

**Comment by p0mvn** [comment]
Non-blocking for v13

**Comment by RusAkh** [comment]
I'll do that
