### ISSUE TITLE
test(stableswap): `iterKCalculator` function

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3439]
## Background

Test this:
https://github.com/osmosis-labs/osmosis/blob/6398733549c124cb973eaa20d7aaba0fe6915ab9/x/gamm/pool-models/stableswap/amm.go#L269

## Acceptance Criteria
- a few table-driven test cases
- ensure that the invariant in comments holds

**Comment by RusAkh** [comment]
I'll do that

**Comment by ValarDragon** [comment]
Hey, is it alright if I take this over? I think its actually fairly involved to get a useful test for this

**Comment by ValarDragon** [comment]
I think was resolved
