### ISSUE TITLE
Transaction failed "Signature verification failed"

### ISSUE THREAD

**Issue by Synthacon** [osmosis-labs/osmosis#346]
Hi, 
Trying to swap OSMO to ION and  seeing following error:

**Transaction failed**
 signature verification failed; please verify account number (xxxxx), sequence(43) and chain-id (osmosis-1):unauthorized

**Comment by wellhat** [comment]
I've experienced this issue also when swapping ATOM to OSMO today.

**Comment by ValarDragon** [comment]
Its due to it taking a long time for a bonding tx to get on chain, a second tx being made simultaneously, but Keplr not auto-incrementing the sequence number until the first tx gets on chain.

Should be fixed now with bonding txs getting on chain relatively quickly
