### ISSUE TITLE
block syncing stop at 6969520

### ISSUE THREAD

**Issue by sing1ee** [osmosis-labs/osmosis#3466]
#### System information

Osmosis version: `v12.3.0`
OS & Version: Linux ubuntu 20.04
Commit hash: 

#### Expected behaviour
Keep the latest block height

#### Actual behaviour
stop at 6969520

#### Steps to reproduce the behaviour

1. This morning I found that the block synchronization stopped at 6969520
2. I checked the releases and found v12.3.0 is a hard fork version, so I upgraded to v12.3.0
3. After restarting the service, the block height is still at 6969520

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ValarDragon** [comment]
You have to resync from a snapshot unfortunately. You can download a pruned one from here: https://quicksync.io/networks/osmosis.html

Were waiting on the SDK to complete refactoring of the IAVL key formats, for this to become an easy thing to rolback.
