### ISSUE TITLE
Integrate strategy pattern for `tick` & relocate strategy to own package

### ISSUE THREAD

**Issue by hieuvubk** [osmosis-labs/osmosis#3510]
## Background

Refer from [#3232(comment)](https://github.com/osmosis-labs/osmosis/pull/3232#pullrequestreview-1190996348)
We should implement this design for `NextInitializedTick`  to remove the `zeroForOne` check as much as possible

**Comment by p0mvn** [comment]
Thanks @hieuvubk . 

Synched offline that this has been partially complete while not being tracked in issues
