### ISSUE TITLE
osmoutils.GetIfFound semantics discussion

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3530]
Can be changed later / can discuss in an issue, should not block this PR. Perhaps this should be called `HasWithType` ?

e.g. if we were masters of the store interface
```
store.HasProtoMsg("myKey", types.Pool)
```

Has to indicate its a bool (rather than assuming you'd get the object back)

OR is proto.Message here actually mutated? If so lets update the comment, but this doesn't actually make sense to me as an API.

Why don't just make a method called `Get` thats the same as MustGet, but returns an error instead of panics?

_Originally posted by @ValarDragon in https://github.com/osmosis-labs/osmosis/pull/3512#discussion_r1032655165_

**Comment by p0mvn** [comment]
I think that the method does what we expect it to do - that is return a value if it is found by mutating a `proto.Message` parameter.

This has the same signature as `MustGet` with an extra return boolean indicating whether a value was found at that key.

I think that we should not be returning an error when a value at a given key is not found because it would be difficuly to distinguish a database error from "not found" error for clients.

In my opinion, the problem here is the confusing spec that should be changed to:

```
// GetIfFound returns a value at key by mutating the result parameter. Returns true if the value was found and the
// result mutated correctly. False otherwise. Returns error only when database or serialization errors occur
// returns a boolean indicating whether value exists for the given key and error
func GetIfFound(store store.KVStore, key []byte, result proto.Message) (found bool, err error) {
    // stub
}
```

@ValarDragon let me know what you think

**Comment by ValarDragon** [comment]
Not sure why we don't just make the API

```
func Get(store, key, result) (found bool, err error)
```

**Comment by p0mvn** [comment]
> Not sure why we don't just make the API
> 
> ```
> func Get(store, key, result) (found bool, err error)
> ```
> 
> AFAIK, this is not uncommon

I'm supportive of renaming it to just `Get` and improving the godoc. Will PR a change for this
