### ISSUE TITLE
feat(CL): convertToCFMMPool helper

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3538]
**Background**

We tend to cast from `PoolI` to `TraditionalAmmInterface` in many places. We should add a helper instead:

```go
func convertToCFMMPooll() (types.TraditionalAmmInterface, error) {
    	cfmmPool, ok := poolI.(types.TraditionalAmmInterface)
	if !ok {
		return nil, fmt.Errorf("given pool does not implement TraditionalAmmInterface, implements %T", poolI)
	}
       return cfmmPool, nil
}
```

and a similar helper for the concentrated pool conversion

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/3497#discussion_r1033010263_

**A/C**
- helper introduced
- tests added
- replace all casts with the use of this helper

**Comment by ThanhNhann** [comment]
Can I handle this ?

**Comment by p0mvn** [comment]
@ThanhNhann thanks for checking in. This is already being addressed by: https://github.com/osmosis-labs/osmosis/pull/3546
