### ISSUE TITLE
feat(app/upgrades): implement twap record migrations for geometric logic

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3542]
## Background

The existing twap records should be migrated in the upgrade handler so that the geometric twap accumulator is initialized to 0 for each record.

## Suggested Design

Add logic in v14 upgrade handler, iterating over all possible twap records and setting the geometric twap accumulator to 0

## Acceptance Criteria
- migrations added
- unit tested
- e2e test passses

**Comment by hieuvubk** [comment]
@p0mvn Hi its blocked by pr [#3420 ](https://github.com/osmosis-labs/osmosis/pull/3420) right?

**Comment by p0mvn** [comment]
@hieuvubk yessir. Just merged #3420 . This is also blocked on the v14 upgrade handler being present.

We have a CI job to generate it automatically. We would like to test it instead of adding the upgrade handler manually. However, the CI job is currently being triggered by the release:
https://github.com/osmosis-labs/osmosis/blob/f364fe4bbef43236acd13980d8794bfb4eeee19e/.github/workflows/auto-update-upgrade.yml#L8-L10

There is an issue to make it also run manually: https://github.com/osmosis-labs/osmosis/issues/3495.

If you have the capacity and interest in tacking #3495 to CI-generate the v14 upgrade handler and then adding the migrations described here, that would be amazing. Please let me know if you're willing to pick up #3495 and then this.

**Comment by MasterPi-2124** [comment]
@p0mvn I am doing auto-generating upgrade handler on manual inputs from user as suggested on #3495. Here is my [workflow](https://github.com/MasterPi-2124/osmosis/actions/workflows/manually-update-upgrade.yml) with examples of generating `v14` upgrade handler, which leads to this [pull request](https://github.com/MasterPi-2124/osmosis/pull/2) and [result](https://github.com/MasterPi-2124/osmosis/commit/a0cfecafd5ea759bd241a9fff9d3f3cda13b986e).

**Comment by MasterPi-2124** [comment]
About the release trigger, the workflow will be automatically running, and it will automatically take release tag as input. So you will only have to specific version on manual trigger.

I made this PR request: https://github.com/osmosis-labs/osmosis/pull/3577
