### ISSUE TITLE
feat(CL): convertToConcentratedPool helper

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3559]
**Background**

We will need to cast `PoolI` to `ConcentratedPoolExtension ` in many places. We should add a helper instead:

```go
func convertToConcentratedPool() (types.ConcentratedPoolExtension, error) {
    	concentratedPool, ok := poolI.(types.ConcentratedPoolExtension)
	if !ok {
		return nil, fmt.Errorf("given pool does not implement ConcentratedPoolExtension, implements %T", poolI)
	}
       return concentratedPool, nil
}
```

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/3535#discussion_r1034092906

**A/C**
- helper introduced
- tests added
- replace all casts with the use of this helper

**Comment by ThanhNhann** [comment]
Can I handle this? @czarcas7ic
