### ISSUE TITLE
feat(client): change environment via CLI

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3597]
## Background

Currently, we have several environments:
- mainnet (under `$HOME/.osmosisd`)
- localosmosis (under `$HOME/.osmosisd-local`)

Separate folders for each are created for convenience to avoid having localosmosis overwriting mainnet client configurations.

However, to use a non-default config folder, users must provide a `--home` flag like:
```bash
osmosisd q tx {txhash} --home=$HOME/.osmosisd-local
```

We would like to avoid it and, instead, configure the environment permanently by setting it via a separate CLI command.

## Suggested Design

1. Modify `osmosisd` installation to create an environment file and source it in `.profile`

Modify [makefile installation step](https://github.com/osmosis-labs/osmosis/blob/1276d98bcc5cb45ad23423299f8261b004dd6dfb/Makefile#L92-L93) to also do the following:
- create a file under `$HOME/.osmosisd/env`
- set the following environment variable there `OSMOSISD_ENVIRONMENT=mainnet`
- source the path of the `env` to `.profile`: `. "$HOME/.osmosisd/env"`

Note that `cargo` works in this way.

2. According to the value of `OSMOSISD_ENVIRONMENT`, set the home dir

Set it here: https://github.com/osmosis-labs/osmosis/blob/1276d98bcc5cb45ad23423299f8261b004dd6dfb/cmd/osmosisd/cmd/root.go#L58

- mainnet => `$HOME/.osmosisd`
- localosmosis => `$HOME/.osmosisd-local`

3. Create a CLI command `osmosisd config set-env localosmosis`

This environment must update the value of `OSMOSID_ENVIRONMENT` at "$HOME/.osmosisd/env"`

## Acceptance Criteria
- switching between config folders via CLI is seamless
- new CLI command implemented
- environment sourced in `.profile`

**Comment by ValarDragon** [comment]
This would be awesome!

**Comment by nicolaslara** [comment]
I like this a lot! 

It would be great if we could also point to a custom home dir `osmosisd config set-env ~/devel/osmosis/v15-home`. 

Maybe we can give those directories names, but it may add complexity.
