### ISSUE TITLE
Failed deposit of asset - missing funds - "block height >= packet timeout"

### ISSUE THREAD

**Issue by 88plug** [osmosis-labs/osmosis#360]
Hi guys, I don't know where to go for support so I came here

I setup Keplr wallet and received ATOM to it.
Then I logged into Osmosis with the Keplr extension, Assets > Deposit Cosmos Hub - ATOM
I could see my ATOM balance, so used MAX and even got the notifications in browser that it was succesful.
I waited 10 minutes and nothing appeared in assets - 1 hour later and still nothing.

Origin ATOM wallet : 
https://atomscan.com/accounts/cosmos13cpa3h7tjceqpnuu38ts9u5l0pyf80x322lvly
Destination "Deposit Cosmos Hub - ATOM" wallet : 
https://www.mintscan.io/osmosis/account/osmo13cpa3h7tjceqpnuu38ts9u5l0pyf80x3z3vufk

Here is proof of IBC Transfer success:
https://atomscan.com/transactions/91BDDCAADBAD0F8CC27695F3F29150B848050580B85AFEA16B0A75D02CD31350

And the error message of the ATOM (Osmosis) receiving wallet:
```
failed to execute message; message index: 1: receive packet verification failed: block height >= packet timeout height (1-134107 >= 1-134104): packet timeout
```
https://www.mintscan.io/osmosis/txs/C2DF94570A862ECF0F31228644347C9037C8058D3761F2FF386DBBDDD9F82873

Even though this "failed" the original ATOM was not re-deposited to the origin wallet.

I am new user - don't know who to call or what to do now but I am missing $1000 because of some packet timeout error...

**Comment by giansalex** [comment]
@88plug you can go to [discord](https://discord.gg/bp7App5e)
