### ISSUE TITLE
Swaprouter - Add AfterCFMMPoolCreated Hook

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3612]
## Background

See @p0mvn's comment here https://github.com/osmosis-labs/osmosis/pull/3607#discussion_r1038805065

## Suggested Design

Since concentrated liquidity pools do not require gauges, we want to make a AfterCFMMPoolCreated hook that triggers gauge creation instead of how it is currently triggered on AfterPoolCreated. 

## Acceptance Criteria

TBD

**Comment by hieuvubk** [comment]
Hi would I work with this

**Comment by p0mvn** [comment]
This is now completed by https://github.com/osmosis-labs/osmosis/pull/4838
