### ISSUE TITLE
feat(auto/code-gen): improve upgrade handler code-gen to auto-run CI and apply labels

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3628]
## Background

There has been great progress toward code generating the upgrade handler via CI in:
- https://github.com/osmosis-labs/osmosis/pull/3100/
- https://github.com/osmosis-labs/osmosis/pull/3578

Now, we can run the script that opens a PR like this:
https://github.com/osmosis-labs/osmosis/pull/3627

There are some minor automation improvements possible.

## Suggested Design

1. Auto-apply our mandatory state-compatibility labels
 * It should be `V:state/breaking`

2. Auto-run CI upon opening the code-generated pool request.
* See #3627 where I had to close and reopen PR to be able to run the CI. CI should run automatically upon PR creation

## Acceptance Criteria
- State-breakage label is auto-applied on PR creation
- CI runs on PR creation w/o manual intervention

**Comment by MasterPi-2124** [comment]
I created this pr on my fork and seem that it is working now: https://github.com/MasterPi-2124/osmosis/pull/12

**Comment by p0mvn** [comment]
Closed by: https://github.com/osmosis-labs/osmosis/pull/4031
