### ISSUE TITLE
fix(CI): e2e-init images are not published on release tag

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3631]
## Background

The CI job introduced in https://github.com/osmosis-labs/osmosis/pull/3249

was not triggered by either of `v13.0.0` or `v13.1.0` tags

We need to understand why it did not run and fix it.

## Acceptance Criteria
- fix the e2e-image upload CI job t run on a release tag

**Comment by p0mvn** [comment]
cc: @anhductn2001 please let me know if you have any context on this

**Comment by p0mvn** [comment]
Looks like v13.1.0 osmosis images did not get published as well:
https://hub.docker.com/r/osmolabs/osmosis/tags

cc: @niccoloraspa for awareness

**Comment by anhductn2001** [comment]
Seems like github action not working when we push v13.x.0. Maybe we should take a look at this [script](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/push-docker-images.yml#:~:text=on%3A,%23%20ignore%20rc)

**Comment by p0mvn** [comment]
Does anyone know if this has been addressed already?

**Comment by niccoloraspa** [comment]
Confirming that it's working
