### ISSUE TITLE
feat(ci/code-gen): upgrade handler code gen bumps up e2e-init version

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3632]
## Background

This is a follow-up to: https://github.com/osmosis-labs/osmosis/issues/3628

## Suggested Design

The upgrade-handler CI job should also bump up the previous e2e init version:
https://github.com/osmosis-labs/osmosis/blob/13618066bc646ca33754bffd019ba38410f5a945/tests/e2e/containers/config.go#L30

Assume we are upgrading a v14 upgrade handler.

The logic should work as follows:

1. Query the latest tag from the docker hub: https://hub.docker.com/r/osmolabs/osmosis-e2e-init-chain/tags

2. 
- If the major version latest tag matches 14 - 1 = 13, choose that full version. It can be `v13.0.0` or `v13.1.0` or `v13.0.1`
- if the major version latest tag does not match 13 (e.g. `v12.2.0`). Change it to `v13.0.0` (`14 - 1 = 13`)

Similarly, it should also bump up `previousVersionOsmoTag`

## Acceptance Criteria
- upgrade handler code-gen script is updated to choose the appropriate versions for `previousVersionOsmoTag`
- upgrade handler code-gen script is updated to choose the appropriate versions for `previousVersionInitTag`

**Comment by MasterPi-2124** [comment]
I saw that you changed `previousVersionOsmoRepository` to `osmolabs/osmosis-dev`, and the tags in there are really hard to be identified as suitable for changing. So I filter them to only check on tags in these example formats: 
- 13.1.2 (no any alphabets ending)
- 13.2
If there are not any tags available, the default tag should be `13.0.0`

`previousVersionInitTag` is the same as above with the letter `v` as prefix. Detail can be seen at: https://github.com/MasterPi-2124/osmosis/pull/12
