### ISSUE TITLE
[chore 🧹]  Update README with more detailed information

### ISSUE THREAD

**Issue by niccoloraspa** [osmosis-labs/osmosis#3643]
## Background

The current README does not provide enough information about the project and its goals, as well as clear instructions for getting started and contributing. 

It would be useful to update the README with more detailed information and instructions to make it easier for potential users and contributors to understand and engage with the project.

## Suggested Design

We can build on top of what ChatGPT proposed https://hackmd.io/@sq7nPjAATDS1_frTus12Wg/H1IQUchws, fixing the mistakes and adding the missing sections (joining mainnet/testnet, links to docs).

## Acceptance Criteria

`README.md` updated

**Comment by ValarDragon** [comment]
want to submit a PR with the initial improvement, to get the ball rolling?

**Comment by faddat** [comment]
@niccoloraspa hey, could you share the prompts you used for this?

Also, I'm super happy to kick off the PR.  The linked doc was written by chatgpt?

amaze.

**Comment by niccoloraspa** [comment]
Sure! I just copied the current one as an explanation and just asked if ChatGPT could write a GitHub Readme. The AI gods did the rest

**Comment by Haukar** [comment]
Hello, I am new and this seems like something I can help on please let me know

**Comment by p0mvn** [comment]
This issue is outdated. We can revisit the improvements we want in a new issue. Closing for now
