### ISSUE TITLE
Querying all validators and delegators causes the node to hang

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#365]
This has been reported by BigB from SmartStake, and been a significant pain point for them.

> @Valardragon looks like a similar issue (that was happening with delegations api) is now happening with the /validators (not /staking/validators). a node of mine crashed with this api today (the api was working fine till yesterday night). issue appears to affect public node end points too e.g. http://rpc.osmosis.akash.host/validators and https://rpc-osmosis.itastakers.com/validators

Querying all the validators or delegators will cause a node to hang. This is probably a bug in the SDK stargate code, as our staking module is relatively untouched. We should investigate this

**Comment by arno01** [comment]
can confirm.

rpc.osmosis.akash.host points to `kfqnp70bol8cv049c6bsh5j6sg.ingress.sjc1p0.mainnet.akashian.io` (single IP behind) which is a deployment on Akash Provider `akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal`.
This endpoint is running TWO different validators (bitcana & osmosis) behind which is a no-bueno!

## Evidence

```
$ dig +noall +answer rpc.osmosis.akash.host
rpc.osmosis.akash.host.    294    IN    CNAME    kfqnp70bol8cv049c6bsh5j6sg.ingress.sjc1p0.mainnet.akashian.io.
kfqnp70bol8cv049c6bsh5j6sg.ingress.sjc1p0.mainnet.akashian.io. 9 IN A 139.178.68.79
```

```
$ curl -s -H 'Connection: close' http://kfqnp70bol8cv049c6bsh5j6sg.ingress.sjc1p0.mainnet.akashian.io/status | jq -r '.result | [ (.node_info | .id, .listen_addr, .network, .version, .moniker), (.sync_info | .latest_block_height,.latest_block_time,.catching_up)] | @csv'
"55ce8256412e0997eae7aa807e9f05a52dfd29b3","tcp://0.0.0.0:26656","bitcanna-1","v0.34.13","bitcanna-snapshot-1","593280","2021-11-09T16:35:20.478959262Z",false

$ curl -s -H 'Connection: close' http://kfqnp70bol8cv049c6bsh5j6sg.ingress.sjc1p0.mainnet.akashian.io/status | jq -r '.result | [ (.node_info | .id, .listen_addr, .network, .version, .moniker), (.sync_info | .latest_block_height,.latest_block_time,.catching_up)] | @csv'
"98007de3a7ecfa00b89a662c89c0561cdfc60d04","tcp://0.0.0.0:26656","osmosis-1","0.34.14","osmosis-snapshot-1","1925601","2021-11-09T16:35:23.665291291Z",false
```

## Refs

Akash Discussion at #validators-mainnet channel https://discord.com/channels/747885925232672829/751246770885099533/907670290643976283

Osmosis Discussion at #validators channel https://discord.com/channels/798583171548840026/842550346865180682/907669603394682904

**Comment by arno01** [comment]
@daniel-farina looks like it got fixed.
curl'ed it again multiple times, am only getting "osmosis-1" now.

**Comment by ValarDragon** [comment]
This is dependent on the IAVL speed fixes we are working on, and ABCI mutex contentions #604
