### ISSUE TITLE
refactor: simplify pool creation app testing helpers

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3675]
Note: planning to create an issue to streamline these helpers to reduce redundant boilerplate

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/3638#discussion_r1041385060_

@p0mvn to provide more context

**Comment by mattverse** [comment]
+1 on this! Yeah I think it's time we refactor all these messy helper methods

btw, why have concentrated liquidity label for this issue?

**Comment by mattverse** [comment]
Punting on this issue since the original post in https://github.com/osmosis-labs/osmosis/pull/3638#discussion_r1041385060 has not been merged. Also down to close this issue
