### ISSUE TITLE
[CL]: Tick Spacing Default

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3684]
## Background

For now, we are setting the parameter to the following: `AuthorizedTickSpacing: []uint64{1, 10, 60, 200}`

## Suggested Design

We should run benchmarks to see which tick spacings we should allow. If tick spacing of 1 has very low overhead, it should be the only option for all pools.

## Acceptance Criteria

TBD

**Comment by p0mvn** [comment]
@czarcas7ic  Is there anything that needs to be done here still?

**Comment by czarcas7ic** [comment]
I am going to close this for now, but we may want to look into how we simply to the pool creator the optimal creation strategy (i.e. creating the pool with default tick spacing of 10 and make their exponenetAtPriceOne one less than intended)
