### ISSUE TITLE
Allow migration of x/lockup uosmo to staking to a valset preference

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#3703]
## Background

We should add a new message in valset preference which allows breaking of a bonded lockup (by ID) of osmo, of length <= 2 weeks, add takes all that osmo and stakes according to your current validator set preference. If you don't have a valset preference, return an error. (Noting that there is an implicit valset preference if you've already staked)

## Suggested Design

- New message type in x/valset-preference
- Takes in lock ID
- Checks if sender is lock ID owner
- Checks that lock ID _only contains uosmo_
- Checks if lock ID is bonded, of duration <= 2 weeks, and has no superfluid relation (ensured by checking that there are no synthetic locks)
- Then calls ForceUnlock
- Takes unlocked osmo, and stakes according to valset pref
- If valset pref not found, return error

Only question (which we can resolve after implementation) is whether this message long term belongs in its own module or not. Its unfortunate to make valset-preference have an import dependency on x/lockup (though an external user could just pass in `nil` for `x/lockup`, it would still cause them import / build issues). The reverse would also be unfortunate, due to the high amount of complexity in `x/lockup`. Due to SDK module code bloat, its a minor inconvenience to make a new module, but perhaps worth it post-implementation.

## Acceptance Criteria

- [ ] Can safely convert a 2 week bonding position to staking to a valset pref

**Comment by mattverse** [comment]
> Checks that lock ID only contains uosmo

Don't know if there's any lock that only contains uosmo? Normal locks from the pool contains pool shares + there's no incentive rn to lock only uosmo, user would rather stake it and earn rewards
