### ISSUE TITLE
docs, release

### ISSUE THREAD

**Issue by Kwaskoff** [osmosis-labs/osmosis#372]
Guys.. 
you can make release like https://github.com/cosmos/gaia/releases with binary!!
or.. ok - you haven't binary, but.. where build manual?! like https://github.com/cosmos/gaia/blob/main/docs/gaia-tutorials/installation.md
p.s. and how I can check airdrop without any extension and frontend like https://app.osmosis.zone?! I use gaia!!
Thx

**Comment by ValarDragon** [comment]
Releases are getting included in all new tags now!
