### ISSUE TITLE
[CL]: Create Concentrated Pool: Check Denoms Exist On Chain

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3723]
## Background

See https://github.com/osmosis-labs/osmosis/pull/3687/#discussion_r1048716779

We should add a function to validate basic that checks if the denoms exist on chain https://github.com/osmosis-labs/osmosis/blob/da489c82c4b86fd3a6dc0ec1bb8eecee7629410d/x/concentrated-liquidity/model/msgs.go#L87-L90

Right now, we just check that the denoms are valid.

**Comment by RusAkh** [comment]
Is this free to work on?

**Comment by mattverse** [comment]
Closed by https://github.com/osmosis-labs/osmosis/pull/3804
