### ISSUE TITLE
CreateGauge fails on CLI with empty StartTime

### ISSUE THREAD

**Issue by mconcat** [osmosis-labs/osmosis#373]
CLI command `create-gauge` fails with an empty StartTime flag. Empty StartTime was intended to be considered as an immediate start, but `MsgCreateGauge.ValidateBasic` returns an error if the start time is empty. As modifying ValidateBasic is a consensus-breaking change, the CLI command needs to use an arbitrary time(either `time.Unix(0, 0)` or `time.Now()`).

**Comment by ValarDragon** [comment]
Fixed in https://github.com/osmosis-labs/osmosis/commit/5bd55ad827f7d394f47133fa84a68fe9da51e960, we need to cherry pick into master

**Comment by ValarDragon** [comment]
Cherry picked in #374
