### ISSUE TITLE
Create stableswap and CL pools pre upgrade in v15

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3742]
In E2E testing

**Comment by p0mvn** [comment]
Must be done here:
https://github.com/osmosis-labs/osmosis/blob/f3398f2a2a9926a4c2a3ba6542e5f22359db4804/tests/e2e/configurer/upgrade.go#L129

Relevant helpers for stableswap and CL pool creation added in `command.go`

- e2e test continues to pass
