### ISSUE TITLE
`TestGetPoolModule`: add concentrated-liquidity test case

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3796]
Follow the link below for context:

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/3794#discussion_r1052695653_
      

**A/C**
- test case added

**Comment by ThanhNhann** [comment]
Can I handle this?

**Comment by p0mvn** [comment]
@ThanhNhann thanks for checking in. It looks like this was addressed in #3794 but the issue wasn't closed. Going to close it, sorry.

Let me know if any other existing issue looks interesting for you
