### ISSUE TITLE
[CL][Swap Router]: move poolIsActive() check from gamm to swaprouter

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3798]
TODO: consider moving this to swaprotuer

_Originally posted by @p0mvn in https://github.com/osmosis-labs/osmosis/pull/3764#discussion_r1051491467_

**Comment by p0mvn** [comment]
Blocked on: https://github.com/osmosis-labs/osmosis/issues/3807 . We need to make sure that API is introduced to make sure that we don't miss adding this check to it.

**Comment by mattverse** [comment]
@p0mvn  What's the reason we want to move that check to the swaprouter? Seems that the caller function(`SwapExactAmountIn`) is getting called in other places as well within the gamm module, I'm concerned that if we move that check to the swap router layer, any other methods calling the `SwapExactAmountIn` would not have the isActive check

**Comment by p0mvn** [comment]
The reason is that it would be great to perform the `IsActive` check for CL pools as well. As a result, x/swaprouter might be a good shared location for doing so.

I think the issue you are referring to (ref: https://github.com/osmosis-labs/osmosis/issues/3130) is orthogonal toIsActive`,

No client other than swaprouter should call `SwapExactAmountIn` in `x/gamm`. https://github.com/osmosis-labs/osmosis/issues/3130 is to investigate how we can prevent these other clients from doing so.

The `IsActive` check here is to have a quick switch guard for us to turn of all pools quickly (including CL) if there is a security incident in progress given, assuming that #3130 is addressed
