### ISSUE TITLE
Allow "rebonding" during "unbonding" period

### ISSUE THREAD

**Issue by cbrum11** [osmosis-labs/osmosis#382]
As the title says - Would like to be able to "rebond" to the initial "unbond" period (1, 7, or 14 day) anytime after "Unbond All" is chosen and before unbonding is complete.  Obviously, after rebonding, if you unbonded again, the clock restarts for the full unbonding period...

There may be a conscious reason why this option was not baked in from the beginning of the design - but if not, would love to see this feature

**Comment by ValarDragon** [comment]
Agreed, I think this would be a great feature!

**Comment by Jmichals3** [comment]
In addition to rebonding, you should be able to bond to the longer time preference without the need to unbond.  

For example, should be able to bond to 14 days from 1 or 7 days without unbonding but wouldn’t be allowed to switch from 14 to 7 or 1 day without unbonding

**Comment by czarcas7ic** [comment]
@pysel can you link the PR to this issue please?

**Comment by pysel** [comment]
I think it is linked already: https://github.com/osmosis-labs/osmosis/pull/4713/

@czarcas7ic

**Comment by ValarDragon** [comment]
We have decided we are not going to do this
