### ISSUE TITLE
Is this a viable solution for partial unbond of Superfluid locks?

### ISSUE THREAD

**Issue by t4sk** [osmosis-labs/osmosis#3830]
Normal locks can partial unbond, but superfluid locks can't. Will this be a viable solution for partial unbond of superfluid locks?

Modifies the function BeginUnlock
- BeginUnlock will call a hook to super fluid if synthetic lock exists
- Superfluid hook will execute code to split synthetic lock into 2 (locking and unlocking)
https://github.com/osmosis-labs/osmosis/blob/67ab2f574b886d37313911342b1e78bd4b941b98/x/lockup/keeper/lock.go#L164-L176

![osmosis-pr](https://user-images.githubusercontent.com/8084705/209097831-3bba3609-853a-4510-ad4f-85bc8b71e0c0.png)

**Comment by ValarDragon** [comment]
This looks great! Would love for this to get in

**Comment by stackman27** [comment]
Would love to have partialUndelegation and partial unBonding if possible

**Comment by MbBrainz** [comment]
Any update on this issue?

**Comment by t4sk** [comment]
WIP
