### ISSUE TITLE
cli: Make cmd to list all module account string/address pairs

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#385]
This is mostly an SDK change that should eventually get upstreamed. This will help with debugging funds, and viewing community pool funds in an explorer.

**Comment by ValarDragon** [comment]
We would like to add a query for `osmosisd query auth display_all_module_accounts` which then displays the human readable name, and then the account address for every module account.

**Comment by mattverse** [comment]
Closing this issue with https://github.com/osmosis-labs/cosmos-sdk/pull/19!
Also, this goes under the issue https://github.com/osmosis-labs/osmosis/issues/410 (upgrade to cosmos sdk v0.43.0)
