### ISSUE TITLE
Commentary/Praise: using go.work

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#3860]
Go workspaces will make Osmosis much easier to work on compared to other multi-module repos in cosmos.

Here's an example:

* https://github.com/cosmos/cosmos-sdk/pull/14411

**Comment by tac0turtle** [comment]
Go.work is for local development. In the sdk er have a Go.work.example and the Developer can remove the .example. 

Pushing go.work to the repo will cause issues. If you check GitHub gitignore recommendation it ignores go.work as well

**Comment by faddat** [comment]
nooooooooooooooooooooooooooooooo

<with love effect>

-jacob
