### ISSUE TITLE
Add `active=true` query param to `/osmosis/pool-incentives/v1beta1/external_incentive_gauges` query

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis#3873]
## Background

On the frontend, we must maintain a JS object that maps pools IDs to active external gauges. This is a manual process by @JeremyParish69, and we're looking to automate it. Additionally, we then fire of a large number of queries to get the latest gauge data for each gauge in the aforementioned map.

The `/osmosis/pool-incentives/v1beta1/external_incentive_gauges` query currently returns all gauges, active and previously active. For all gauges and its data, the resulting list is _massive_ and is not performant enough to be queries on every users' browser.

## Suggested Design

We should add a query param to the query to allow the node to optionally filter for currently active gauges. This would greatly reduce the size of response.

## Acceptance Criteria

Query accepts some type of query param that only returns active external gauges.

**Comment by ValarDragon** [comment]
I think we've moved away from this, to serving this query via other means
