### ISSUE TITLE
feat(x/swaprouter): add new queries to stargate whitelist

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3882]
## Background

`x/swaprouter` moved some queries from `x/gamm`. We need to add them to stargate whitelist.

## Suggested Design

- Add `NumPools` to stargate whitelist: https://github.com/osmosis-labs/osmosis/blob/574443a1faab1e49902116ca6239c5477046a7f4/x/swaprouter/client/grpc/grpc_query.go#L33
- Add `EstimateSwapExactAmountOut` to stargate whitelist: https://github.com/osmosis-labs/osmosis/blob/574443a1faab1e49902116ca6239c5477046a7f4/x/swaprouter/client/grpc/grpc_query.go#L43
- Add `EstimateSwapExactAmountIn` to stargate whitelist: https://github.com/osmosis-labs/osmosis/blob/574443a1faab1e49902116ca6239c5477046a7f4/x/swaprouter/client/grpc/grpc_query.go#L53

## Acceptance Criteria
- all specified queries are stargate-whitelisted

**Comment by GNaD13** [comment]
Hi, can I take this issue?

**Comment by mattverse** [comment]
Hey @GNaD13 thanks for the offer! Will take this issue in-house for faster iteration of the remaining issues, thanks for the offer!
