### ISSUE TITLE
test(CL): updatePosition

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3884]
## Background

`updatePosition` in `lp.go` is missing tests.

## Suggested Design

Add tests with test coverage maximized

## Acceptance Criteria
- tests added
- coverage maximized

**Comment by GNaD13** [comment]
Hi, can I take this issue?

**Comment by czarcas7ic** [comment]
Hey, all concentrated liquidity issues are going to be held in house until we reach MVP. Thanks for proactively reaching out though!
