### ISSUE TITLE
[CL]: Overflow Equation

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3887]
Uni v3 claims these the first of these two formulas is more accurate and the later is used for overflows. We should investigate if this is needed for our implementation.

`sqrtPriceNext = (liquidity * sqrtPriceCurrent) / ((liquidity) + (amountRemaining * sqrtPriceCurrent))`
`sqrtPriceNext = ((liquidity)) / (((liquidity) / (sqrtPriceCurrent)) + (amountRemaining))`

See https://github.com/osmosis-labs/osmosis/blob/603a3504df0c7c98fa9fb6b7484e4ac962c34165/x/concentrated-liquidity/internal/math/math.go#L93-L115

## Suggested Design

If the overflow equation is needed, we need to create a test that shows this overflow occuring. If it does not apply to us, we should simply remove the second equation and only use the first equation, with no need for an overflow test.

## Acceptance Criteria
- Full investigation into why two equations were required in the uni v3 design, and an explanation of why we do or do not need them
- If we need both, a test is created to show the overflow protection
- If we don't need both, only utilize a single one in all scenarios

**Comment by stackman27** [comment]
In this logic, shouldn't we always run this if statement? Because (amountRemaining * sqrtPriceCurrent)  / (amountRemaining) will always equal sqrtPriceCurrent
```
product := amountRemaining.Mul(sqrtPriceCurrent) 
 	// use precise formula if product doesn't overflow 
 	if (product.Quo(amountRemaining)).Equal(sqrtPriceCurrent) { 
 		denominator := liquidity.Add(product) 
 		if denominator.GTE(liquidity) { 
 			return liquidity.Mul(sqrtPriceCurrent).QuoRoundUp(denominator) 
 		} 
 	} 
```

**Comment by p0mvn** [comment]
AFAIU, there might be some difference from rounding and truncation behavior at the precision end.

I'd try following approach to investigate this:
- trying to see if all existing CL unit tests pass
- write more unit tests for `GetNextSqrtPriceFromAmount0RoundingUp` trying to reproduce hitting the if condition and not hitting it
- Observe if there is any difference between having the existing logic and `return liquidity.Mul(sqrtPriceCurrent).QuoRoundUp(denominator)` only.

If there is no difference, we can directly implement the suggestion here. If there is some, we would have to deep-dive into why this rounding logic is needed
