### ISSUE TITLE
bug(CL): write tick to state during swaps

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3890]
## Background

Currently, the ticks are not written back to state when they are updated during swaps.

## Suggested Design

We need to make sure that ticks are updated.

## Acceptance Criteria
- add tests upon fixing the problem. For example, you cannot drain the same liquidity multiple times

**Comment by mattverse** [comment]
Do ticks not get updated via https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/swaps.go#L71?

**Comment by p0mvn** [comment]
I don't think so. Ticks would have to be updates as we cross them since they have liquidity drained.

This would have to happen at a much lower level of abstraction:
- either here: https://github.com/osmosis-labs/osmosis/blob/f611e01c7fb9ab9d5348250cb0b65e08f3ec651b/x/concentrated-liquidity/tick.go#L46
- oe here: https://github.com/osmosis-labs/osmosis/blob/f611e01c7fb9ab9d5348250cb0b65e08f3ec651b/x/concentrated-liquidity/swaps.go#L312

**Comment by mattverse** [comment]
Closing this issue as an outcome from investigation that the tick state does not need to get updated during swaps, instead the fee accumulators need to be updated, will post a separate issue / PR for this task
