### ISSUE TITLE
test(CL): TestAuthzMsg for CL module

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3914]
## Background

We need a test for authz serialization de-serialization for CL module messages.

## Suggested Design

Add a test similar to: https://github.com/osmosis-labs/osmosis/blob/f611e01c7fb9ab9d5348250cb0b65e08f3ec651b/x/swaprouter/types/msgs_test.go#L277

for all CL module messages

## Acceptance Criteria
- tests added
- pass

**Comment by p0mvn** [comment]
Blocked on: https://github.com/osmosis-labs/osmosis/pull/3913

Once #3919 is complete, this issue is available for pick up

**Comment by RusAkh** [comment]
hello @p0mvn. I see #3913 is merged, may I pick this one?

**Comment by p0mvn** [comment]
Sounds great, thanks
