### ISSUE TITLE
[SwapRouter] misc: Delete duplication of `SwapAmountInRoute` between gamm module and swap router module

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3921]
## Background

cref: https://github.com/osmosis-labs/osmosis/pull/3880#discussion_r1059985454

Right now, we have two implementations of `SwapAmountInRoute`, one in the gamm module(legacy) and the new `SwapAmountInRoute` struct / proto that has been introduced in the swap router module. 

There is no reason to keep both structs: the goal of this issue is to delete the `SwapAmountInRoute` from the gamm module and remove duplication of the struct between modules.

The same goes for `SwapAmountOutRoute`.

## Suggested Design
- Remove `SwapAmountInRoute` from gamm module
- Remove `SwapAmountOutRoute` from gamm module

**Comment by hieuvubk** [comment]
Could I work with it

**Comment by mattverse** [comment]
@hieuvubk  We're trying to get the swap router / concentrated liquidity asap, but as long as this doesn't take to long, yeah go for it!

**Comment by p0mvn** [comment]
Would like to note that this is blocked on #3880. Please wait for that to be merged

**Comment by p0mvn** [comment]
Marked this as "Help wanted" since this is not on the critical path.

**Comment by phamminh0811** [comment]
Could I work with it?

**Comment by mattverse** [comment]
@phamminh0811 yes please!
