### ISSUE TITLE
feat(CL Fees): Initialize / update fee accumulator at position updates

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3926]
## Background
In #3893, @p0mvn has prototyped the concentrated liquidity fees.
This PR is a part of splitting that PR into multiple components with tests.

This issue focuses on implementing and testing the `initializeFeeAccumulatorPosition` and `updateFeeAccumulatorPosition` method and its dependency methods. 

The methods are to be called in `createPosition` and `updatePosition`.

## Acceptance Criteria
- Extract `initializeFeeAccumulatorPosition` and `updateFeeAccumulatorPosition` from #3893.
- test with coverage maximized. This includes creating tests for the `initializeFeeAccumulatorPosition` and `updateFeeAccumulatorPosition`, as well as creating all unit tests for all dependency methods.

**Comment by mattverse** [comment]
Blocked by https://github.com/osmosis-labs/osmosis/pull/3874

**Comment by p0mvn** [comment]
Looks like this was completed in: https://github.com/osmosis-labs/osmosis/pull/3936
