### ISSUE TITLE
Regression in v0.42.7 SDK

### ISSUE THREAD

**Issue by colin-axner** [osmosis-labs/osmosis#397]
I just noticed the [v2](https://github.com/osmosis-labs/osmosis/releases/tag/v2.0.0) contains v0.42.7 as the SDK dependency. There is a [known bug](https://github.com/cosmos/cosmos-sdk/issues/9800#issuecomment-889228038) in v0.42.7 and v0.42.8 which affects all nodes. Doing a hard fork to this version risks disabling IBC in the case that the first IBC tx fails after the upgrade (this is what occurred on the desmos testnet)

Please downgrade the SDK version to v0.42.6. State sync will be broken on this version, but there are no risks involved with accidentally disabling IBC or causing app hash mismatches

**Comment by ValarDragon** [comment]
Thanks! Forgot to reply on the github issue - We will be switching to v0.42.9!

**Comment by ValarDragon** [comment]
Version `v3.1.0` does this!
