### ISSUE TITLE
[CL]: Add tests for validateTickRangeIsValid

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3983]
## Background

The following function is currently untested

https://github.com/osmosis-labs/osmosis/blob/a3f2abbd9235b3b1f8b74c3409fa262c99c9c0a1/x/concentrated-liquidity/tick.go#L106-L107

https://github.com/osmosis-labs/osmosis/pull/3874#discussion_r1066563154

## Suggested Design

Add test cases for the validateTickRangeIsValid function

## Acceptance Criteria

* Input valid tick ranges at various exponentAtPriceOne and tickSpacings with no error
* Input invalid tick ranges at various exponentAtPriceOne and tickSpacings with an error

**Comment by DongLieu** [comment]
Can I handle this ? @czarcas7ic
