### ISSUE TITLE
[CL]: Explore pre-computing max and min ticks for each exponentAtPriceOne

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3986]
## Background

Right now, we utilize a GetMinAndMaxTicksFromExponentAtPriceOne function to determine the min and max ticks given an exponentAtPriceOne:

https://github.com/osmosis-labs/osmosis/blob/a3f2abbd9235b3b1f8b74c3409fa262c99c9c0a1/x/concentrated-liquidity/internal/math/tick.go#L180-L185

Roman suggested we should potentially just precompute these instead of computing them on the fly each time.

https://github.com/osmosis-labs/osmosis/pull/3874#discussion_r1066444002

## Suggested Design

I'm not entirely sure if this is a great idea, since I don't think this is very computationally intensive. With that being said, I think its still worth having a discussion on the best way forward for this.

If we do go forward with this, we just need to ensure how we computed the min and max ticks for each exponentAtPriceOne is commented nearby.

## Acceptance Criteria

* Decision point on if we should or should not pre compute max and min ticks for each exponentAtPriceOne
* If we decide to do so, modify GetMinAndMaxTicksFromExponentAtPriceOne to return min and max ticks without having to run computation each time.

**Comment by mattverse** [comment]
Although we do have a pre-set of authorized tick spacing, they are practically part of params used in the CL module. With that being said, Im not so sure if we can have a preset calculation or if using a pre-set calculation would be the best option here. Params can be easily changed via governance, while using hard coded pre-calculated values using the default authorized tick spacing requires constant updates

**Comment by p0mvn** [comment]
I don't see these being set via governance.

There are min and max values here:
https://github.com/osmosis-labs/osmosis/blob/316005aca4dcc3c01ca8249934b9907014ff55e8/x/concentrated-liquidity/types/constants.go#L15-L16

So it still makes sense to precompute these if we are limiting the allowed rand to the hardcoded constant values

I think what is set via governance is "authorized tick spacing" which is separate from the exponents at price one discussed here.  Why do we still need this authorized tick spacing? CC: @czarcas7ic . I remember having discussions where we can just keep the value of 1. However, I'm unsure what the conclusion was.

**Comment by czarcas7ic** [comment]
I haven't heard anything with regards to performance impact of single tick spacing default. With that being said, I don't think it has been tested/benchmarked throughly yet.
