### ISSUE TITLE
(CL Test): Add tests for inverse relationship testing between `TickToPrice` and `PriceToTick`

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3993]
## Background

Upon implementing https://github.com/osmosis-labs/osmosis/pull/3874(Geometric tick spacing), we have re-implemented `TickToPrice` function and `PriceToTick` function.

As we test the inverse relationship for joinPool and exitPool in the gamm module, it would be best if we could add a test for ensuring the inverse calculation between the two methods.

## Acceptance Criteria

- Added test case using pre-defined test vectors that calls `TickToPrice` and then using the returned value calling `PriceToTick` and then checking if we get the same test vectors that we used as inputs

**Comment by p0mvn** [comment]
Marked this as "Help wanted" since this test is not on the critical path.

**Comment by hieuvubk** [comment]
Hi could I work with it @mattverse @p0mvn

**Comment by mattverse** [comment]
@hieuvubk yes please!

**Comment by ThanhNhann** [comment]
Hey @mattverse, I checked the code again and see that the `TickToPrice` function is not in main branch right now, can you plz check it?

**Comment by ThanhNhann** [comment]
I see that this #4003  had changed `TickToPrice ` to `TicksToSqrtPrice`, should we change the name function to keep working on this issue? @mattverse

**Comment by mattverse** [comment]
@ThanhNhann  Yes in this case, lets test inverse relationship between TicksToSqrtPrice and PriceToTick. Im assuming that there would be a little bit of margin of error that would have to be considered when designing the test cases

**Comment by ThanhNhann** [comment]
Thank @mattverse, I have updated the tests
