### ISSUE TITLE
refactor(osmoutils): rename accum `createPosition` to `initOrUpdatePosition`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3995]
**Context**

We should rename the `createPosition` function in `osmoutils/accum` to `initOrUpdatePosition` since its semantics include not only creation but also updates.

`accum_test.go` also needs to be updated to reflect this change. Also, modify the godoc for this function to reflect the new semantics.

_Originally posted by @mattverse in https://github.com/osmosis-labs/osmosis/pull/3990#discussion_r1067975195_

**A/C**
- `createPosition` renamed to `initOrUpdatePosition`
- tests renamed as well
- godoc added / modified
- comments in all callers are modified as well

**Comment by hieuvubk** [comment]
Could I take this?

**Comment by p0mvn** [comment]
Yes please @hieuvubk
