### ISSUE TITLE
e2e: automatically bump `OSMOSIS_E2E_UPGRADE_VERSION` on major releases

### ISSUE THREAD

**Issue by RusAkh** [osmosis-labs/osmosis#4029]
## Background

In #3100 we added a Github Action that triggers on new major release and:

> 1. creates a new folder for upgrade handler in app/upgrades
>2. increases E2E_UPGRADE_VERSION in Makefile by one
>3. changes app/app.go file

and creates a pull request

I noticed that this action does not bump `OSMOSIS_E2E_UPGRADE_VERSION` in https://github.com/osmosis-labs/osmosis/blob/main/.vscode/launch.json

## Suggested Design

Increase the version to v14 before implementing the script

In addition to those 3 changes that action does, it should also bump the version of `OSMOSIS_E2E_UPGRADE_VERSION`

## Acceptance Criteria

* Design implemented
* Link to PR from fork showing this action works

**Comment by MasterPi-2124** [comment]
There are 2 issues #3628 and #3632 related to this, and I created a pr #4031. I think we will need to work on that before doing this issue. Can you guys take a look into that? @p0mvn @RusAkh ?
