### ISSUE TITLE
concentrated-liquidity cli: unable to parse exponentAtPriceOne

### ISSUE THREAD

**Issue by RusAkh** [osmosis-labs/osmosis#4041]
## Background

Currently `osmosisd tx concentratedliquidity create-concentrated-pool` takes 4 parameters as an argument:
* denom1
* denom2
* tickSpacing
* [exponentAtPriceOne](https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/architecture.md#formulas)

As you can see from the link,`exponentAtPriceOne` takes negative values as an argument. However, when you try running cli command and passing negative value, it fails, because cli interprets negative values as flags.

Passing a string (ex: "-2") does not work because cli interprets it as if there are no quotes in the line.

## Suggested Design

There is a solution using `--` as in https://github.com/urfave/cli/issues/645, however, it would mean we won't be able to pass flags, because it will parse flags as arguments:

When using:
```
osmosisd tx concentratedliquidity create-concentrated-pool ua ub 1 -- -1 --from val --keyring-backend test --chain-id localosmosis 
```

you get:

```
Error: accepts 4 arg(s), received 10
```

1) Because of that, the only solution I personally see to pass a negative value is to pass `exponentAtPriceOne` as a flag.

2) However, there is an easier way to do it, but it is somewhat dirty: to pass positive values in the range of (1; 12) and then invert them upon parsing arguments.

## Valuable links
* https://forums.swift.org/t/pass-negative-number-as-command-line-argument/60129/7
* https://github.com/urfave/cli/issues/645

## Acceptance Criteria

You can pass `exponentAtPriceOne` to `create-concentrated-pool` cmd.

**Comment by RusAkh** [comment]
it seems this it more a Mac problem, I tested it in linux environment and it works fine

**Comment by p0mvn** [comment]
Discussed offline and going to close for now
