### ISSUE TITLE
[Story][CL]: Invariant testing for concentrated liquidity

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4047]
## Background

> As an engineer, I want to have the certainty that different traits of Concentrated Liquidity always remain true, in other words, have invariants testings to assure safeness 

## Acceptance Criteria
Investigate and implement the following invariants testings for concentrated liquidity

- https://github.com/osmosis-labs/osmosis/pull/4060
- https://github.com/osmosis-labs/osmosis/pull/4057
- https://github.com/osmosis-labs/osmosis/pull/4076
- https://github.com/osmosis-labs/osmosis/issues/4164
- https://github.com/osmosis-labs/osmosis/issues/3992

-------
- Swap fee accumulator should never decrease by design

**Comment by p0mvn** [comment]
I would like to also think more about invariants related to swaps and collecting fees.

I don't have any specific suggestions at the moment. However, the general idea is to have some invariants to make sure that it is impossible to overclaim fees

**Comment by mattverse** [comment]
Cool! Thanks for the suggestion! Would think about how to make a good testing from the fees!

**Comment by p0mvn** [comment]
Hi @mattverse . Seeing that there are 2 remaining items on the list here. I'm assuming these are blocked on swap fee PRs?

If so, is it possible to break down the remaining work into issues please to have a sense of what's remaining on the sprint board?
