### ISSUE TITLE
Move x/staking to this repository

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#405]
We need to start doing a lot of changes to `x/staking`, so we should move it to this repo, not the SDK. We will have to watch all the changes in the SDK for staking, and consider backporting them here from now on though. Hopefully this won't prove to be to burdensome, as the SDK does not do a rapid release cycle.

**Comment by sunnya97** [comment]
Probably do this after updating to Cosmos SDK v0.43

**Comment by faddat** [comment]
I'm in big support of vendoring.

I think of blockchain code bases as monoliths, ideally.

**Comment by ValarDragon** [comment]
Closing this for now, its a discussion to be decided as part of the superfluid work. There are updates we need to make, but we are trying to mitigate intrusiveness. As we've learned, rebasing / cherrypicking updates is actually a ton of work.
