### ISSUE TITLE
(CL Test): Inverse relationship between swaps

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4065]
This issue is a part of invariant testing.

Upon doing swaps in a concentrated liquidity pool, we want to make sure that we get preserved the same amount when we do a swap from denom1 -> denom2 and the back from denom2 -> denom1 using the amount out in the first swap.

This testing should be done for both  `SwapOutGivenIn` and  `SwapInGivenOut`.

We should be abstracting the testing vectors used in existing test cases to remove code duplication upon testing the same things as done in #4057 

We do not expect them to be exactly equal due to roundings and swap fees, but expect them to be within the expected margin of error

**Comment by p0mvn** [comment]
Looks like this can be closed
