### ISSUE TITLE
e2e: check node update failure before running e2e_test.go

### ISSUE THREAD

**Issue by stackman27** [osmosis-labs/osmosis#4066]
## Background
Currently if there is a node failure, it gets detected in e2e_test.go, but i believe that should be checked right after upgrade proposal. 

## Suggested Design
Check that nodes are running successfully after `runProposalUpgrade` function in tests/e2e/configurer/upgrade.go

## Acceptance Criteria
1. all e2e must pass 
2. better upgrade handler error logic 
3. Update docs in "good things to know" section, ref: https://github.com/osmosis-labs/osmosis/pull/4106

**Comment by p0mvn** [comment]
@stackman27 hey please re-assign yourself if you're planning to be working on this. If not, please let us know so that someone else can pick this up

**Comment by stackman27** [comment]
Free to pickup
