### ISSUE TITLE
[CI] Add GitHub Action to push docker images, that antedate development 

### ISSUE THREAD

**Issue by RusAkh** [osmosis-labs/osmosis#4070]
## Background

In #3503 @niccoloraspa added a Github Action that automatically pushes images to [docker hub](https://hub.docker.com/r/osmolabs/osmosis-dev) on certain events (see #3503). 

We need the same workflow for https://hub.docker.com/r/osmolabs/osmosis-e2e-init-chain.

## Suggested Design

Similar workflow as in #3503, which pushes images of previous versions, when backport to previous tag happens, to https://hub.docker.com/r/osmolabs/osmosis-e2e-init-chain.

## Acceptance Criteria

Design implemented, tested from a private fork

**Comment by p0mvn** [comment]
More context: https://github.com/osmosis-labs/osmosis/issues/1415#issuecomment-1403775868
