### ISSUE TITLE
Build a validator preferences module

### ISSUE THREAD

**Issue by antstalepresh** [osmosis-labs/osmosis#408]
For auto-staking, we will need to build a validator preference module where a user can configure multiple preferred validators.

In progress in https://github.com/osmosis-labs/osmosis/pull/381

**Comment by ValarDragon** [comment]
What we need out of a validator set preferences module is:

A proto definition of validator set preference
```proto
message ValidatorPreference {
  string val_oper_address = 1 [ (gogoproto.moretags) = "yaml:\"address\"" ];
  // weight as a decimal between 0 and 1
  string weight = 2 [
    (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
    (gogoproto.moretags) = "yaml:\"autostake_rate\"",
    (gogoproto.nullable) = false
  ];
}

message ValidatorSetPreference {
  repeated ValidatorPreference preferences = 1 [ (gogoproto.nullable) = false ];
}
```

* A state entry indexed by delegator address to specify a ValidatorSetPreference object
* A message where a delegator can specify ValidatorSetPreference, and it writes to above state entry
* A query, where you can query a delegators ValidatorSetPreferences.
  * If the delegator has no validator set preference object, see if they have staked any tokens. If so, construct a validator set preference object by looking at all of their existing delegations on the fly as a query
  * If there is no validator set preference + no staked tokens, make the response clearly indicate this.

**Comment by ValarDragon** [comment]
Replaced with #2579
