### ISSUE TITLE
old github-pages deployment

### ISSUE THREAD

**Issue by doggystylez** [osmosis-labs/osmosis#4082]
## Background

outdated version of [osmosis docs](https://docs.osmosis.zone) was [deployed](https://osmosis-labs.github.io/osmosis) on Feb 2, 2022.

## Suggested Design

delete [deployment](https://github.com/osmosis-labs/osmosis/actions/runs/1785904910)

## Acceptance Criteria
n/a

**Comment by ValarDragon** [comment]
I believe this was fixed
