### ISSUE TITLE
test(CL Fees): functional tests for CL fees

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4089]
## Background

We need functional tests for CL fees.

## Suggested Design

This should be a Go test withing a CL module that does the following:
- creates a pool with several positions from different accounts at various ranges. Maybe 1-3 positions from 3-5 accounts.
  * full range position
  * narrow range position
  * overlapping ranges
  * consecutive ranges
- performs 1-2 swaps from 3 accounts
- attempts to claim fees
- asserts that the right amount is claimed for each account

## Acceptance Criteria
- functional test added
- the correct amount claimed for each account

**Comment by RusAkh** [comment]
https://github.com/osmosis-labs/osmosis/issues/4085 shall I close this then?

**Comment by p0mvn** [comment]
> #4085 shall I close this then?

This is separate. This issue is related to testing the calculations at a lower level of abstraction while making sure that we don't withdraw more fees than needed.

In e2e terst, we want to do something similar but we don't have to make assertions about math being correct. It's more so - making sure nothing breaks and the chain keeps running

**Comment by p0mvn** [comment]
I think we need to revisit our functional tests to determine why #4423 was uncaught.
