### ISSUE TITLE
test(CL): Create swap tests with different positions and ticks

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4095]
## Background

Our current swap tests only tests swaps with pools with 2positions and 4 ticks at most. 

Since now we have the base layer testing with the 2 positions and 4 ticks, we want to create a swap test with more positions and ticks. 

## Suggested Design
Since we have a thorough swap testing for each individual scenarios in our current swap test, the suggested design of this testing is focusing on the testing scenario and story itself, rather than trying to do a detailed TDD with alot of cases.

## Acceptance Criteria
- Tests with different positions has been made

**Comment by mattverse** [comment]
Also considering about changing this test case to benchmark tests on gas and computational time, testing how much resource it takes upon swap crossing T ticks

**Comment by p0mvn** [comment]
Discussion from call: reuse setup logic from https://github.com/osmosis-labs/osmosis/issues/4089

**Comment by czarcas7ic** [comment]
Waiting to address this issue until @p0mvn addresses the known swap logic bug. @p0mvn let me know if you disagree
