### ISSUE TITLE
Upgrade to cosmos SDK v0.44.0

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#410]
The Cosmos SDK excitingly had its `v0.43.0` release recently!

We should upgrade our SDK version to be v0.43.0. Steps to do this are:

* Pull the branch and tags into our osmosis-labs/cosmos-sdk fork.
* Rebase all the changes from `v0.42.9-osmo-v2-upgrade`, and the `v0.42.7-osmo-rebase` branches. (There are some changes that are on both, and several that are only on one of the branches each)
* PR to Osmosis main to chagne to that
* Change all usages of `v043_temp` folder to use the actual code from `v043`.
* Add a cosmovisor upgrade definition to the app.go for migrating all of the SDK modules to `v043`

**Comment by faddat** [comment]
Working on it

**Comment by ValarDragon** [comment]
Thanks! I've also been working on manually doing the rebase (I'm trying to complete it today). We unfortunately have a ton of merge conflicts with every commit though

**Comment by faddat** [comment]
Yes yes exactly

**Comment by faddat** [comment]
On a related note, I'm thinking of trying to spin up with whomever and how ever-- a fast moving cosmos SDK, think like Linux - next

**Comment by sunnya97** [comment]
How's this process going?

**Comment by faddat** [comment]
Actually it got bumped.

That said, things flowed right back in this direction again.

Maybe I will spend tomorrow on it, because after looking at all the available options and evaluating a few ideas we want to use the EIP sign mode code that you wrote.

**Comment by ValarDragon** [comment]
Ah sorry, we also halted work on this. We're no longer planning to use SDK v0.43.0 in the next release

**Comment by faddat** [comment]
Oh that's okay, I'll dig around and see what I can see and if I can get the osmosis SDK up to 0430 I'll put in a pull request for it.

**Comment by ValarDragon** [comment]
Amazing, tysm!

**Comment by faddat** [comment]
So, good news!

- [x] Cosmos-SDK is on 0.44.0 (Osmosis-SDK)
- [ ] Osmosis is upgraded

**Comment by ValarDragon** [comment]
Closed by #538
