### ISSUE TITLE
test(e2e): parallelize e2e tests

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4101]
## Background

Currently, e2e tests run in sequence but they don't have to be.

## Suggested Design

Implement this into the e2e test suite: https://github.com/cosmos/cosmos-sdk/issues/12332 so that we can run tests in-parallel safely

Ensure that https://github.com/osmosis-labs/osmosis/issues/2569 is complete first
- Having the tests depend on each other does not allow running them in-parallel.

Make e2e tests run in parallel. 

## Acceptance Criteria
- switch to `gotest.tools` in e2e test suite
- ensure all tests can run in-parallel
- reconfigure the e2e test suite to execute all tests in-parallel

**Comment by czarcas7ic** [comment]
Hey @ThanhNhann @hieuvubk, is this still being worked on? If so, do you need any further guidance? Happy to set up a call. If moving on to other things, we will unassign. Thanks

**Comment by hieuvubk** [comment]
> Hey @ThanhNhann @hieuvubk, is this still being worked on? If so, do you need any further guidance? Happy to set up a call. If moving on to other things, we will unassign. Thanks

Yes we would like to have a call with you, for now we still working on that but got some probs. We can discuss further in the call

**Comment by czarcas7ic** [comment]
Great, please hit me up on slack when you would like a call @hieuvubk
