### ISSUE TITLE
Fix Level DB set up for app testing

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4121]
## Background

Right now when we are performing level db set up in app testing, we use a fixed directory for making a new level db instance.
cref: https://github.com/osmosis-labs/osmosis/blob/main/app/test_helpers.go#L52

 This occasionally causes tests to crash, as we're using the same directories for all tests. This should not be the case, rather we should be using temporary / random directories for each and every instance of level db being made.

## Suggested Design
We have three possible ways of fixing this issue: 

1. Change the indicated part in line to use random directory values. 

2. Or, a different approach to this can be adding an argument for the path of directory we want to create in the method( cref: https://github.com/cosmos/cosmos-sdk/blob/main/testutil/sims/simulation_helpers.go#L25)

3. Use `os.TempDir()` to make temporary directory (cref: https://github.com/cosmos/cosmos-sdk/blob/main/x/genutil/collect_test.go#L40)

**Comment by ValarDragon** [comment]
Why are we even using level DB for our app testing? We should just be using it for perf testing
