### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#413]
Sort of a note to self-- feel free to assign to me.

https://github.com/go-echarts/statsview

Should let us get some better insights into what's going on while syncing.

Can be a special build in the makefile so that it doesn't burden the default build.

Probably a starting point, not the destination.

**Comment by faddat** [comment]
https://github.com/arl/statsviz

**Comment by ValarDragon** [comment]
This would be awesome to integrate, so we can understand where sync time and live execution time is going!

The thing I was thinking of before was making a separate build that ran with creating a `cpu.out` that could be passed into pprof. I think using the tools you linked is a better approach!

**Comment by faddat** [comment]
I assume that we're open to helping to make this a PhD project for HNUST CS students?

**Comment by ValarDragon** [comment]
Sorry, missed the last message!

> Well on some levels I agree with you. However, I think that what we should do is once the chain begins to sync What should show up in the log is blocks per second, updated once per second. It should also tell you how many peers you are connected to.

I think this is a great idea!

>  IAVL
>  Various mutexes
>  Stuff that can be optimized.

Totally agreed. FWIW, as I've been benchmarking various things for our epoch time, most of the computation time problem at epoch time is coming from many random SDK efficiencies, that cause way too many allocations. (But I imagine for most blocks, and for space usage, its all signatures & IAVL & mutex locks)

> By the way, after we spoke, I started to look to hire or otherwise engage with someone who has more experience than I do with performance profiling in go. I think that this task is going to get quite in-depth.

This would be amazing, tysm!

> I assume that we're open to helping to make this a PhD project for HNUST CS students?

I'm probably down! What exactly does it entail to make something a PhD project?

**Comment by ValarDragon** [comment]
Closing for now in favor of #1014
