### ISSUE TITLE
Reward distribution network issues

### ISSUE THREAD

**Issue by greg-szabo** [osmosis-labs/osmosis#414]
This is an investigative discussion about network node issues regularly arising right after the daily reward distribution. (Between 5PM UTC and 5:30PM UTC.) We are trying to pin down the exact cause as well as trying to find workarounds until then.

Symptoms:
* Full nodes/sentry nodes lose connection to other nodes. Not necessarily all nodes.
* Full nodes/sentry nodes get behind in height and struggle to catch up.
* Nodes (possibly all types) cannot reconnect to available nodes. (This might be temporary but at one point patience run out and the node is restarted by the operator.)
* Large amount of validators miss blocks (https://osmosis-stats.blockpane.com/)
* RPC endpoints on nodes are not responsive.

Please add any other symptoms you experience and any ideas that come up that might be the cause. Validators, developers, node operators are welcome to chip in.

**Comment by greg-szabo** [comment]
One correlation I'm trying to make is regarding Tendermint's abci_query:

We see similar symptoms when we abuse RPC on a node. The RPC issue boils down to Tendermint's abci_query call (and some other stuff). So my question is: is it possible that the rewards calculation/distribution also goes through the same code path and struggles with the same bottlenecks?

**Comment by zmanian** [comment]
We saw this behavior on the iqlusion vaidator node before we upgraded our storage for the node.

The node wouldn't crash but it would lose its sentry connections.

There was a also a mis configuration on the node that I think prevented reconfiguration.

But we have experienced p2p disconnections during the reward distribution epoch.

**Comment by greg-szabo** [comment]
I just added that we also noticed the RPC endpoints not responding. If the P2P endpoints do the same, that might be why the P2P disconnects happen.
Why the whole thing locks up, is still an interesting question.

Another correlation I made today (might be a red herring):
I noticed Hermes trying to pull 200MB of websocket data at one point (https://github.com/informalsystems/ibc-rs/issues/1299) but websockets have a size constraint (https://github.com/tendermint/tendermint/issues/6729).

**Comment by Sdpierret** [comment]
we experience the same issue than @zmanian with some nodes.
they recover peers but they don't reconnect to the validator

we need to restart the node to reconnect to the validator

![image](https://user-images.githubusercontent.com/82807727/129800782-3fe566ad-37fc-4ed9-ae6c-ef56be7577e7.png)

**Comment by Sdpierret** [comment]
error log at epoch time :
```
Aug 18 17:11:01.319 ERROR [osmosis-1] failed to collect events: WebSocket driver failed: WebSocket Error: failed to read from WebSocket connection: Space limit exceeded: Message length too big: 206467490 > 16777216 (code: 1)
Aug 18 17:11:01.320  INFO [osmosis-1] successfully reconnected to WebSocket endpoint ws://127.0.0.1:36657/websocket
```
this is what @greg-szabo report yesterday.

**Comment by ValarDragon** [comment]
It seems like the entire p2p network disconnects when a block takes too long. We should file an issue on Tendermint and investigate the situation there. Perhaps p2p keep alives are locked behind a mutex with the consensus connection.

In parallel, we have a non-state breaking fix to lower epoch time, which should hopefully help here as well.

**Comment by faddat** [comment]
I was thinking that shorter epochs might be a good band-aid, too.

**Comment by ValarDragon** [comment]
This non-state breaking change for epoch time improvement is currently in testing!

**Comment by zmanian** [comment]
our p2p disconnect at the epoch looks like this

```
5:15PM INF committed state app_hash=B88A9CAF1A8A701CA03281CB1868685F93730813BCDACA819ADE36353B6F2E56 height=834940 module=state num_txs=1
5:15PM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
5:15PM INF Timed out dur=-262040.505549 height=834941 module=consensus round=0 step=1
5:15PM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
5:15PM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
5:15PM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
5:15PM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
5:15PM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
5:15PM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
5:15PM INF Timed out dur=3000 height=834941 module=consensus round=0 step=3
```

**Comment by greg-szabo** [comment]
SIFChain reported similar symptoms back in February: https://github.com/tendermint/tendermint/issues/6184

@ValarDragon if you attended Tendermint Core this week by any chance, could you update us here too? Or link any issues you opened discussed over there.

**Comment by Halimao** [comment]
any new progress? I start a full node two days ago, unfortunately it hanged and stoped to sync block, also couldn't response to rpc request every day, and need to be restart node to resync the block -_-||

**Comment by chmichael** [comment]
Distributing the rewards causes almost for 30 minutes osmosis engine/swaps to be dead! Please fix this!

**Comment by ValarDragon** [comment]
Closing this for now!

Most of the issue has been alleviated as far as I'm aware. Further work to mitigate it is acutally resolvable via a much simpler issue #1083
