### ISSUE TITLE
(CL): Add `TickRangeLiquidityDepth` Query for Better FrontEnd Support

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4149]
## Background

We want to have the following query to better support Front-end (cc. @jonator )

- Within a price range(or above and below the current price if given one hi or lo price value), return liquidity for each tick

Namely, `TickRangeLiquidityDepth`

## Suggested Design
- Create an iterator method that takes in start tick and end tick, use their prefixes and which then returns `sdk.Iterator`
- Create a secondary method using the iterator method created above to iterate over all the ticks within the range and then put them in a separate array
- Add protos for query that would look something like this
   - req: upper tick, lower tick (can be nil)
   - res: array of stuct that contains a) tick Index b) liquidity(sdk.Int)

## Blockers
We also need to think about how to handle full range positions. Iterating over **all** ticks would definitely be too much unnecessary computation. We need to think of a way to get the liquidity existing from tick A~ tick B without having to iterate overall ticks, and then we can use that method to return with longer ranges when we're further away from the current spot price

## Acceptance Criteria
- The query has been added along with necessary test cases
-  Iterator method and test cases has been implemented
- We want to double assure this is not a burden in terms of computation, a benchmark test for this query would be great

**Comment by ValarDragon** [comment]
So what exactly is "liquidity depth"? Is it, for a price range `[p1, p2]` and current price `p`, how much needs to be bought/sold to get to `p1` and `p2` respectively?

**Comment by jonator** [comment]
Yes but per individual tick, or a subset of ticks

The horizontal bars here, with vertical axis being price:

![image (5)](https://user-images.githubusercontent.com/4606373/216021020-714bf54c-0d1c-41e4-8f38-1ee9fa0f28cf.png)
