### ISSUE TITLE
Panic Handling In MultihopEstimateOutGivenExactAmountIn borks Protorev

### ISSUE THREAD

**Issue by NotJeremyLiu** [osmosis-labs/osmosis#4180]
## Background

Panics are caught when swapping (https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/swap.go#L39-L44) but not when estimating a swap (https://github.com/osmosis-labs/osmosis/blob/d28c7412c8d16ed48a20f7b770185d238d83f12b/x/poolmanager/router.go#L133). 

The specific panic that brought this to our attention for Protorev was in stableswap `solveCFMMBinarySearchMulti`: (https://github.com/osmosis-labs/osmosis/blob/d28c7412c8d16ed48a20f7b770185d238d83f12b/x/gamm/pool-models/stableswap/amm.go#L315), but generally any of these panics could likely cause an issue if `MultihopEstimateOutGivenExactAmountIn` does not catch the panics.

## Suggested Design

We are open to different forms of resolution, whether that may be core team adding panic catching in `MultihopEstimateOutGivenExactAmountIn` or us catching panics in Protorev, but we are waiting for core team decision on best way forward.

## Acceptance Criteria

All current protorev tests pass, and adding new tests to purposefully trigger the panics does not result in the actual panic to cause a halt.

**Comment by ValarDragon** [comment]
I think we should definitely just catch this panic -- quite silly for estimate to panic haha
