### ISSUE TITLE
(CL): Add Batched Liquidity Amount Queries for FrontEnd

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4191]
## Background
While https://github.com/osmosis-labs/osmosis/issues/4149 focuses on querying and returning liquidity for each and every individual ticks, we also need a query that batches and groups ticks by given units. Using this query, front-end would be able to draw a abstracted graph of the liquidity distributed for a pool

## Suggested Design

Suggested design for this query is to take in parameter of lower tick, upper tick and the batch size.
Batch size would be restricted by a constant to prevent future spams (someone would be able to send spam quereis via doing a query of batch size 1 from minTick to maxTick).

If given unit of batch size is small enough, we can also allow more precise responses by using medians in between the batch size.

## Acceptance Criteria
- Query For Batched Liquidity Depth has been implemented

**Comment by p0mvn** [comment]
Closing this as the alternative is being pursued in: https://github.com/osmosis-labs/osmosis/pull/4714
