### ISSUE TITLE
localnet: localosmosis does not correctly track CL pools creations

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#4203]
## Background

While working on e2e for CL, I noticed that when running `localosmosis` and creating a CL pool:
```
osmosisd tx concentratedliquidity create-concentrated-pool uion uosmo 1 "[-1]" 0.01 --from val --chain-id localosmosis --keyring-backend test 
```
(no errors returned at this point)
and then trying to query it with: 
```
osmosisd q concentratedliquidity pools --chain-id localosmosis
```
(or `osmosisd q concentrated pool 1 --chain-id localosmosis`)
I was always getting an empty response (or `pool not found` in case of querying by id): 
```
pagination:
  next_key: null
  total: "0"
pools: []
```

I looked into this issue, but did not find a reason for this wrong behavior. The reason I blame localosmosis is because when running an e2e test and creating a concentrated pool there, further query returns the pool correctly

UPD: same goes for `gamm` pools, running:
```
osmosisd tx gamm create-pool --pool-file tests/e2e/scripts/pool1A.json --from val --keyring-backend test --chain-id localosmosis -y
```
and then querying all the pools returns empty response 

UPD2: creating a pool by executing command on docker container running `localosmosis` AND from `pools` account actually works

```
docker exec <localosmosis container id> osmosisd tx gamm create-pool --pool-file <file> --from pools --chain-id localosmosis --keyring-backend test
```
## Suggested Design

localosmosis returns created CL pools

## Acceptance Criteria

design implemented, tested manually

**Comment by cipherzzz** [comment]
I can look into this if you want to assign it to me

**Comment by pysel** [comment]
@cipherzzz sounds good, thank you!

**Comment by pysel** [comment]
please, check out `UPD2` at issue description, maybe it will help

**Comment by p0mvn** [comment]
Got fixed in: https://github.com/osmosis-labs/osmosis/pull/4486
