### ISSUE TITLE
Metadata for denom `uion`, `uosmo` not registered

### ISSUE THREAD

**Issue by byeongsu-hong** [osmosis-labs/osmosis#4224]
#### Expected behaviour

1. Query `/cosmos/bank/v1beta1/denoms_metadata/uion` should respond
2. Query `/cosmos/bank/v1beta1/denoms_metadata/uosmo` should respond

#### Actual behaviour

1. Query failed with (22): rpc error: code = NotFound desc = client metadata for denom uion: key not found
2. Query failed with (22): rpc error: code = NotFound desc = client metadata for denom uosmo: key not found

**Comment by ValarDragon** [comment]
Oh yeah, yikes. I confirmed via the CLI.

I thought we fixed this for `uion` in one of the upgrades.

cc @mattverse can you guide @stackman27 re how to get this fixed / in the next upgrade handler?

**Comment by mattverse** [comment]
OC! @stackman27 reach me out if you have any questions on getting a fix out! Also please feel free to assign me as reviewer once PR is r4r

**Comment by stackman27** [comment]
sounds good, i'll let you know!

**Comment by ValarDragon** [comment]
Closing, will get into next upgrade :)
