### ISSUE TITLE
Need more seed nodes

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#426]
We've added seed nodes to init.go, and now need known validators to add their seed nodes directly to that file using a pull request.  Make sure to label your seed as yours.  

https://github.com/osmosis-labs/osmosis/blob/main/cmd/osmosisd/cmd/init.go

**Comment by faddat** [comment]
Kinda not maybe?

The thinking:

We should have validator engagement here on Github, as well.

Maybe I'm wrong about this and maybe we should close the issue, but the way that I'm looking at being a validator across a number of chains is that part of that task overall, is things like this.  

Actually have reached out over discord, too. 

Maybe I am over-expanding what we should think of validators as doing?

I look at the validator set like 100 engineering team members, each of whom bring unique skills to the table.  

https://commonwealth.im/osmosis/proposal/discussion/2036-proposal-per-validator-epoch-bonus-for-better-decentralization

Sort of tied into that.  

Does it make sense?

**Comment by faddat** [comment]
Hey, I'm going to add a node to the file, and will add a few others.  

The issue is this:

Infrastructure is dynamic.

**Comment by ValarDragon** [comment]
We've gotten some more seeds since the issue was made! I don't think this github issue is going to reach more people,  we can brainstorm more ways to get more seeds.
