### ISSUE TITLE
CPU griefing over p2p

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#4268]
## Background

The issue was discovered like this:

- because Larry sleeps near his validator and the fan kept him awake
- investigated by Jorge from Stargaze, who thought it was just a stargaze issue
- patched by Jorge from Stargaze
- seen on the Cosmos hub by Jorge from Stargaze
- discussed on twitter by Zdeadex from Stakelab, who was downtime-trolling Stakefish (deservedly, imo)
- Seen by Notional team members
- Long patched our Gaia validator and cpu usage immediately dropped
- Notional and Informal investigated, and in the end, the root cause was the sensors from Observatory.zone -- Clemens from Cryptocrew put us in touch with Rockaway, the makers of Observatory

All tendermint networks are likely effected.

## Suggested Design

Use github.com/informalsystems/tendermint v0.34.26

## Acceptance Criteria

Nodes should work without any functional difference whatsoever.  If the operator has been experiencing higher than normal cpu usage, they should see that drop. 

Closed by: 

* #4267

**Comment by ValarDragon** [comment]
Closing as details of this don't need to be in open github issues, beyond apply security update.
