### ISSUE TITLE
Blocks per second

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#427]
Osmo and Gaia are fat, and likely to get fatter fast.

One thing that's very noticeable is as chain state grows, sink speed goes up disproportionately. I propose to change the current block log flying past the screen to an error's only log as well as an indicator showing how many blocks per second are being synced which is refreshed every one or two seconds.

This is part of #413 -- the idea is to first, be able to measure the result of changes with ease instead of the current state of the art:

erm, it took x hours y minutes to get synced, felt faster than yesterday.

**Comment by faddat** [comment]
I think I know how to do this now

**Comment by faddat** [comment]
To make log output more useful, I've been working towards getting this implemented in tendermint itself:

https://github.com/tendermint/tendermint/pull/9764

@czarcas7ic & @vuong177 & @blockpane 

-- curious how you'd feel about a default tendermint log output like:

```
Block Height: 43545   | Inbound Peers: 200  | outbound peers: 200 | blocks per second: bps
```

**Comment by czarcas7ic** [comment]
When I first read this I thought you meant BPS of the live chain itself, not the syncing BPS. Tbh anything is better than what it is now, but yeah I think this would be nice to have (with priority on noise reduction, but things like sync bps speed would be cool!)

**Comment by faddat** [comment]
When I made the issue, I didn't know how to solve the issue :)

But, seems getting somewhere now.

**Comment by ValarDragon** [comment]
Closing due to us tracking this goal separately! Were actively workign towards speeding this up :)
