### ISSUE TITLE
[CL Incentives] Implement tick-level set and get functions for uptime trackers

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4275]
## Background

Each tick currently needs to track something analogous to `feeGrowthOutside` for uptimes. Similar to incentive records, we need to store these in state in a way that is easily accessible (e.g. `getAllUptimeTrackersForTick`) while also being easy to abstract into a different module in the future.

## Suggested Design

- Follow similar design to #4274

## Acceptance Criteria

- All new and existing tests should pass

**Comment by p0mvn** [comment]
Assuming this is now complete and not needed so closing
