### ISSUE TITLE
Randomize CL Functional Fee Test

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#4361]
## Background

See https://github.com/osmosis-labs/osmosis/pull/4282#discussion_r1109412778

## Suggested Design

We should make a separate testing function that randomizes the following values:

https://github.com/osmosis-labs/osmosis/blob/9cd236692a27225f65cd8f66adbdf5a96e014fa4/x/concentrated-liquidity/fees_test.go#L1036-L1042

The only constraint I see is that numAccounts must be one larger than the largest numPosition (so we have enough accounts created to initialize these positions).

**Comment by pysel** [comment]
hey @czarcas7ic. I do not really understand why numAccounts should be strictly one larger than max of `num<positionType>`? I understand why max of any position type cannot be greater than numAccounts, but are they not allowed to be equal?
