### ISSUE TITLE
chore: backport grpc replace in sdk fork to v14.x and v15.x

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4381]
## Background

We need to update the cosmos-sdk dependency with the following change:
https://github.com/osmosis-labs/cosmos-sdk/pull/417

## Suggested Design

- Merge it into `cosmos-sdk` `v13.x`
-  Merge it into `cosmos-sdk` `v15.x`
- Update `osmosis` `v14.x` `go.mod` to point to the tip of `cosmos-sdk` `v13.x`
- Update `osmosis` `v15.x` `go.mod` to point to the tip of `cosmos-sdk` `v15.x`
- patch release `v14.0.2`
- patch release `v15.x`

## Acceptance Criteria
- change released in `v14.x`
- change released in `v15.x`

**Comment by tac0turtle** [comment]
How can I help get this work done?

**Comment by p0mvn** [comment]
> How can I help get this work done?

Having PRs made against the desired fork branches and with CI passing would be super helpful. Once we have that, we can retag Osmosis right away

**Comment by tac0turtle** [comment]
made a branch to v15.x and will test on mainnet if it fixes our issue
