### ISSUE TITLE
[EPIC]: CosmWasm Pool Type

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/osmosis#4389]
## Background

`poolmanager` currently only supports Gamm and Concentrated Liquidity pool types, which limits flexibility for adding/upgrading pool types without chain upgrades. This proposal suggests integrating the CosmWasm pool type into the Osmosis `poolmanager` to address this limitation.

## Proposed Design

At high level, we need `cosmwasm-pool` module and adding `CosmWasm` to `poolmanager`'s `PoolType`

`cosmwasm-pool` expose `CreateCosmWasmPool` where `MsgCreateCosmWasmPool` contains

- `CodeId`: uint64
- `InstantiateMsg`: []byte

So that it can instanitate contract with `codeId` and `instantiateMsg` and store the contract address in the pool.

It requires implementation of `PoolI` and `SwapI` associated to `CosmWasm` pool type.

For `PoolI`, except from `GetAddress` `String`, `GetId` and `GetType`; the following methods are delegated to the contract queries with the following spec.

```go
// query msg:
// { "get_swap_fee": {} }
// response:
// { "swap_fee": <swap_fee:string> }
GetSwapFee(ctx sdk.Context) sdk.Dec

// query msg:
// { "get_exit_fee": {} }
// response:
// { "exit_fee": <exit_fee:string> }
GetExitFee(ctx sdk.Context) sdk.Dec

// query msg:
// { "is_active": {} }
// response:
// { "is_active": <is_active:boolean> }
IsActive(ctx sdk.Context) bool

// query msg:
// { "get_total_shares": {} }
// response:
// { "total_shares": <total_shares:number> }
GetTotalShares() sdk.Int

// query msg:
// { "get_total_pool_liquidity": {} }
// response:
// { "total_pool_liquidity": [{ "denom": <denom:string>, "amount": <amount:string> }>,..] }
GetTotalPoolLiquidity(ctx sdk.Context) sdk.Coins

// query msg:
// { "spot_price": { quote_asset_denom: <quote_asset_denom>, base_asset_denom: <base_asset_denom> } }
// response:
// { "spot_price": <spot_price:string> }
SpotPrice(ctx sdk.Context, quoteAssetDenom string, baseAssetDenom string) (sdk.Dec, error)
```

For `SwapI`, except for `InitializePool` that only will just set pool model in `KVStore` and `GetPool` that all the info is available on the module, the following methods are delegated to the contract sudos/queries with the following spec where response data refers to [this](https://sourcegraph.com/github.com/CosmWasm/wasmvm@825dceaacd28f72bb6cf622a164991c5dade125c/-/blob/types/msg.go?L26:2&popover=pinned).

```go
// sudo msg:
// {
//   "swap_exact_amount_in": {
//     "sender": <sender:string>,
//     "token_in": { "denom": <denom:string>, "amount": <amount:string> },
//     "token_out_denom": <token_out_denom:string>,
//     "token_out_min_amount": <token_out_min_amount:string>,
//     "swap_fee": <swap_fee:string>
//   }
// }
// response data:
// { "token_out_amount": <token_out_amount:string> }
SwapExactAmountIn(
  ctx sdk.Context,
  sender sdk.AccAddress,
  pool PoolI,
  tokenIn sdk.Coin,
  tokenOutDenom string,
  tokenOutMinAmount sdk.Int,
  swapFee sdk.Dec,
) (sdk.Int, error)

// query msg:
// {
//   "calc_out_given_in": {
//     "token_in": { "denom": <denom:string>, "amount": <amount:string> },
//     "token_out_denom": <token_out_denom:string>,
//     "swap_fee": <swap_fee:string>,
//   }
// }
// response data:
// { "token_out": { "denom": <denom:string>, "amount": <amount:string> } }
CalcOutAmtGivenIn(
  ctx sdk.Context,
  poolI PoolI,
  tokenIn sdk.Coin,
  tokenOutDenom string,
  swapFee sdk.Dec,
) (tokenOut sdk.Coin, err error)

// sudo msg:
// {
//   "swap_exact_amount_out": {
//     "sender": <sender:string>,
//     "token_in_denom": <token_in_denom:string>,
//     "token_in_max_amount": <token_in_max_amount:string>,
//     "token_out": { "denom": <denom:string>, "amount": <amount:string> },
//     "swap_fee": <swap_fee:string>
//   }
// }
// response data:
// { "token_in_amount": <token_in_amount:string> }
SwapExactAmountOut(
  ctx sdk.Context,
  sender sdk.AccAddress,
  pool PoolI,
  tokenInDenom string,
  tokenInMaxAmount sdk.Int,
  tokenOut sdk.Coin,
  swapFee sdk.Dec,
) (tokenInAmount sdk.Int, err error)

// query msg:
// {
//   "calc_in_given_out": {
//     "token_in_denom": <token_in_denom:string>,
//     "token_out": { "denom": <denom:string>, "amount": <amount:string> },
//     "swap_fee": <swap_fee:string>,
//   }
// }
// response data:
// { "token_in": { "denom": <denom:string>, "amount": <amount:string> } }
CalcInAmtGivenOut(
  ctx sdk.Context,
  poolI PoolI,
  tokenOut sdk.Coin,
  tokenInDenom string,
  swapFee sdk.Dec,
) (tokenIn sdk.Coin, err error)
```

## Tasks

```[tasklist]
### CosmWasm Pool Tasks
- [ ] #4765
- [ ] #4779
- [ ] https://github.com/osmosis-labs/osmosis/issues/5329
- [ ] https://github.com/osmosis-labs/osmosis/issues/5328
```

**Comment by ValarDragon** [comment]
Quick thoughts:
- We need to be careful about who is the instantiator of the contract. Importantly, it cannot be a module account that is reused for any other purpose.
- I think we should be careful to only allow contracts meeting the interface to be used. (E.g. imagine a contract that only implements join pool, but no exit) Some ideas for this:
  - Separately whitelist / maintain a registry for contracts that meet the interface
  - Permissionlessly "test" that a code ID satisfies an interface.

**Comment by iboss-ptk** [comment]
> We need to be careful about who is the instantiator of the contract. Importantly, it cannot be a module account that is reused for any other purpose.

I imagine `CreateCosmWasmPool` will also register the contract to get `poolmanager`'s msgs routed to, meaning, even though random person instantiate the contract, that contract will not be part of the active pool.

> I think we should be careful to only allow contracts meeting the interface to be used. (E.g. imagine a contract that only implements join pool, but no exit) Some ideas for this:
> - Separately whitelist / maintain a registry for contracts that meet the interface

Right. So it's like a 2-step gov process where we need to 1. store code and 2. register the code id as valid CosmWasm pool. But as `poolmanager` only have restriction on swap interface, do we want to define standard for join and exit interface for cosmwasm pool? or should we just leave it case by case for flexibility.

>  - Permissionlessly "test" that a code ID satisfies an interface.
Should be technically possible.

**Comment by p0mvn** [comment]
1. Are you proposing having this method on `PoolI`. I don't think it makes sense to have it for some pool types (e.g. concentrated liquidity) but if nothing else works, we can make this return "not implemented" error from CL or panic

```
// query msg:
// { "get_total_shares": {} }
// response:
// { "total_shares": <total_shares:number> }
GetTotalShares() sdk.Int
```

2. 
> I imagine CreateCosmWasmPool will also register the contract to get poolmanager's msgs routed to, meaning, even though random person instantiate the contract, that contract will not be part of the active pool.

I think that makes sense. If the contract is already instantiated, we fail pool creation, making it only successful if the `cosmwasm-pool` module account creates it

3.
> Should we store pool assets in contract account or module account? I think it's better to store in contract account so that managing pool assets is all done in contract if there is no any other concerns.

Storing them in the contract makes sense to me

**Comment by iboss-ptk** [comment]
@p0mvn The `GetTotalShares` was from a snapshot of PoolI at the point of that writing. Thanks for clarifying for the rest!

**Comment by p0mvn** [comment]
@iboss-ptk 

I would like to better understand how Go side `coswasmp-pool`'s interfaces and messages are going to translate into Cosmwasm pool implementations.

- What are the examples of some future CosmWasm pools that we are expecting other than transmuter?
   * Is `transmigrator` also going to be implemented as a pool type and plugged into this model?
- Are they all going to have the same interface? What are some common interfaces and where do they differ?
    - For example, I see that transmuter has `JoinPool` , `ExitPool` and `Transmute` execute message entrypoints.
        - In the context of transmuter, does `MsgSwapExactAmountIn` in `poolmanager` translate to `MsgExecute::Transmute`?
        - What does `poolmanager`'s `MsgSwapExactAmountOut` translate to?
        - For `JoinPool` and `ExitPool` do we need to create corresponding messages in the `coswasm-pool` Go module?

**Comment by p0mvn** [comment]
Also, would appreciate ideas on how to integration test this Go side if there are any

**Comment by p0mvn** [comment]
@iboss-ptk initial draft is ready here: https://github.com/osmosis-labs/osmosis/pull/4675

Please review

**Comment by iboss-ptk** [comment]
@p0mvn 

> * What are the examples of some future CosmWasm pools that we are expecting other than transmuter?
>   
>   * Is `transmigrator` also going to be implemented as a pool type and plugged into this model?

- I don't think `transmigrator` is a pool type, it doesn't have anything resemble pool by any means, only interacting with other pools.
- There is yet to have any other type of CosmWasm pool type in the pipeline.

> * Are they all going to have the same interface? What are some common interfaces and where do they differ?
>   * For example, I see that transmuter has `JoinPool` , `ExitPool` and `Transmute` execute message entrypoints.
>     
>     * In the context of transmuter, does `MsgSwapExactAmountIn` in `poolmanager` translate to `MsgExecute::Transmute`?
>     * What does `poolmanager`'s `MsgSwapExactAmountOut` translate to?

- both `MsgSwapExactAmountIn` & `MsgSwapExactAmountOut` can be transmute since it has no slippage

>    * For `JoinPool` and `ExitPool` do we need to create corresponding messages in the `coswasm-pool` Go module?
- My initial thought was to keep `PoolI` the way it is and establish other interfaces on cosmwasm side as needed.
- If there is any extension from `PoolI` needed, I think having either:
  - proxy execute/query contract and abstract away querying contract address and send execute/query directly, or
  - retrieving contract address
  would be required

**Comment by p0mvn** [comment]
@iboss-ptk ACK, thanks for the replies.

I have some more questions around `transmuter`. Will keep updating this message as questions come up. Please get back at your convenience.

- Seeing swap fee as [hard-coded to zero](https://github.com/osmosis-labs/transmuter/blob/ccb00121c83f2f1bedec2a47a920f68aa1eead0e/contracts/transmuter/src/contract.rs#L14). Is this final?
