### ISSUE TITLE
Write a changelog

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#440]
We need to start maintaining a changelog, so it becomes easier to track all the changes between software versions. Theres currently no way for an end user to see them all at a glance.

We should model the changelog off of the changelogs in the SDK & gaia imo.

**Comment by faddat** [comment]
All right well, if we're not digging into the past I can create the properly formatted document for that and make a pull request and if you don't like it you can just reject it :-)

**Comment by faddat** [comment]
I just noticed that this was assigned to you, do you want to handle it?

**Comment by ValarDragon** [comment]
Your welcome to handle it! I think its currently copying a changelog format from the SDK, but without the links to every issue/PR. (I can backfill it)

**Comment by faddat** [comment]
I see what you just merged, I think there's just a single small change needed, I'll make that now.

**Comment by faddat** [comment]
Done.  Reckon that this can now be closed, and maybe we add a thang to pull requests letting folks know to update the changelog.
