### ISSUE TITLE
[CL Incentives] Add check to only sync uptime accums when necessary

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4422]
## Background

We currently sync uptime accumulators before any operation that uses their values (e.g. tick init, tick crossing etc.). Since a single function is technically capable of triggering many of these updates, we are likely taking on redundant computation in the average case.

## Suggested Design

- Add a check for `LastLiquidityUpdate < ctx.Blocktime()` before all uses of `updateUptimeAccumulatorsToNow`

## Acceptance Criteria

- New and existing tests should pass

**Comment by p0mvn** [comment]
What if instead of having this function be executed in locations such as `getTickInfo` and `crossTick`, we move up this call higher in the execution flow. E.g. to `updatePosition` function or the swap-related functions?

Not sure if this is right but just another idea to explore - if having these tracked be updated is necessary for each block, maybe we have it in "begin block"?

**Comment by p0mvn** [comment]
ref: https://github.com/osmosis-labs/osmosis/pull/4399#discussion_r1117820456

**Comment by AlpinYukseloglu** [comment]
> What if instead of having this function be executed in locations such as getTickInfo and crossTick, we move up this call higher in the execution flow? E.g. to updatePosition function or the swap-related functions.

Perhaps a simpler approach would be to rename `getTickInfo` to `getOrInitTickInfo`, much like what we have in other parts of the CL package.

> Not sure if this is right but just another idea to explore - if updating these trackers is necessary for each block, maybe we have it in "begin block"?

We don't necessarily need to update every tracker for every tick each block. In fact, if a pool isn't touched for 1,000 blocks, the incentive accumulators should remain unchanged – this is by design! I think the approach suggested in the issue achieves the minimum number of calls possible all things considered.

**Comment by AlpinYukseloglu** [comment]
This was addressed in an earlier PR (we already skip accumulator updates [if no time has elapsed](https://github.com/osmosis-labs/osmosis/blob/e8a79d501ea58c97c7b256e41247a243a7df717b/x/concentrated-liquidity/incentives.go#L374-L377))
