### ISSUE TITLE
Full Powered Token Factory Integration tracking issue

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4444]
- https://github.com/osmosis-labs/osmosis/pull/4382
- https://github.com/osmosis-labs/osmosis/pull/4417
- https://github.com/osmosis-labs/cosmos-sdk/pull/421
- https://github.com/osmosis-labs/osmosis/pull/4590
- https://github.com/osmosis-labs/osmosis/issues/5043

**Comment by p0mvn** [comment]
@mattverse confirmed that we can

**Comment by p0mvn** [comment]
Reopened to track this unit testing is complete

**Comment by mattverse** [comment]
Added issue for tracking testing
