### ISSUE TITLE
build: update cosmos-proto to 1.0.0-beta2

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4447]
## Background

We should update the dependency: https://github.com/osmosis-labs/osmosis/pull/4431

However, there are concerns about state-breakage

## Suggested Design

We should try updating it in a patch release and check state-compatibility via state compatibility CI job

## Acceptance Criteria
- manual backport PR to v15.x
- confirm no state breakage
- merge the change to `main` only after confirming

**Comment by ValarDragon** [comment]
Done
