### ISSUE TITLE
[CL Incentives] Align accumulator abstractions between incentives and fees

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4453]
## Background

Fees and incentives currently share very similar patterns of logic that are implemented with different abstractions. This makes them more confusing to understand relative to each other and overall increases the surface area for bugs in our code. 

Although this is likely not release-blocking, we should align them to use similar abstractions for code hygiene.

## Suggested Design

- Implement `UptimeGrowthBelowTick` and `UptimeGrowthAboveTick` for incentives to abstract away the "flipping" logic of `UptimeGrowthOutside`, which is usually the primary source of confusion during reviews.

## Acceptance Criteria

- All new and existing tests pass.

**Comment by p0mvn** [comment]
Seems that this is complete
