### ISSUE TITLE
[CL Incentives][bugfix]: Replace all uses of `frozenUntil` with `joinTime` and `freezeDuration`

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4457]
## Background

We currently key positions by `lowerTick`, `upperTick`, and `frozenUntil`:
https://github.com/osmosis-labs/osmosis/blob/ccc07c3d1831e84dbbf35fb842ff3973f08e912f/x/concentrated-liquidity/types/keys.go#L71

This has the sideeffect of allowing users to add liquidity to existing positions by simply specifying the same tick range and `frozenUntil`. Since users would not be able to withdraw positions until their freeze period is over, this might seem like a feature, but it unfortunately allows for incentive gaming by allowing for users to put in dust amounts for the majority of the freeze duration and then pile in liquidity at the end, skipping the freeze altogether.

Even if we wanted to resolve this by making liquidity updates reset the freeze timer, we would still need more information in the position proto, as `frozenUntil` does not specify how long the intended freeze was. It's not clear, however, that even this is desirable UX.

I propose that we replace `frozenUntil` at the proto level and in the position key with `joinTime` and `freezeDuration`. This would push new positions to not be fungible with old ones, making it not possible to "update" an existing frozen position. I believe this lends itself to better UX than resetting the full freeze duration for all liquidity, even if the amount added is a dust amount.

If we are worried about saving space in state for positions that don't freeze (likely to be few to none after we implement #4456), then we can special-case the `joinTime` for positions with no freeze duration to make them fungible.

## Suggested Design
> Note: if alpo-cl-uptime-claim is not yet merged, a PR for this issue should branch off of that.

- Replace `frozenUntil` proto with `joinTime` and `freezeDuration`
- Tweak all uptime checks (currently `frozenUntil - ctx.BlockTime >= supportedUptime`) to use `freezeDuration` instead (e.g. `freezeDuration >= supportedUptime`)

## Acceptance Criteria

- All new and existing tests pass

**Comment by stackman27** [comment]
completed https://github.com/osmosis-labs/osmosis/pull/4468
