### ISSUE TITLE
Reduce the size of ``crosschain-swaps`` and ``outpost`` contracts

### ISSUE THREAD

**Issue by expertdicer** [osmosis-labs/osmosis#4458]
## Background

The current code of ``crosschain-swaps`` and ``outpost`` contracts use an import of ``swaprouter`` in cargo.toml, which causes the size of wasm bytecode of ``crosschain-swaps`` and ``outpost`` to increase heavily. Currently, the size of ``crosschain-swaps`` is more than 1mb, which is too large to store code on Osmosis testnet (osmo-test-4), makes the process of testing it impossible.

## Suggested Design

Remove the import of ``swaprouter`` in both ``crosschain-swaps`` and ``outpost`` contracts and write a new packages contains ``msg`` that all 3 contracts use.

Remove theses: 
https://github.com/osmosis-labs/osmosis/blob/ccc07c3d1831e84dbbf35fb842ff3973f08e912f/cosmwasm/contracts/crosschain-swaps/Cargo.toml#L62

https://github.com/osmosis-labs/osmosis/blob/ccc07c3d1831e84dbbf35fb842ff3973f08e912f/cosmwasm/contracts/outpost/Cargo.toml#L59

## Acceptance Criteria
- All new and existing tests pass

**Comment by nicolaslara** [comment]
Thanks for reporting this and for the exploration work! Closing this in favour of [#4494](https://github.com/osmosis-labs/osmosis/issues/4494) (since that lead to a larger reduction the the size of the bytecode)
