### ISSUE TITLE
x/lockup, restructure and reduce the lockrefs

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#447]
Currently x/lockups has many ways of iterating over locks / stores of references to a lock, and consequently repeated state. A lot of this is redundant / not needed imo, and should now be optimized out. (I think this will help alot with removing surplus code)

Here is the current list of references we store:

1. `{KeyPrefixLockTimestamp}{LockEndTime}`
2. `{KeyPrefixLockDuration}{Duration}`
3. `{KeyPrefixAccountLockTimestamp}{Owner}{LockEndTime}`
4. `{KeyPrefixAccountLockDuration}{Owner}{Duration}`
5. `{KeyPrefixDenomLockTimestamp}{Denom}{LockEndTime}`
6. `{KeyPrefixDenomLockDuration}{Denom}{Duration}`
7. `{KeyPrefixAccountDenomLockTimestamp}{Owner}{Denom}{LockEndTime}`
8. `{KeyPrefixAccountDenomLockDuration}{Owner}{Denom}{Duration}`

This means there are 8 separate sub-trees here. I don't think that subtrees `1-4` have any use case. All their use cases are taken over by `5-8`. I see no reason why we wouldn't just iterate over all denominations when we want all the denominations, using iterators.

I think we can also better combine the remaining lockrefs. I think we should store it as:
5. `{KeyPrefixLocksByDenom}/{Denom}/Bonded/{Duration}`
6. `{KeyPrefixLocksByDenom}/{Denom}/Unbonding/{EndTime}`
7. `{KeyPrefixLocksByAccount}/{Owner}/{Denom}/Bonded/{Duration}`
8. `{KeyPrefixLocksByAccount}/{Owner}/{Denom}/Unbonding/{EndTime}`

This enables better iterability over the lock references, and I think is generally clearer. Thoughts?

**Comment by antstalepresh** [comment]
Currently those do not have any use-cases yet - if we won't have use-cases for the top 4 in the future as well, we can remove those keys and add if needed in the future.

**Comment by mattverse** [comment]
One question I have is if we fix the key prefixes and refKeys, how would it affect existing stores?

**Comment by ValarDragon** [comment]
yes, changes to refkey structure require migration code

**Comment by ValarDragon** [comment]
I think we can close this issue tbh, and just deal with it all as part of refactoring for the ORM module once its ready
