### ISSUE TITLE
CLI: list environments

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4527]
## Background

Recently we merged a quality of life improvement: https://github.com/osmosis-labs/osmosis/pull/3787

Upon using it more today, I realized that it would be useful to have an additional command for listing all available environments.

## Suggested Design

Create a command `list-env` that functions similar to `get-env` but prints all available environments

## Acceptance Criteria
- new CLI added
- prints all environments

**Comment by p0mvn** [comment]
@hieuvubk @ThanhNhann folks, flagging this issue in case there is interest in picking it up

**Comment by czarcas7ic** [comment]
If picking up this issue, please reach out to @p0mvn if the context in this issue is not clear enough.

Side note, should add docs on how to properly utilize this somewhere.
