### ISSUE TITLE
Add a benchmark for gamm swap messages

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#454]
We should create a benchmark for how long an AMM trade takes on different pool weights. This would be done by creating a benchmark in https://github.com/osmosis-labs/osmosis/tree/main/x/gamm/keeper, that created a couple new pools, and then execute `b.N` trades against them, each trade of varying sizes.

We can then look at a profiler to see if theres anything we should do to speed things up & see how much it gets slowed down with our future feature work.

**Comment by faddat** [comment]
should this be run in CI, or something a dev should run manually and then post results on?

**Comment by ValarDragon** [comment]
Hrmm, great question. I think it should be done manually and get results posted on. What do you think?

My initial thinking is that I don't want it in CI since then we may risk getting overemphasis on performance, where really I think with exception to the epoch, most performance improvement points comes from places in the SDK / larger levers to be pulling. (Parallelization of signature verification for instance)

I think it'd be good to have a daily build that just runs benchmarks to see if there any regressions that day, just so things get flagged though! (And perhaps a manually triggerable workflow if we're ever sus)

Maybe we should run epoch benchmarks in the CI once epoch is fast enough for any commit that touches the relevant modules tho?

**Comment by RusAkh** [comment]
Hello @ValarDragon is this still needed?

**Comment by ValarDragon** [comment]
This should exist, but we need some more creativity around this. Going to close for now, the immediate demand is reduced thanks to mainnet syncs
