### ISSUE TITLE
refactor(CL): positions joint time and freeze duration from position value

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4545]
## Background

Currently, we have join time and freeze duration in both key and a value of a position in state.

As a result, they might go out of sync.

For example, notice [here](https://github.com/osmosis-labs/osmosis/blob/f8297548d8b39be599d076576a5da8fa5ae46063/x/concentrated-liquidity/position.go#L115-L126) that we set a position with join time and freeze duration given by parameters. However, `position` struct also contains such fields that are likely to diverge.

## Suggested Design

Remove `joinTime` and `freezeDuration` from `model.Position`

## Acceptance Criteria
- fields removed
- tests updated

**Comment by stackman27** [comment]
completed https://github.com/osmosis-labs/osmosis/pull/4552
