### ISSUE TITLE
[CL Migrations] Fix Position Initialization Issue upon migration

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4547]
## Background
Currently, migrating to a full range position requires at least one position to pre-exist in the pool or would else error. (Full range sets desired amounts to zero, while the initial position being set for the pool cannot be zero).

This is concerning since we are setting initial price from the amounts given from the user, but we don't update them after recalculation. 

## Acceptance Criteria
Problem statement mentioned above has been solved.

**Comment by czarcas7ic** [comment]
I actually don't see this problem existing. The migrate_test.go test case in both gamm and superfluid has no pre-existing positions but the migration is still successful. Can you explain the way you were able to get this error?

**Comment by mattverse** [comment]
Closing this issue after noticing that this issue was caused due to https://github.com/osmosis-labs/osmosis/issues/4539
