### ISSUE TITLE
Better document our process for profiling our code

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#456]
We should document the process for generally doing benchmarks & profiling. (probably in CONTRIBUTING.md?)

Currently in whatever folder I'm running benchmarks for, I'll do: 
```
go test -benchmem -bench DistributionLogicLarge -cpuprofile cpu.out -test.timeout 30m -v
```
(For the epoch code, this is in `x/incentives/keeper`)

Then once that is done, and I get the short benchmark results out, I do:
```
go tool pprof -http localhost:8080 cpu.out
```

and look at the graphviz output!

Note that if you are doing things that are low-level / small, the overhead of cpuprofile may mess with cache effects, etc. However for things like epoch code, or relatively large txs, this totally works!

**Comment by ValarDragon** [comment]
Another thing to document is the way to work with updating the cosmos sdk.

The way I do it is I'll commit & push to our cosmos-sdk fork in a new branch somewhere, and then I'll grab the commit hash. Then I do 
```
go get github.com/osmosis-labs/cosmos-sdk@{my commit hash}
```

I get a message like:
```
go get: github.com/osmosis-labs/cosmos-sdk@v0.33.2 updating to
	github.com/osmosis-labs/cosmos-sdk@v0.42.10-0.20210829064313-2c87644925da: parsing go.mod:
	module declares its path as: github.com/cosmos/cosmos-sdk
	        but was required as: github.com/osmosis-labs/cosmos-sdk
```

Then I copy paste the `v0.42.10-0.20210829064313-2c87644925da` bit, and I replace the corresponding section of `go.mod` here:https://github.com/osmosis-labs/osmosis/blob/main/go.mod#L34

The do `go mod vendor`, and your set.

**Comment by faddat** [comment]
This is so very useful. As we begin to approach that larger profiling task I will definitely be using these methods.
