### ISSUE TITLE
ci/e2e: generating upgrade handler on release tag does not work

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4576]
## Background

In [the following job](https://github.com/osmosis-labs/osmosis/actions/runs/4387875828/jobs/7683694866), CI skipped some steps necessary to auto-open a PR with a code-generated upgrade handler.

Upon running it manually, it worked here:
https://github.com/osmosis-labs/osmosis/actions/runs/4393249217

## Suggested Design

We need to make sure it runs when release is created

## Acceptance Criteria
- upgrade handler job runs when release is creaeted

**Comment by anhductn2001** [comment]
Can you check it @MasterPi-2124 ?
