### ISSUE TITLE
chore: Standardise and Maintain epochs module.

### ISSUE THREAD

**Issue by puneet2019** [osmosis-labs/osmosis#4612]
## Background
- [Move epochs module into its own go.mod - PR 4336](https://github.com/osmosis-labs/osmosis/pull/4336)  is merged to main .
- Now it can be used by just importing the module, Multiple teams have been forking epochs module to their repositories.
- the version that is merged tracks cosmos-sdk v0.45.x 
Now that it can be imported by teams it becomes important to maintain a tag corresponding to major versions of cosmos-sdk 

## Suggested Design
- Would like to see a version of x/epochs tagged
- And the make it compatible with v0.46.x, and tag another. 
- then same with v0.47.x

## Acceptance Criteria

- there should be a tag corresponding to cosmos-sdk v0.45.x for epochs.
- there should be a tag corresponding to cosmos-sdk v0.46.x for epochs.
- there should be a tag corresponding to cosmos-sdk v0.47.x for epochs.

**Comment by puneet2019** [comment]
@mattverse @p0mvn could you help with correct tags? and help with this issue?

**Comment by puneet2019** [comment]
Undertand, thank you for the reply! so to be clear, I can update x/epochs, and make PRs for v0.46.x, and v0.47.x?

**Comment by ValarDragon** [comment]
We are planning to now get this into the upstream SDK!
