### ISSUE TITLE
Swap fee tracking

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#462]
# How should swap fee be tracked

Clearly every LP wants to know how much they've earned in swap fees. Its time to plan & implement this!

(1) precisely & correctly define earnings in swap fees
(2) Figure out how to implement, and what belongs on-chain and what belongs off-chain

In principle, I think the definition should correspond to the intuition that "your swap fee rewards is the surplus in tokens your LP share currently corresponds to, relative to a hypothesized pool with 0 swap fee, but every Liquidity addition, removal, and swap was identically replayed against it".

But that intuition leaves a decent number of questions.
1) Do we imagine trades as still adding liquidity to the pool, but with no new LP shares minted?
2) Do we have them do no liquidity addtions, and the pool ends in different ratios
etc.

I think doing a simple example eliminates all of this. 

#### Example

Lets consider a 50-50 BTC<>ETH pool, near flippening where I LP 1 btc and 10 ETH. (So 1:10 ratio) A ton of trades & flippening happen, and I end up at 2.2BTC, 5.5 ETH. How much swap fee did I get? Well if we imagined my original assets moving along the curve to this new 2:5 ratio, I'd have 2 BTC, 5 ETH at 0 swap fee. So my swap fee rewards is the difference, `.2 BTC, .5 ETH`.

#### Generalizing to 50-50 pools

Great! Now how do we compute this in general for 50-50 pools? This is a bit straightforward. Suppose I put in (x_1, y_1) ad the current spot ratio of a:b. Then my positions 'uniswap constant' is `x_1 y_1 = k_1`. We can see directly how many assets is my LP share worth now. Lets call that `(x_t, y_t)`. The swap fee earned is what we get, when we subtract my initial assets at the new spot ratio `c:d`, according to uniswap curve, from the total assets I receive. So we first compute that with constant `k_1`, what assets would I have at the current spot ratio. Lets call these `x_2, y_2`, I'll spare the arithmetic derivation of them.

So then swap fee rewards are `(x_t - x_2, y_t - y_2)`. This answers swap fees for one liquidity add. Now the main question is how do we make this efficiently computable when I have many different add events.

#### Generalizing to multiple liquidity adds

Ideally, I should not have to loop over every liquidity add. 

I believe this is possible by when you add liquidity, by determining the 'initial assets, at current ratios under preserved `k` value' when you add new liquidity in, then adding to those asset amounts the amount of assets your newly LP'ing. Then you treat the `k` value you get after that process as the `k` to be constant under as your start point.

{TODO: Come back tomorrow and improve explanation of this section}

#### Tracking

Will brainstorm some more to see if theres some part of this that makes sense to track on-chain, but on initial impression this seems like something that should be completely tracked off-chain, as you have to maintain per-user records of when they LP. We don't want these going into the token itself, as we want the tokens to be fungible.

#### Non 50-50 pools

We need to ensure the general idea ^^ works out for non-50-50 pools. We can check out how Balancer / Loopring do this.

cc @UnityChaos @dogemos @sunnya97 @Thunnini @dillan @ibrar

**Comment by hieuvubk** [comment]
It's great. Is anyone on processing? I think using subgraph is a good solution

**Comment by ValarDragon** [comment]
This was done in other forms, e.g. https://hackmd.io/@osmosis/Hk1IK8UU3?type=view
