### ISSUE TITLE
fix(CL): avoid store key formatting with `fmt.Sprintf`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4626]
## Background

Using `fmt.Sprintf` to format storage keys may not be the best approach for several reasons:

- Performance: `fmt.Sprintf` is slower than other key formatting alternatives, such as using `strings.Builder` or simple string concatenation. When working with storage keys that require high performance, such as in databases or caching systems, using `fmt.Sprintf` may introduce unnecessary overhead.

- Readability: When formatting complex storage keys, using `fmt.Sprintf` can lead to less readable code due to the use of formatting specifiers. It might be harder to understand the final key structure, which can be problematic when debugging or maintaining the code.

- Error-prone: It's easy to make mistakes when using `fmt.Sprintf` with multiple formatting specifiers, such as providing the wrong data types or an incorrect number of arguments. This can result in subtle bugs that are difficult to identify and fix.

- Inefficient memory usage: `fmt.Sprintf` creates a new string object, which can lead to increased memory allocations and garbage collection pressure in performance-critical applications.

Instead, consider using alternative methods for formatting storage keys:

Simple string concatenation: If you are working with a small number of strings, using the + operator for concatenation is a more efficient and straightforward option:
```go
key := "user:" + userID + ":email"
```

strings.Builder: For more complex key structures or when concatenating a larger number of strings, using strings.Builder is an efficient and readable approach:
```go
var builder strings.Builder
builder.WriteString("user:")
builder.WriteString(userID)
builder.WriteString(":email")
key := builder.String()
```

By choosing a more suitable method for formatting storage keys, you can improve the performance, readability, and maintainability of your code.

## Suggested Design

Follow this format:
https://github.com/osmosis-labs/osmosis/blob/222d66bdf2dd8277cb81505e1a0120619619c8df/x/concentrated-liquidity/types/keys.go#L63-L65

To further improve the above, consider pre-allocating the byte buffer

## Acceptance Criteria
- key format in the concentrated liquidity module is refactored
- efficient approaches sed
- byte buffer pre-allocated

**Comment by p0mvn** [comment]
We also format addresses as bytes that have 2x amplification because `fmt.Sprintf` uses 2 characters for every byte, leading to 2 bytes for every byte in the original address.

**Comment by DongLieu** [comment]
can i handle it?
