### ISSUE TITLE
Python scripts for getting mutex data from pprof at epoch time

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#463]
Something that would help alot for debugging why Tendermint p2p disconnects at the epoch time per @tycoish is if we can get some output from pprof from a live node at the time. 

So a node needs to enable pprof by setting the `pprof_laddr = "{your IP}:6060"` in their config.toml

Then we should make a python script, which every say 15 seconds, starting a couple minutes before epoch (I'd guess roughly 5:10PM UTC), and ending several minutes after epoch (say 5:30PM UTC) should get debug information about the epoch, and log these to a file. 

The way I'd imagine this to be logged would be 1 folder per "python script tick", and each folder having a different file logging each of:
- osmosisd status (or at least block height & timestamp)
- curl/wget http://{your ip}:6060/debug/pprof/goroutine?debug=1
- curl/wget http://{your ip}:6060/debug/pprof/mutex?debug=1
- curl/wget http://{your ip}:6060/debug/pprof/block?debug=1

**Comment by czarcas7ic** [comment]
Would this still be valuable information? I can try playing with it in my free time if so.

**Comment by ValarDragon** [comment]
yeah this would still be really valuable!

Depending on how good pprof from the binary is, could also point the way for getting more node performance profile tooling

**Comment by ValarDragon** [comment]
The need for this is now solved
