### ISSUE TITLE
[CL]: Query Position's Underlying Assets

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#4632]
## Background

When querying a position, we only show that position's total liquidity. This number does not matter as much to the end user / integrators. We need to create a query that translates this liquidity value to the respective underlying asset0 and asset1.

## Suggested Design

TBD

## Acceptance Criteria

- Query shows amount of asset0 and asset1 a position is entitled to
- Query is has basic test cases added

**Comment by p0mvn** [comment]
I believe that the equations for that are the following:

![image](https://user-images.githubusercontent.com/34196718/225451324-fc78cc43-0335-4a7d-8c3a-5d82c11aadb8.png)
