### ISSUE TITLE
[CL] Refactor positions state to key by id

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4647]
## Background

Currently, we have the following structure of the position key:
https://github.com/osmosis-labs/osmosis/blob/c9a496ab0e0d374c3021d6ab6e9e7393e414b4fb/x/concentrated-liquidity/types/keys.go#L112-L116

We would like to switch to ID management and position keys in the state.

This will lead us to having additional store indexes for:
- `pool id -> position ids`
- `owner | pool id | lower tick | upper tick -> position ids`
- `position id  -> position struct`

This would address all of the following problems:
- Mars contracts needing to have position id to claim fees on behalf of users
- Having a single owner in key breaks this ability
- Queries 
   - for positions by user
   - for positions by pool id
   - Problem: having the current key structure does not allow us to have one or the other query as iteration depends on key order
- Future NFT contract becomes trivial to implement
    - With the current design, there is a problem in that when we transfer a position via an external NFT contract, internally on-chain we still have the position belonging to the original owner
- Remove freeze id as a parameter
    - This refactor will also simplify the ability to remove freeze id as a parameter

## Suggested Design

```[tasklist]
### Tasks
- [ ] #4648
- [ ] #4649
- [ ] #4650
- [ ] #4651
```

## Acceptance Criteria
- positions are keyed by IDs in state

**Comment by czarcas7ic** [comment]
All subtasks complete! Closing
