### ISSUE TITLE
Change environment feature does not respect custom home directory via --home flag

### ISSUE THREAD

**Issue by DavidNix** [osmosis-labs/osmosis#4654]
#### System information

Osmosis version: v15.0.0
OS & Version: Linux
Commit hash: ff18d82

#### Expected behavior

`osmosisd init --home custom` persists all files to the directory specified by the `--home` flag.

#### Actual behaviour

`osmosisd init --home custom` always creates a directory at `$HOME/.osmosisd` in addition to any custom directory via `--home` flag. This behavior cannot be customized or circumvented. 

The addition of [ChangeEnvironmentCmd()](https://github.dev/osmosis-labs/osmosis/blob/c9a496ab0e0d374c3021d6ab6e9e7393e414b4fb/cmd/osmosisd/cmd/change_environment.go#L21) related to https://github.com/osmosis-labs/osmosis/pull/3787 specifically the function [CreateEnvFile](https://github.dev/osmosis-labs/osmosis/blob/c9a496ab0e0d374c3021d6ab6e9e7393e414b4fb/cmd/osmosisd/cmd/init.go#L188-L223) in `InitCmd` appears to be the root cause. 

#### Steps to reproduce the behaviour

On your local machine using v15.0.0. 

1. `make build`
1.  `ls ~/.osmosisd` will error as expected because it does not exist yet.
1. `./build/osmosisd init --home custom moniker`
1. `ls -a ~/.osmosisd` was created and has `.env` file. This is unexpected.

## Context

As a node operator, saving data anywhere outside of `--home` is unexpected, inconsistent behavior. In other words, the current behavior breaks [the Principle of Least Surprise](http://principles-wiki.net/principles:principle_of_least_surprise). 

We always set `--home` to a consistent directory because of these advantages:
* We have a consistent place to look for files. Some chains do not follow a predictable pattern for the chain, binary, and home folder name. A consistent home folder allows us to more easily build automation for inspecting files, for example.
* We do not create a hidden (.dot) file so it's more easily discoverable. (i.e. Don't have to remember to always `ls -a`. )

This seeming innocent changed caused several hours of downtime for our Osmosis RPC deployment because:

```
Error: Failed to create environment file: mkdir /home/operator/.osmosisd: permission denied
```

We strive for strict security on all our deployments.

My proposal is to respect the `--home` flag and save this `.env` only in the designated home folder. Do not default to `$HOME/.osmosisd`. Notably, I do not have all the context around this feature. But my intuition is since the default home is `$HOME/.osmosisd` via simply `osmosisd init moniker`, then I would hope the feature still works despite the location of the home dir.

The PR's original goal was:

> To avoid the user having to add the --HOME flag to each cli cmd, configure the environment permanently by setting it via a separate CLI command.

I appreciate the goal. I'm betting this was explored, but a common pattern in cli apps is to accept a flag OR an environment variable.

Example:
```sh
# In my shell session
export COSMOS_CHAIN_HOME=custom
```

```go
home := "$HOME/.osmosisd"
if v := os.Getenv("COSMOS_CHAIN_HOME"); v != "" {
    home = v
}
cmd.Flags().String(cli.HomeFlag, home, "node's home directory")
```

Or you may be able to make use of [Viper's Env Var features](https://github.com/spf13/viper#working-with-environment-variables). 

To me, this feels like a nice feature for the SDK vs. Osmosis-specific. I agree, it is annoying to constantly set the `--home` flag.

**Comment by p0mvn** [comment]
Hey @DavidNix . Thanks for this issue.

Apologies for this breakage. We will look into this, aiming to support the original `--home` behavior and the new `set-env` in conjunction.

cc: @hieuvubk

**Comment by hieuvubk** [comment]
@p0mvn @DavidNix Could u pls check this [pr](https://github.com/osmosis-labs/osmosis/pull/4676). 
I think instead of ignoring `set-env` if there is a `home` flag. We can specify usage with a flag. We will only save the env variable if the `init-env` flag is used. If not, keep it as cosmos-sdk is doing.
Wdyt?

**Comment by DavidNix** [comment]
> @p0mvn @DavidNix Could u pls check this [pr](https://github.com/osmosis-labs/osmosis/pull/4676).
> I think instead of ignoring `set-env` if there is a `home` flag. We can specify usage with a flag. We will only save the env variable if the `init-env` flag is used. If not, keep it as cosmos-sdk is doing.
> Wdyt?

I appreciate the quick response!

That would solve the issue for us. But, it looks like a backwards breaking change. This won't affect us (I doubt we'll ever use the `set-env` feature). But for other users, they'll need to be aware of setting this new flag to true. 

Candidly, I'm not 100% clear on the value of the `set-env` feature and why it needs to be a .env file in a well known location versus, for example, letting the user set an env var.
