### ISSUE TITLE
fix: go mod auto-update to commit to custom branch when dependency module is updated

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4660]
## Background

In the following PR, I made changes to `osmoutils`:
https://github.com/osmosis-labs/osmosis/pull/4659

The autoupdate job ran successfully but did not make a commit to my branch:
https://github.com/osmosis-labs/osmosis/actions/runs/4452408410/jobs/7820019622?pr=4659

## Suggested Design

The CI should auto-commit to my branch when I change one of the dependency modules in the repository

## Acceptance Criteria
- auto-commits to custom branch

**Comment by p0mvn** [comment]
@pysel are you available to look into this please?

**Comment by p0mvn** [comment]
Also, noticed the following problem:

![image](https://user-images.githubusercontent.com/34196718/226152205-0f778d72-7579-4228-a307-4ce4621b1695.png)

When the bot commits, the CI is not run so you have to close the PR and reopen it. We should make sure that closing-reopening isn't necessary

**Comment by p0mvn** [comment]
Additionally, the bot seems to be comitting at the wrong time breaking the PR: 

[40986dd](https://github.com/osmosis-labs/osmosis/pull/4659/commits/40986ddaec8410d191509d128faf3fd5d673eaa5)

Relevant PR: https://github.com/osmosis-labs/osmosis/pull/4659

**Comment by pysel** [comment]
> Additionally, the bot seems to be comitting at the wrong time breaking the PR:
> 
> [40986dd](https://github.com/osmosis-labs/osmosis/pull/4659/commits/40986ddaec8410d191509d128faf3fd5d673eaa5)
> 
> Relevant PR: #4659

hey @p0mvn, could you please elaborate on this? I do not really get this

**Comment by p0mvn** [comment]
So I manually fixed `go.mod` in my PR #4659, and the bot committed over it with the wrong change. The commit that broke it is linked

The way I think it currently works is that when a commit to any branch is made within a repository, this workflow runs.

Therefore, when I merge a PR that contains `osmoutils` changes to `main`, this action will make a commit to all open PRs

This is not desired.

The goal of this workflow is to commit directly to your custom branch when you update `osmoutils` or any other dependency module.

See our discussion here: https://github.com/osmosis-labs/osmosis/pull/4666#discussion_r1141407194

**Comment by pysel** [comment]
yes, that makes sense. As I said, I checked that when pushing to your local branch, this workflow only runs on local branch. However, if that is indeed how it works when a PR is merged, I could simply remove the `main` branch from those, which should be triggering this action. I think, this will be ok, because afaik folks do not push directly to main, so go.mod will still be updated at some point while working on the local branch. 

CC: @p0mvn

**Comment by p0mvn** [comment]
> yes, that makes sense. As I said, I checked that when pushing to your local branch, this workflow only runs on a local branch. However, if that is indeed how it works when a PR is merged, I could simply remove the `main` branch from those, which should be triggering this action. I think, this will be ok, because afaik folks do not push directly to main, so go.mod will still be updated at some point while working on the local branch.
> 
> CC: @p0mvn

Yes, removing `main` SGTM
