### ISSUE TITLE
[CL] Change migrations code to osmoCLI

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#4672]
## Background

In https://github.com/osmosis-labs/osmosis/pull/4451, we have implemented client support for migration proposals for Gamm > CL pools. 

We have implemented it using existing CLIs, due to {unknown unknowns} that came up while implementing it uisng osmo CLI. 

Listed below were the blockers or questions I personally had whilst implementing this into osmoCLI. 

1. converting osmocli.TxCliDesc object to cobra.Command object? The [govClient Proposal handler](https://github.com/osmosis-labs/osmosis/blob/aad013223a/x/gamm/client/proposal_handler.go#L11) takes in cobra.Command, so we would still need a way to use cobra.Command object.
2.  Do flags get automatically mapped to fields? Ex) https://github.com/osmosis-labs/osmosis/blob/aad013223afcd934a7cd84fad24a1f1103a96b34/x/gamm/client/cli/flags.go#L125 Here we are setting a flag for deposit, and in the message field, we have a field named "Initial Deposit" How do we map the flag to the actual field value?

3. How do we manually set a field value for the message? In govtypes.MsgSubmitProposal, we have a field named IsExpedited, where previously we would just set the field to false and then broadcast the tx. How do we achieve the same goal using osmo cli?

## Suggested Design
Replace the migration code of cli to osmo cli. 

## Acceptance Criteria
Problem statement above has been resolved and migration code has been changed to use osmocli.

**Comment by hieuvubk** [comment]
Hey can I work with it

**Comment by ValarDragon** [comment]
Lets close this, I think if we want to do more CLI refactors, its probably worth considering upstream's tooling
