### ISSUE TITLE
Protorev Events Not Emitted In Logs

### ISSUE THREAD

**Issue by NotJeremyLiu** [osmosis-labs/osmosis#4692]
## Background

Currently, ProtoRev events only appear in tx.events and not in log events. This is because log events are appended to at the runMsg level, not the tx level (https://github.com/cosmos/cosmos-sdk/blob/v0.47.0-rc2/baseapp/baseapp.go#L806). 

## Suggested Design

Need to append to the log events in the posthandler.

## Acceptance Criteria

ProtoRev events are included in logs.

**Comment by ValarDragon** [comment]
We want to remove events from logs anyway
