### ISSUE TITLE
Trade module data source issue: ATOM->REGEN $dollar amount not equal to REGEN->ATOM 

### ISSUE THREAD

**Issue by petefarmer** [osmosis-labs/osmosis#470]
a word is worth a mili-picture:

<img width="517" alt="regen-atom" src="https://user-images.githubusercontent.com/4610821/132960734-a528b825-c9cd-44b1-9950-954b695e0121.png">

<img width="533" alt="atom-regen" src="https://user-images.githubusercontent.com/4610821/132960752-348a3fd2-0264-459d-9c76-c20e362adf3d.png">

**Comment by ValarDragon** [comment]
Was this fixed?

**Comment by petefarmer** [comment]
I presume so, but not sure. I based this on an observation on the day I
added the issue but it seems okay today.

AFAIK no patch was submitted, at least not by me.

Thanks for following up!
--p

**Comment by ValarDragon** [comment]
np! IIRC, this was a fix that was done on the data backend, just wasn't sure if it landed. If were not seeing it on the front-end, its presumably landed then
