### ISSUE TITLE
fix(e2e): rate limiting contract configuration settings

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4703]
## Background

In v15, we configured the rate limiting contract via upgrade handler.

Now, that we are performing the upgrade from v15 to v16 in #4575 , the v15 upgrade handler code is not going to run. As a result, we need to configure the contract in the genesis from an updated image

## Suggested Design

- create a PR to main where:
   -  [these configurations](https://github.com/osmosis-labs/osmosis/blob/29647afa778554e3ae013cbf2e15daf6a530b882/app/upgrades/v15/upgrades.go#L133-L215) are executed on the rate limiter contract
   - contract instantiation pre-upgrade is uncommented

## Acceptance Criteria
- rate limiter e2e test works
- e2e passes

**Comment by p0mvn** [comment]
In https://github.com/osmosis-labs/osmosis/pull/4575, had to disable the rate limiting param tests until the params are set via genesis overwrite.

Ref: https://github.com/osmosis-labs/osmosis/pull/4575/files#r1148441164

**Comment by nicolaslara** [comment]
To do this, we would need the rate limiting module to have access to a ContractKeeper with higher permissions (so it can instantiate the contract on genesis). This is easy enough to do, but expands the permissions of the module unnecessarily. 

Does it make more sense to just remove this test on e2e? I don't think we need it. If we want to test intearactions with RL, we can instantiate a new contract in the test and configure it specifically for that.

**Comment by p0mvn** [comment]
> Does it make more sense to just remove this test on e2e? I don't think we need it. If we want to test intearactions with RL, we can instantiate a new contract in the test and configure it specifically for that.

Thanks for looking into it. This makes sense to me
