### ISSUE TITLE
Possible mult-stake txn bug

### ISSUE THREAD

**Issue by cbrum11** [osmosis-labs/osmosis#472]
Over the last couple weeks I have experienced a behavior consistently that I believe is undesirable.  I can't say it has occurred every time I have tried these below actions, but at least > 90% of the time.

I am currently staking with 2 validators and also have some funds in 2 separate pools. Basically, everyday, I attempt the same 3 txns.  It does not seem to matter when I do these actions (near reward distribution time or even the day after).

1. Delegate the pool rewards to either Validator 1 or Validator 2
2. Delegate Validator 1 rewards to Validator 1
3. Delegate Validator 2 rewards to Validator 2

Sometimes txn 2 and 3 above are reversed.  However, without fail, the 3rd txn is never allowed because the pop-up after clicking "manage" always shows 0 (or near 0) Osmo available.  I have provided screenshots below for reference.  You can see that the Keplr wallet view has the same issue - also shows I still have staking rewards to claim but the available tokens spot are blank.  Maybe this is primarily a Keplr issue?

Additionally, I always use LOW for the gas and change the gas value to 600000 on every txn.

I have attempted the following - none of these steps have resolved the issue.
1. Cleared my Chrome cache
2. Completely exited out of Chrome
2. Logged out and back into Keplr

Please let me know if you need any more information - I would be happy to provide it.  Thanks for your hard work and for developing such exciting tech.  My family is benefiting financially from your dedication to a quality product - so I can't say thank you enough.

![image](https://user-images.githubusercontent.com/20428729/132961785-16463082-bff4-4e01-bc77-f8a95c2578c2.png)

![image](https://user-images.githubusercontent.com/20428729/132961789-94bcce7a-3925-4317-9800-94e2aad8e7e0.png)

![image](https://user-images.githubusercontent.com/20428729/132961847-5b8b1c95-3af1-4225-83dd-dd07fe20e7da.png)

**Comment by ValarDragon** [comment]
Is it possible that your claiming all rewards, and the delegating all the claimed rewards to your first validator?

**Comment by ValarDragon** [comment]
Closing for now, as the screenshots heavily suggest that is what is happening
