### ISSUE TITLE
[Routing] Add a registry to check if a chain allows forwarding

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#4731]
Epic: https://github.com/osmosis-labs/osmosis/issues/4344
Continuation of https://github.com/osmosis-labs/osmosis/pull/4694

## Background

We need to check that the chains in the path allow forwarding before sending the transaction to prevent packets from getting stuck in the middle

## Suggested Design

 * Add a new registry

## Acceptance Criteria

 * The registry exists and is tested
 * XCS checks this before sending the packets

**Comment by ValarDragon** [comment]
Is this easiest as a new column in the registry table, or as a gating condition for inclusion to the registry, and automatically checked by the contract. (Similar to how we were considering making contracts test that the counterparty is the same as Osmosis)

**Comment by nicolaslara** [comment]
I was thinking as a column, but only having channels we can route through be accepted might be a better idea 🤔
