### ISSUE TITLE
CL: canonical pool creation

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4757]
Context in: https://app.clickup.com/t/8677q2qb5

**Comment by p0mvn** [comment]
For this issue, we need to decide on initialization parameters, implement it in the upgrade handler and e2e test

**Comment by czarcas7ic** [comment]
I am going to take this issue, and implement this for the OSMO <> DAI pool with params that make sense to me. That way, all we will need to do is agree on final params and change them rather than wait on a final decision before implementing.
