### ISSUE TITLE
Filter a query by`height` doesn't works listing pools

### ISSUE THREAD

**Issue by RaulBernal** [osmosis-labs/osmosis#4795]
#### System information

Osmosis version: `Osmosis version`
v15.0.0
Linux
#### Expected behaviour
When I query the pools from command line filtering by height it works.

#### Actual behaviour
When I do the same querying the LCD it doesn't 

#### Steps to reproduce the behaviour
https://rest.cosmos.directory/osmosis/osmosis/gamm/v1beta1/pools?height=8710740
It should return 949 pools in place of "all" 957 (at the moment of writing this)

**Comment by ValarDragon** [comment]
Yikes, this was related to historic heights not getting passed into REST properly, this has since been fixed.
