### ISSUE TITLE
[CL] Implement reward splitting and Balancer migration

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4828]
## Background

Our current approach for incentives ignores Balancer pools and assumes that every LP will immediately have to migrate to continue earning incentives. While we eventually want everyone to migrate, this makes for odd UX, especially since we will not immediately have superfluid rewards ready for CL at launch. Specifically, the primary issues posed by the current setup are as follows:
1. Rush for LPs to migrate (bad UX and risks breaking dependent contracts/vaults)
2. Mass unlock for superfluid staked OSMO
3. LPs can mass-exit by migrating and leaving (since we removed freezing)
4. LPs are forced to choose between superfluid incentives and chain incentives

## Suggested Design

There are a number of approaches to addressing these issues, but for many reasons we have internally converged on making the following key changes:

#### Required

- #4836
  - #4837
- #4840 
- #4839

#### Optional

- #4841

## Acceptance Criteria

- All of the functionality above is implemented and thoroughly tested

**Comment by ThanhNhann** [comment]
Hey @p0mvn, is this the issue we have discussed?

**Comment by p0mvn** [comment]
We can close this now, as major work is complete and minor issues are tracked separately
