### ISSUE TITLE
[Incentives] Refactor createGauge to accomodate for CL gauges

### ISSUE THREAD

**Issue by stackman27** [osmosis-labs/osmosis#4833]
## Background
After merging https://github.com/osmosis-labs/osmosis/pull/4526,  we pass in dummy variables to `lockuptypes.QueryCondition{}` for CL gauges to pass createGauge function. While we do not use any `lockuptypes.QueryCondition{}` parameters we pass the values so that we do not have to modify the lower level createGauge function 

## Suggested Design
There are couple of ways of fixing this; 
1. modify createGauge to accomodate different type of pool Gauges, this will be modifying the queryCondition check in the `createGauge` function
2. allow `lockuptypes.QueryCondition{}` to be empty in `createGauge` function

## Acceptance Criteria
- new tests as well as old tests should pass

> Goals & criteria for success
> e.g.
> - all existing and new tests should pass

**Comment by hieuvubk** [comment]
Is this issue still available, I see we have `CreateConcentratedLiquidityPoolGauge` for CL gauge.
But looks like we're over checking this condition:
https://github.com/osmosis-labs/osmosis/blob/main/x/pool-incentives/keeper/keeper.go#L98-L101

**Comment by stackman27** [comment]
so this issues a suggestion to change this QueryCondition https://github.com/osmosis-labs/osmosis/blob/main/x/pool-incentives/keeper/keeper.go#L111

right now its 
```
	lockuptypes.QueryCondition{
			LockQueryType: lockuptypes.ByTime,
			Denom:         sdk.DefaultBondDenom,
	},
```

which essentially is pretty useless, it was added so that we can skip this logic check (https://github.com/osmosis-labs/osmosis/blob/main/x/incentives/keeper/gauge.go#L100) because we donot really care about the lockup type for CL incentive gauges

**Comment by hieuvubk** [comment]
Make sense to me

**Comment by ValarDragon** [comment]
I believe this was handled in some of Alpins recent work
