### ISSUE TITLE
[CL]: Redirect balancer incentives to the canonical CL pool

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#4839]
## Background

Once #4836 is merged, all incentives for the balancer pool should be removed and all the rewards should instead go to the canonical CL pool. This is because, behind the scenes, rewards going to CL get rerouted to the balancer equivalent gauge.

## Suggested Design

- Add a change in the upgrade handler to remove the balancer pool incentive and add that incentive to the CL equivalent pool

## Acceptance Criteria

- Tests exist that show the removal and addition of this incentive record behaves as intended.

**Comment by p0mvn** [comment]
Discussed more context for this:
- create a CL pool
- create a link balancer <> CL pool (store link in x/gamm migration records)
- handed gauge updates
  * get balancer's gauges
  * get CL gauges
  *     -> redirect balancer emission's rate to CL gauges
- do not delete old balancer gauges and keep them in-state (discount rate CL emissions logic will update them separately)
