### ISSUE TITLE
initGenesis now working on main

### ISSUE THREAD

**Issue by niccoloraspa** [osmosis-labs/osmosis#4858]
#### System information

Osmosis version: `osmosisd built from `f0db307cf17aeba513dbdf5a699c0159e2e30a71`
 
OS & Version: Linux

Commit hash:  `f0db307cf17aeba513dbdf5a699c0159e2e30a71` 

#### Error

When starting a localnet from a testnetified state-export, I get the following error:

```bash
8:31AM INF running initialization for module module=poolmanager
panic: unknown field "pool_routes" in types.GenesisState

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc001199eb8?, {0xc001032000?, 0x4d4c65?, 0xc0000bc120?}, {0x2eabe60?, 0xc15c31d6a0?})
        github.com/cosmos/cosmos-sdk@v0.46.9/codec/proto_codec.go:176 +0x45
github.com/osmosis-labs/osmosis/v14/x/poolmanager/module.AppModule.InitGenesis({{}, {{0x2e98df8, 0xc000280fa0}, {0x2ebda60, 0xc001820c30}, {0x0, 0x0}, {0x2e91aa0, 0xc000016540}, {0x2e98fb0, ...}, ...}, ...}, ...)
```

Full log: https://pastebin.com/raw/BVp0L8ix

**Comment by p0mvn** [comment]
Discussed offline and agreed on approaches to further debug this.

Init genesis should be working on main as this CI is passing: https://github.com/osmosis-labs/osmosis/actions/workflows/test-e2e-makefile.yml

Going to close this for now. Please let me know if issue persists
