### ISSUE TITLE
[CL][Incentives][tests] Invariant testing for CL incentives

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4863]
## Background

CL incentives have pretty strong unit tests but are missing end to end invariant tests to ensure that they never put the system in unintended states.

## Suggested Design

Invariant tests for the following (and any more that come up while testing):
- X tokens are used to create incentive records, which emit fully until cleared -> all incentives are claimed. Total tokens gone to claimers should be exactly X (minus rounding)

## Acceptance Criteria

- All new and existing tests pass

**Comment by p0mvn** [comment]
@AlpinYukseloglu can you please add more context on the invariants that need to be tested here?

**Comment by AlpinYukseloglu** [comment]
#5093 added the class of tests I had in mind when creating this issue.
