### ISSUE TITLE
Remove wasmEnabledProposals []wasm.ProposalType from NewOsmosisApp

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#4865]
## Background

NewOsmosisApp has too many args. Currently there is an arugment for altering the wasm enabled proposals.

This is as far as I can tell useless, and should be removed. App.go should hardcode this list (which is derived from calling the function)

This should just be a simple deletion of the arg, corresponding calls to it.

**Comment by tungbq** [comment]
Can I pick up this task?
