### ISSUE TITLE
refactor: integrate protorev into concentrated liquidity

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4873]
## Background

Currently, protorev only supports gamm pools. We should add support for CL pools by routing all the logic via the `x/poolmanager` module

## Acceptance Criteria
- protorev refactored to utilize APIs from `x/poolmanager`

**Comment by NotJeremyLiu** [comment]
I think protorev already supports this out of the box (would need to add tests though)

**Comment by NotJeremyLiu** [comment]
We use poolmanager for our trades: https://github.com/osmosis-labs/osmosis/blob/4c4114a4e7e6694610c0177ee24f2a4526effd09/x/protorev/keeper/rebalance.go#L200

**Comment by p0mvn** [comment]
What we need to make sure is that all of these methods are called on the poolmanager keeper instead of gamm:
https://github.com/osmosis-labs/osmosis/blob/d0b2ef69c14cc06bb90c2d8221a499224bbe3285/x/protorev/types/expected_keepers.go#L27-L32

Otherwise, concentrated liquidity cannot be supported because CL pools exist in a separate module. Pool manager acts like a router that propages calls either to `x/gamm` or `x/concentrated-liquidity`.
