### ISSUE TITLE
[CL] Implement `AddToPosition` for non-superfluid positions

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4914]
## Background

Since we've decided to table charging for our MVP for the sake of position fungibility, we need to implement a separate `AddToPosition` function and message that captures the fungibility-related behavior we need without requiring us to do an API break if we re-introduce charging and, secondarily, not hurting contract UX.

## Suggested Design

- The simplest way to achieve this is likely to have `AddToPosition` delete the old position and then create a new one with the combined amounts. This approach also happens to be safe with the charging paradigm and thus minimizes risk of API breaks in the future. It also lets us avoid having to deal with uptime/charge of exactly zero, as 1 nanosecond is sufficient for these purposes

## Acceptance Criteria

- All new and existing tests pass

**Comment by p0mvn** [comment]
My impression was that for removing charging we concluded  on a different direction. Followed up with @AlpinYukseloglu to update on the latest.

Going to treat this issue as a general "Removing charging from CL" for now
