### ISSUE TITLE
[CL][Incentives]: Modify logic for getting lockup durations to be guaranteed to get longest duration

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4916]
## Background

Our current implementation of reward splitting assumes that the longest lockup duration is the last one in the array of durations placed in state. While this is currently true, it is technically possible for this to be updated such that the last duration is not the longest, since we are not guaranteed that the list is sorted.

## Suggested Design

- Instead of changing lockup set logic (which would risk breaking other parts of the codebase), we should simply add a `GetLongestLockupDuration` function that gets the lockup durations from state, iterates over them, and returns the longest one. This should likely live in the incentives module and be called 

## Acceptance Criteria

- All new and existing tests pass

**Comment by mattverse** [comment]
@AlpinYukseloglu Can you provide detail line in code for 

> Our current implementation of reward splitting assumes that the longest lockup duration is the last one in the array of durations placed in state.
