### ISSUE TITLE
Upgrading to Tendermint 0.34.13: apphash doom

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#492]
I triggered an apphash error by upgrading to 0.34.13

Possibly a tendermint issue. 

```
@@ -17,7 +17,7 @@ require (
        github.com/spf13/cobra v1.1.3
        github.com/spf13/pflag v1.0.5
        github.com/stretchr/testify v1.7.0
-       github.com/tendermint/tendermint v0.34.12
+       github.com/tendermint/tendermint v0.34.13
        github.com/tendermint/tm-db v0.6.4
        google.golang.org/genproto v0.0.0-20210114201628-6edceaf6022f
        google.golang.org/grpc v1.37.0
@@ -29,7 +29,7 @@ replace google.golang.org/grpc => google.golang.org/grpc v1.33.2

 replace github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.2-alpha.regen.4

-replace github.com/tendermint/tendermint => github.com/tendermint/tendermint v0.34.12
+replace github.com/tendermint/tendermint => github.com/tendermint/tendermint v0.34.13

 replace github.com/cosmos/cosmos-sdk => github.com/osmosis-labs/cosmos-sdk v0.42.10-0.20210915013958-01114e89a579
 ```

leads to

```
12:49PM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:49PM INF Starting localClient service connection=query impl=localClient module=abci-client
12:49PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:49PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:49PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:49PM INF Starting EventBus service impl=EventBus module=events
12:49PM INF Starting PubSub service impl=PubSub module=pubsub
12:49PM INF Starting IndexerService service impl=IndexerService module=txindex
12:49PM INF ABCI Handshake App Info hash="3]�|9���_P��/I��o1�)�y-�\x19U��]�;�" height=1419667 module=consensus protocol-version=0 software-version=
12:49PM INF ABCI Replay Blocks appHeight=1419667 module=consensus stateHeight=1419667 storeHeight=1419668
12:49PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 335DE87C39FDCDDE5F50FFF92F49F6F76F31EC29D8792DD21955B7B55DFD3B88, got C5F9899FC058F0F494B9826D5E351C4977309F2A7A40DF4E871A1CA3C36BE1F8
```

9:01PM INF executed block height=1424275 module=state num_invalid_txs=0 num_valid_txs=6
9:01PM INF commit synced commit=436F6D6D697449447B5B3139392032322031363920313538203934203130322038342031332036332038372030203938203137322032313220323620313431203134312032313420383420323020363320313831203230372039332034382034392034332036203235342039342033392034325D3A3135424239337D
9:01PM INF committed state app_hash=C716A99E5E66540D3F570062ACD41A8D8DD654143FB5CF5D30312B06FE5E272A height=1424275 module=state num_txs=6
9:01PM INF indexed block height=1424275 module=txindex
panic: Failed to process committed block (1424276:0A3736F8C7FEACDFE24002EF270C7ACCA4B470F99C760BDC924297A3C51D2BD4): wrong Block.Header.AppHash.  Expected C716A99E5E66540D3F570062ACD41A8D8DD654143FB5CF5D30312B06FE5E272A, got 8006A8A86A4CB9E843A9CD0BE71C70BF6B87D8D01BC3A058EFCC6C68EDC05728

goroutine 131 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0098d6380, 0x0)
        github.com/tendermint/tendermint@v0.34.13/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.13/blockchain/v0/reactor.go:110 +0x85
[root@archive osmo1]# exit
exit

**Comment by ValarDragon** [comment]
This hasn't only happened once more since we deployed tendermint `v0.34.14`, and has been running fine. Closing for now.
