### ISSUE TITLE
test: maneuver tick spacing once created

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4938]
## Background

We have concluded to launch with exponent at price one of -6 and tick spacing of 100.

The idea is to potentially decrease tick spacing in the future for some pools to 10 or 1 for greater tick granularity for limit orders

## Suggested Design

We must have a test confirming that upon decreasing the tick spacing on an existing pool, the pool does not break and can be swapped against.

## Acceptance Criteria
- add Go test confirming this
   * create CL pool with tick spacing of 100
   * add positions
   * maneuver tick spacing to 10 and confirm that still able to swap
   * maneuver tick spaing to 1 and confirm that still able to swap
   * reason about how this works for fees and incentive collection

**Comment by czarcas7ic** [comment]
Realized I need to split this up into two parts:
1. Create a gov method for updating tick spacing
2. Then add functional test the primary issue described.

Working on part one now.
