### ISSUE TITLE
fix: bug with liquidity net in direction query

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4939]
## Background

![image](https://user-images.githubusercontent.com/34196718/232377533-232090f3-ebd8-4e59-9b4a-673aeac3bac1.png)

https://osmosis-network.slack.com/files/U02UCH04W8J/F0531V32JJK/jon_osmosisd-local3.zip

cc: @jonator 

## Acceptance Criteria
- investigate and fix the bug

**Comment by jonator** [comment]
* It seems the same [query](http://localhost:1317/osmosis/concentratedliquidity/v1beta1/query_liquidity_net_in_direction?pool_id=1&token_in=uosmo&use_cur_tick=true&use_no_bound=true) in the other direction with many more ticks has no issues. Perhaps it's the case with a single tick in the requested direction?
