### ISSUE TITLE
ProtoRev: Event / Query Patch Tracking

### ISSUE THREAD

**Issue by NotJeremyLiu** [osmosis-labs/osmosis#4942]
## Background

This issue is to track changes to ProtoRev to be introduced in a non-state breaking patch.

These changes add transparency into the module by emitting events upon successful protorev backruns and adds a query to query the highest liquidity pools stored.

## Acceptance Criteria

Review / Merge PRs:

- [x] https://github.com/osmosis-labs/osmosis/pull/4829
- [x] https://github.com/osmosis-labs/osmosis/pull/4878

**Comment by p0mvn** [comment]
`v15.1.0` is now releasesd with these changes included
