### ISSUE TITLE
CLI:  Add gas config to the client.toml config file 

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#4962]
## Background

Many CLI txs require custom gas configs. This is annoying to write every time and leads to long commands. We can add a config for this in client.toml specifying the default if they are not set

## Suggested Design

Base it on https://github.com/CosmosContracts/juno/pull/601

## Acceptance Criteria

Txs on the CLI don't require `--gas auto --gas-prices 0.1uosmo --gas-adjustment 1.3` as those can be directly picked up from the config

**Comment by hieuvubk** [comment]
Is anyone working on this?

**Comment by nicolaslara** [comment]
no, just added it yesterday when I was sick of copy pasting the gas params :p
