### ISSUE TITLE
[CL]: round up or down priceToTick

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#4979]
## Background

We recently hardcoded the exponentAtPriceOne parameter as -6 and expect pools to generally use a tick spacing of 100. After doing this, we realized that priceToTick needs to take into consideration tick spacing in order to return a tick that is initializable for the pool. With this being said, their may be time when the tick returned should be round up or down to ensure the resulting value is in favor of the protocol to prevent harmful bugs.

## Suggested Design

One option is to add a boolean of roundUp to PriceToTick. Then, determine in all locations this is called if it should be rounding up or down to ensure the number does not return more funds to the user than expected.

## Acceptance Criteria

TBD

**Comment by p0mvn** [comment]
Realized that https://github.com/osmosis-labs/osmosis/pull/4998 doesn't fully address this issue, will look into this more here
