### ISSUE TITLE
devux(localosmosis): output a warning if the localosmosis image does not match current git commit hash

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4995]
## Background

The localosmosis image is not auto-rebuilt when user pulls from `main`.

This sometimes causes problems that are unintuitive to debug

## Suggested Design

When user runs any localosmosis Makefile command, there should be a check whether an image is up-to-date. If not, a warning is printed.

## Acceptance Criteria
- generalize and modify t[his script](https://github.com/osmosis-labs/osmosis/blob/main/tests/e2e/scripts/run/check_image_sha.sh) to be able to use it with both e2e and localosmosis
- check whether an image is up-to-date whenever any localosmosis command is run using the script above
- output a warning to stdout, if an image is out of date

**Comment by deividaspetraitis** [comment]
Hey @p0mvn, @ValarDragon is this still relevant? I would be happy to give a try to work on this issue.

**Comment by p0mvn** [comment]
Hey @deividaspetraitis . Thank you!

The localosmosis tool hasn't been used extensively by the team in recent times. As a result, we will no longer maintain it.
