### ISSUE TITLE
x/GAMM: Create a function to refund all LP shares for a pool

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#502]
We should create a function in `x/gamm` that takes in a pool ID, and then dissolves that pool, and refunds the LP shares back into the constituent assets, and distributes to all holders. This would eventually become something callable in upgrades or governance, to dissolve pools with less than $X liquidity. (See https://gov.osmosis.zone/proposal/discussion/2047-proposal-raise-the-pool-creation-fee-and-refund-pools-with-less-than-1000-tvl/ for discussion from Osmosis community on why this is quite desirable!)

This would be done by iterating over all accounts looking for folks who hold that pools LP shares. If you hold that pools shares, then it burns those shares, and then gives you the constituent tokens back.

It then destroys the pool. 

If there are any LP shares IBC'd out of Osmosis, I think those should for now just be 'stuck', as a v1 of this feature. We can make a way to redeem them back subsequently.

**Comment by daniel-farina** [comment]
Will be closed by #652
