### ISSUE TITLE
[CL][Internal Review][fungifyChargedPosition][validatePositionsAndGetTotalLiquidity]: fully charged duration is assumed to be the largest one in SupportedUptime in tests

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5039]
## Background

Similar to #5038, there is an incorrect assumption in tests about largest supported uptime being the one to be fully charged

## Suggested Design

We should analyze the uses of this variable and confirm that there is no broken logic similar to #5038 
Additionally, we should remove this assumption that fully charged duration is the last one in supported uptimes. Instead, we should modify the tests to reconfigure the authorized params and make the fully charged position be inferred from params

## Acceptance Criteria
- investigate all uses in tests
- refactor tests to infer the fully charged duration from params instead of grabbing the last one from supported uptimes
- fix any test cases that break
- confirm that there is no misuse of this in message flow being tested

**Comment by AlpinYukseloglu** [comment]
Pushed a cleanup PR, but for the remaining acceptance criteria, I was unable to find any more references to "fully charged" in tests. Minor related fixes around longest lockable duration fetching are in the PR.
