### ISSUE TITLE
Fix make proto-gen when you have a vendor folder

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#504]
`make proto-gen` fails if you use a `vendor` folder. @robert-zaremba pointed out in https://github.com/osmosis-labs/osmosis/pull/496#issuecomment-934709990 that the proto script searches for all `.proto` files and attempts to compile them. This is done in this line https://github.com/osmosis-labs/osmosis/blob/main/scripts/protocgen.sh#L12

When I tried to add a `--prune "*/vendor/*"` or `-not -path "*/vendor/*"` as an argument to that find command, the problem still persisted. Namely I get:
```
make proto-gen
Generating Protobuf files
/third_party/proto: does not exist
make: *** [proto-gen] Error 1
```

Not sure how we fix this. (Its possible I did the ignoring wrong!)

When fixed, we should upstream to the SDK.

**Comment by robert-zaremba** [comment]
In fact, the find command searches only in the `./proto` director (and it's subdirectories):

    find ./proto -path -prune -o -name '*.proto' -print0

The issues sounds like something is importing `/third_party/proto` but can't find it.
