### ISSUE TITLE
[CL][Internal Review][getNextPositionIdAndIncrement]: unit test

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5040]
## Background

`getNextPositionIdAndIncrement` is missing unit tests

## Acceptance Criteria
- unit test added

**Comment by pysel** [comment]
hey @p0mvn. I want to have more context on this. Doesn't a unit test[ already exist](https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/position_test.go#L375)?

**Comment by p0mvn** [comment]
Awesome, thanks
