### ISSUE TITLE
test: Test full powered token factory in node environment

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#5043]
## Background

Full powered token factory has been finished full implementation along with unit tests, but it has not yet been tested on an actual node.

## Acceptance Criteria
- Ensure that all logical flows of token factory have been tested
   - This includes bank hooks being properly triggered
 - According msgs and queries that have been used in the process have been attached

**Comment by p0mvn** [comment]
This seems outdated. If this needs testing, new issue should be made
