### ISSUE TITLE
[Internal Review][CL][TestInitOrUpdateFeeAccumulatorPosition] validate specific errors

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5046]
## Background

This test needs to check specific errors

## Acceptance Criteria
- errors checked

**Comment by p0mvn** [comment]
CC: @czarcas7ic since you're working on collect fees

**Comment by czarcas7ic** [comment]
@p0mvn do you want me to assign it to myself? Just checking since you self assigned

**Comment by p0mvn** [comment]
I've already completed it. Just signaling so that we don't overlap by accident
