### ISSUE TITLE
[Internal Review][CL][TestInitOrUpdatePositionUptimeAccumulators] add error test cases

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5047]
## Background

This test is missing error test case. Most of them are happy path

## Suggested Design

Add error tests

## Acceptance Criteria
- error tests added
- all pass

**Comment by stackman27** [comment]
wonder what else there is to test at this layer of function 
`NonPositiveLiquidityForNewPositionError` is the only function specific error here. rest is tested well on their respective function
