### ISSUE TITLE
[CL]: incentives individual accum positions not exporting / importing

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#5049]
## Background

[See the following commit](https://github.com/osmosis-labs/osmosis/pull/5024/commits/8e01a2634132b3105ad47b3d3188d82382d9a4c4). This fixed an issue where we did not import and export individual position's fee accum values. This exact fix will likely need to be done for the incentive accumulator positions as well.

CC @stackman27 since you are auditing that section of the code.

## Suggested Design

Look over above commit. Implement for incentives import export genesis logic.

## Acceptance Criteria

TBD

**Comment by p0mvn** [comment]
Is this internal review related?

**Comment by p0mvn** [comment]
Is this complete?
