### ISSUE TITLE
[Internal Review][CL][fungifyChargedPosition] add functional test fungifying in-between swaps 

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5051]
## Background

Currently, we don't have test cases that attempt to fungify positions in-between swaps

## Suggested Design

We should add these test cases as at least one bug was uncovered in incentives and fees claiming stemming from using the wrong accumulator when adding to position accumulator rewards

## Acceptance Criteria
- add test where incentives were and were not distributed due to the current tick being inside or outside of the position's range
- add test where fungifying happens after a swap occurred below, in-between and above position's ticks
- ensure that incentives and fee claiming still functions as expected

**Comment by AlpinYukseloglu** [comment]
The first point is now thoroughly tested throughout `incentives_test.go`. Will work on the second once we get fee rename changes in (#5268)
