### ISSUE TITLE
[CL][Internal Review][`createPosition`, `withdrawPosition`] Invariant testing for position creation and withdrawal

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#5053]
## Background

Adding tighter bounds to #5026 required removing a number of invariant tests that covered proper rounding behavior when closing down and reopening a position. We should add these back in as a separate test to ensure that this behavior is well-tested.

## Suggested Design

- Test expected behavior around withdrawing a full position then recreating an identical one

## Acceptance Criteria

- All new and existing tests pass

**Comment by p0mvn** [comment]
@AlpinYukseloglu is this still valid? Can you take this on please in this sprint?

**Comment by AlpinYukseloglu** [comment]
This issue was addressed since the problems that caused it were fixed & the mentioned PR was updated to never remove the required tests
