### ISSUE TITLE
check all errors

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#5060]
To make the upgrade easier, we usually begin by linting.  It seems to me that:

* we should disable paralleltest 
* we should disable testpackage
* we should lint the tests so they benefit from formatting & checks for double imports
* we should use thelper so that we can get the maximum amount of information from test failures
* we should check errors in tests

**Comment by faddat** [comment]
after adding error checks, we get an error in the lockup module:

```go
		if test.expectPass {
			// creation of lock via LockTokens
			msgServer := keeper.NewMsgServerImpl(suite.App.LockupKeeper)
			_, err = msgServer.LockTokens(sdk.WrapSDKContext(suite.Ctx), types.NewMsgLockTokens(test.param.lockOwner, test.param.duration, test.param.coinsToLock))
			suite.Require().NoError(err) // this is new, and checking it yeilds an error
```

**Comment by nicolaslara** [comment]
I think the issue above makes sense and the expectation is that there would be an error there. The failing test is https://github.com/osmosis-labs/osmosis/blob/ff89649e9bdcc98f2409edb7769c2948a6ca8bb0/x/lockup/keeper/msg_server_test.go#L38 which means the lockup will fail, and the test passing is "the lockup failed and the amount locked is still 10 as before"

**Comment by faddat** [comment]
ok, I think in this case then I won't check that error.

**Comment by faddat** [comment]
so, I misnamed the bran ch for #5062.  I am going to close the pr, and do it form faddat/check-all-errors

**Comment by faddat** [comment]
Closing in favor of #5109
