### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by Magicloud** [osmosis-labs/osmosis#5068]
#### System information

Osmosis version: v15.1.0
OS & Version: Linux
Commit hash: Github tag v15.1.0

#### Expected behaviour

Running properly

#### Actual behaviour

Crashing with huge error log.

#### Steps to reproduce the behaviour

Running v15.1.0 on testnet osmo-test-5.

#### Backtrace

[osmo-test-5.v15.1.0.log](https://github.com/osmosis-labs/osmosis/files/11382067/osmo-test-5.v15.1.0.log)

When submitting logs: please submit them as text and not screenshots.

**Comment by Magicloud** [comment]
Seems working fine. Thanks.

**Comment by Magicloud** [comment]
It happens again.

**Comment by ValarDragon** [comment]
This should've been fixed
