### ISSUE TITLE
Remove JSON marshalling of gaugeIDs

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#507]
We use JSON marshalling for gaugeIDs in several locations. We should remove this, and replace it with a more efficient serialization format. This will need a state migration.

I just noticed it being used here: https://github.com/osmosis-labs/osmosis/blob/d3e00da98551cc77db54ea4de0f974703f298de2/x/incentives/keeper/store.go#L80 and in a couple iterators. We should change all of these to no longer be using json.

**Comment by mattverse** [comment]
I'm closing this issue noticing that it isn't getting mistakenly getting JSON marshalled to the state machine, but only a process of unmarshalling.
