### ISSUE TITLE
CL: determine if MulRoundUp is necessary in `CalcAmount1Delta`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5073]
## Background

Brought up by @jonator 

Rounding up at precision end might be an overkill in `CalcAmount1Delta`:
https://github.com/osmosis-labs/osmosis/pull/5022/files#diff-a42e16487ca96d7745417718dff2b3349a0fb18deadc2e1a130cbb87977a8550R108

since we already take the `Ceil()`.

## Suggested Design

Consider reverting to regular multiplication

## Acceptance Criteria
- decision is made

**Comment by AlpinYukseloglu** [comment]
Agreed – in fact, doing mul roundup and ceil also creates an edge case where the total loss to rounding can even exceed 1 (if the first roundup pushes to the next int). Net impact should be minimal regardless but will make this change anyway

**Comment by jonator** [comment]
https://github.com/osmosis-labs/osmosis-frontend/blob/c306b5953a8f45945b250716932c445ca4c97794/packages/math/src/pool/concentrated/math.ts#L101

Should I make any changes here to maintain parity?
