### ISSUE TITLE
Refactor gauge distribution code into its own file

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#508]
The gauge distribution code as it is very long, and in both the hooks directory and the `gauge.go` file. This should all be moved to a single file called `distribute.go`, that can more easily be looked at all together.

**Comment by mattverse** [comment]
Do we simply want to refactor by moving organize methods in a seperate file?
Or do we also want to set the refactoring scope to deleting unused methods etc?

**Comment by mattverse** [comment]
Also, is there a need to separate files for what's currently in `hooks.go`? Seems like there aren't much and could still serve as a single file
