### ISSUE TITLE
osmomath: disable thelper for some testing functions

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#5163]
## Background

A few functions in `osmomath/decimal.go` are test helper functions, but they are not marked as helper functions

## Suggested Design

mark these functions as helpers

## Acceptance Criteria

helper functions marked

**Comment by pysel** [comment]
hmm, on the second look, I now see that adding t.Helper there does not do anything useful, because those functions internally do not fail the test (aka: call `t.FailNow`, `t.Fatal` etc), so adding a t.Helper mark is a no-op. I just wanted to remove the linting warnings, but now that I revisited this, I decided to simply disable them for those specific functions

**Comment by ValarDragon** [comment]
Cool thanks!
