### ISSUE TITLE
Test node and epoch efficiency by allocating 1GB memory ballast of data in main 

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#518]
source: https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap-26c2462549a2/

Basically, trick the golang garbage collector to trigger the garbage collector less often. The entire time during epoch time is spent in garbage collection, so this seems very much worth a try to see if it speeds things up.

**Comment by faddat** [comment]
I don't think that the whole time is in gc, and the rockdb results show it-- maybe I video cast my nodes at epoch?

**Comment by ValarDragon** [comment]
I agree, this issue was pre-understanding the many leveldb & iavl issues in depth
