### ISSUE TITLE
Increase initial shares to 100 * 10^18

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#52]
Currently, the initial shares given to the first LP of a pool is 100 * 10^6.  I wonder if this might not have enough precision.  Especially, because usually the initial creator of a pool might be a massive whale (such as the project team) to kickstart the pool and add an extremely high amount of liquidity.

Balancer uses 100 * 10^18 as the initial shares amount.
https://github.com/balancer-labs/balancer-core/blob/master/contracts/BConst.sol#L33

Maybe we should use something similar?

**Comment by Thunnini** [comment]
I personally don’t think it’s a huge issue, but changing the precision of the share is a fairly easy change. Feel free to change it to an amount that you feel is safe. Do you think issuing 1000^(10^18) could be better instead?
