### ISSUE TITLE
tests: Should we use s. or suite. ?

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#5223]
In osmosis we have many tests, some are like:

suite *KeeperTestSuite

others are like

s *KeeperTestSuite

I've made a PR that tries to standardize around s, but fact is it doesn't matter one way or another which we do.

So I figured I would open an issue because what likely does matter is that we adhere to a standard:

* https://github.com/osmosis-labs/osmosis/pull/5222

**Comment by p0mvn** [comment]
I'm supportive of the consistency of using `s` everywhere

**Comment by faddat** [comment]
Then it shall be s.
