### ISSUE TITLE
Are `x/mint` tokens minted daily or weekly?

### ISSUE THREAD

**Issue by rootulp** [osmosis-labs/osmosis#5224]
## Context

https://github.com/osmosis-labs/osmosis/blob/9e1ca7beb15efaf027282946b7231a4bdfc4f32f/x/mint/README.md?plain=1#L26

## Problem

As far as I can tell, new tokens are minted in the epoch block that occurs daily not weekly.

<img width="264" alt="Screenshot 2023-05-18 at 12 29 24 PM" src="https://github.com/osmosis-labs/osmosis/assets/3699047/ca05b93e-2048-46b2-ab22-20fe97d74fad">

Source: https://www.mintscan.io/osmosis/parameters

## Proposal

1. Update any relevant code in the `x/mint` module to set the default to one day not one week.
2. Update this line in the README

**Comment by rootulp** [comment]
Additional supporting evidence

https://github.com/osmosis-labs/osmosis/blob/9e1ca7beb15efaf027282946b7231a4bdfc4f32f/x/epochs/README.md?plain=1#L29

**Comment by p0mvn** [comment]
It is one day. Sorry, might be outdated. If you PR an update, we would appreciate the help
