### ISSUE TITLE
Enable --log_format flag

### ISSUE THREAD

**Issue by mdyring** [osmosis-labs/osmosis#523]
It would be desirable to enable the --log_format flag similar to other Cosmos SDK based chains.

JSON log output is easier to parse/massage than plain text. :-)

```
--log_format string   The logging format (json|plain) (default "plain")
```

**Comment by ValarDragon** [comment]
Is this missing on all queries, or just some?

**Comment by mattverse** [comment]
We are missing `log_format`, `log_level`
