### ISSUE TITLE
[CL]: merge locked and unlocked migration messages 

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5235]
## Background

Currently, we have locked migration in superfluid and unlocked migration in gamm.

## Suggested Design

We should combine these messages to avoid fragmentation

## Acceptance Criteria
- combined
- tested

**Comment by p0mvn** [comment]
Low priority, let's not pursue this until we get internal reviews fully complete

**Comment by ValarDragon** [comment]
This was fixed at some point
