### ISSUE TITLE
Chore: Fix SDK fork's branches and ensure osmosis-main and v16.x match

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#5255]

**Comment by p0mvn** [comment]
@mattverse assigning you based on earlier discussions in chain dev

TODOs:
- check v16 includes everything that is on `osmosis-main`
- delete `osmosis-main`
-  make `osmosis-main` off of `v16.x` (ping Dev if no permissions)

**Comment by stackman27** [comment]
i believe we can close this right? https://github.com/osmosis-labs/osmosis/pull/5409
