### ISSUE TITLE
CI: Don't require changelog & state machine labels for markdown only changes

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#5270]
## Background

We should stop requiring changelog & state machine labels for PR's that only touch markdown files. 

This will lower some of the fighting the CI / manual steps we & contributors have to do.

**Comment by tungbq** [comment]
Hey @ValarDragon do you need any help? I'd like to work on the CI task like this. Can I pick up this task?

**Comment by p0mvn** [comment]
> Hey @ValarDragon do you need any help? I'd like to work on the CI task like this. Can I pick up this task?

Hey @tungbq . We would appreciate help with this issue. Please feel free to PR a change

**Comment by tungbq** [comment]
> state machine labels
> 
Thanks @p0mvn!
Hi @ValarDragon, regarding to the `state machine labels` that you mentioned, do they mean that they are in the required label list of https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/required_labels.yml workflow: `"V:state/breaking, V:state/compatible/no_backport, V:state/compatible/backport"`?

**Comment by p0mvn** [comment]
That's correct. There is one more label that is applicable: `A:no-changelog`

**Comment by p0mvn** [comment]
Please see: https://github.com/osmosis-labs/osmosis/pull/5311

**Comment by tungbq** [comment]
> Please see: #5311

I'm on vacation for last several days so could not check it earlier. I'm looking into it to find another approach to resolve this.

**Comment by tungbq** [comment]
New approach has been proposed in #5357, please have a look.
