### ISSUE TITLE
sanity check ICA messages by hand (no blacklist implemented yet)

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5272]

**Comment by p0mvn** [comment]
@stackman27 and @p0mvn to do this as part of v16 release process

**Comment by stackman27** [comment]
@ValarDragon are these referring to whitelisted "queries" or messages" ? i was able to find whitelisted queries in wasmbindings/stargate_whitelist.go. Not sure where to look for messages

**Comment by mattverse** [comment]
So we have both interchain queries and ICA messages, both of which can be queried via params

**Comment by p0mvn** [comment]
We discussed on the call. No action necessary. This was about checking whether we need to add anything to the whitelist. No requests hapenned
