### ISSUE TITLE
Manually bump ibc-go: https://github.com/osmosis-labs/osmosis/pull/5031

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5273]
- check if newer version exists
- review changelog and confirm no major changes preventing us from doing the upgrade
- if none, bump up

**Comment by p0mvn** [comment]
Consider this version: https://github.com/cosmos/ibc-go/releases/tag/v4.4.0

**Comment by ValarDragon** [comment]
I dont think we should bump to v4.4.0, it is only doing dep updates

**Comment by stackman27** [comment]
@p0mvn should we close this issue too considering we donot want to bump to v4.4.0?

**Comment by p0mvn** [comment]
We still need to apply the huckleberry patch since we are on v4.3.0 on `main`. So I think we can go straight to v4.4.1 just for the sake of being at the latest within the same major

**Comment by p0mvn** [comment]
I think this got addressed by: https://github.com/osmosis-labs/osmosis/pull/5320
