### ISSUE TITLE
[CL] test changing authorized params

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5324]

**Comment by p0mvn** [comment]
We should test and confirm that nothing breaks if we change authorized params

**Comment by AlpinYukseloglu** [comment]
Just to clarify the proposal here – the intended behavior for most incentives operations is to operate on all supported uptime accumulators, regardless of which are authorized.

An example to illustrate is imagine if all uptimes were authorized and then, after incentives were created for them, they were unauthorized – `collectIncentives` should still collect from the emitting incentive records that were created when the uptimes were authorized.

So the only logic that should really depend on authorized uptimes should be incentive creation (which is already tested). The equivalent in any other scenario is functionally the same as testing the case where no records were added to unauthorized uptime accumulators.

**Comment by AlpinYukseloglu** [comment]
Discussed offline and decided it makes sense to run incentives tests on multiple authorized uptime permutations for robustness.
