### ISSUE TITLE
[CWPool]: decide on the need between ContractAddress and PoolAddress

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5328]
## Background

Cosmwasm pools currently have both pool address and a contract address.

Pool address is only created because of the shared logic in the poolmanager module. However, it ends up being unused.

## Suggested Design

Determine whether both `ContractAddress` and `PoolAddress` are needed.

One option is to overwrite "address generator" in wasmd to generate predictable address from pool id (the same logic as we use in `x/poolmanager` for other pools. The downside of this approach is needing to make the modifications to `wasmd`. However, it is the cleanest

## Acceptance Criteria
- Decide on the need between `ContractAddress` and `PoolAddress`
- Implement the solution and remove the need for having both

**Comment by p0mvn** [comment]
CC: @iboss-ptk @nicolaslara

**Comment by nicolaslara** [comment]
I don't think it's a problem to have both identifiers as long as they both point to the same place; they are generated at creation and never modified.

However, if we want to have just the pool id, we could leverage create2 which allows us to create predictable addresses. The only caveat would be that we need to ensure that we don't allow anyone else to instantiate contracts in those addresses (maybe by reserving a label namespace? can we be sure it's not possible to find a collision in that case?). 

I'd also like to avoid modifying wasmd as we will probably want to unfork it once the sdk unfork is done, so maybe upstreaming changes that allow for us to add custom logic to address generation?

**Comment by p0mvn** [comment]
Thanks for the feedback

> I don't think it's a problem to have both identifiers as long as they both point to the same place

Unsure what you mean exactly by pointing to the same place. `ContractAddress` is generated by `wasmd` via msg instantiate. At the same time, `PoolAddress` is generated[ by this from `pool id`](https://github.com/osmosis-labs/osmosis/blob/74dc21583284fe3605983fc87c042c8f4727a954/x/poolmanager/types/pool.go#L35-L38). So they both are associated with the same pool but they point to separate module accounts.

So I agree that this is not a problem but having two addresses is redundant. If we could utilize `ContractAddress` as the `PoolAddress`, I think that would be ideal.

However, there are 2 problems with using "ContractAddress" as the "PoolAddress":
1. x/poolmanager CreatePool logic would have to be extensively refactored. This is tractable, just a large change of critical code path
2. The "ContractAddress" is not derived in the same way as "PoolAddress"es of other pool models.
   * To mitigate that, we could use the "create2" suggestion. However, we would have to make changes to wasmd to expose an API that can supply a custom address generator to "create 2". Currently, "create 2" API uses [an internal address generator with custom parameters.](https://github.com/osmosis-labs/wasmd/blob/09c49d81d38990d232080069b9804af35d68a1b0/x/wasm/keeper/contract_keeper.go#L70-L92)
   * In general, I don't really know if having pool address be generated in a predictable way from pool id is a required property. Maybe we can have the default "msg instantiate" contract address be in place of the "pool address"

> The only caveat would be that we need to ensure that we don't allow anyone else to instantiate contracts in those addresses (maybe by reserving a label namespace? can we be sure it's not possible to find a collision in that case?).

I think this can be guaranteed by a check similar to this:
https://github.com/osmosis-labs/osmosis/blob/74dc21583284fe3605983fc87c042c8f4727a954/x/poolmanager/create_pool.go#L125-L129

> I'd also like to avoid modifying wasmd as we will probably want to unfork it once the sdk unfork is done, so maybe upstreaming changes that allow for us to add custom logic to address generation?

This makes sense to me. Due to time constraints, we can modify the fork and then immediately upstream post-release.

@nicolaslara  please let me know if you have further thoughts. I think the big question is this:
- Is having pool address be generated in a predictable way from pool id is even a required property? If not, we can simply use contract address as the pool address and have only one address

**Comment by iboss-ptk** [comment]
> Is having pool address be generated in a predictable way from pool id is even a required property? If not, we can simply use contract address as the pool address and have only one address

I don't think this is required, as for pool creation process, the only potential need I can imagine is to prepare account in advance before contract instantiation, which does not seems to be the case in general. IMO

**Comment by nicolaslara** [comment]
> Unsure what you mean exactly by pointing to the same place

What I meant is that I think it's ok to have the redundancy as long as nothing can change it in a way that a contract that identified a pool now identifies a different pool (and same for the pool id). Even if we do this, I don't think it needs to be release blocking and can be done as an improvement.

It's still unclear to me how we would reserve the addresses. We can reject any instantiation with a label of `poolmanager/pool_id:.*` but on which conditions are those allowed? is it a whitelist of senders? Or maybe only the having the poolmanager module as the sender?

**Comment by p0mvn** [comment]
Thanks for the feedback.

I settled on the approach in: https://github.com/osmosis-labs/osmosis/pull/5370

Please review PR description and comments left for context.

I agree that this is not launch blocking. However, having duplicate addresses in the pool store model isn't ideal. We wouldn't later be able to remove the redundancy without migration.

Since we concluded that we don't need pool addresses be necessarily predictable, I simply made the pool address be the contract address for a cw pool.

I removed some restrictions that were previously preventing that and explained why they work in the PR

> It's still unclear to me how we would reserve the addresses. We can reject any instantiation with a label of poolmanager/pool_id:.* but on which conditions are those allowed? is it a whitelist of senders? Or maybe only the having the poolmanager module as the sender?

I think this simpler approach also removes the need for having to reason about this.

Please let me know if you agree on the suggested approach in https://github.com/osmosis-labs/osmosis/pull/5370
