### ISSUE TITLE
README: Add link to swagger and REST endpoints people can query

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#533]
@faddat thankfully added notes recently on how to spin up a node more easily. We should also add documentation / quick links for:
* querying data from the chain (Swagger, a node to do it against e.g. datahub, and an example)
* Mintscan as the block explorer to look at latest activity
* Info.Osmosis.Zone
* Imperator Swagger API

**Comment by czarcas7ic** [comment]
@daniel-farina you can assign me to this if you would like. I'm currently unsure of the best place in the github docs for them (own section or within networks) but I can write out the content none the less.

**Comment by faddat** [comment]
I suggest that the content be put right here-- everything we think of as osmosis, goes in here :). That way docs are versioned with code.

**Comment by czarcas7ic** [comment]
![Screenshot 2021-11-29 190614](https://user-images.githubusercontent.com/40078083/143967016-c34eb046-21d4-4921-b517-1f3f05186fa9.png)

@daniel-farina does this page close this issue? The only thing that might need documentation would be the REST server but even swagger kind of guides you through it. LMK if you think it needs more to it and I'll accordingly, thanks.

**Comment by ValarDragon** [comment]
That page lgtm! Can we close this issue once that data is on the repo's main README as well? (Or would you prefer an entire readme redesign in light of the docs)

**Comment by czarcas7ic** [comment]
@ValarDragon I just realized that Imperator.co's REST server lacks a large amount of queries normal swagger servers have. With that being said, its the best public osmosis REST server that I am aware of. Might need to be another issue created to make a public REST server with all swagger query options. IMO there should eventually be an official osmosis gRPC and REST endpoints (similar to how crypto.org has), but that's a separate discussion I suppose.

**Comment by czarcas7ic** [comment]
And yeah to answer your question I think at the completion of this when the docs folder is finally merged to main I would imagine the repo's main README would have to be reimagined.

**Comment by ValarDragon** [comment]
Ok sgtm, can close for now if a README rewrite is already planned!

Yeah, we definitely need to link the "standard" query swagger and the imperator one. (We can probably recommend the imperator one, especially as it gets more expansive, but its anyways useful for cross-chain interoperability to have the standard one)
