### ISSUE TITLE
Add a protocol swap fee. E.g. 20% of all swap fees go to Osmosis protocol (distributed to stakers)

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5342]
Design doc owner: @czarcas7ic 

- Fixed fee contrary to a proportion of the spread factor

**Comment by ValarDragon** [comment]
Note specification this will likely have many more details per governance.

**Comment by sunnya97** [comment]
Relevant governance proposal:  https://www.mintscan.io/osmosis/proposals/530
