### ISSUE TITLE
v16: unblock testnet by fixing a twap issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5343]
## Background

Reported by Niccolo. Some more context: wap issue: https://osmosis-network.slack.com/archives/C047MFF0U1X/p1685109827095009

## Acceptance Criteria
- We need to fix this to unblock the testnet

**Comment by czarcas7ic** [comment]
current state of issue:

created branch https://github.com/osmosis-labs/osmosis/tree/adam/twap-record-upgrade-handler with what I believe to be the fix. If @niccoloraspa runs it and it fixes the issue I will open up a PR.
