### ISSUE TITLE
Make an active gauges per pool query

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#535]
This should be done to remove the need for PR's like this on the front-end: https://github.com/osmosis-labs/osmosis-frontend/pull/62/commits/974a72f1016937f1e1c874a00c9df12f43cf11b1 (so removing the need for this entire field: https://github.com/osmosis-labs/osmosis-frontend/blob/master/src/config.ts#L70)

**Comment by mattverse** [comment]
Closed with PR https://github.com/osmosis-labs/osmosis/pull/572
