### ISSUE TITLE
[CL][osmoutils]: Implement slice helper for getting max value in a slice

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#5365]
## Background

We have recently added a number of CL helpers that are essentially just getting the largest value in a slice (`getLongestLockableDuration`, `getLongestSupportedUptime`). We should add a new helper to `slice_helper.go` in osmoutils to abstract out this logic and prevent further duplicate code around similar setups in the future

## Suggested Design

- Implement a standard max value in slice helper that deals with generic types and takes in a comparison function (or just uses built in ones & deals with built in values instead)

## Acceptance Criteria

- New function is tested and all existing tests pass

**Comment by pysel** [comment]
hey @AlpinYukseloglu, there is an interesting PR by @p0mvn that does similar thing to what you described here: https://github.com/osmosis-labs/osmosis/pull/5035#issuecomment-1571113260

it helps find i'th smallest element in the array (it is also generic and takes the `less` function as a parameter). If the PR gets merged, I could create a wrapper of this function to find max and min value of the array, just so it is easier to use. Lmk what you think

**Comment by p0mvn** [comment]
> hey @AlpinYukseloglu, there is an interesting PR by @p0mvn that does similar thing to what you described here: #5035
> 
> it helps find i'th smallest element in the array (it is also generic and takes the `less` function as a parameter). If the PR gets merged, I could create a wrapper of this function to find max and min value of the array, just so it is easier to use. Lmk what you think

Would you be interested in driving that PR to completion? I can help review it later

**Comment by pysel** [comment]
yeah sure, it is pretty much ready, just a few changes required

**Comment by p0mvn** [comment]
Sweet, would appreciate help with the required changes

**Comment by ValarDragon** [comment]
GOing to close this one for now, if it comes up when folks are writing the next use case, lets write it at that time.
