### ISSUE TITLE
Add Help Wanted and Good First Issue labels to link checker report 

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#5385]
## Background

We have a workflow that creates a report of broken links every 2 weeks: https://github.com/osmosis-labs/osmosis/issues/5384. I think we should add Help Wanted and Good First Issue labels to these reports, just so any person can pick it up without hesitation.

## Suggested Design

Add `Help Wanted` and `GFI` labels to link checker workflow

## Acceptance Criteria

Labels attached to issues created by workflow

**Comment by ValarDragon** [comment]
I don't think this makes sense to do. People can just filter issues by label
