### ISSUE TITLE
Fix import paths github action 

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#5391]
## Background

The import paths workflow seems broken:
https://github.com/osmosis-labs/osmosis/actions/runs/5115321530

## Acceptance

The workflow works when manually running it

**Comment by pysel** [comment]
#5401 fixes the logic for getting the `version_to_replace` variable

there is another issue with this workflow:

the workflow will still fail, because after updating import paths to (for example) v16 from v15, [some](https://github.com/osmosis-labs/osmosis/blob/main/tests/cl-go-client/go.mod#L8) recently introduced modules will have an invalid version set. Ex:

How go.mod of `cl-go-client` looks after workflow run (from v15 to v16):
```
github.com/osmosis-labs/osmosis/v16 v15.0.0-20230530235412-9f091596cbcf
```

error it results in is:

> version "v15.0.0-20230530235412-9f091596cbcf" invalid: should be v16, not v15


[Here](https://github.com/osmosis-labs/osmosis/actions/runs/5150914405/jobs/9275587891) is how this error looks in gh actions.

Question to reviewers:
Are we running this workflow after the release is created or before? In former case, it would be easy to simply change the version of `github.com/osmosis-labs/osmosis/vX` in modules that import it

**Comment by p0mvn** [comment]
Before

**Comment by p0mvn** [comment]
@pysel thanks for the timely update of this script! Do you think you could also auto-apply state compatibility and changelog labels to the PR created by this CI job?

**Comment by p0mvn** [comment]
Also, FYI, the proto-gen CI check is failing: https://github.com/osmosis-labs/osmosis/actions/runs/5159223921/jobs/9293878347?pr=5408

**Comment by p0mvn** [comment]
The script doesn't seem to run `make proto-all` at the end, can we fix that?

**Comment by pysel** [comment]
the logic for proto has not been changed, but it only runs `proto-gen`, w/o formatting them

**Comment by pysel** [comment]
Closing as resolved
