### ISSUE TITLE
CalculateSpotPrice should be fee-less

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#54]
Currently we have two functions:  `CalculateSpotPrice` and `CalculateSpotPriceSansFee`.

I know, this is using the naming used in the Balancer code, but I think this nomenclature of SpotPrice including fees is quite non-standard in industry and we should it correctly.  (Even the balancer docs, define spot price as not including fees:  https://docs.balancer.finance/core-concepts/protocol/index#spot-price).

I'd recommend switching:
- `CalculateSpotPriceSansFee` -> `CalculateSpotPrice`
- `CalculateSpotPrice` -> `CalculateSpotPriceWithFee`.

**Comment by ValarDragon** [comment]
Thats whats already done in this branch https://github.com/osmosis-labs/osmosis/tree/gamm_updates

**Comment by sunnya97** [comment]
Closed by https://github.com/osmosis-labs/osmosis/commit/4a5ed584f8361eef9387594d496bd4f364e5d169

**Comment by sunnya97** [comment]
While the lower level unexposed functions were switched, the exposed keeper functions are still `CalculateSpotPriceSansFee` and `CalculateSpotPrice`.

See:  https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/swap.go#L238

These should be fixed as well.
