### ISSUE TITLE
Automatically apply state compatibility and changelog labels to PRs created by import paths github action

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#5413]
## Background

PRs created by import paths workflow do not automatically include state and changelog labels (ex: https://github.com/osmosis-labs/osmosis/pull/5408), hence, a reviewer should manually apply them. 

## Suggested Design

Automatically apply `V:state/compatible/no_backport` and `A:no-changelog` labels

## Acceptance Criteria

Workflow updated, labels get applied

**Comment by tungbq** [comment]
Proposed a change in #5415
