### ISSUE TITLE
localosmosis: increase max block gas limit

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5429]
## Background

Increase block gas limit to 120m in localosmosis

In Osmosis | Smart Contracts TG channel, it was brought up that this mismatch is causing issues due to increased gas charge in msg create denom.

We should update the configuration to match mainnet to make sure that msg create denom does not charge all block gas

## Acceptance Criteria
- block gas limit is increased in localosmosis to 120M

**Comment by DongLieu** [comment]
can i handle it?

**Comment by p0mvn** [comment]
This is duplicate of: https://github.com/osmosis-labs/osmosis/issues/5440

@DongLieu can you handle #5440 please?
