### ISSUE TITLE
Daily at 10:15 to 10:20 AM PDT Validator Loses Connection

### ISSUE THREAD

**Issue by lightiv** [osmosis-labs/osmosis#545]
I am on version v4.1.0 for my validator and sentried.  Every day my validator loses connection to it sentries.  I assume this is happening with the Epoch as it is every day at the same time.  Logging into the nodes they all appear to be reading blocks normally.  Restarting the sentries and then the validator restores normal operations.

**Comment by daniel-farina** [comment]
@lightiv 

I would like to start collecting more information as we try to see if these issues are known issues. Could you please share:

**Environments from the nodes**

OS (e.g. from /etc/os-release):
```
cat /etc/os-release
```

**Infrastructure**
Could you share information regarding how these nodes were setup? Do you have documentation or what instructions were followed? 


Thank you!

**Comment by daniel-farina** [comment]
Closing, should be fixed with #603
