### ISSUE TITLE
Write a test for JoinPool gas no longer growing linearly with number of tokens

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#547]
We need to write a test case to ensure that JoinPool's gas amount no longer grows linearly with the number of token denoms on-chain

**Comment by mattverse** [comment]
This issue is closed with https://github.com/osmosis-labs/osmosis/pull/586

**Comment by ValarDragon** [comment]
Hey, lets keep issues open until the PR gets merged!
