### ISSUE TITLE
[CL][Internal Review] Add functional to Distribute coins using InternalGauge and External Gauge 

### ISSUE THREAD

**Issue by stackman27** [osmosis-labs/osmosis#5471]
## Background
we added the ability to use internal and external gauge in here: https://github.com/osmosis-labs/osmosis/pull/5459. Now it'll be good to have functional testing on it

## Invariants to Check
- check if internal gauge are not created when external gauge is expected and vice versa 
- check NoLock is only for CL gauges 
- check correct emission rate and coins distributed per epoch 
- more tbd

## Acceptance Criteria
- rigorously test both the flows 
- all test should pass without hindering other tests/flow

**Comment by p0mvn** [comment]
We need to create the following tests:
- Create 2 balancer pools
- Create 2 concentrated pools
- Create 1 external by duration gauge perpetual via `MsgCreateGauge`
- Create 1 external by duration gauge non-perpetual over 2 epochs `MsgCreateGauge`
- Create 1 external no-lock gauge perpetual `MsgCreateGauge`
- Create 1 external no-lock gauge non-perpetual over 2 epochs `MsgCreateGauge`
- Create distribution records for internal incentives using `HandleReplacePoolIncentivesProposal`
  * incentivize one of the balancer pools (that is lockable durations associated with them
  * incentivize one of the concentrated pools

Then, let 1 epoch pass artifically. Validate that:
- internal incentives were correctly distributed to the right pool
- external gauge incentives were correctly distributed to the right pools
- IncentivizedPools query returns the right thing
- ExternalGauges query returns the right thing

Next, remove distr records completely using logic in  `HandleReplacePoolIncentivesProposal`

Let second epoch pass. Confirm that

- only external non-perpetual gauges with 2 epochs distributed
- no internal incentive distribution

Let thing epoch pass. Confirm that:
- nothing distributes as non-perpetual gauges with 2 epochs have ended and perpetual gauges have not been reloaded
