### ISSUE TITLE
Add governance proposal type to change pool params

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#548]
Can be used to standardize Swap Fee and Exit Fees before per-pool governance exists.

**Comment by daniel-farina** [comment]
@romelukaku  @sunnya97 
Is this ticket still work in progress or was it already merged with a PR? 

Thank you!

**Comment by sunnya97** [comment]
It was not already merged.  @romelukaku are you still working on it?

**Comment by romelukaku** [comment]
no I'm not, sorry I haven't done this already
I'll start now

**Comment by mconcat** [comment]
What is the status on this issue? If it is available I would like to start working on it

**Comment by sunnya97** [comment]
@hieuvubk Which PR?

**Comment by hieuvubk** [comment]
> Change pool params (swap fee, exit fee) via proposal #1725

https://github.com/osmosis-labs/osmosis/pull/1725
