### ISSUE TITLE
Refactor createPosition to use struct param and return

### ISSUE THREAD

**Issue by Pipello** [osmosis-labs/osmosis#5485]
## Background

From discussion: https://github.com/osmosis-labs/osmosis/pull/5484#discussion_r1224487254

## Suggested Design

This might be long refactoring but from what I saw the current signature of `createPosition` is as 
```golang
func (k Keeper) createPosition(ctx sdk.Context, poolId uint64, owner sdk.AccAddress, tokensProvided sdk.Coins, amount0Min, amount1Min sdk.Int, lowerTick, upperTick int64) (positionId uint64, actualAmount0 sdk.Int, actualAmount1 sdk.Int, liquidityDelta sdk.Dec, lowerTickResult int64, upperTickResult int64, err error)
```
This ends up with parent function calls looking like:
```golang
a, b, c, d, err = keepers.ConcentratedLiquidityKeeper.CreateFullRangePosition(...)
```
This is not really good for maintenance or new features.

The solution could be to provide a return struct and a param struct such as:
```golang
type createPos struct {
    poolId uint64
    owner sdk.AccAddress
    tokensProvided sdk.Coins
    amount0Min sdk.Int
    amount1Min sdk.Int
    lowerTick int64
    upperTick int64
}

type position struct {
    positionId uint64
    actualAmount0 sdk.Int
    actualAmount1 sdk.Int
    liquidityDelta sdk.Dec
    amount1Min sdk.Int
    lowerTickResult int64
    upperTickResult int64
}

func (k Keeper) createPosition(ctx sdk.Context, createPos *createPos) (pos *position, err error)
```

The parent callers are used across many files but solving this issue would reduce technical debt

## Acceptance Criteria

- existing calls are using the new structures

**Comment by Pipello** [comment]
From what I see in the `x/concentrated-liquidity/lp.go` this might be the top of the iceberg and it would make sense to start by smaller pieces such as [emitLiquidityChangeEvent](https://github.com/osmosis-labs/osmosis/blob/e144e3f600d031b6e7ee1ca17148e7bb2b717988/x/concentrated-liquidity/lp.go#L514) and build up from there

**Comment by Pipello** [comment]
This was partially solved by: https://github.com/osmosis-labs/osmosis/pull/5983
I am fine with closing it

**Comment by ValarDragon** [comment]
Thanks for that PR!
