### ISSUE TITLE
osmosis-labs/osmosis@v1.0.4 requires  -> github.com/gogo/protobuf@v1.3.3 -> unknown revision v1.3.3

### ISSUE THREAD

**Issue by devudilip** [osmosis-labs/osmosis#5508]
While installing "github.com/osmosis-labs/osmosis/x/gamm/types" it throws the below error. 

```
github.com/osmosis-labs/osmosis@v1.0.4 requires
 github.com/gogo/protobuf@v1.3.3: reading github.com/gogo/protobuf/go.mod at revision v1.3.3: unknown revision v1.3.3
```
While the above dependency has "1.3.2" as latest.

https://github.com/gogo/protobuf/releases

**Comment by faddat** [comment]
Hey, I think you're trying to use Osmosis as a library?

in our go.mod files, we have a replace statement for this.  Yeah it is a bit of a pain.

**Comment by AlpinYukseloglu** [comment]
Hmm odd that go mod vendor/tidy didn't pick this up. @faddat's suggestion should fix the issue.
