### ISSUE TITLE
[CL]: Consider removing all sqrtPrice to Tick conversions and run core logic fully in sqrt price domain

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#5519]
## Background

Given the severity of the bugs recently discovered related to two-way conversions between ticks and prices, a number of suggestions have come up internally around how we might be able to eliminate this class of bugs altogether by never relying on a consistent inverse relationship between prices and ticks.

Specifically, the main approach that has been discussed is to stop tracking `currentTick` as a pool field and stop relying on ticks in general for bound checks or internal CL math.

This has the ultimate effect of removing the need for ever converting from price to tick, meaning that we only have to ensure we maintain a sound 1-way map from ticks to sqrt price (requires resolving #5517) and don't have to worry about breaking the inverse relationship between prices and ticks.

## Suggested Design

- Change swap logic to never rely on current tick and instead store the next initialized tick in either swap direction
- Change all tick-based bound checks like the one below with sqrtPrice based ones instead:
https://github.com/osmosis-labs/osmosis/blob/6ad2827c67cee185f2b7652ed7ae4cdea955f979/x/concentrated-liquidity/model/pool.go#L254
- Update all related tests in a way that preserves the vectors they are testing while ideally not doing a 500+ line change

## Acceptance Criteria

- All new and existing tests pass
- Updated code is very carefully reviewed by multiple people as it touches several important parts of our CL codebase

**Comment by p0mvn** [comment]
Closing since addressed now
