### ISSUE TITLE
CL: swap tick boundary test vectors

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5538]
## Background

These are the test vectors that we would like to hit:

- zero for one swap until tick + second zero for one swap 
- zero for one swap below tick + second zero for one swap
- zero for one swap above tick + second zero for one swap

repeat the same combinations but second swap is one for zero

- one for zero swap until tick + second one for zero swap 
- one for zero swap below tick + second one for zero swap
- one for zero swap above tick + second one for zero swap

repeat the same combinations but second swap is one for zero

## Acceptance Criteria
- Test vectors covered

**Comment by p0mvn** [comment]
Additional vectors:
consider the impact of price limit on this

**Comment by p0mvn** [comment]
We should repeat the same vectors with tick spacing of 1 and 100 to ensure the are no edge cases around that

**Comment by p0mvn** [comment]
In particular, where the are ticks surrounding the tick being crossed when tick spacing is one

**Comment by AlpinYukseloglu** [comment]
Linking this issue to ensure it's flagged in #5428

We should definitely expand the randomized swap portion of #5476 to cover this

**Comment by p0mvn** [comment]
Just FYI, The test vectors listed here are already covered by hand-picked values in https://github.com/osmosis-labs/osmosis/pull/5526
