### ISSUE TITLE
the node hang

### ISSUE THREAD

**Issue by lkk2003rty** [osmosis-labs/osmosis#5566]
## Background
while the node is running, but it hang on height 10081945
```
1:39AM ERR Stopping peer for error err="blockchainReactor validation error: wrong Block.Header.AppHash.  Expected BAAB3FA881F9702B312798EE2C05EABA0183E9C698684AB5EE01F48CF979AF41, got E021BB192E86671CBD4F1E607B4676A0280F43D5A304F9B7DA2FD74740CA10CF" module=p2p peer={"Data":{},"Logger":{}}
```

How to fix it?

**Comment by ValarDragon** [comment]
Oof this was an app hash issue. We believe the root cause of this has been solved. Will try to get patch releases out for historical versions to make this pain point go away for everyone in the future
