### ISSUE TITLE
Chain id is not specified in examples of using osmosisd

### ISSUE THREAD

**Issue by bitcartel** [osmosis-labs/osmosis#5679]
Documentation here: https://docs.osmosis.zone/cosmwasm/testnet/cosmwasm-deployment

Has examples of using osmosisd e.g.
```osmosisd tx wasm execute $CONTRACT_ADDR "$TRY_INCREMENT" --from wallet --gas-prices 0.025uosmo --gas auto --gas-adjustment 1.3 -y```

But they do not specify the chain id which is required. Examples only work if this is added:
```
--chain-id osmo-test-5
```

If there is an environment variable which osmosisd can use to obtain the chain id, please specify the environment variable and document setting it up. Otherwise, consider adding --chain-id xxx to the examples.

**Comment by faddat** [comment]
@bitcartel would it work for you, to set the chain-id by default in client.toml, so that you don't need to set it?

This could make testnets a little messy but I bet we can find a workaround

**Comment by mattverse** [comment]
Hey @bitcartel Thanks for the PR! Yeah I think default chain-ids can cause alot of confusions or perhaps it can be an extra overhead in certain cases, (although I do agree that this is annoying) 

For now I have created a PR to update the docs (https://github.com/osmosis-labs/docs/pull/218), the docs website should be updated any time soon. Again, thanks for the PR!

**Comment by ValarDragon** [comment]
Closing since it looks like we mitigated the problem here? Hopefully the set-env work for working with testnet has also fixed this pain point
