### ISSUE TITLE
Remove Exit Fee from Create Pool cli

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#5686]
## Background

We have removed Exit Fees from all Balancer Pools in the previous version upgrade.
However, the cli command for creating a Balancer Pool still takes in Exit Fees mandatorily, and then have the field set to 0. 

## Suggested Design
What we should really be doing is remove exit fee completely when creating pools

## Acceptance Criteria
Problem statement mentioned above has been solved

**Comment by deividaspetraitis** [comment]
hey @mattverse, @ValarDragon is this still relevant? I would be happy to give a try to work on it.

**Comment by deividaspetraitis** [comment]
Please correct in case I am looking at the wrong place, but it seems that [NewBuildCreateBalancerPoolMsg](https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/client/cli/tx.go#L399C6-L399C35) called by [BuildCreatePoolCmd](https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/client/cli/tx.go#L399C6-L399C35) is still using Exit Fees and passing to [PoolParams](https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/client/cli/tx.go#L448). Is it the goal actually of the task to remove passing exit fee completely to PoolParams or something more?

**Comment by czarcas7ic** [comment]
@deividaspetraitis it is still relevant. It is using it, but the exit fee no longer is utilized, so setting it to anything is essentially doing nothing. So the desire is to remove it and just set to zero or nil so the person submitting the CLI command doesn't think they are setting a param that will actually do something

**Comment by deividaspetraitis** [comment]
Got it, thanks @czarcas7ic for clarification, I will open a pull request for review once it is ready.
