### ISSUE TITLE
Volume based incentive splitting

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5723]
## Context

Design doc owner: @AlpinYukseloglu 

Volume-based incentives is a system to incentivize a denom pair assuming that there are 2 pools for the same pair such as classic and CL pool. Then, the distribution to each of the pools will be dynamically split based on volume.

## Acceptance Criteria
- Design document created
- Implemented

**Comment by stackman27** [comment]
i wrote this short hackmd (still WIP) https://hackmd.io/pHu-rz92QPKRKsD0gEG96Q

please lmk if my understanding is accurate

**Comment by p0mvn** [comment]
Closing in favor of https://github.com/osmosis-labs/osmosis/issues/6057
