### ISSUE TITLE
Fix docker CI tests

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#574]
The docker CI tests are currently broken. It appears to be an issue with downloading golang? https://github.com/osmosis-labs/osmosis/runs/4068503457?check_suite_focus=true

We should fix this

**Comment by daniel-farina** [comment]
@ValarDragon  The latest commit that had a failure is [here](https://github.com/osmosis-labs/osmosis/actions/runs/1423973875/attempts/1). I re-ran it after I noticed it was working just fine on my fork. This time it completed fine. I guess it was a depency/library that was not available for a few days. 

**Failed run** (10 days ago)
https://github.com/osmosis-labs/osmosis/actions/runs/1423973875/attempts/1
**Sucesfull run** (second attempt a yesterday)
https://github.com/osmosis-labs/osmosis/actions/runs/1423973875/attempts/2

I think we can close this issue for now.

**Comment by ValarDragon** [comment]
oh amazing, thanks! Glad it got sorted out
