### ISSUE TITLE
Fix cli_test.go in modules

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#578]
Currently, cli_test.go in `epochs`, `gamm`, `incentives`, `pool-incentives` module are only testing whether the return type for the cli command is correct, which should not be the case.

Each test in `cli_test.go` should ensure that the cli implementation of the grpc_query.go and msg_server.go is tested, with the specified implementation and simulation of each case for the specified command.

This could be easier done by referencing `grpc_query_test.go`.

**Comment by ValarDragon** [comment]
Instead of work on this, lets focus attention towards strategies to get more CLI code automatically generated & deletable.
