### ISSUE TITLE
perf: Analyze state export performance issue

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#580]
We need to get some profiler output for where time during state exports is going. Just tried doing a state export, and so far have been waiting 40 minutes, with no progress indication.

My initial suspicion is issues with sequential JSON serialization in the SDK + locality-inefficient data read pattern (due to IAVL issue)

**Comment by faddat** [comment]
In the case that you're describing, are we talking about just the tip, or are we exporting history, too?

**Comment by ValarDragon** [comment]
Just the tip

**Comment by ValarDragon** [comment]
Closing for more recent issues
