### ISSUE TITLE
Unable to resolve type URL `/cosmos.staking.v1beta1.MsgCancelUnbondingDelegation`

### ISSUE THREAD

**Issue by Ryz0nd** [osmosis-labs/osmosis#5839]
#### System information

Osmosis version: `Osmosis version`
OS & Version: Windows/Linux/OSX
Commit hash: 

#### Expected behaviour
It seems that `/cosmos.staking.v1beta1.MsgCancelUnbondingDelegation` is not functioning correctly. 
Is it not supported yet in Osmosis?

I expected it to be possible since the cosmos SDK version is 0.47.3.

### Msgs
```
"msgs": [
  {
    "type": "cosmos-sdk/MsgCancelUnbondingDelegation",
    "value": {
      "amount": {
        "amount": "1042932",
        "denom": "uosmo"
      },
      "creation_height": "10511121",
      "delegator_address": "delegatorAddress",
      "validator_address": "validatorAddress"
    }
  }
],
```

### Response
```
Error: unable to resolve type URL /cosmos.staking.v1beta1.MsgCancelUnbondingDelegation: tx parse error
```

**Comment by doggystylez** [comment]
Osmosis uses its own fork of the cosmos sdk and it looks like that message is not implemented https://github.com/osmosis-labs/osmosis/blob/326dfb08a9af17d53ed5d5a71ac4a591e72ae4b0/go.mod#L326

**Comment by Ryz0nd** [comment]
I didn't realize that Osmosis was using their own Cosmos-SDK, thanks!
