### ISSUE TITLE
Remove ExponentAtPriceOne From Gov Prop CreateConcentratedPool

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#5894]
## Background

The exponentAtPriceOne should already be hard coded as -6. There should be no option to provide an exponentAtPriceOne in the gov prop.

## Suggested Design

> Here, you can put concrete steps as to what to do next
> e.g.
> - create test file in...

## Acceptance Criteria

> Goals & criteria for success
> e.g.
> - all existing and new tests should pass

**Comment by ValarDragon** [comment]
Completed
