### ISSUE TITLE
Create Message for Staking Conversion

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#5898]
## Background

Extension of https://github.com/osmosis-labs/osmosis/issues/5630

We want to create a message that will do all the breakings of locks / superfluid convert them all to osmo and stake. 

Main Reason for this is that the contracts for this action can be complicated, cause they will need to do some complex authz stuff, and also we can avoid having to write a contract, complex frontend multimsg etc. 

## Suggested Design

Create a message in either lockup module or superfluid module (might have to look deeper into this before making decision) for breaking locks / superfluid and then converting them all to osmo and stake

## Acceptance Criteria
 
- Test has been added
- Feature mentioned above has been completed

**Comment by AlpinYukseloglu** [comment]
The logic for this should be quite similar to how we handle migrations, except simpler since the staking part should be well abstracted right?

**Comment by mattverse** [comment]
@AlpinYukseloglu Yes, basically adding up different APIs from here and there!
