### ISSUE TITLE
Support concurrency for IAVL

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#5928]
## Background

Related issues are:
- https://github.com/osmosis-labs/osmosis/issues/5001
- https://github.com/cosmos/iavl/issues/696

Previously, concurrency in IAVL were not supported due to issues mentioned above. Right now nodes would occasionally crash with racing conditions, even with concurrency option turned off.

## Suggested Design

Use sync.Map for the map where race condition is happeninng. 

https://github.com/cosmos/iavl/pull/802 PR is up here, we need to decide how we want to apply this in v17 since it would time some time to get upstreamed.

**Comment by amanPradhan05** [comment]
Can I fix this issue?

**Comment by mattverse** [comment]
@amanPradhan05 Thanks for asking! Unfortunately, we already have the fix ready in https://github.com/cosmos/iavl/pull/802! I just have to create a PR pointing to main 🔥

**Comment by ValarDragon** [comment]
I believe this should be fixed now?
