### ISSUE TITLE
V5 Release

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#593]
* - [x] Make v5.x branch (exclude Matt's query proto breaking PR)
* - [x] Create a state export
* - [x]  Run "transcript of manual commands" to generate a testnet genesis.json
* - [ ]  Make a list of everything that needs to tested
  * - [x]  Min fees per sunny's work
    * - [x] Pool pair assets work -- pending 
    * - [x] Osmo still works
    * - [x] Non white listed thing throws an error
    * - [x]  We need to add to the upgrade handler, the list of whitelisted token IDs
  * - [ ]  State Migration works
    * - [x]  (Chain keeps running after migration)
    * - [x]  This checks as a constituent, the epoch struct change
    * - [x] Pool balances work
    * - [ ] Lockup balances are unaltered
  * - [ ] Bech32IBC
    * - [x] Normal sends work
    * - [ ] IBC sends work
  * - [ ]  JoinPool doesn't grow in gas amount
     * - [ ]  JoinPool gas should be lower. So just check gas amount post-upgrade
  * - [ ]  Metamask works
  * - [ ]  Everything un-ugpraded still works (e.g. daily rewards, swapping)
    * - [ ] Get front-end on testnet
    * - [ ]  Epoch time is roughly on par with now
    * - [ ] Pool Swapping words
    * - [ ] Daily rewards work
    * - [ ] Adding to Lock works
    * - [ ] Create pool works
  * - [x] Airdrop reclaim works as expected
    * - [x] We've spot tested this in a small testnet, we need to test in detail
    * - [x] Adjust airdrop end date in a state export, and see balances change
  * - [x] Measure upgrade time
* - [x]  Communicate w/ validators for updating public testnet
* - [x]  Claims testing. (Need to test post claim date, the 80% gets claimed, and clawback works)

**Comment by daniel-farina** [comment]
Update:

- Testnet working, going through upgrade succesfully
- All the things we want to test pre & post testnet work
- Plan for airdrop claim date, so we can test the clawback
- Probably just changing a parameter in the genesis file, to be (say) 2hrs after attempting testnet start
- Eth secp & bech32ibc in
- Testing both of those
- We don’t know of any front-end breaking things
- Craft a metamask tx

**Comment by ValarDragon** [comment]
Also writing here things on these branches we need to ensure get backported to main:
- [] bech32ibc version bumps
- [] SDK version bumps
- [] Changing beginblock ordering

**Comment by ValarDragon** [comment]
Now that the v5 release is out, the remaining task is to get all of the v5 custom code / fixes onto main.
