### ISSUE TITLE
IBC v2 Upgrade

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#594]
This is a placeholder to work and discuss the IBC v2 upgrade.

**Comment by ValarDragon** [comment]
Once #610 is merged, I _think_ this should be as simple as just changing the import version everywhere. I've asked @adityashripal in a DM as well just to double check.

**Comment by faddat** [comment]
If our modules don't independently do anything other than IBC's transfer port, then yes, it is that simple

**Comment by ValarDragon** [comment]
Closed by #610 then
