### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6007]
## Background

> This is where you can provide code examples or context (e.g. past PR's)
> e.g.
> - The following PRs contributed to...

## Suggested Design

> Here, you can put concrete steps as to what to do next
> e.g.
> - create test file in...

## Acceptance Criteria

> Goals & criteria for success
> e.g.
> - all existing and new tests should pass

**Comment by p0mvn** [comment]
Please note that this is for ClickUp integration testing

**Comment by p0mvn** [comment]
Deleted this issue on ClickUp, wasn't updated here

**Comment by osmosis-clickup** [comment]
Testing User ID

**Comment by osmosis-clickup** [comment]
Testing User ID 2
