### ISSUE TITLE
Tokenfactory Hooks Finalization

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6026]
Design doc owner: @mattverse 

Please add context

**Comment by p0mvn** [comment]
Hi there! It seems like there are no labels assigned to your issue. Could you please add labels to help us better understand the context of the issue? Once the labels are added, I'll be able to assist you more effectively. Thank you!

**Comment by mattverse** [comment]
Hey @p0mvn Token factory hooks should be finalized in v17. Is there a specific reason you had in mind for adding this to v18 scope?

**Comment by p0mvn** [comment]
Will DM to catch up on this
