### ISSUE TITLE
Fixing val-set-pref bugs

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6028]
TBD

**Comment by p0mvn** [comment]
Hi there! I noticed that you mentioned a bug, but I don't see any labels assigned to this issue. It would be really helpful if you could add some labels to provide more information about the bug you are experiencing. This will ensure that the right people can see and address the issue promptly. Thank you!

**Comment by stackman27** [comment]
@p0mvn this is the only one i'm tracking https://github.com/osmosis-labs/osmosis/pull/5967

are there other ones?

**Comment by osmosis-clickup** [comment]
From  (in ClickUp):

**Comment by p0mvn** [comment]
> @p0mvn this is the only one i'm tracking #5967
> 
> are there other ones?

Let's discuss this synchronously tomorrow. From earlier discussions with @ValarDragon , there might be more things we want to fix. However, I don't have anything specific at this time

**Comment by p0mvn** [comment]
Issues from call:
- https://github.com/osmosis-labs/osmosis/issues/5646
- gas problem to investigate

**Comment by czarcas7ic** [comment]
@mattverse assigning you for now based on your message two days ago, if this is something you cannot take on we can assign to someone else, but just assigning so it does not get lost
