### ISSUE TITLE
Allow Go 1.21 to be used

### ISSUE THREAD

**Issue by larry0x** [osmosis-labs/osmosis#6074]
## Background

Now that Go 1.21 is released, and there's no known incompatibility with 1.21, I think we can either:

1. allow any 1.20+ version to be used, or
2. only allow the latest version (1.21)

## Suggested Design

If we take approach (1), here's a way we can edit the Makefile: https://github.com/larry0x/osmosis/commit/03520eb94b1b1c1d17dac3932b2a6da9f859866d

## Acceptance Criteria

If me know if you want me to create a PR on this. Thanks

**Comment by ValarDragon** [comment]
Can you PR approach one, I like it!
