### ISSUE TITLE
[VS Incentives]: Track volume growth in PoolManager state

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6091]
## Background

Once `trackVolume` is implemented and well-tested in #6090, the next step is to call it inside both PoolManager swap functions (in given out and out given in). While this should be a light implementation, it needs to be thoroughly tested, hence the separate issue.

## Suggested Design

- Since `SwapExactAmountIn` and `SwapExactAmountOut` are implemented by the respective pool types they are being called on, we need to track volume at the `RouteExactAmountIn` and `RouteExactAmountOut` level of abstraction instead so we can ensure our logic does not leak out of the PoolManager module
- I believe the simplest approach would be to call `trackVolume` on the _input_ amount of both routing functions right before the final return line. e.g. between these lines:
https://github.com/osmosis-labs/osmosis/blob/b3cbdd4702d5f63d1e1747118c22e713996dcc0d/x/poolmanager/router.go#L102-L103
- We want to always track volume on tokenIn instead of tokenOut because we want volume to be inclusive of fees. It would of course also be technically acceptable to track only in output amounts (and thus exclude fees), but I believe including fees is more representative of the actual volume that's generated. In any case, it needs to be the same one for both functions.

## Testing Strategy

TBD

## Acceptance Criteria

- All new and existing tests pass
- Volume is correctly tracked for new and existing pools

**Comment by p0mvn** [comment]
We have an API for `SwapExactAmountIn` and should be tracking volume there as well:
https://github.com/osmosis-labs/osmosis/blob/114a49891945bd432570e9c516879b4fd00d9576/x/poolmanager/router.go#L188

We should probably make `RouteExactAmountIn` call this API and actually implement volume tracking + taker fee tracking inside `SwapExactAmountIn`
