### ISSUE TITLE
[VS Incentives]: Implement volume splitting policy for group gauges

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6155]
Background

Currently our group gauges default to an even split. Now that volume tracking and querying is implemented, we are ready to implement the volume splitting policy for group gauges.

Suggested Design

Since all volume is denominated in OSMO, we can simply weight gauges by their osmo volume
This should roughly require the following components:

Implement GetOsmoVolumeForPool
Update GroupGauge struct to track weights for each internal ID, starting at 0.
Update calcSplitPolicyCoins to do the following:

// Get internal Ids for the group gauge

// Use pool incentive keeper's `GetPoolIdFromGaugeId` to get pool ID corresponding to each

// In loop, as each pool ID is retrieved, get osmo volume with `GetOsmoVolumeForPool` - gauge's weight last weight and assign result as the new weight for that gauge ID

// When all weights are updated, loop back through and distribute pro rata for each of the coins in the gauge

Consider adding a cap to the number of coins or pool IDs to avoid spam

Acceptance Criteria

Goals & criteria for success
e.g.
all existing and new tests should pass

**Comment by p0mvn** [comment]
@AlpinYukseloglu Could you please confirm that this was addressed by this PR https://github.com/osmosis-labs/osmosis/pull/6366 and can be closed?

> Consider adding a cap to the number of coins or pool IDs to avoid spam

This point is to be handled at group gauge creation time, right?

**Comment by AlpinYukseloglu** [comment]
Yes, this is addressed by #6366 and #6431. The spam vector mentioned in this issue is tracked more robustly in #6491, so we're good to close this.
