### ISSUE TITLE
[VS Incentives]: Create wrapper for `CreateGroupGauge` that takes in pool IDs

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6159]
Background

CreateGroupGauge currently takes in a list of internal gauge IDs. While this is appropriate for the abstraction of a "gauge that distributes to gauges", it does not provide the UX we want of letting people create volume splitting gauges on a list of pools.

Suggested Design

Implement CreateGroupGaugeDefault that takes in a list of pool IDs  and sets up the group gauge pointed to each of their default perpetual gauges.

Acceptance Criteria

All new and existing tests pass

**Comment by p0mvn** [comment]
This is a duplicate of https://github.com/osmosis-labs/osmosis/issues/6404
