### ISSUE TITLE
Prepare testnet genesis

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#616]
We need to prepare a new testnet genesis file for the v5 upgrade testing / new testnet to be based off of

We should also sync with @czarcas7ic for what faucet address to use

**Comment by czarcas7ic** [comment]
@ValarDragon we can use:
osmo1xqhlshlhs5g0acqgrkafdemvf5kz4pp4c2x259

If a different address needs to be used to make it easier that's fine, I will just need the seed. Will also need to ensure my testnet node upgrades properly which shouldn't be an issue, will also need to update testnet instructions on the gitpage

**Comment by ValarDragon** [comment]
Ok will add that address to the genesis file thats in progress rn! 

Will talk to you before we go through with the genesis file. Right now were making one anyway for testing the v5 upgrade, and thought it'd be nice to reset the testnet with a better faucet & updated parameters / node operators.

**Comment by faddat** [comment]
Let's distribute that genesis via ipfs, it'll be much simpler than the git lfs stuff.

**Comment by mattverse** [comment]
Closing this issue with v5 upgrade, v6 upgrade successfully being finished.
