### ISSUE TITLE
Use go modules versioning

### ISSUE THREAD

**Issue by jhernandezb** [osmosis-labs/osmosis#621]
I had an issue importing osmosis in a project we are working on while adding the dependency.
```
go get github.com/osmosis-labs/osmosis@v4.2.0                                  
go get: github.com/osmosis-labs/osmosis@v4.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```

Had to manually specify the commit hash in order to work since semver is being followed only on github releases but not in go modules.

Example: 
```
// go.mod

module github.com/osmosis-labs/osmosis/v4

```

This might be an overkill tho since all import paths must change, but not sure if there is some tooling out there that might benefit from multiple version imports.
```
import "github.com/osmosis-labs/osmosis/v4/x/gamm/keeper
```

**Comment by faddat** [comment]
we're working on tooling that could benefit from that, too. 

I'll try and get this set tomorrow.

**Comment by ValarDragon** [comment]
Getting this in would be huge. Sorry its been on the backlog for > 1 month since cosmosstation pointed it out, but never gotten to.

Would be very grateful for someone submitting a PR for this 🙏

**Comment by faddat** [comment]
@ValarDragon I guess that fully, this is five PR's, one for each version?

wdyt?
