### ISSUE TITLE
[Test Improvements] Create app testing helper methods

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#6226]
## Background
Currently sometimes writing a test would take so much time on the test setup, due to wiring etc. 
For example, if we want to test superfluid, we would have to manually create Balancer pool, create lock, register it as superfluid asset and then have it superfluid delegated. 

As we can see, this is **alot** of boiler plate, it would take me more time to wire stuff down then actually start writing my test code in some instances. 

## Suggested Design

We can improve this by creating good helper methods beforehand for different modules. 
Some of the helper methods that comes into my mind as I am writing this is 
- superfluid setup
- CL pool setup
- incentive and gauge setup
- lock set up

and so on.

Also, most work should have been already done, its just that the helper methods are defined as helper methods within each module's keeper packages, and we want to mitigate this to app testing suite so that we can import and use these methods anywhere.

**Comment by ValarDragon** [comment]
I think this has been solved? lets re-open if were still fighting similar problems
