### ISSUE TITLE
feat(osmomath): mutative and efficient BigDec truncations with arbitrary decimals

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6257]
## Background

Currently, our `SDKDec()` method of `BigDec` does a lot of reallocations. Additionally, this function only truncates to `sdk.Dec` with precision of 18.

## Suggested Design

We should have a way to truncate an arbitrary number of digits. The number of reallocations should be minimized. Mutative and non-mutative versions should be implemented.

See `chopPrecisionAndTruncate` function for reference. Also, see how `chopPrecisionAndRoundUpNonMutative` and `chopPrecisionAndRoundUp` are implemented. Clean up and enhance abstractions where applicable.

## Acceptance Criteria
- Implement arbitrary decimal truncation
- Implement mutative and non-mutative versions
- Reallocations minimized
- Refactor `SDKDec()` to utilize these new functions to minimize reallocations while preserving state-compatibility.
- Test coverage maximized
- Optimize this to be the first client of efficient variable truncation: https://github.com/osmosis-labs/osmosis/pull/6256#discussion_r1312117983

**Comment by p0mvn** [comment]
Hey. For reference, please see `Mul` and `MulMut` methods defined on the `sdk.Decimal`

The benefit of the mutative version is that it doesn't reallocate and mutates the receiver directly. However, it cannot be used always. As a result, we need two versions for most math methods

**Comment by pysel** [comment]
in cases of mutative `Mul`, `Quo`, `Add`, and etc, both receiver and the return value have same types (sdk.Dec in case of `Mul`, for example). in the case of `SDKDec` function, the receiver is of type `BigDec` and the output is `sdk.Dec`, hence, we cannot set the latter to the former.

we could set the underlying `*big.Int` of the latter to the former, but I suppose that it breaks the point of osmomath.BigDec -> sdk.Dec conversion. if this is the desired approach, please, lmk! thanks

cc: @p0mvn

**Comment by p0mvn** [comment]
`osmomath.BigDec` is 36 decimals. `sdk.Dec` is 18 decimals.

To make the mutative `SDKDec` version defined on the `osmomath.BigDec`, we need to make it reuse the first 18 decimals of the original buffer and truncate the rest.

There should be a warning made that it makes the original `osmomath.BigDec` unusable
