### ISSUE TITLE
fix: unbond and stake serialization issues

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6330]
## Background

There are serialization issues with unbond and stake message.

Empty string for the validator address doesn't get properly serialized and causes signature mismatch issues.

The same problem for zero lock id

Context: https://osmosis-network.slack.com/archives/C03JT90769K/p1694032456473589?thread_ts=1693917419.462069&cid=C03JT90769K

## Suggested Design

- placeholder for empty validator address as "none"
- change lock id from 0 to -1 to signify unlocked

## Acceptance Criteria
- changes applied
- unit tests updated
- confirmation from @jonator that FE is unblocked receieved

**Comment by jonator** [comment]
While this is not a perfect solution, it would save us time until telescope can handle nullable values, and is a proven solution when looking back to the "migrate to full range position" message (using lockId -1 instead of 0)

**Comment by mattverse** [comment]
Left comment in frontend channel

**Comment by ValarDragon** [comment]
Closing this for now, since its FE libs serialization error.
