### ISSUE TITLE
feat: query to get balances of all CL pools

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6331]
## Background

Currently, FE has to query balances for every CL pool as these are not present in the pool model.

This is not scalable.

## Suggested Design

Add a separate query in the CL module to get balances of all CL pools and return them together with IDs

## Acceptance Criteria
- implemented
- tested
- confirmation from @jonator that this addresses the need

**Comment by jonator** [comment]
IDs should be sufficient. Would be nice for CW pools too.

**Comment by hieuvubk** [comment]
@p0mvn is this one still available? Willing to work with

**Comment by jonator** [comment]
@hieuvubk  hieuvubk

**Comment by p0mvn** [comment]
Concluded that this is not needed
