### ISSUE TITLE
Cannot start a node with cleveldb enabled

### ISSUE THREAD

**Issue by blewater** [osmosis-labs/osmosis#636]
Hi,

### Osmosis version:
`git checkout v3.1.0`

### Error in Ubuntu 20.04 with the cleveldb option enabled
```shell
INF starting ABCI with Tendermint
Error: unknown db_backend cleveldb, expected one of goleveldb,memdb
```
### build Instruction
```shell
make build OSMOSIS_BUILD_OPTIONS=cleveldb

go build -mod=readonly -tags "netgo ledger gcc" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=osmosis -X github.com/cosmos/cosmos-sdk/version.AppName=osmosisd -X github.com/cosmos/cosmos-sdk/version.Version=3.1.0 -X github.com/cosmos/cosmos-sdk/version.Commit=13916d1e10bca718b6ea7f4b84715710bc319e6d -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,gcc" -X github.com/cosmos/cosmos-sdk/types.DBBackend=cleveldb -w -s' -trimpath -o /home/mar/go/src/github.com/osmosis-labs/osmosis/build/ ./...
```
### Start script

```shell
rm -rf $HOME/.osmosisd/

cd $HOME

osmosisd init --chain-id=testing testing --home=$HOME/.osmosisd
osmosisd keys add validator --keyring-backend=test --home=$HOME/.osmosisd
osmosisd add-genesis-account $(osmosisd keys show validator -a --keyring-backend=test --home=$HOME/.osmosisd) 1000000000stake,1000000000valtoken --home=$HOME/.osmosisd
osmosisd gentx validator 500000000stake --keyring-backend=test --home=$HOME/.osmosisd --chain-id=testing
osmosisd collect-gentxs --home=$HOME/.osmosisd

osmosisd start --home=$HOME/.osmosisd --db_backend=cleveldb
```

### Clevel db build instructions [ref](https://docs.tendermint.com/master/introduction/install.html#compile-with-cleveldb-support)
```shell
sudo apt-get update
sudo apt install build-essential

sudo apt-get install libsnappy-dev

wget https://github.com/google/leveldb/archive/v1.20.tar.gz && \
  tar -zxvf v1.20.tar.gz && \
  cd leveldb-1.20/ && \
  make && \
  sudo cp -r out-static/lib* out-shared/lib* /usr/local/lib/ && \
  cd include/ && \
  sudo cp -r leveldb /usr/local/include/ && \
  sudo ldconfig && \
  rm -f v1.20.tar.gz
```

What am I missing?

**Comment by daniel-farina** [comment]
What does your config file look like?
What is the value of db_backend = ?

**Comment by daniel-farina** [comment]
Sorry not too familiar with cleveldb, what is the reason to use it instead of goleveldb? 
Similar issues: 
https://github.com/tendermint/tendermint/issues/4003
https://forum.cosmos.network/t/compiling-tendermint-with-cleveldb/5026/2

**Comment by blewater** [comment]
We are exploring it for block generation performance gains for our node during epoch settlements. It is the general consensus within the ecosystem that goleveldb is the least performant DB option for running validator nodes; other options being cleveldb, rocksdb.
Cleveldb is the first recommended option by the tendermint team when database trx activity is high (i.e., [ref1](https://github.com/tendermint/tendermint/issues/3905#issuecomment-522895226), [ref2](https://github.com/tendermint/tendermint/issues/1162#issue-292028323))

An example of going as far as making Rocksdb the [default option](https://github.com/desmos-labs/desmos/issues/111).

**Comment by faddat** [comment]
Have you tried with rocksdb?

I have been experimenting with badgerdb.

**Comment by blewater** [comment]
@faddat Same result but at least I can get a stripped tendermint node work with cleveldb. I haven't been successful in getting a v34 tendermint node launch with either v5.18.3 or latest v6 Rocksdb built in Ubuntu 20.04, Go 1.17.

**Comment by faddat** [comment]
@blewater sooooooo -- I did a bunch of work with RocksDB back in the day.  Can confirm that it is very, very performant.  

* Do we know if Desmos is still using Rocks only?  (seems not by a glance at Makefile, but not sure)
* One of the things that helped me a lot with working with all that low level C++ was using Arch linux, and yes, it is a pain to get rolling.  Also, I generally did not use gcc, but clang instead.  Maybe try making clang your default cxx like:

export CXX=clang

-- and you probably want to make sure it is the very latest clang.  

You might need to install additional libraries for this.  Our build process for Blurt was always pretty complex.  I think I've seen that badger is a pretty good set of tradeoffs between native Goness and speed.  That's what I am evaluating and here is how I am compiling-- note that I do not mess with the Makefile:

go install -tags badgerdb ./...

here's how I run osmosis:

```bash
ulimit -n 50000
osmosisd start --pruning nothing --db_backend badgerdb --p2p.seeds 1b077d96ceeba7ef503fb048f343a538b2dcdf1b@136.243.218.244:26656,2308bed9e096a8b96d2aa343acc1147813c59ed2@3.225.38.25:26656,902bdfe51b6a97cc9369664a21c87ed61d471d2a@136.243.218.243:26656,085f62d67bbf9c501e8ac84d4533440a1eef6c45@95.217.196.54:26656,f515a8599b40f0e84dfad935ba414674ab11a668@osmosis.blockpane.com:26656,63aba59a7da5197c0fbcdc13e760d7561791dca8@162.55.132.230:2000
```

Also I need to note that the ulimit thing is very important.  I now have a node syncing faster than I've ever seen before.

**Comment by faddat** [comment]
https://user-images.githubusercontent.com/7142025/144724185-f456cc10-5f49-4778-b8fa-0873bf8309e8.mov

**Comment by faddat** [comment]
go build -mod=readonly -tags "netgo ledger cleveldb gcc" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=osmosis -X github.com/cosmos/cosmos-sdk/version.AppName=osmosisd -X github.com/cosmos/cosmos-sdk/version.Version=3.1.0 -X github.com/cosmos/cosmos-sdk/version.Commit=13916d1e10bca718b6ea7f4b84715710bc319e6d -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,gcc" -X github.com/cosmos/cosmos-sdk/types.DBBackend=cleveldb -w -s' -trimpath -o /home/mar/go/src/github.com/osmosis-labs/osmosis/build/ ./...

**Comment by faddat** [comment]
your errors resemble this?

# github.com/jmhodges/levigo
../go/pkg/mod/github.com/jmhodges/levigo@v1.0.0/batch.go:4:11: fatal error: 'leveldb/c.h' file not found
 #include "leveldb/c.h"
          ^~~~~~~~~~~~~
1 error generated.

**Comment by faddat** [comment]
To make-happy goRocksdb, do exactly, on exactly arch linux:

```bash
pacman -Syyu rocksdb base-devel snappy cmake
```

go get github.com/tecbot/gorocksdb

**Comment by faddat** [comment]
I think that we can eliminate badgerdb from the competition.  It is really, really slow doing the update from v3.1.0 to v4.2.0

**Comment by blewater** [comment]
@faddat thanks for all the detailed input! 

> I think that we can eliminate badgerdb from the competition. It is really, really slow doing the update from v3.1.0 to v4.2.0, even with the caching changes. 

ACK

> I don't really see any advantages to using cleveldb-- are there any>?

Based on older community feedback at least modest performance improvements with a relatively easy build process. 
Have you tested it against the latest SDK nodes to validate whether it sustains its performance edge compared to goleveldb?

> Desmos is still using Rocks only? (seems not by a glance at Makefile, but not sure)

They still offer it as an option for validators to choose. https://docs.desmos.network/fullnode/rocksdb-installation/
But I haven't been able to run it following their instructions.

I distilled installation instructions for a functional Ubuntu (tested  in v20.04) rocksdb installation from this [issue](https://github.com/tecbot/gorocksdb/issues/126)
``` shell
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
git checkout v5.18.3
make clean
make shared_lib -j4
sudo cp --preserve=links ./librocksdb.* /usr/local/lib/
sudo cp -r ./include/rocksdb/ /usr/local/include/
sudo ldconfig
```
To test a successful check the following commands whether they link with the `rocksdb` shared lib.
Note the content of test.cpp is found [here](https://cdmana.com/2021/01/20210115215845374e.html)
```shell
cd /tmp
g++ -std=c++11 -o rocksdbtest test.cpp -lrocksdb -lpthread -ldl
./rocksdbtest
get bar success!!
```

Yet `gorocksdb` is still unhappy; I still run into the following issues when I run the following:
```shell
CGO_CFLAGS="-I/path/to/rocksdb/include" \
CGO_LDFLAGS="-L/path/to/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd" \
  go get github.com/tecbot/gorocksdb
# github.com/tecbot/gorocksdb
../../../../pkg/mod/github.com/roysc/gorocksdb@v1.1.1/transactiondb.go:255:17: could not determine kind of name for C.rocksdb_optimistictransactiondb_checkpoint_object_create
../../../../pkg/mod/github.com/roysc/gorocksdb@v1.1.1/transactiondb.go:208:12: could not determine kind of name for C.rocksdb_optimistictransactiondb_property_value
../../../../pkg/mod/github.com/roysc/gorocksdb@v1.1.1/transactiondb.go:236:2: could not determine kind of name for C.rocksdb_optimistictransactiondb_write
../../../../pkg/mod/github.com/roysc/gorocksdb@v1.1.1/transactiondb.go:59:12: could not determine kind of name for C.rocksdb_transactiondb_property_value
```
> If you value your time & sanity, do use arch linux. [Rocksdb installation]

Unfortunately, not an available option.

**Comment by faddat** [comment]
I built https://github.com/notional-labs/sos around arch because it was the only place I could get C++ builds to work correctly, consistently.  ah, I think you missed something in my directions-- check out the info on go.mod

**Comment by ValarDragon** [comment]
Sorry, behind on following up on this. Will read through in a bit more detail in a few days, currently trying to get v5 testing things through before focusing much more time on performance issues.

LevelDB is a pretty bad fit for our access patterns, so it seems like we should not use this. I'd heavily recommend not focusing on CLevelDB. Rocks DB and BadgerDB are the places we should put more focus on imo.

@valnodes is looking into the data structures / db configurations in more detail to get better opinions on which is better for our use case. We're also working on getting much better data access patterns in IAVL for most usecases.

**Comment by daniel-farina** [comment]
We decided to use rocksdb for now. There are significant issues with leveldb that will not work with our use case. Thank you for the suggestion!
