### ISSUE TITLE
feat(osmomath): introduce more mutative math helpers for `BigDec`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6370]
## Background

See the diff in this PR:
https://github.com/osmosis-labs/osmosis/pull/6369

Notice TODOs marked with "TODO: (perf)"

We can optimize our math by creating mutative versions of the linked math helpers on `BigDec` that do not reallocate the internal buffer.

## Suggested Design

For each individual helper, create a separate PR with the mutative versions that do not reallocate the internal buffer

## Acceptance Criteria
- One PR per helper for BigDec defined on `osmomath`
- Unit tests 
- All TODOs in https://github.com/osmosis-labs/osmosis/pull/6369 are resolved

**Comment by p0mvn** [comment]
Related work: https://github.com/osmosis-labs/osmosis/pull/6261

**Comment by hieuvubk** [comment]
@p0mvn Hi is anyone working on this?

**Comment by pysel** [comment]
hey @hieuvubk, I suppose it is free to pick up, since this has Help Wanted label! Thanks!
