### ISSUE TITLE
v20: Remove OSMO 2 hop route discount

### ISSUE THREAD

**Issue by osmosis-clickup** [osmosis-labs/osmosis#6373]
Slack Context 

The OSMO 2 hop router discount is being removed in v18. So, our router should no longer include that discount in our quoting logic.

**Comment by p0mvn** [comment]
CC: @AlpinYukseloglu for awareness about this issue.

**Comment by czarcas7ic** [comment]
@p0mvn is this referring to the frontend router?

**Comment by p0mvn** [comment]
No, this is the multihop OSMO discount that we have in poolmanager

**Comment by p0mvn** [comment]
@czarcas7ic  See this discussion: https://app.clickup.com/t/86a0t4467?comment=90130005156880&threadedComment=90130005156881

I think this is a follow-up to a gov prop

**Comment by czarcas7ic** [comment]
Gotcha, on it
