### ISSUE TITLE
[Feature]: Option 2: Add message as argument to TokenFactory send hooks

### ISSUE THREAD

**Issue by apollo-sturdy** [osmosis-labs/osmosis#6389]
### Summary

Add field `message: CosmosMsg` to `SudoMsg::TrackBeforeSend` and `SudoMsg::BlockBeforeSend` enum variants.

### Proposed Feature

There are currently two before send bank hooks for TokenFactory, `BlockBeforeSend` and `TrackBeforeSend`. These both have the arguments/fields `from: String`, `to: String`, and `amount: Coin`. It would be great if a fourth field `message` could be added with type [`CosmosMsg`](https://github.com/CosmWasm/cosmwasm/blob/main/packages/std/src/results/cosmos_msg.rs#L27). When a user sends coins in a CosmosMsg, this message would be included in the `BlockBeforeSend` and `TrackBeforeSend` hooks. This would allow contracts to conditionally perform actions depending on the kind of message.

### Example

User calls a contract with
```rust
CosmosMsg::Wasm(
    WasmMsg::Execute { 
        funds: Vec<Coin>,
        contract_addr: String,
        msg: Binary
    }
)
```
and sends coins with the funds field. Before executing the contract and transfering the coins to it, the chain would call `BlockBeforeSend` and `TrackBeforeSend` with the CosmosMsg as a field. The hook contract could then match on the message, see that it is a contract execution, check which contract is being executed and what action is being performed on the contract. If it is a specific action, it could for example block the send, deduct a tax from the user, or similar action.

**Comment by czarcas7ic** [comment]
@apollo-sturdy follow on question, would these message fields be useful in the Track/Block AfterSend fields as well? Or just the BeforeSend fields?

**Comment by mattverse** [comment]
@czarcas7ic AFAIK this is a alternative to the after send hooks

**Comment by apollo-sturdy** [comment]
> @apollo-sturdy follow on question, would these message fields be useful in the Track/Block AfterSend fields as well? Or just the BeforeSend fields?

Yes, I think for full flexibility would be good to have it in both.

**Comment by PaddyMc** [comment]
Closing, if this is still an issue ask here => https://github.com/strangelove-ventures/tokenfactory
