### ISSUE TITLE
[VS Incentives]: Investigate whether creating gauge ref keys is necessary for group gauges

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6405]
## Background

Investigate whether ref keys need to be created for group gauges. It seems this was added without fully exploring/understanding whether it is necessary so it should be double checked.

## Suggested Design

- Confirm necessity of ref link creation at end of `CreateGroupGauge`

## Acceptance Criteria

- Issue is settled and captured in comments & tests

**Comment by p0mvn** [comment]
For speed of delivery, I propose the following:
- `Group`s do not have a lifecycle. If `Group`'s underlying group `Gauge` has finished, the `Group` becomes unusable
- We gate `Group` creation by a high fee and governance
 * As a result, `Group` creation can either be achieved via high price r waiting for 5 days in voting
- Similar to CL pools, we create a sub-dao that can bypass governance and the fee for ease of management of internal incentive

**Comment by p0mvn** [comment]
more context: all external incentives use non-perpetual gauges. If we want external incentivizers to support, we should allow non-perpetual.

If we go with non-perpetual and no pruning, should leave opportunity to prune in the future

**Comment by p0mvn** [comment]
Conclusions from this issues have been discussed. The outcomes are transferred into TDD and follow-up issues. 

Next step: https://github.com/osmosis-labs/osmosis/issues/6434

Closing this
