### ISSUE TITLE
Consolidate code between incentives InitGenesis and CreateGauge

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#644]
We recently ran into testnets from state-exports crashing due to a slight inconsistency between Initgenesis and CreateGauge, that becomes an issue upon gauge deletion.

The actual bug was resolved, but not the underlying issue -- we have distinct code paths for lots of the create gauge and init genesis logic. We should consolidate this logic, to just have one code path.

**Comment by pwang00** [comment]
I think I have a solution implemented for this, but I need to test it locally before pushing.  Are the respective tests in `x/inventives/keeper/gauge_test.go`?
