### ISSUE TITLE
[CI][State Compat] Fail state compat check if app hash is detectted

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6455]
## Background

Currently, if an app hash is detected, we do not fail the CI and it keeps on running:
https://github.com/osmosis-labs/osmosis/pull/6449

This leads to confusion and time wasted waiting for nothing (unless you check ofc)

## Suggested Design

Still, for better feedback loop, we should detect an app hash and fail the CI if it occurs

## Acceptance Criteria
- fail state compact CI if app hash is detected

**Comment by anhductn2001** [comment]
I think it is difficult to detect the app hash. The best way currently in my mind is to set a timeout for this job. If you agree I will do it. @p0mvn

**Comment by ValarDragon** [comment]
I believe this is solved?
