### ISSUE TITLE
rename(osmomath): PrecisionDec-> DecPrecision

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6466]
I feel like we should change to DecPrecision at some point 🤔

_Originally posted by @mattverse in https://github.com/osmosis-labs/osmosis/pull/6261#discussion_r1328200393_

**Comment by mattverse** [comment]
@p0mvn Do you have thoughts on PrecisionDec vs DecPrecision? 

As originally discussed in the PR, I think having the Dec Suffix is confusing, leading us to think that it is returning a Dec object thus be changed to DecPrecision (just for code sanity wise). wdyt?

**Comment by p0mvn** [comment]
I'm happy with the change. There is also a `PrecidisionBigDec` that we should update to `BigDecPrecision` for consistency

**Comment by pysel** [comment]
personally, `DecPrecision` sounds as if it returns `Dec`'s precision. doesn't `DecWithPrecision` make more sense in this context?

**Comment by p0mvn** [comment]
@pysel I think @mattverse meant renaming PrecisionDec to DecPrecision and not DecWithPrecision like originally assumed

**Comment by pysel** [comment]
Oh, I see! Sorry for confusion. Makes total sense then
