### ISSUE TITLE
IBC minor version bump for penumbra support?

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#6482]
>Penumbra has contacted us asking to backport to the v4 release line a bump of ics23 to v0.10.0. This version of ics23 added [the field ](https://github.com/cosmos/ics23/pull/136)prehash_compare_key[ to the SMT proof spec to support proving nonexistence in sparse trees](https://github.com/cosmos/ics23/pull/136). It was thought initially that counterparties didn't need to upgrade to this version of ics23 to open a connection with Penumbra, but it turns out that this assumption is not correct because the [Cosmos SDK rejects unknown fields](https://github.com/cosmos/cosmos-sdk/blob/a3a049bc2577632b94ff2236c2b01a250e85b16d/x/auth/tx/decoder.go#L27) (so even if all the fields in the proof spec are optional, if the counterparty does not know the prehash_compare_key field, then the transaction will fail).
The connection to Osmosis is Penumbra's top priority at the moment, and they said that you would be able to do an upgrade to a new minor version of v4 in approximately 3 or 4 weeks. 

ref https://osmosis-network.slack.com/archives/C03NA1C6JSX/p1695018978663109

**Comment by ValarDragon** [comment]
Yeah, we should bump this IBC version!

**Comment by hdevalence** [comment]
There's a new version of `ibc-go` out now: https://github.com/cosmos/ibc-go/issues/4710

**Comment by hdevalence** [comment]
Flagging this comment: https://github.com/osmosis-labs/osmosis/pull/6643#issuecomment-1751394570

I think the changes in #6653 don't remove the replace directive on the ICS23 dep, which was the content of the 4.5 update, so this wouldn't be closed by #6653 as yet.

**Comment by avahowell** [comment]
The replace directive was later removed, so this can be closed now. Penumbra<>Osmosis IBC is tested and working
