### ISSUE TITLE
[VS Incentives]: Ensure denom spam vector is accounted for in group gauge creation

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6491]
## Background

Similar to regular gauge creation, group gauges have the potential spam vector of creating an arbitrary number of denoms which are linearly iterated over during gauge distribution. We should ensure that this is protected against with a linearly scaling gas fee as is done with regular gauge creation.

## Suggested Design

- Linearly scale gas with number of denoms, similar to how it is done here:
https://github.com/osmosis-labs/osmosis/blob/b7c73fbcf351ffe0a5666443557a41aaf398d7a4/x/incentives/keeper/gauge.go#L189

## Acceptance Criteria

- New guardrail is tested
- All existing tests pass

**Comment by p0mvn** [comment]
Addressed
