### ISSUE TITLE
Refactor general math functions to be in our own osmo-math library

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#65]
I think we will have a growing number of math operations that we will need high precision & fast implementations of. I think we should move such functions & related types into its own `osmo-math` package in the root directory. For now, `Pow` with fractional exponent would go in there.

**Comment by sunnya97** [comment]
@ValarDragon should this be #post-launch?

**Comment by ValarDragon** [comment]
Yes
