### ISSUE TITLE
feat: add message for transferring CL position ownership

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6541]
## Background

We need a message for transferring CL position ownership.

## Suggested Design

- Implement `MsgTransferPosition`
- Under the hood withdraws the position and creates it on behalf of receiver
- Add spam prevention mechanism of min USD value to be eligible for tansfer
- Consider special casing community pool to bypass restriction

## Acceptance Criteria
- Message implemented
- Unit tested
- Local osmosis tested

**Comment by pysel** [comment]
> Add spam prevention mechanism of min USD value to be eligible for tansfer

asking to learn: doesn't the required gas paid for this transaction already prevents potential spam attacks?
