### ISSUE TITLE
Feegrant module absent

### ISSUE THREAD

**Issue by cryptonrd** [osmosis-labs/osmosis#6563]
### What happened?

I was trying to authorize an account to pay fees using balance present in another account. I've seen this feature is available in cosmos-sdk, and the module seems to be there in the osmosis cosmos-sdk fork, but when tryint to use it with the CLI, it is absent.

I also tried creating a transaction template with gaiad and then adjust the values and sign it with osmosisd, but the message is not registered.

Is there any current alternative to use this feature or are there any plans to add it back with the sdk unfork?

### Osmosis Version

19.1.0

### How to reproduce?

In the CLI:

`osmosisd tx feegrant grant --help`

Module is not present.

**Comment by ValarDragon** [comment]
There is not currently a plan to add it into Osmosis, due to complex interactions it has with other modules.
