### ISSUE TITLE
[VS Incentives]: Add sync step to Group creation logic

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6581]
## Background

Currently Groups have all their weights initialized to zero when they are created. While we want to keep this as a first step, it is important that we also ensure that invalid Groups cannot be created (e.g. for pools that have issues related to volume tracking) and that weights are never zero to avoid division by zero panics (it seems one such bug was already encountered.

The guardrail I had intended to put in place but seems to have not made it into any issue (my bad!) is to run a cycle of `syncGroupWeights` after the Group is initialized with zero weights, and then properly handle the error (instead of quietly skipping it like we do in epoch code). This has a couple benefits:
1. Guarantees that all Groups are at least valid when they are created
2. Gives each created Group a base set of weights to fall back to if there are any issues after creation
3. Avoids having the first epoch for volume splitting be based on cumulative volumes (which would presumably favor the oldest pool instead of the highest last-epoch volume one)

## Suggested Design

* See above

## Acceptance Criteria

- All new and existing tests should pass
- Tests should be added to ensure that attempts at Group creation with an invalid internal gauge (e.g. a non-OSMO paired token with untrackable volume) error

**Comment by p0mvn** [comment]
Agree with the issue as a whole but something that stood out to me:

> Gives each created Group a base set of weights to fall back to if there are any issues after creation

What is the fallback mechanism you're referring to? I think that in either case if there is an issue in one of the pools, the group would fail to sync and would always be skipped

> Avoids having the first epoch for volume splitting be based on cumulative volumes (which would presumably favor the oldest pool instead of the highest last-epoch volume one)

In the original scenario, the cumulative volume would be equivalent to the current volume at the very first epoch. The fact that a pool is the oldest is irrelevant since we don't track volume from the max(pool creation time, volume tracking launch)

**Comment by AlpinYukseloglu** [comment]
> What is the fallback mechanism you're referring to? I think that in either case if there is an issue in one of the pools, the group would fail to sync and would always be skipped

For context this only applies for Groups that already include invalid pools at creation. When the syncing process is "skipped" due to an issue with a pool, this is functionally equivalent to falling back to the existing weights. If the Group is guaranteed to be valid and we do a first sync at creation, then when we get to the first distribution, it syncs again and now has up to date `CurrentWeight`s that track volume in the last epoch (or since creation). Note how now, it is not possible for the Group sync to error and fall back to weights of zero, which are technically invalid weights for allocation logic.

> In the original scenario, the cumulative volume would be equivalent to the current volume at the very first epoch. The fact that a pool is the oldest is irrelevant since we don't track volume from the max(pool creation time, volume tracking launch)

Right, but if the first epoch distributes based on _cumulative_ volume as the current weight, then this will strongly favor pools that have been accumulating volume for a long time. For instance, if in 1 year we launch a new USDC/NEWTOKEN pool and volume split it with a pool that's been around since this feature's launch, the latter will get almost all the incentives for the first epoch (which will sync based on cumulative volume).

Happy to discuss offline if either I misunderstood your questions or you'd like to discuss further!

**Comment by p0mvn** [comment]
I will DM @AlpinYukseloglu
