### ISSUE TITLE
Is it a typo?

### ISSUE THREAD

**Issue by ajansari95** [osmosis-labs/osmosis#659]
code- https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/genesis.proto#L2

Was just scrolling through the proto files, found that v1beta1 is not included in the above proto package, is it a typo or for any specific reason?

**Comment by ValarDragon** [comment]
Yeah good catch, not sure whats going on there either. Going to close this and add it as another item in #682
