### ISSUE TITLE
Light theme now please!!!

### ISSUE THREAD

**Issue by bitcoinmeetups** [osmosis-labs/osmosis#6596]
Light theme please!!! I cannot see anything on my special type of screen. Why no themes? Please prioritize, it is uncomfortable to use the website at the moment.

**Comment by pysel** [comment]
hey @bitcoinmeetups. thanks for reaching out! 

this repository is responsible for a core protocol logic, frontend is out of scope of this repo.

I suggest you open in issue here: https://github.com/osmosis-labs/osmosis-frontend, it will probably be a good place to discuss the matter!

**Comment by p0mvn** [comment]
CC: @jonator

**Comment by p0mvn** [comment]
Thanks for the request. This is now tracked internally by our frontend team: https://app.clickup.com/t/86a0z8mup
