### ISSUE TITLE
Osmosis-sdk vs cosmos-sdk & ibc-go upgrades

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#662]
Hi!

so, recently ibc-go v2.0.2 came out and it bumps iavl and the cosmos-sdk.  

Should I/we:

* Bump only ibc-go
* In a ludicrously careful process, make merge commit(s) so that cosmos-sdk merges into osmosis-sdk easily and after that, follow along with upstream when bumpings happen?

**Comment by ValarDragon** [comment]
I think we basically just went with only bumping ibc-go in v6, but have ended up bumping iavl since. (You did the iavl bump =) ) 

Don't really plan on updating the SDK yet, purely since it has no changes that would impact next release, and we want to update to SDK v0.45.0 as soon as its out anyway
