### ISSUE TITLE
CI: require every TODO introduced in a pull request have a link to a corresponding issue in the repository

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#6659]
## Background

It would be useful to have a CI workflow that would require every TODO in a PR to include a link to a corresponding issue in the line below. It would significantly improve repository quality.

Though, there should be a way to bypass it, if needed

## Suggested Design

Fail CI if a PR introduces a line with TODO without a link to the issue attached on a line below (with a way to bypass it)

## Acceptance Criteria

workflow implemented

**Comment by pysel** [comment]
before starting to work on it, I would like to hear other folks' opinions on this one!

cc: @mattverse @p0mvn @ValarDragon

**Comment by ValarDragon** [comment]
I don't think we should do this
