### ISSUE TITLE
[Feature]: osmosisd: Query pool by coin denom

### ISSUE THREAD

**Issue by jasbanza** [osmosis-labs/osmosis#6712]
### Summary

A new osmosisd poolmanager query to return a list of pools, filtered by token denom.

### Problem Definition

There is currently no way to query LPs where a token is listed.
It would be great to simply enter a command in osmosisd CLI with a given token denom.

### Proposed Feature

Add a new CLI command:
`osmosisd q poolmanager list-pools-by-denom [denom]`

**Comment by hieuvubk** [comment]
Is anyone working on this?

**Comment by DongLieu** [comment]
can i handle it?
