### ISSUE TITLE
End-to-end IBC tests

### ISSUE THREAD

**Issue by adizere** [osmosis-labs/osmosis#672]
# Problem statement

The recent IBC connection creation problem (#665) highlights that end-to-end testing of Osmosis releases would be important. This testing ideally would take place in an IBC testnet, running with an actual relayer.

# Proposal

In ibc-rs, to test the functionality of Hermes, we do end-to-end tests in CI against two gaiad chains. This CI setup achieves the following: (1) spins up 2 gaiad networks in Docker (each network consisting of a single node), and (2) runs Hermes alongside those two networks and triggers a series of IBC transactions and scenarios to tests that Hermes works correctly.

More details can be found here:
https://github.com/informalsystems/ibc-rs/tree/master/ci#continous-integration-for-ibc-rs

I think a similar CI setup could be easily achievable for Osmosis. The requirement, at a high-level, is to be able to run an Osmosis single-node network in a Docker, and then to scaffold two such networks and run the relayer between them. The readme above gives some instructions (in particular [this section](https://github.com/informalsystems/ibc-rs/tree/master/ci#upgrading-the-gaia-chains-release-and-generating-new-container-images)) on how we maintain the Gaiad binaries, which are probably useful in doing so for Osmosis.

If there is interest in adding such a end-to-end test in your CI, we'd be happy to help review and maintain the work.

Note: This may be a sub-task of #656, but the scope of that issue is not really clear.

**Comment by ValarDragon** [comment]
We should definitely add CI for this, thank you for pointing out the ibc-rs work for CI here!

**Comment by nooomski** [comment]
We're interested in the [same thing](https://github.com/cosmos/gaia/issues/1048). Wondering if there's a sensible way to work together on this?

**Comment by ValarDragon** [comment]
Closed by https://github.com/osmosis-labs/osmosis/pull/1216
