### ISSUE TITLE
Adding --gas=auto to any cli cmd causes error

### ISSUE THREAD

**Issue by rohitbison** [osmosis-labs/osmosis#673]
On v6.0.0 osmosisd cli, adding `--gas=auto` ends up returning this error:

```
Error: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = invalid empty tx: invalid request
Usage:
  osmosisd tx distribution withdraw-rewards [validator-addr] [flags]

Flags:
```

**Comment by rohitbison** [comment]
@ValarDragon

**Comment by ValarDragon** [comment]
We've seen a bunch of people having issues with this. Need to figure out whats going on, and roll it into next minor version

**Comment by UnityChaos** [comment]
I tried to replicate this back when it was first posted and wasn't able to. Tried again now and still not able to. Only thing I can figure is that there was some problem in the build process? (such as needing to run `go mod vendor` which I originally had to when switching the repo to v6.0.0)

**Comment by ValarDragon** [comment]
Can you try again on v6.0.0, and re-open if the problem persists?
