### ISSUE TITLE
[SQS] Move closer to v1 of the implementation

### ISSUE THREAD

**Issue by PaddyMc** [osmosis-labs/osmosis#6749]
## Background

The side car query server is designed to optimise pool routes for third parties that wish to enable optimal route transaction though Osmosis pools

- [ ] Same algorithm for finding routes as FE implemented
- [ ] Direct quote prototype over CFMM pools are almost complete
- [ ] Split route quotes over CFMM is the next step
- [ ] Start adding CL and CW pools into the set up after

## Acceptance Criteria

- SQS has an implementation the above task

**Comment by ValarDragon** [comment]
I believe this can be closed now, as v1 is in prod!
