### ISSUE TITLE
Increase default CLI gas from 200k to 350k

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#675]
Currently the CLI defaults gas used to 200k if nothing is provided. Not really sure why its defaulting to a constant vs gas=auto.

But given that it is defaulting to something, and cases will likely persist where it defaults, we should bump the default imo. Its an unnecessary headache for CLI folks first interacting with the chain.

I suggest we bump the default 200k to 350k.

**Comment by mattverse** [comment]
This happens to be set as a constant in the sdk side. Will create a PR in the cosmos SDK in osmosis repo and address issue for it
