### ISSUE TITLE
Update our SDK dependency to SDK v0.45.x

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#676]
We should update our SDK dependency to SDK v0.45.x branch. This would be done by cherry-picking all of our changes on the v0.44.x branch, onto a new v0.45.x branch.

This is on the critical path for integrating cosmwasm.

**Comment by faddat** [comment]
I hate that I love to do this?

not really.  It taught me so much last time.  I'd like to give it another go.

**Comment by faddat** [comment]
https://github.com/CosmWasm/wasmd/issues/685

If it is alright with the other osmo contributors, I'd prefer to get to a git graph that looks more like the final image there, it is far easier to maintain over time, though more difficult at first.

**Comment by ValarDragon** [comment]
The way we did it last time, and would prefer to do this time would be to go through our commit history and cherry pick each of our commits onto `v0.45.x` (and remove from cherry-pick any commits that landed upstream)

**Comment by faddat** [comment]
Happy to-- would you mind explaining why this is preferable?

**Comment by daniel-farina** [comment]
Currently blocked until SDK v0.45.x is ready. ETA: end of this week or next week.

**Comment by ValarDragon** [comment]
> Happy to-- would you mind explaining why this is preferable?

Yeah! A couple reaosns:
- Rebasing our changes onto the SDK 45 causes a bunch of git merge errors, and is actually super hard to review. (Theres typically a merge conflict for every commit to the same file, which makes it really hard to resolve, and at the end can't be cleanly reviewed)
- Its no longer then easy to tell what are different changes from our repo and main SDK

So with the cherry-picks:
- Its much easier to just do
- Its easy to skim and see our custom changes
- Easy to take out changes we've upstreamed during this time
