### ISSUE TITLE
[Bug]: TxFee Module does not allow routing through Supercharged pools

### ISSUE THREAD

**Issue by JohnnyWyles** [osmosis-labs/osmosis#6783]
### What happened?

The TXFee module allows different assets to be used as gas fees on Osmosis and then swapped through a specified pool at epoch.

This list of assets is maintained as a whitelist of denom and pool ID paired.

Adding a route that uses a Supercharged pool is not valid and gets the following error:
`Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: pool with ID 59 does not exist: invalid proposal content: invalid request`

Pool 59 is the OSMO/JUNO Supercharged pool on testnet.

From @p0mvn:
> Looked into this. The problem is that we use gamm module as the spot price calculator:
> https://github.com/osmosis-labs/osmosis/blob/68dd76d47c1a53475f556a52ef48bf37cb7a99b7/app/keepers/keepers.go#L385
> Poolmanager needs to be given here.

Urgency - as most new pools are made as Supercharged pools now, this blocks the use of the main pools of:
* USDC
* USDT
* TIA
* DYDX
as gas tokens, making this quite urgent for onboarding users of these chains/stables.

We can work around this by booting up an OSMO/X classic pool for each, but obtaining liquidity may be an issue.
I think, eventually, we should also be using Protorev routes to find a route that does not require a direct OSMO pairing also as these may also become less common.

### Osmosis Version

12.1.0

### How to reproduce?

Testnet transaction:
`osmosisd tx gov submit-proposal update-fee-token --fee-tokens ibc/8E2FEFCBD754FA3C97411F0126B9EC76191BAA1B3959CB73CECF396A4037BBF0,59 --title="Update Fee Token Test" --from=osmo19mywfjzj324w5ukf7ss6jak0dg9hnljfp0rfx4 --description="Testing that fee tokens move through CL pools without issue and do not overwrite all existing settings. \n\n * Adds JUNO through CL pool 59 as fee token. \n* Should not impact ION through pool 1" --deposit=125000000uosmo --from=osmo19mywfjzj324w5ukf7ss6jak0dg9hnljfp0rfx4 --gas=auto --gas-prices 0.0025uosmo --gas-adjustment 1.3 --node="[https://rpc.osmotest5.osmosis.zone:443](https://rpc.osmotest5.osmosis.zone/)" --chain-id="osmo-test-5"`

Results in the error above

**Comment by ValarDragon** [comment]
Fixed on Jan 8
