### ISSUE TITLE
Remove `PoolAsset` and manage corresponding fields in Balancer Params

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#681]
Implementing gamm module generalization for different pool-models, we should move `poolAsset` in pool.proto into balancerParams or balancerPool. Token and token weights should be managed within the balancerPool package for better generalization of the gamm module.

**Comment by mconcat** [comment]
We may need to move pool weights into the balancer pool model, but not the pool assets, for managing the assets on the keeper side. Ref #131
