### ISSUE TITLE
Investigate v1beta1 in proto files

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#682]
Both the cosmos-sdk and osmosis repo has a convention of placing proto files of a module under a v1beta1 folder. 
We want to understand the reason or functionality behind this and remove these if possible for better code-hygiene

**Comment by ValarDragon** [comment]
Needs decision / status if this worth the migration cost, or if it even is a migration cost atm

**Comment by ValarDragon** [comment]
So we should make the new gamm work use v1beta1. Also we should see why the old gamm proto files, don't include `v1beta1` in their import. Thanks @ajansari95 for pointing this out, https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/genesis.proto#L2

We need to see if updating these is state breaking / proto breaking, or client breaking. And if so, evaluate whether its worth it or not.

**Comment by mattverse** [comment]
Does this mean that we put all proto files under `osmosis/proto/osmosis/gamm/v1beta1`?

**Comment by ValarDragon** [comment]
Yeah we should. But also need to figure out if we need to add `v1beta1` into the import

**Comment by mattverse** [comment]
This change would be state breaking. Also, if we're putting all proto files under `osmosis/proto/osmosis/gamm/v1beta1` we would also need to include v1beta1 into the import. 
Luckily https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/genesis.proto#L2 was not included in a release, we would not have to go through a state breaking update in order to fix this.
