### ISSUE TITLE
Add migration logic to tokenfactory module

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#689]
Need to initialize the storekey for the tokenfactory module for when doing an in-place migration.  Required for next upgrade.

**Comment by sunnya97** [comment]
@ValarDragon @alexanderbez do you know how I'm supposed to do this?  Is there an example somewhere?

**Comment by ValarDragon** [comment]
https://github.com/osmosis-labs/osmosis/blob/main/app/app.go#L407-L411

**Comment by alexanderbez** [comment]
Seems pretty straight forward

**Comment by sunnya97** [comment]
Added into #1362
