### ISSUE TITLE
Create stableswap

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#690]
Now that gamm generalization is mostly merged, we should aim to make a stableswap be the next new pool type.  I propose using the Curve v1 model as inspiration (as described in the whitepaper:  https://curve.fi/files/stableswap-paper.pdf)

**Comment by ValarDragon** [comment]
The actual pool interface doesn't specify necessary / sufficient methods for use in the keeper. We need to add scaffolding for different types still.

**Comment by ValarDragon** [comment]
We have better indexes of steps here
