### ISSUE TITLE
Add any other relevant docs from other repos

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#691]
Sub task from #581 
We need to hunt down all documentation from other repos, including front-end and add them to the official docs. A follow up will be needed in to then remove these docs from the original source and link them to the official docs.

**Comment by daniel-farina** [comment]
@czarcas7ic  and @daniel-farina  had a conversation about this today. Moving it to Sprint 4, low priority for now.

**Comment by czarcas7ic** [comment]
Closing and reopening in the osmosis docs repo
