### ISSUE TITLE
fix: total liquidity poolmanager grpc gateway query

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6941]
## Background

We need to fix the path to avoid overlapping with pools:
https://github.com/osmosis-labs/osmosis/blob/8be655fec88104b2c796f67f0dba7b58a7150bc8/proto/osmosis/poolmanager/v1beta1/query.proto#L115-L119

Similar fix to: https://github.com/osmosis-labs/osmosis/pull/6939

**A/C**
- Fix implemented
- Test on localosmosis

**Comment by DongLieu** [comment]
can i handle it?
