### ISSUE TITLE
Only allow a single swap fee and exit fee for new pools

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#700]
I think this is a good simple first step in the process of re-imagining the Osmosis pool swap fees model.

I know we want more complex features going forward, but this is a good starting point to start building off of

**Comment by ValarDragon** [comment]
I don't agree for swap fee:
https://github.com/osmosis-labs/osmosis/pull/702#issuecomment-1002859444

**Comment by ValarDragon** [comment]
Closing for now, lets re-open discussion if this is something that wants to be revisited
