### ISSUE TITLE
chore: update actions/labeler from 4.3.0 to 5.0.0

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#7008]
## Background

Note that actions/labeler from 4.3.0 to 5.0.0 is a breaking change.

We should update the structure of https://github.com/osmosis-labs/osmosis/blob/main/.github/labeler.yml to be compatible with the update.

## Acceptance Criteria
- https://github.com/osmosis-labs/osmosis/blob/main/.github/labeler.yml 
- updated actions/labeler from 4.3.0 to 5.0.0
- Labeler CI passes

**Comment by umbr4g3** [comment]
@p0mvn can I work on this? Funny enough I enjoy debugging GitHub Actions. I should be able to test everything and ensure the labeler works within my fork.
