### ISSUE TITLE
Start the internal error

### ISSUE THREAD

**Issue by leezijie** [osmosis-labs/osmosis#717]
https://docs.osmosis.zone/developing/network/join-mainnet.html#install-osmosis-binary
When I'm done with this procedure, the following error is reported when the "cosmovisor start" command is used to start the system.Please help me.

10:47AM INF starting ABCI with Tendermint
10:47AM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:47AM INF Starting localClient service connection=query impl=localClient module=abci-client
10:47AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:47AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:47AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:47AM INF Starting EventBus service impl=EventBus module=events
10:47AM INF Starting PubSub service impl=PubSub module=pubsub
10:47AM INF Starting IndexerService service impl=IndexerService module=txindex
10:47AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=6.0.0
10:47AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
10:47AM INF initializing blockchain state from genesis.json
10:47AM INF running initialization for module module=capability
10:47AM INF running initialization for module module=auth
10:47AM INF running initialization for module module=bank
10:47AM INF running initialization for module module=distribution
10:47AM INF running initialization for module module=staking
10:47AM INF running initialization for module module=slashing
10:47AM INF running initialization for module module=gov
10:47AM INF running initialization for module module=mint
10:47AM INF minted coins from module account amount=225000000000000uosmo from=developer_vesting_unvested module=x/bank
10:47AM INF running initialization for module module=crisis
10:47AM INF asserting crisis invariants inv=0/13 module=x/crisis name=distribution/nonnegative-outstanding
10:47AM INF asserting crisis invariants inv=1/13 module=x/crisis name=distribution/can-withdraw
10:47AM INF asserting crisis invariants inv=2/13 module=x/crisis name=distribution/reference-count
10:47AM INF asserting crisis invariants inv=3/13 module=x/crisis name=distribution/module-account
10:47AM INF asserting crisis invariants inv=4/13 module=x/crisis name=staking/module-accounts
10:47AM INF asserting crisis invariants inv=5/13 module=x/crisis name=staking/nonnegative-power
10:47AM INF asserting crisis invariants inv=6/13 module=x/crisis name=staking/positive-delegation
10:47AM INF asserting crisis invariants inv=7/13 module=x/crisis name=staking/delegator-shares
10:47AM INF asserting crisis invariants inv=8/13 module=x/crisis name=gamm/pool-account-balance-equals-expected
10:47AM INF asserting crisis invariants inv=9/13 module=x/crisis name=gamm/pool-total-weight
10:47AM INF asserting crisis invariants inv=10/13 module=x/crisis name=bank/nonnegative-outstanding
10:47AM INF asserting crisis invariants inv=11/13 module=x/crisis name=bank/total-supply
10:47AM INF asserting crisis invariants inv=12/13 module=x/crisis name=gov/module-account
10:47AM INF asserted all invariants duration=269.209956 height=0 module=x/crisis
10:47AM INF running initialization for module module=ibc
10:47AM INF running initialization for module module=genutil
panic: internal

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs(0x29f6a20, 0xc000054080, 0x2a11f40, 0xc000e5ab40, 0x0, 0x0, 0xc0012bea00, 0x9, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/genutil/gentx.go:113 +0x328
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis(0x29efca0, 0xc0005250e0, 0x29aca80, 0xc000f8fef0, 0xc00100ab90, 0x7f748ac27118, 0xc000380000, 0x29f6a20, 0xc000054080, 0x2a11f40, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/genutil/module.go:99 +0x198
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc0000ee1c0, 0x29f6a20, 0xc000054080, 0x2a11f40, 0xc000e5ab40, 0x0, 0x0, 0xc0012bea00, 0x9, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:310 +0x4f5
github.com/osmosis-labs/osmosis/app.(*OsmosisApp).InitChainer(0xc0001b7900, 0x29f6a20, 0xc000054080, 0x2a11f40, 0xc000e5ab40, 0x0, 0x0, 0xc0012bea00, 0x9, 0x0, ...)
	github.com/osmosis-labs/osmosis/app/app.go:753 +0x230
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0003b3ba0, 0x0, 0xed85ec810, 0x0, 0xc0012bea00, 0x9, 0xc0001fdaa0, 0x3b79b40, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:62 +0x358
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00116ef60, 0x0, 0xed85ec810, 0x0, 0xc0012bea00, 0x9, 0xc0001fdaa0, 0x3b79b40, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0000fcee0, 0x0, 0xed85ec810, 0x0, 0xc0012bea00, 0x9, 0xc0001fdaa0, 0x3b79b40, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc005057b98, 0xb, 0x0, 0x2073b06, 0x7, 0xc0012bea00, 0x9, 0x1, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0x695
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc005057b98, 0x2a13400, 0xc0001ee410, 0x1, 0x1)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x478
github.com/tendermint/tendermint/node.doHandshake(0x2a0ec40, 0xc0000fd6a0, 0xb, 0x0, 0x2073b06, 0x7, 0xc0012bea00, 0x9, 0x1, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0011ebb80, 0x29ec9e0, 0xc0000cf400, 0xc0000fcc10, 0x29aa600, 0xc0001fd600, 0xc0000fcc80, 0x2784c10, 0xc0000fcd70, 0x29f7920, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x20a5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0012e25e0, 0x0, 0x0, 0x0, 0x2a1f0a0, 0xc001313620, 0x0, 0x0, 0x2a01220, 0xc0011e6d80, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:263 +0x665
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00122db80, 0xc0012e2700, 0x0, 0x2, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:129 +0x1ec
github.com/spf13/cobra.(*Command).execute(0xc00122db80, 0xc0012e26e0, 0x2, 0x2, 0xc00122db80, 0xc0012e26e0)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00121e000, 0x0, 0x0, 0xc0011e8880)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/osmosis-labs/osmosis/cmd/osmosisd/cmd.Execute(0xc00121e000, 0x2a01280, 0xc001189a80)
	github.com/osmosis-labs/osmosis/cmd/osmosisd/cmd/root.go:150 +0x158
main.main()
	github.com/osmosis-labs/osmosis/cmd/osmosisd/main.go:13 +0x2f
exit status 2

**Comment by ValarDragon** [comment]
This looks like you skippped the "Download Chain Data" section of the guide!

**Comment by leezijie** [comment]
> This looks like you skippped the "Download Chain Data" section of the guide!

Oh yes, I skipped it. What is the difference between pruned and default.

**Comment by ValarDragon** [comment]
Its from the SDK's pruning modes. Basically how much of history you want to be able to query. If you don't care about querying blocks older than now, you can use pruned. if you want to query only a couple historical heights prior to download height, and certain 'threshold blocks' (Every 500th IIRC?) you can use default pruning.

This doesn't matter for after the sync height. So if you just want to join the network, and query latest state, you can download a pruned node, and then run a default pruning setup afterwards.

**Comment by leezijie** [comment]
> Its from the SDK's pruning modes. Basically how much of history you want to be able to query. If you don't care about querying blocks older than now, you can use pruned. if you want to query only a couple historical heights prior to download height, and certain 'threshold blocks' (Every 500th IIRC?) you can use default pruning.
> 
> This doesn't matter for after the sync height. So if you just want to join the network, and query latest state, you can download a pruned node, and then run a default pruning setup afterwards.
Thank you so much. It's been very helpful
