### ISSUE TITLE
[Bug]: Failing to initialize home folder due to `app.toml` config initialization

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#7179]
### What happened?

A bug happened!

Failing to initialize home folder due to `app.toml` config initialization

### Osmosis Version

v21

### How to reproduce?

```
osmosisd init test --home=.osmosisd-conf
Error: failed to parse .osmosisd-conf/config/app.toml: '' expected a map, got 'interface'
```

**Comment by PaddyMc** [comment]
closing as this has been solved :bow:
