### ISSUE TITLE
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by ducknessman** [osmosis-labs/osmosis#718]
iI have question 

the error info 
5:53AM INF starting ABCI with Tendermint
5:53AM INF Starting multiAppConn service impl=multiAppConn module=proxy
5:53AM INF Starting localClient service connection=query impl=localClient module=abci-client
5:53AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
5:53AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
5:53AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
5:53AM INF Starting EventBus service impl=EventBus module=events
5:53AM INF Starting PubSub service impl=PubSub module=pubsub
5:53AM INF Starting IndexerService service impl=IndexerService module=txindex
5:53AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=6.0.0
5:53AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
5:53AM INF initializing blockchain state from genesis.json
5:53AM INF running initialization for module module=capability
5:53AM INF running initialization for module module=auth
5:53AM INF running initialization for module module=bank
5:53AM INF running initialization for module module=distribution
5:53AM INF running initialization for module module=staking
5:53AM INF running initialization for module module=slashing
5:53AM INF running initialization for module module=gov
5:53AM INF running initialization for module module=mint
5:53AM INF minted coins from module account amount=225000000000000stake from=developer_vesting_unvested module=x/bank
5:53AM INF running initialization for module module=crisis
5:53AM INF asserting crisis invariants inv=0/13 module=x/crisis name=bank/nonnegative-outstanding
5:53AM INF asserting crisis invariants inv=1/13 module=x/crisis name=bank/total-supply
5:53AM INF asserting crisis invariants inv=2/13 module=x/crisis name=distribution/nonnegative-outstanding
5:53AM INF asserting crisis invariants inv=3/13 module=x/crisis name=distribution/can-withdraw
5:53AM INF asserting crisis invariants inv=4/13 module=x/crisis name=distribution/reference-count
5:53AM INF asserting crisis invariants inv=5/13 module=x/crisis name=distribution/module-account
5:53AM INF asserting crisis invariants inv=6/13 module=x/crisis name=staking/module-accounts
5:53AM INF asserting crisis invariants inv=7/13 module=x/crisis name=staking/nonnegative-power
5:53AM INF asserting crisis invariants inv=8/13 module=x/crisis name=staking/positive-delegation
5:53AM INF asserting crisis invariants inv=9/13 module=x/crisis name=staking/delegator-shares
5:53AM INF asserting crisis invariants inv=10/13 module=x/crisis name=gov/module-account
5:53AM INF asserting crisis invariants inv=11/13 module=x/crisis name=gamm/pool-account-balance-equals-expected
5:53AM INF asserting crisis invariants inv=12/13 module=x/crisis name=gamm/pool-total-weight
5:53AM INF asserted all invariants duration=3.098285 height=0 module=x/crisis
5:53AM INF running initialization for module module=ibc
5:53AM INF running initialization for module module=gamm
5:53AM INF running initialization for module module=txfees
5:53AM INF running initialization for module module=genutil
5:53AM INF running initialization for module module=evidence
5:53AM INF running initialization for module module=transfer
5:53AM INF created new capability module=ibc name=ports/transfer
5:53AM INF port binded module=x/ibc/port port=transfer
5:53AM INF claimed capability capability=1 module=transfer name=ports/transfer
5:53AM INF running initialization for module module=bech32ibc
5:53AM INF running initialization for module module=poolincentives
5:53AM INF running initialization for module module=claim
5:53AM INF minted coins from module account amount= from=claim module=x/bank
5:53AM INF running initialization for module module=incentives
5:53AM INF running initialization for module module=epochs
5:53AM INF running initialization for module module=lockup
5:53AM INF running initialization for module module=authz
5:53AM INF Done init genesis
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

my version 
cosmovisor  version
name: osmosis
server_name: osmosisd
version: 6.0.0
commit: dfe74a35ccc7f8a182b7a9ca943e9bc720ab1f51
build_tags: netgo,ledger
go: go version go1.17.3 linux/amd64
build_deps:
{snipped because unnecessary}

osmosisd
name: osmosis
server_name: osmosisd
version: 6.0.0
commit: dfe74a35ccc7f8a182b7a9ca943e9bc720ab1f51
build_tags: netgo,ledger
go: go version go1.17.3 linux/amd64
build_deps:
{snipped because unnecessary}

the genesis.json gen_tx  is 10000000

**Comment by ValarDragon** [comment]
> the genesis.json gen_tx is 10000000

What does this mean?

What did you do to get this, this is very unclear

**Comment by ducknessman** [comment]
> > genesis.json gen_tx 是 10000000
> 
> 这是什么意思？
> 
> 你做了什么得到这个，这很不清楚

![image](https://user-images.githubusercontent.com/30320671/148340851-833d2415-39e1-49fd-a2e9-ba60c5fc90a1.png)

**Comment by ducknessman** [comment]
> > the genesis.json gen_tx is 10000000
> 
> What does this mean?
> 
> What did you do to get this, this is very unclear

like cosmos bug:
https://github.com/tendermint/tendermint/issues/5084
i think osmosis is enough
