### ISSUE TITLE
Reuse code for parsing integer slices from string

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#722]
There are several places in the codebase (CLI folders) where we ad-hoc write parsing of a comma-delimited string into `[]uint64` ro `[]sdk.Int`. We should have a single method we call for this, not ad-hoc implemented in line.

The function for `[]uint64` is written here: https://github.com/osmosis-labs/osmosis/blob/834238839bee9126a85aed1f63e3fa36887fbd00/cmd/osmosisd/cmd/balances_from_state_export.go#L343-L358

We should move that function and write one for SDK.Int in 
https://github.com/osmosis-labs/osmosis/blob/main/osmotestutils/cli_helpers.go

We should then switch `balances_from_state_export`, and pool incentives CLI's to use this.
 
This is implemented in-line in the pool-incentives CLI code here: https://github.com/osmosis-labs/osmosis/blob/main/x/pool-incentives/client/cli/tx.go#L49-L69 & https://github.com/osmosis-labs/osmosis/blob/main/x/pool-incentives/client/cli/tx.go#L143-L163

**Comment by akhtariev** [comment]
Looking into this...

**Comment by iButcat** [comment]
Oups sorry, I forgot to say I was on this as well.

**Comment by akhtariev** [comment]
Ok, no worries @iButcat

**Comment by iButcat** [comment]
@ValarDragon, Hi, I think that's good, can you review my PR please ?
