### ISSUE TITLE
x/txfees: Make an ante-handler filter for recognizing High gas txs, and having a min gas price for them

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#724]
Similar to #723 , we should make a mempool filter for high gas fee txs to have non-zero fee requirements. (Configurable by every full node operator)

E.g. if gas fee > $THRESHOLD, require minimum-gas-price to be at least `x`. 

Would require two params in the app.toml config `threshold` and `x`. Though maybe its fine to just hardcode the threshold?

I think its probably worthwhile for governance to consider requiring this in the state machine. (Though that could also be premature with cosmwasm, unclear how cosmwasm contracts will perform gas-wise)

**Comment by ValarDragon** [comment]
I suggest we hard code first $THRESHOLD=1 million gas, and get a config param for `MINIMUM_GAS_PRICE`.

We can probably implement this first with `MINIMUM_GAS_PRICE = .01uosmo`

**Comment by hleb-albau** [comment]
took it
