### ISSUE TITLE
About the RPC apis

### ISSUE THREAD

**Issue by leezijie** [osmosis-labs/osmosis#725]
![image](https://user-images.githubusercontent.com/32590143/148374524-50b15e7e-25e7-43fd-82a6-d640eacbaa19.png)
Why is there no query for account balance in API list

**Comment by czarcas7ic** [comment]
It would be a POST request to abci_query with the path of /cosmos.bank.v1beta1.Query/AllBalances (I think, I will have to double check later)

**Comment by ValarDragon** [comment]
You'll probably have a better time using the REST or GRPC endpoints

**Comment by leezijie** [comment]
> It would be a POST request to abci_query with the path of /cosmos.bank.v1beta1.Query/AllBalances (I think, I will have to double check later)

Thanks

**Comment by leezijie** [comment]
> You'll probably have a better time using the REST or GRPC endpoints
I don't see any arguments to start rest
![image](https://user-images.githubusercontent.com/32590143/148520881-c9fba85f-39d9-4e97-b6e6-dd73d15a6c10.png)

**Comment by czarcas7ic** [comment]
@leezijie if you are running a caught up node it defaults to port 1317. If you want a UI for it go into the app.toml (or might be config.toml) and enable swagger. Then you would go to localhost:1317/swagger/

**Comment by czarcas7ic** [comment]
But if you are looking to just query balanced easily without catching up a node, run a CLI query with the flag --node and put in the address uf a public RPC node like "http://osmo-sync.blockpane.com:26657". Lmk if you need further instructions

**Comment by leezijie** [comment]
> But if you are looking to just query balances easily without catching up a node, run a CLI query with the flag --node and put in the address uf a public RPC node like "http://osmo-sync.blockpane.com:26657". Lmk if you need further instructions

Thanks a lot

**Comment by leezijie** [comment]
> 
Why do I still get an error when I open it
![image](https://user-images.githubusercontent.com/32590143/148630034-7e68ba65-ce7c-480e-af09-dbda9b440edb.png)
![image](https://user-images.githubusercontent.com/32590143/148630048-df00e00e-aa53-4185-8a82-f2b1758ef6c8.png)

**Comment by czarcas7ic** [comment]
Just and a "/" at the end of swagger
Ex:
IP:9885/swagger/

**Comment by leezijie** [comment]
> Just and a "/" at the end of swagger

Thank you, brother. It finally worked😂
