### ISSUE TITLE
[Feature]: disable sqs ingest when syncing

### ISSUE THREAD

**Issue by doggystylez** [osmosis-labs/osmosis#7252]
### Summary

the ingester is ingesting blocks while the node syncs to the chain. however, since it is also overwritten each time there is a new height ingested, it seems wasteful to ingest old heights

### Proposed Feature

disable ingest when node status `catching_up` is true by some other metric

**Comment by p0mvn** [comment]
Thanks for the issue.

This makes sense but it is still useful for testing. As the node is syncing, I might want to have the data to continue ingesting so that I can test routes.

We can have a config value to disable SQS ingest during sync.

**Comment by doggystylez** [comment]
looks like this has been implemented
