### ISSUE TITLE
[Bug]: grpc: received message larger than max (11284320 vs. 10485760)

### ISSUE THREAD

**Issue by lajiww** [osmosis-labs/osmosis#7264]
### What happened?

when i called /blocks/13099039, i got this error `{\"code\":8,\"message\":\"grpc: received message larger than max (12068624 vs. 10485760)\",\"details\":[]}"}`

### Osmosis Version

v21.1.4

### How to reproduce?

call this api /blocks/13099039

**Comment by lajiww** [comment]
<img width="883" alt="image" src="https://github.com/osmosis-labs/osmosis/assets/26184507/8bd725ce-463d-43d1-b135-77d5ce405fdb">

**Comment by shassal** [comment]
I am also getting the same error for block : **13095531**

Error:
{
    "code": 8,
    "message": "grpc: received message larger than max (12992550 vs. 10485760)",
    "details": []
}

**Comment by czarcas7ic** [comment]
Can you confirm if this is still occurring on v22? It should be resolved

**Comment by lajiww** [comment]
Thank you. I test with block 13542815. it is ok
