### ISSUE TITLE
Make an interface for 'simple' CFMM pools (Balancer, StableSwap)

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#727]
We need to make an interface that contains all the swap functions needed for simple Constant Function Market Makers, so its easy to build something that meets the interface, and automatically gets all the needed functionality built out for it.

We should make these swap functions all take swap fee as a parameter, to enable routing applications that want to play with the swap fees in multi-hop.

**Comment by ValarDragon** [comment]
Talked to Joon on a call. The v1 plan for this is to make an interface, that has an underlying pool, and every method in https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/swap.go .

With the exception that these functions should take in swap fee as a parameter

**Comment by mconcat** [comment]
Proposed interface:
```go


// proto struct
type Asset struct {
  TotalShares sdk.Int
  TokenBalances sdk.Coins
}

// pure function for swap operation
type SwapI interface {
  SolveConstantFunctionInvariant(balanceIn, balanceOut sdk.Coin, amount sdk.Dec) (sdk.Dec, error)
}

// pool model interface that exposes swap expression
type ModelI interface {
  Swap() SwapI
}

// proto struct
type Param struct {
  SwapFee sdk.Dec
  ExitFee sdk.Dec
  Governer sdk.AccAddress
}

// proto struct
type Pool struct {
  Model ModelI
  Asset Asset
  Param Param
}
```

Goal: remove weight entirely from the gamm/keeper, and encapsulate it inside (each) pool models. Separate common assets and params from the pool, so the pool models can delegate asset management to the keeper. The pool can still maintain its own state(in case of balancer, weight and smooth weight change), if necessary.

**Comment by ValarDragon** [comment]
Notes from call: 

* Adding ctx to SwapI
* We need a second interface, which has every single derived swap method. Then we make that second interface whats actually used in the gamm code, and we make it so that, anything that implements `SolveConstantFunctionInvariant` automatically implements every constituent swap method.

**Comment by ValarDragon** [comment]
Done
