### ISSUE TITLE
osmosisd 6.0.0 crashes  when run according to 'joining testnet' tutorial

### ISSUE THREAD

**Issue by aftermathdigital** [osmosis-labs/osmosis#728]
I'm experiencing this issue:

https://github.com/osmosis-labs/osmosis/issues/519 

But with testnet.

I'm new to running nodes on cosmos, and tried to follow this tutorial:

https://docs.osmosis.zone/developing/network/join-testnet.html

When it comes time to run the node, I get the following fatal error:

```
Jan 05 20:34:48 TestNode cosmovisor[1395]: panic: unknown field "current_epoch_ended" in types.EpochInfo
Jan 05 20:34:48 TestNode cosmovisor[1395]: goroutine 1 [running]:
Jan 05 20:34:48 TestNode cosmovisor[1395]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x198a680, {0xc00017c380, 0xc000d40e70, 0xc000d40ff0}, {0x25b0390, 0xc039bf80d8})
```

as per issue 519.

As work-arounds I tried using osmosid 6.0.1 after 6.0.0 failed, and tried building cosmovisor from the master branch of cosmos-sdk when v0.42.9 failed.

One thing of note - the following instruction:

```
wget -O - https://mp20.net/snapshots/osmosis-testnet/osmosis-testnet-mp20-latest.tar.xz | xz -d -v | tar xvf -
```
Gave the following output `Cannot write to ‘-’ (Success).`, so I later tried the following incase the issue was with the snapshot:
```
wget https://mp20.net/snapshots/osmosis-testnet/osmosis-testnet-mp20-latest.tar.xz
tar xf ./osmosis-testnet-mp20-latest.tar.xz
cp -r ./home/ ~/.osmosisd/
```
Which I believe is equivelant, but I got the same result either way.

**Comment by czarcas7ic** [comment]
I believe there is an issue with the snapshot that was provided. I will be looking into it, sorry for the inconvenience

**Comment by aftermathdigital** [comment]
There was/is indeed an issue with the snapshot. The directory tree contains all of the paths from the root, when the joining testnet guide assumes the archive only contains the folder you need. It looks like dff has created a new package, but it has a similar error where the directory path isn't what the guide expects.

FWIW, until either the guide is updated, or more likely, the archive contains the path the guide expects, you can work around this issue by extracting the data directory in the archive to ~/.osmisisd/data. I'm closing this as it's not related to the repo, and there exists a workaround for now.

**Comment by chrisbartolo** [comment]
@aftermathdigital  how did you solve? I'm running into the same issue. I've attempted to use the updated commands in the [docs](https://github.com/osmosis-labs/osmosis/commit/f73e43276247b23c09306230b9e7ce56b0d3e979#diff-3063f4b1678e14ba3bab5e78abd33ed0c67ff9bb49728d5f32350c3e7fb04362) but had the same issue. I then wget the tar file, extracted, and moved the contents of the home/.../data/ directory to .osmosisd/data   but still doesn't work and gives me the same error.

**Comment by czarcas7ic** [comment]
@chrisbartolo to my understanding, if you added the `--strip-components=4` flag then there should be no need to move the contents. So it sounds like there was an issue with the commands you typed in

**Comment by aftermathdigital** [comment]
Hey, I fixed this before the advice to use `--strip-components=4` was posted, if you extract the archive you'll notice it contains a subdirectory `data`, copy this directory to `~/.osmosisd/`.

It's possible this is functionally the same as `--strip-components=4` is the same, but I know when the snapshot was re-uploaded it had a different path again, so to be sure you can just manually copy out the data folder.

**Comment by chrisbartolo** [comment]
Thanks. Yeah, checked the folders they were being cleared after export due to an issue in my script it seems. Manually cleaned the data folder, extracted the file again and moved all contents. Booted up well, running.
