### ISSUE TITLE
Framework for running unit tests against a live chain

### ISSUE THREAD

**Issue by UnityChaos** [osmosis-labs/osmosis#729]
Framework to specify a set of "action" / "result" pairs, which allow us to check that post-upgrade behavior is as expected.

Current idea is to write a simple python library which can take simple descriptions of an action (as a set of transactions to submit) and a result (as a set of queries to run and the values we expect to them to return), and the library can then run these transactions and queries, and report any values which don't match expectation.

For example we should be able to specify a create-pool transaction, and then queries to check that the pool exists, has the right parameters, it's module account exists, etc.

**Comment by UnityChaos** [comment]
Moving a bunch of the TODOs from the original tracking issue here, basically just a list of modules for which we will want to have robust tests.

- [ ] Sends
  - [ ] Bech32IBC
- [ ] Paying fees with whitelisted tokens
- [ ] GAMM Functions
  - [ ] Pool Creation
  - [ ] Join / Exit Pool (test all variations)
  - [ ] Swaps (test all variations)
- [ ] Lock creation 
- [ ] Gauge Creation
- [ ] Epoch payouts (not a transaction, but we should test that gauges continue to work through queries)
- [ ] Governance
  - [ ] Proposal, Deposit, Voting
  - [ ] Parameter changes
  - [ ] PoolIncentive changes
- [ ] IBC (more complicated ofc, may require a multi chain testnet environment if we want to test incoming stuff)
  - [ ] channel creation
  - [ ] transfers
  - [ ] channel recovery?

**Comment by ValarDragon** [comment]
Captured by end to end testing work!
