### ISSUE TITLE
[Bug]: "grpc: received message larger than max (12992550 vs. 10485760)"

### ISSUE THREAD

**Issue by shassal** [osmosis-labs/osmosis#7336]
### What happened?

I am  getting the error for block : 13095531

Error:
{
"code": 8,
"message": "grpc: received message larger than max (12992550 vs. 10485760)",
"details": []
}

Attaching screenshot :

![image](https://github.com/osmosis-labs/osmosis/assets/117088401/cd5bccc1-b346-4c93-b316-f1b31696febb)

### Osmosis Version

21.0.0

### How to reproduce?

Try querying the block:
http://10.213.120.122:1317/cosmos/base/tendermint/v1beta1/blocks/13095531

**Comment by PaddyMc** [comment]
Thanks for the issue, this is a setting in the config, please re-open if you feel it's necessary to investigate
