### ISSUE TITLE
Testnet V2

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#734]
Now that we have fixed some of the issues that currently exist in the old testnet, we should now create a new testnet with these fixes. This testnet will be something stable that integrators can test their setups on (we may later create a second testnet to test extreme/likely-to-break-things changes).

- [x] Use testnet script to set up node with peer (6 hr epochs, chain-id osmosis-lab-0)
- [x] At least one relayer set up
- [x] Set up discord faucet with new address
- [x] Chainlayer host for snapshots
- [x] Move validator node to more powerful VM

**Comment by ValarDragon** [comment]
TODO:
- retag v6.2.0 as v6.2.0-testnet
- Delete v6.2.0
- Remove state breaking bech32ibc change, retag v6.2.0 as v6.3.0

**Comment by czarcas7ic** [comment]
@ValarDragon as we discussed previously, upgrading from v6.1.0 to v6.2.0 was state breaking and caused anyone running testnet to corrupt their db. Will the same thing happen then when we revert on v6.3.0? Making a software upgrade prop to go from v6.2.0 to v6.3.0 should mitigate this right?
