### ISSUE TITLE
[Bug]: Bank Module DenomOwners returns not implemented on osmosis

### ISSUE THREAD

**Issue by hindsight9923** [osmosis-labs/osmosis#7353]
### What happened?

When testing #6847 using both gRPC and lcd with an ibc denomination and uosmo both attempts return a "not implemented on osmosis. use an indexer" status. Removing the implementation of this bank module function was not listed in scope of the most recent upgrade.

![image](https://github.com/osmosis-labs/osmosis/assets/71187380/90d9896c-e69f-4eb1-807c-94b11b16e1b9)
url - https://lcd.osmosis.zone/cosmos/bank/v1beta1/denom_owners/uosmo

### Osmosis Version

main

### How to reproduce?

url - https://lcd.osmosis.zone/cosmos/bank/v1beta1/denom_owners/uosmo
Execute gRPC call using denomOwners method on osmosis returns the same "not implemented" results

**Comment by ValarDragon** [comment]
It is not implemented in osmosis and plan to never do it. The design decision to include is a significant flaw imo as it slows down important core logic.
