### ISSUE TITLE
SpotPriceAfter in swap.go is not set

### ISSUE THREAD

**Issue by mconcat** [osmosis-labs/osmosis#736]
https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/keeper/swap.go#L63

**Comment by sunnya97** [comment]
Oh you're right.  Good thing, it looks like nothing uses it rn.  But we should patch this

**Comment by ValarDragon** [comment]
We can probably just remove this. It was only there for some convenience in testing IIRC

**Comment by ValarDragon** [comment]
Argument has been deleted!
