### ISSUE TITLE
bad magic number

### ISSUE THREAD

**Issue by ducknessman** [osmosis-labs/osmosis#739]
If this happens, is it only possible to resync?
second question how to stop the osmosis?

8:33AM INF acknowledged written module=x/ibc/channel packet="{33358 transfer channel-7 transfer channel-113 [123 34 97 109 111 117 110 116 34 58 34 50 52 57 54 48 48 48 48 48 48 48 34 44 34 100 101 110 111 109 34 58 34 117 104 117 97 104 117 97 34 44 34 114 101 99 101 105 118 101 114 34 58 34 111 115 109 111 49 109 57 108 101 56 52 101 107 122 118 112 55 122 121 110 117 48 48 54 117 110 55 106 121 113 121 102 112 113 57 108 116 50 97 121 122 56 99 34 44 34 115 101 110 100 101 114 34 58 34 99 104 105 104 117 97 104 117 97 49 109 57 108 101 56 52 101 107 122 118 112 55 122 121 110 117 48 48 54 117 110 55 106 121 113 121 102 112 113 57 108 116 112 110 54 117 115 103 34 125] 1-2705697 0}"
8:33AM INF executed block height=2705657 module=consensus num_invalid_txs=1 num_valid_txs=22
panic: failed to write batch: leveldb/table: corruption on table-footer (pos=1270613): bad magic number [file=39909301.ldb]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc001afa180)
	github.com/cosmos/cosmos-sdk@v0.44.5/store/iavl/store.go:112 +0x165
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x2948f9, 0xc001f78f30)
	github.com/cosmos/cosmos-sdk@v0.44.5/store/rootmulti/store.go:966 +0x150
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0012ad9a0)
	github.com/cosmos/cosmos-sdk@v0.44.5/store/rootmulti/store.go:380 +0x6f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc001294820)
	github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:307 +0x231
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000921e60)
	github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:264 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x36fab80)
	github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x1}, {0xc001d5c2f8, 0x7}}, {0xc001d5c300, 0x9}, 0x1, 0x2948f9, {{0xc018d149a0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc001d5c2f8, 0x7}}, {0xc001d5c300, 0x9}, 0x1, 0x2948f9, {{0xc018d149a0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x1}, {0xc001d5c2f8, 0x7}}, {0xc001d5c300, 0x9}, 0x1, 0x2948f8, {{0xc001d60060, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x1}, {0xc001d5c2f8, 0x7}}, {0xc001d5c300, 0x9}, 0x1, 0x2948f8, {{0xc001d60060, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01a83de78, {0x2608490, 0xc001252270})
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x1}, {0xc001d5c2f8, 0x7}}, {0xc001d5c300, 0x9}, 0x1, 0x2948f8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00113ea00, {0x25b41b0, 0xc001128f00}, 0xc001f72600, {0x2593e20, 0xc00364ecf0}, 0x0, 0x0, 0xc001f727a0, {0x25daca0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2618dd8, 0xc001133020}, {0x0, 0x0}, {0x25e37d0, 0xc0010e1e20}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:263 +0x7c5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0011cd180, {0xc001222ea0, 0x0, 0x2})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0011cd180, {0xc001222e80, 0x2, 0x2})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000155400)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/osmosis-labs/osmosis/cmd/osmosisd/cmd.Execute(0xc0000001a0)
	github.com/osmosis-labs/osmosis/cmd/osmosisd/cmd/root.go:150 +0xf4
main.main()
	github.com/osmosis-labs/osmosis/cmd/osmosisd/main.go:13 +0x25
exit status 2
8:35AM INF starting ABCI with Tendermint

**Comment by ValarDragon** [comment]
Looks like your database got corrupted, no idea how

**Comment by ValarDragon** [comment]
Closing for now, I believe this was a database corruption that happened at an earlier point, and just got hit. You would have to resync
