### ISSUE TITLE
Use F1 based reward distribution for v1

### ISSUE THREAD

**Issue by Thunnini** [osmosis-labs/osmosis#74]
## Background
We initially delayed the idea of using an F1-based reward distribution mechanism for Osmosis due to concerns on the timeline, but I do think we can adopt the F1-based module without significantly delaying the launch schedule. I believe there are minimal benefits of an epoch-based system over the F1-based system, and only opens up spam attack risk vectors as well as instability in the block times due to the iterations required.

The x/farm module provides a much more sustainable and manageable architecture, and I've made progress on the implementation that I believe it will create no delays for launch. (Refer to the [pool-yield branch](https://github.com/osmosis-labs/osmosis/tree/pool-yield))

Below is an outline of how the current architecture functions.

### Farm Module

- Other modules create a farm
- Farm module doesn't custody the shares, but the rewards are managed(and custodied) by the farm module
- Farm module is created by an external module, but external accounts can provide additional incentives to farms that are already created
- Users can request the farm module for unclaimed rewards

### Pool-Yield (to be changed to Pool Incentive) Module

- x/gamm `afterPoolCreate` hook created.
- Pool-yield module sets the `lockableDurations` at genesis (i.e. 1 week / 2 week / 4 week)
- Pool-yield module creates a farm (according to the number of `lockableDurations`) when the x/gamm `afterPoolCreate` is run
- lockup module
    - `onTokenLocked`  - When the hook runs this, the pool-yield module checks if the locked token is the pool share token. If it is a pool share token, then it will check if the duration matches the  `lockableDurations`. If both conditions are true, it will get the farm and add the farm share according to the locked poolShare amount. (Because the farm module doesn't custody the farm's share, the lockup module custodies the shares.)
    - `onTokenUnlocked`  - This is the opposite process of `onTokenLocked`.
- External accounts can query the x/pool-yield module by specifying the `poolId` and `lockableDurations` and find the `farmId`.
- x/farm module supports external incentives, but the incentives must be added on a regular periodical basis for the duration that the additional incentives is active (i.e. reward added once per day).
- `AddPoolIncentives` proposal can be used to add records. The records consist of farm Id and weight. When the record is added, reward is allocated according to the record's farm ID. The reward amount equals to weight/ totalWeight.
    - To consider the potential the amount of farms/lockable duration increases, the pool-yield module uses an unnormalized weight since normalizing becomes fairly inconvenient when the number of farm becomes large.
- `RemovePoolIncentives` proposal is the opposite of the above proposal
- Because feeCollector manages the entire minted inflation in the same module account as the previous block's transaction fees are handled, and the distribution module take the entire remaining amount that's left in the feeCollector module account, the pool-yield module's begin block must be run between the mint module and the distr module's begin block.
- The pool-yield takes the `mintedDenom` according to the `allocationRatio` from the feeCollector module account then distributes the amount to farms according to the logic described above, then the distribution module uses the remaining amount.
- Issue (TODO):
    - Each module has a specific set of order that it takes its allocated amount in
    - The allocation taken by each designation (i.e. pool incentives, developer DAO, etc) is relative to the remaining amount
    - Therefore, setting the parameter is not very logical:
        - i.e. 100 OSMO minted, 50% liquidity incentives, 20% developer dao)
            1.  liquidity incentives take the 50%
            2. Developer dao parameter must be set to 0.4(40%) because the liquidity incentives already took half, and only half is remaining (20% of total, but relatively 40% of the remaining minted amount)
        - feeCollector account manages the transaction fee and the inflation minted amount in the same account, and can't know which % is the transaction fee. Therefore, the transaction fees are distributed in the same allocationRatio as the minted inflation amount.
    - If the mint module can specify the amount that is to be allocated to pool-yield/developer-dao, then this should be able to be resolved.
        - ACTION ITEM → merge new mint module implementation to Osmosis-Labs repository
    - [ ]  Create `updatePoolIncentives` proposal type.
    - [ ]  Need to create more CLI and gRPC queries
    - [ ]  DeveloperDAO (should be easy lift)

### Discussion

- It'd be good for the lockup module to send tokens that have expired lockup at each block, rather than having each user to manually unlock their tokens. (Because the amount of lock tx that can be included in a block is limited, and the amount of  unlock depends on the amount of lock, this alleviates concerns about spam)
    - Needed because the pool-yield module needs to remove expired lockup LP shares out of actively incentivized farms. and if this isn't done automatically, the pool-yield module needs to take care of this and having the lockup module handle this would simplify the design significantly while also making it easier for users.

**Comment by ValarDragon** [comment]
Closing in favor of #542 existing
