### ISSUE TITLE
Cancel Unstake on leap wallet error 

### ISSUE THREAD

**Issue by zildjian106** [osmosis-labs/osmosis#7406]
'/cosmos.staking.v1beta1.MsgCancelUnbondingDelegation' does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

I get this error trying to cancel an unstake of my coreum. Does not work. Any ideas? Am I doing something wrong?

**Comment by ValarDragon** [comment]
I think this is the wrong repo? You can't stake coreum from osmosis. 

You'd have to check on the coreum projects github, alas I am not familiar with them
