### ISSUE TITLE
Question: Can XCSv2 forwarding be disabled?

### ISSUE THREAD

**Issue by dillu24** [osmosis-labs/osmosis#7433]
I have a question about version 2 of the Crosschain Swaps Contract. Let's say I have chain A and Osmosis. Is it possible to send ATOM from chain A, swap them for JUNO and leave the swapped tokens on Osmosis?

If yes, how would the memo look like?

**Comment by nicolaslara** [comment]
At the moment there isn't as the contract expects to do an IBC transfer at the end. However, an interesting way to get the same behaviour would be to use IBC's [loopback client](https://github.com/cosmos/ibc/tree/main/spec/client/ics-009-loopback-cilent) (aka localhost) to create an ibc channel to the chain itself.

**Comment by PaddyMc** [comment]
Closing this issue as there is a reply to the question!
