### ISSUE TITLE
Fix gas test for lockup module, gamm module

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#748]
Current gas test in the lockup module and gamm module has a hard coded gas amount that we expect it to use, and the test fails if gas used within the test is different from the hard coded has amount.

This structure requires `gas_test.go` to change everytime there's a change in the lockup logic and gamm logic, also having to merge `gas_test.go` everytime we have a PR in gamm module or lockup module.

We can fix this test so that instead of hard coding expected gas, we set a maximum amount of gas that we would allow to be used, and simply test if gas used is below `maximum_amount_gas`

**Comment by ValarDragon** [comment]
Agreed this is really annoying to update. Originally I was thinking we say as long as its within 10% of target, its fine. But tbh, we can adjust that later, doing a maximum amount gas seems more than fine for now imo
