### ISSUE TITLE
Add comment to go.mod to specify which branch of osmosis-labs/cosmos-sdk we are using

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#751]
Right now, it just looks something like:
`github.com/osmosis-labs/cosmos-sdk v0.43.0-rc3.0.20211209072213-711e78b4f6b4`
and this is hard to tell.

Is there some other way to know, that I'm not aware of?

**Comment by faddat** [comment]
no, not really (to my knowledge)

I find that best result comes from schlepping on a tag, but the tags aren't branches and end up doing undesired stuff over time.
