### ISSUE TITLE
Querying total-locked-of-denom pre-V4

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#753]
The following query does not work for any pools created pre V4: ` osmosisd query lockup total-locked-of-denom <denom> [flags]`

Additionally, the CLI flag description says the default for --min-duration is "1d", however this should only take the time in seconds.

**Comment by mattverse** [comment]
Is this a different issue from https://github.com/osmosis-labs/osmosis/issues/670?

**Comment by czarcas7ic** [comment]
You are totally right, forgot I wrote that, thank you for pointing that out!
