### ISSUE TITLE
Querying account's LP shares by lockup duration

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#756]
Currently, there is no way to query an account's locked LP shares by denom and lock length. The closest we can get to this is by querying  ```osmosisd query lockup account-locked-longer-duration-denom [address] [duration] [denom]``` 
This however separates all the outputs by lock-id.

The reason for this (thank you to @ValarDragon for the explanation) is that during launch, there was a gas bug whose mitigation in the front-end involved creating a slight "jitter" in the lock duration by adding slight ms to the end of the duration. 

We can counteract this jitter by either creating a `--jitter` flag that takes into account plus or minus the defined jitter value (I think the jitter only happened in the positive direction but just saying plus or minus in case this is not true) and returns all bonded tokens within the range of the duration +- the defined jitter OR find the max jitter in either direction and simply implement that in the query (i.e if someone queries their locked tokens for denom x for 1 day lockup period, it automatically assumes you want to include any LP shares of 1day +- max jitter).

**Comment by ValarDragon** [comment]
yeah jitter should've only happened in the positive direction.
