### ISSUE TITLE
Rename denormalized weight in x/gamm

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#76]
Not sure whats the better name to be using, but it definitely shouldn't be denormalized. Denormal numbers are something very different in relevant contexts =) https://en.wikipedia.org/wiki/Denormal_number (Essentially an edge case of things with floats)

**Comment by sunnya97** [comment]
This is the terminology that Balancer uses to mean weights that aren't normalized to 1.  Do you a better name to use?

**Comment by ValarDragon** [comment]
I think `Weights` and `NormalizedWeights` is significantly better terminology

**Comment by sunnya97** [comment]
Ok

**Comment by ValarDragon** [comment]
Should be done now
