### ISSUE TITLE
[Epic]: Osmosis <> BTC Phase 1

### ISSUE THREAD

**Issue by keruch** [osmosis-labs/osmosis#7643]
### Summary

This epic outlines the Phase 1 implementation of integrating the Bifrost Protocol with the Osmosis blockchain to enable cross-chain asset swaps.

### Problem Definition

This integration aims to leverage Bifrost's bridging capabilities to connect Osmosis with other blockchains, starting with the BTC network, to facilitate decentralized cross-chain asset transfers.

### Work Breakdown

Scaffold x/bridge module:
- params:
    - Allowed source_chains []string
    - Allowed asset  on source chain []string
- Create MsgMint:
    - Message MsgMint { sender: String, source_chain: String, dst_address: String, asset_name: String, amount: BigInt }
    - Create  func that checks if sender is allowed to execute mint.
    - Check if not Shutdown
    - If allowed mint using token factory a coin with denom: MsgMint.source_chain + MsgMint.asset_name, amount: amount
- Create MsgBurn:
    - Message MsgBurn { sender: String, coin: Coin, dst_address: String}
    - Decompose coin.denom to -> source_chain and asset_name
    - Burn the asset
- Create MsgUpdateSigners
    - Can only be executed by Gov
    - Updates the valset allowed to sign
- Creat MsgShutdown:
    - Can be called by the current signers, same as MsgMint
    - Specifies source_chain to shutdown

**Comment by faddat** [comment]
it is so sensible, I could go blind from looking at this
