### ISSUE TITLE
[Feature]: x/tokenfactory: make mint/burn methods public

### ISSUE THREAD

**Issue by keruch** [osmosis-labs/osmosis#7670]
### Summary

I suggest making x/tokenfactory mint and burn methods public to allow other modules to use these methods through Go interfaces.

### Problem Definition

During implementing the x/bridge module, I noticed that x/tokenfactory doesn't have public mint and burn methods, so I can't call them from my module as usual (through the interface defined in `types/expected_keepers.go`). The only option to call them from the other module is to call the x/tokenfactory MsgServer directly, which seems overcomplicated in this context.

### Proposed Feature

Make mint and burn methods public.

**Comment by ValarDragon** [comment]
This should be done via SDK msgs
