### ISSUE TITLE
[Bug]: Getting invalid denom when querying at specific heights on rest/cosmos/staking/v1beta1/pool

### ISSUE THREAD

**Issue by shieldstar** [osmosis-labs/osmosis#7695]
### What happened?

Getting invalid denom when querying for specific block heights for both our archive nodes.
Seems the issue is between 0 and 12834099, works from 12834100 until today

```
curl -X GET -H "Content-Type: application/json" -H "x-cosmos-block-height: 12834099" http://127.0.0.1:1317/cosmos/staking/v1beta1/pool
{"code":13,"message":"invalid denom: ","details":[]}
```

**While this works:**
```
curl -X GET -H "Content-Type: application/json" -H "x-cosmos-block-height: 12834100" http://127.0.0.1:1317/cosmos/staking/v1beta1/pool
{"pool":{"not_bonded_tokens":"13862733148321","bonded_tokens":"335222421855613"}}
```

Other public nodes handle this well.
```
curl -X GET -H "Content-Type: application/json" -H "x-cosmos-block-height: 12000000" https://osmosis-rest.publicnode.com/cosmos/staking/v1beta1/pool
{"pool":{"not_bonded_tokens":"14159426935369","bonded_tokens":"358219666141631"}}
```

**This is a proposal to do a software upgrade to the v21.0.0 software tag of the Osmosis codebase on block height 12834100.**

### Osmosis Version

v23.0.0,v23.0.3,v23.0.3-iavl-v1

### How to reproduce?

Works with other public nodes, might need a copy of our data to deepdive. Possible corruptions

**Comment by czarcas7ic** [comment]
I noticed this is a duplication of https://github.com/osmosis-labs/osmosis/issues/7675

Going to close this one in favor of the older one
