### ISSUE TITLE
Tracking of LPs rewards (e.g., as an REST API)

### ISSUE THREAD

**Issue by byebb** [osmosis-labs/osmosis#773]
From an [Osmosis Labs README](https://github.com/osmosis-labs/osmosis/blob/df577b7641d6d2cf4ec65702b8b572171cb2e7af/docs/LP%20rewards/proposed_architecture/README.md):

```markdown
## Goal
We want the goal of being able to distribute LP rewards every epoch, 
without the distribution having to iterate over every single user. 
Every pool allows users to bond LP shares, for a time T. 
There are different rewards given to users depending on how long 
they have bonded their LP shares. For instance, if they have bonded for 7 days, 
they get more rewards than if they bond for 1 day. 
Further, we must prevent the chain and users from being exposed to DOS vectors in this process.
```

I need to know my daily historic rewards from the LPs.
I find nowhere on the Osmosis chain activity of how much is added every day at the rewards release time how much OSMO I received from the tokens bonded in the LPs on [app.osmosis.zone](https://app.osmosis.zone/).

Is it somehow possible to get to this information or does it keep appearing mysteriously on everyone's wallet?

Right now, I started tracking my rewards by having a cronjob that starts every day **right before and after** the release time, which is necessary to be able to compute the difference of the OSMO balance. I do not consider this a solution, as I won't be able to get the past OSMO rewards.

For this I am using **cosmostations** API handle `cosmos/bank/v1beta1/balances/`:

[https://lcd-osmosis.cosmostation.io/cosmos/bank/v1beta1/balances/osmo1evdjzy3w9t2yu54w4dhc2cvrlc2fvnptc9nqa2](https://lcd-osmosis.cosmostation.io/cosmos/bank/v1beta1/balances/osmo1evdjzy3w9t2yu54w4dhc2cvrlc2fvnptc9nqa2)

which provides the following JSON result.

```json
{
  "balances": [
    {
      "denom": "gamm/pool/293",
      "amount": "76237770000000000"
    },
    {
      "denom": "gamm/pool/541",
      "amount": "100000000000000000000"
    },
    {
      "denom": "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
      "amount": "14122"
    },
    {
      "denom": "ibc/655BCEF3CDEBE32863FF281DBBE3B06160339E9897DC9C9C9821932A5F8BA6F8",
      "amount": "1500800"
    },
    {
      "denom": "ibc/987C17B11ABC2B20019178ACE62929FE9840202CE79498E29FE8E5CB02B7C0A4",
      "amount": "2000"
    },
    {
      "denom": "ibc/CD942F878C80FBE9DEAB8F8E57F592C7252D06335F193635AF002ACBD69139CC",
      "amount": "149342"
    },
    {
      "denom": "ibc/F3FF7A84A73B62921538642F9797C423D2B4C4ACB3C7FCFFCE7F12AA69909C4B",
      "amount": "2000"
    },
    {
      "denom": "uosmo",
      "amount": "9356797"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "8"
  }
}
```

The best way to get the OSMO Pools rewards is to have a similar handle that extracts the OSMO rewards "magically" from the OSMO chain (I mean the distributed tokens must be recorded somewhere?)

If you have any further information of how we can get to the Pool rewards, that would really help!

EDIT1: Or what would be even better so see the overall historic pool rewards (yearly/monthly/weekly grouping possible) on the osmosis.zone dashboard. So everyone also without coding skills would be able to see the overall rewards.

**Comment by czarcas7ic** [comment]
This is what you are looking for https://github.com/osmotax/osmotax

This gives you the daily osmo received per epoch from rewards for a specified date range.

**Comment by byebb** [comment]
@czarcas7ic Still, it would be nice to have more non-technical version which would not require one to setup an own database for the rewards. But yes, still much better than nothing!

**Comment by czarcas7ic** [comment]
I agree, this is just a short term solution

**Comment by jM9sr1vsH7nOZ8Y5** [comment]
If you are only interested in your daily rewards without an exact timestamp, this endpoint is very useful:
https://api-osmosis-chain.imperator.co/lp/v1/rewards/historical/{address}/{symbol}
