### ISSUE TITLE
How do I specify a memo for IBC transfers? (osmosisd)

### ISSUE THREAD

**Issue by hkey0** [osmosis-labs/osmosis#7813]
Hello, 
How can I set a memo for IBC transfers via `osmosisd ibc-transfer`? I can set a memo for the tx on the osmosis using the `--note` flag, but if I want to set a memo that needs to be relayed to the other network via IBC transfer, how do I do it?

**Comment by PaddyMc** [comment]
Hello @hkey0, 

You should be able to specify using either the `--note` or --memo` field when running the transaction command.

I think for custom memo fields on certain IBC transactions the relayer would add the memo, it's hard to give more info without knowing what you're trying to do. 

Appreciate your interest in Osmosis but these questions are better asked in Discord or Telegram so I'm closing this issue.
