### ISSUE TITLE
[Feature]: make `osmosisd update-asset-list`  infer the mainnet osmosis chain-id if it is not specified

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#7818]
### Summary

In almost all cases, you want this to be `osmosis-1`, lets just infer that instead of making the user provide that.

Write a println explaining were doing this! (E.g. "No chain-id provided, assuming mainnet (osmosis-1)")

### Proposed Feature

^

**Comment by czarcas7ic** [comment]
I looked into this and realized the design is actually suboptimal. We embed the files using go embed. When we update the asset list, that doesn't change the embeded file, and essentially needs to be run in the repo folder and cant just be run against the binary itself. The best way around this imo is to just have a CI job that regularly updates this across releases.

**Comment by czarcas7ic** [comment]
Actually I think I can just save to the config folder, let me check

**Comment by czarcas7ic** [comment]
Fixed in above PR
