### ISSUE TITLE
[Bug]: Query for CL pools Superfluid equivalent staked returns null

### ISSUE THREAD

**Issue by JohnnyWyles** [osmosis-labs/osmosis#7842]
### What happened?

On the endpoint for SFS by Validator denom:
https://lcd.osmosis.zone/osmosis/superfluid/v1beta1/superfluid_delegations_by_validator_denom?validator_address=osmovaloper1qx6kgrla69wmz90tn379p4kaux5prdkucgvfuf&denom=cl/pool/1135

the equivalent staked amount of OSMO returns null.

This should show the equivalent amount of staked OSMO that the liquidity value represents.
Requested in order to display the current proportion of Staked OSMO that is SFS staked on dashboards.

### Osmosis Version

N/A

**Comment by ValarDragon** [comment]
Thanks! Lets figure out getting `equivalent staked amount` fixed. Cc @mattverse @AlpinYukseloglu
