### ISSUE TITLE
CI job to auto replace assetlists at some interval

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#7859]
## Background

The asset lists here https://github.com/osmosis-labs/osmosis/blob/a057d67ae2b0b1f192c935f181ecea91406f3964/cmd/osmosisd/cmd/osmo-test-5-assetlist.json#L1 and here 
https://github.com/osmosis-labs/osmosis/blob/a057d67ae2b0b1f192c935f181ecea91406f3964/cmd/osmosisd/cmd/osmosis-1-assetlist.json#L1 are fairly outdated. They can now be replaced with the update-asset-list command, but we should just replace these at some regular cadence so they are at least relatively not out of date.

Mainnet can be downloaded from "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/osmosis-1/osmosis-1.assetlist.json" and testnet from "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/osmo-test-5/osmo-test-5.assetlist.json"

## Suggested Design

CI job that opens a PR against main at some regular cadence that updates these two lists which get embedded in the binary at time of compilation

**Comment by deividaspetraitis** [comment]
Hey @czarcas7ic, I would be happy to pick up this task!

I think this functionality can be achieved by copying similar existing workflow and creating new one with proper adjustments. For example [update-go-import-paths.yml workflow](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/update-go-import-paths.yml) seems like a good candidate. To run workflow periodically it's possible by leveraging [workflow schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule).
I am not sure yet about strategy determining whether there are any changes between two files but I assume that should be something very simple such as checking checksum.

Please share your thoughts, suggestions if there is anything I should approach differently than described above.

**Comment by czarcas7ic** [comment]
@deividaspetraitis that course of action sounds good to me! Thanks!
