### ISSUE TITLE
Broken Links Job Gets Rate Limited

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#7877]
## Background

See https://github.com/osmosis-labs/osmosis/issues/7752

Every error is from the job getting rate limited

## Suggested Design

Change the job to only query x per second so it no longer gets rate limited

## Acceptance Criteria

Broken link detector job detects broken links instead of getting rate limited

**Comment by deividaspetraitis** [comment]
It seems there is no available option to specify request limiting per interval `i`. One of possible solutions may be running checks more frequently ( let's say every few hours ) and let failed requests to be retried on the next run while succesfull ones can be [cached](https://github.com/lycheeverse/lychee-action?tab=readme-ov-file#utilising-the-cache-feature), let's say for 24h. Feature to cache only successfully checked links was already proposed in https://github.com/lycheeverse/lychee/issues/1400 including a pull request implementing proposed functionality.

**Comment by czarcas7ic** [comment]
Surely there is an option to make the action run longer, but reduce the rate of requests right?

**Comment by czarcas7ic** [comment]
Tbh this doesn't need to run often, just need a general idea of we have broken links
