### ISSUE TITLE
Make CI run on commit to all branches

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#789]
Currently CI only runs on commit to main, and on all PRs. Its not running on all branches, which has led to test failures in release branches.

We need to change the github workflow for CI to run on commits to all branches.

Thanks @mattverse for finding the issue

**Comment by ValarDragon** [comment]
Related: We also need to fix CI in v6.x

**Comment by Aobasi4** [comment]
Hey, I'd love to give this a shot.

**Comment by ValarDragon** [comment]
Awesome thanks! Please submit a PR

**Comment by ValarDragon** [comment]
this is the main CI workflow: https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/test.yml but getting lint would also be good. We may need to cherry-pick any change here to all the branches, can you do your PR to v6.x so we can test with it there, and then I can get it back into main
