### ISSUE TITLE
Perpetual pot for infinite rewards distribution per epoch

### ISSUE THREAD

**Issue by antstalepresh** [osmosis-labs/osmosis#79]
We need a way to keep a perpetual pot. Such a pot should distribute it's full balance every epoch, but the pot shouldn't disappear afterwards. This is what OSMO rewards will probably go into.

Like the weekly minted amount should go into a perpetual pot that distributes for 1 epoch. But new coins will be sent to this same pot every week until governance decides to vote to change it.

**Comment by Thunnini** [comment]
Considering the state of the module so far, I think the pool-yield(pool-incentives) module could use the onFinishDistribution() hook from the incentives module to create a new pot every time. However, this is a bit inefficient.

How long do you think it will take to implement the perpetual pot? If it doesn't take too much time, we can use the perpetual pot for now.

**Comment by antstalepresh** [comment]
Perpetual pot won't take much time, will be done shortly within 1-2 days.

**Comment by sunnya97** [comment]
closed by #44
