### ISSUE TITLE
Configure defaults for IAVL cache size

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#792]
cref https://github.com/osmosis-labs/cosmos-sdk/pull/59

We used to change this directly in the SDK, @marbar3778 got this into a nice config param, so we need to configure that to be what we had before prior to next release!

See: https://github.com/osmosis-labs/osmosis/blob/main/cmd/osmosisd/cmd/root.go#L98-L101 for where we override it

**Comment by faddat** [comment]
https://github.com/osmosis-labs/osmosis/tree/faddat/iavl-cache

I am thinking like a 1gb cache by default, and then allowing that to be overridden w/ a flag like this from terra:

https://github.com/terra-money/core/blob/9ef67cf1c441bc51937d6285e9cdc5f90cd3b3dd/cmd/terrad/root.go#L242

**Comment by marbar3778** [comment]
I think setting it to 100mb is fine for now. Lets not forget this software is meant to be run by many people on smaller machines not only people who can afford bigger machines. Validators should manually configure their node

**Comment by faddat** [comment]
That's the big-big hope sir:

https://twitter.com/gadikian/status/1488244560442519553

Many tiny computers.
