### ISSUE TITLE
Fix test for 6.x branch to either remove or include pool cleanup

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#794]
Currently the 6.x branch test is broken: it's mainly because we're not including gamm generalization v6.x(which we decided not to include in v6.x), but also because pool cleanup(https://github.com/osmosis-labs/osmosis/pull/652) is currently not included in v6.x. 

Our take should be: 
- either remove `pool_test.go` where pool cleanup tests are included
- or include pool cleanup in v6.x 

depending on whether we want pool cleanup in 6.x or not.

**Comment by ValarDragon** [comment]
Aren't the tests broken due to the function rename? Couldn't we just find/replace all of the new function signatures with the old ones?

**Comment by mattverse** [comment]
They are broken due to function rename BUT, 
they are also broken because 6.x includes pool clean up tests(https://github.com/osmosis-labs/osmosis/blob/v6.x/x/gamm/keeper/pool_test.go#L68), but not the actual logic and methods for pool cleanup

**Comment by ValarDragon** [comment]
Ah I see, your right we should revert the pool cleanup change from the v6.x branch entirely!

**Comment by mattverse** [comment]
Closing in favor of https://github.com/osmosis-labs/osmosis/pull/799
