### ISSUE TITLE
Osmosis TokenFactory CLI is missing `MsgSetDenomMetadata`

### ISSUE THREAD

**Issue by MbBrainz** [osmosis-labs/osmosis#7941]
The `MsgSetDenomMetadata` mentioned in [here in the osmosis docs](https://docs.osmosis.zone/osmosis-core/modules/tokenfactory/#setdenommetadata) is missing from the cli.

https://github.com/osmosis-labs/osmosis/blob/fd7c5a6599f12977fe8b3352e312a5a1c679dfb2/x/tokenfactory/client/cli/tx.go#L15

**Comment by czarcas7ic** [comment]
@PaddyMc did you mean to self assign or can he work on it?
