### ISSUE TITLE
[Bug]: TokenFactory CLI --help for `create-denom` is outdated as it includes `(cost osmo though!)`

### ISSUE THREAD

**Issue by MbBrainz** [osmosis-labs/osmosis#7942]
### What happened?

when running `osmosid tx tokenfactory` the help documentation shows `(Costs osmo though!)`, while since may 2023 this is not the case anymore ([PR with on chain proposal link](https://github.com/osmosis-labs/osmosis/pull/4983)).

This confused me as there was no way to add the fee to the transaction and so i set the `--fees` parameter to 100osmo, (which was the price for tokenfactory a while ago). This was (in hindsight) obviously stupid as its the gas fee and it cased me to have the transaction fail, but the gas fee still payed (basically leading me to spend 100Osmo on fee for nothing ([see tx](https://www.mintscan.io/osmosis/tx/ADEC3A14D784B597267F4EB32439330E9984D3901576CFD9E5AE32BAA055139C?height=14661597)).

```
❯ osmosisd tx tokenfactory
tokenfactory transactions subcommands

Usage:
  osmosisd tx tokenfactory [command]

Available Commands:
  burn                Burn tokens from an address. Must have admin authority to do so.
  change-admin        Changes the admin address for a factory-created denom. Must have admin authority to do so.
  create-denom        create a new denom from an account. (Costs osmo though!)
  mint                Mint a denom to an address. Must have admin authority to do so.
  set-beforesend-hook Set a cosmwasm contract to be the beforesend hook for a factory-created denom. Must have admin authority to do so.
  ```
  

### Osmosis Version

23.0.8

### How to reproduce?

install daemon and run `osmosisd tx tokenfactory`

**Comment by deividaspetraitis** [comment]
hey, please correct if I am wrong, as per my understanding by simply removing `(Costs osmo though!)` from the docs should solve the issue, is that right? As per [proposal](https://www.mintscan.io/osmosis/proposals/489)  denom creation fee should be `0`, unless something have changed since them. I would be more than happy to update docs. cc @PaddyMc

**Comment by MbBrainz** [comment]
probably yes

**Comment by deividaspetraitis** [comment]
Opened [PR-8248](https://github.com/osmosis-labs/osmosis/pull/8248). In case there is any additional work that should be reflected in PR, I am looking forward to discuss it and implement.
