### ISSUE TITLE
[Bug]: RawLog is missing

### ISSUE THREAD

**Issue by norbubb** [osmosis-labs/osmosis#8028]
### What happened?

searchTx response missing RawLog

### Osmosis Version

main

**Comment by ValarDragon** [comment]
This is intentional, it is removed in SDK v50 and was backported to our fork. The data was duplicated with events, is there something you need from the logs that you can't parse from the events?

**Comment by shapeshed** [comment]
Also go stung by this, breaking our indexers.

**Comment by czarcas7ic** [comment]
@shapeshed recommending connecting to osmo-test-5, as we update that a week prior to mainnet so integrators will not break in prod.

Will also do a better job of communicating this in the future.
