### ISSUE TITLE
Couldn't connect to any seeds

### ISSUE THREAD

**Issue by ko0f** [osmosis-labs/osmosis#805]
Followed [Install Osmosis](https://docs.osmosis.zone/developing/cli/install.html#minimum-requirements), then [Joining Mainnet](https://docs.osmosis.zone/developing/network/join-mainnet.html#joining-mainnet), forwarded the p2p port in my router, but when running cosmovisor, this is printed to the log repeatedly -

```
Jan 29 19:56:42 box cosmovisor[1175835]: 7:56PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=40
Jan 29 19:56:42 box cosmovisor[1175835]: 7:56PM INF No addresses to dial. Falling back to seeds module=pex
Jan 29 19:56:42 box cosmovisor[1175835]: 7:56PM INF Dialing peer address={"id":"f515a8599b40....b11a668","ip":"...hidden...","port":26659} module=p2p
Jan 29 19:56:43 box cosmovisor[1175835]: 7:56PM ERR Error dialing seed err="dial tcp ...:26659: i/o timeout" module=p2p seed={"id":"f515a8599b40....b11a668","ip":"...","port":26659}
Jan 29 19:56:43 box cosmovisor[1175835]: 7:56PM INF Dialing peer address={"id":"63aba5....60d7561791dca8","ip":"...hidden...","port":2000} module=p2p
Jan 29 19:56:43 box cosmovisor[1175835]: 7:56PM ERR Error dialing seed err="auth failure: conn.ID (21d7539792ee2e0....56ae0cf499e) dialed ID (63aba59a7da51....1791dca8) mismatch" module=p2p seed={"id":"63aba59a7da....561791dca8","ip":"...","port":2000}
Jan 29 19:56:43 box cosmovisor[1175835]: 7:56PM ERR Couldn't connect to any seeds module=p2p
```

Any idea what could be the issue?

**Comment by faddat** [comment]
Our (Notional's) seed's node ID has changed.  Also been working to put a seed in akash.  I'll try to get both into init.go and that should resolve this.  Thanks!

**Comment by ko0f** [comment]
So after file has been updated, checkout and rebuild to fix - or should I also `osmosisd init NODE_NAME`?

**Comment by ko0f** [comment]
Is there any workaround in the meantime, so it would be possible to start a node?

**Comment by faddat** [comment]
https://github.com/osmosis-labs/osmosis/blob/main/networks/peers.md

:)

Sorry about that!  So what I'm going to do here to make sure that others don't run into this issue is put all of Notional's relay nodes in that file.  Very specifically, what happened is a few weeks ago we had a disk failure on the server that's currently in init.go. 

I think it's really important that osmo be very easy to stand up, so I'll get 3-4 nodes in there from here on in.

Cheers!

**Comment by ValarDragon** [comment]
Going to keep this open until it lands in a release or the installer at get.osmosis.zone

**Comment by ko0f** [comment]
In the mean time, a workaround is to edit `~/.osmosis/config/config.toml`, then edit line with `seeds = "..."` to contain peer IDs with some peers from https://github.com/osmosis-labs/osmosis/blob/main/networks/peers.md

After that restart the node.

**Comment by sinarezaei** [comment]
The mentioned workaround is not working for me.

I updated the `seeds = "..."` from the peers.md file, but still I cannot connet to mainnet. The nodes either give timeout or connection refused error.

Also the ufw on ubuntu server is disabled.

I get the following error:
```
Feb 10 17:41:18 Ubuntu cosmovisor[337259]: 5:41PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=40
Feb 10 17:41:18 Ubuntu cosmovisor[337259]: 5:41PM INF No addresses to dial. Falling back to seeds module=pex
Feb 10 17:41:18 Ubuntu cosmovisor[337259]: 5:41PM INF Dialing peer address={"id":"23142ab5d94ad7fa3433a889dcd3c6bb6d5f247d","ip":"95.217.193.163","port":26656} module=p2p
Feb 10 17:41:18 Ubuntu cosmovisor[337259]: 5:41PM ERR Error dialing seed err="dial tcp 95.217.193.163:26656: connect: connection refused" module=p2p seed={"id":"23142ab5d94ad7fa3433a889dcd3c6bb6d5f247d","ip":"95.217.193.163","port":26656}
Feb 10 17:41:18 Ubuntu cosmovisor[337259]: 5:41PM INF Dialing peer address={"id":"83adaa38d1c15450056050fd4c9763fcc7e02e2c","ip":"44.234.84.104","port":26656} module=p2p
Feb 10 17:41:19 Ubuntu cosmovisor[337259]: 5:41PM ERR Error dialing seed err="dial tcp 44.234.84.104:26656: i/o timeout" module=p2p seed={"id":"83adaa38d1c15450056050fd4c9763fcc7e02e2c","ip":"44.234.84.104","port":26656}
Feb 10 17:41:19 Ubuntu cosmovisor[337259]: 5:41PM INF Dialing peer address={"id":"6bcdbcfd5d2c6ba58460f10dbcfde58278212833","ip":"45.77.220.70","port":26656} module=p2p
Feb 10 17:41:20 Ubuntu cosmovisor[337259]: 5:41PM ERR Error dialing seed err="dial tcp 45.77.220.70:26656: i/o timeout" module=p2p seed={"id":"6bcdbcfd5d2c6ba58460f10dbcfde58278212833","ip":"45.77.220.70","port":26656}
Feb 10 17:41:20 Ubuntu cosmovisor[337259]: 5:41PM ERR Couldn't connect to any seeds module=p2p
```



> In the mean time, a workaround is to edit `~/.osmosis/config/config.toml`, then edit line with `seeds = "..."` to contain peer IDs with some peers from https://github.com/osmosis-labs/osmosis/blob/main/networks/peers.md
> 
> After that restart the node.

**Comment by ValarDragon** [comment]
Updated seeds got into a v6 point release. Please do encourage more people to contribute seed nodes to it though!
