### ISSUE TITLE
Gitpod support

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#807]
If we installed the gitpod app on the osmosis org, we could push from gitpod, which is a web-based code editor that makes it easy not to worry about the local state of your git repository.

**Comment by ValarDragon** [comment]
I enabled gitpod for the org I believe, I think it just needs a PR with the config?

**Comment by RishiKumarRay** [comment]
@ValarDragon can you review this config i have written if you approve and help me adding command and port , I think i will be good to raise a PR to close this issue

**Comment by ValarDragon** [comment]
err, would be asking @faddat to review. I don't know much about gitpod

**Comment by RishiKumarRay** [comment]
@ValarDragon actually i wanted if @faddat can approve the above code then i can surely go for a PR :)

**Comment by faddat** [comment]
oh hey!

Sorry guys, thank god for octobox (github notificiations monitor)

This would actually increase my velocity on osmosis a lot, I use gitpod so I don't need to worry about the state of a local repo

**Comment by faddat** [comment]
```
[gitpod@osmosislabs-osmosis-r18vry12jk2 osmosis]$ git push
remote: Permission to osmosis-labs/osmosis.git denied to faddat.
fatal: unable to access 'https://github.com/osmosis-labs/osmosis.git/': The requested URL returned error: 403
```

I don't think permissions are set up yet
