### ISSUE TITLE
TypeScript SDK to interact directly with node RPC

### ISSUE THREAD

**Issue by ko0f** [osmosis-labs/osmosis#815]
I would like to interact with Osmosis node's RPC to perform swaps using Typescript, directly and not through Keplr; ideally a Web3.js equivalent.

There are very few examples of CosmJS, is that the tool to use to interact with Osmosis?

It would be great if a JS/TS example of how to interact with RPC and swap would be added to the docs.

**Comment by ko0f** [comment]
To build Api.ts class that allows RESTful interaction with a node -

- Checkout https://github.com/osmosis-labs/osmosis
- `cd osmosis/tree/main/client/docs`
- `npm run build`
- `cd static/swagger`
- `npx swagger-typescript-api -p ./swagger.yaml -n Api.ts`

This will build an api class based on swagger API definition, copy `Api.ts` to your project and create an instance -
```
const queryClient = new Api({ baseUrl: 'http://localhost:1317' });
```
assuming an osmosisd is running on localhost.

**Comment by faddat** [comment]
utterly fantastic information.

Maybe you can make a pr to docs?  That's just a better way to capture this info.

Thanks!

**Comment by ValarDragon** [comment]
I believe @pyramation built something to this extent between his Telescope and Cosmology work!

**Comment by pyramation** [comment]
> I believe @pyramation built something to this extent between his Telescope and Cosmology work!

Yes! we do have an alpha version. Beta soon and tracking issue here: https://github.com/osmosis-labs/telescope/issues/95

**Comment by ValarDragon** [comment]
Awesome, going to close this issue in favcr of more discussions there!
