### ISSUE TITLE
Make superfluid staking keeper in app.go a pointer receiver

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#820]
https://github.com/osmosis-labs/osmosis/blob/main/app/app.go#L312

This should be pointer receiver `*superfluidkeeper`.

**Comment by stackman27** [comment]
Hi @ValarDragon, very new to this codebase but what is the purpose of `	invCheckPeriod uint` and is this issue more about replacing it with `superfluidKeeper *unit` ?

**Comment by ValarDragon** [comment]
Ah that link reference broke, should've pointed to https://github.com/osmosis-labs/osmosis/blob/e8642532338794d401ba4bcede5aa9d6bc094b9b/app/app.go#L351. Basically make that a pointer, and make things compile. Should be fairly simple -- examples of how to switch to pointers should be around.
