### ISSUE TITLE
Bring over collection module to our sdk fork to unblock layerzero

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#8228]
[https://osmosis-network.slack.com/archives/C06J1CVQ7PE/p1711426238096449](https://osmosis-network.slack.com/archives/C06J1CVQ7PE/p1711426238096449)

LayerZero integrations are blocked on getting this module implemented.

**Comment by PaddyMc** [comment]
Can we close this as we're upgrading to v0.50 which has collections?
