### ISSUE TITLE
No gas_used field in Reply type

### ISSUE THREAD

**Issue by lvn-hasky-dragon** [osmosis-labs/osmosis#8232]
### What happened?

I have been recently working on upgrading cosmwasm-std dependency (to 2.0.2) in our code base. I noticed that Osmosis node doesn't seem to populate the `gas_used` field in the Reply type: https://docs.rs/cosmwasm-std/2.0.2/cosmwasm_std/struct.Reply.html

Because of this, I got the following runtime error in our codebase:

```
    Status { code: Unknown, message: "failed to execute message; message index: 0: dispatch: submessages: reply: Error parsing into type cosmwasm_std::results::submessages::Reply: missing field `gas_used`: execute wasm contract failed", metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "6920"} }, source: None }
```

Related issue in cosmwasm: https://github.com/CosmWasm/cosmwasm/issues/1611

### Osmosis Version

main

**Comment by mattverse** [comment]
This should be closed with us bumping to cosmwasm 2.0
