### ISSUE TITLE
Update README and docs to state what OS / cpu arch are supported

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#825]
Its noted in: https://github.com/CosmWasm/wasmd

```
The supported systems are limited by the dlls created in wasmvm. In particular, we only support MacOS and Linux. However, M1 macs are currently not supported. For linux, the default is to build for glibc, and we cross-compile with CentOS 7 to provide backwards compatibility for glibc 2.12+. This includes all known supported distributions using glibc (CentOS 7 uses 2.12, obsolete Debian Jessy uses 2.19).
As of 0.9.0 we support muslc Linux systems, in particular Alpine linux, which is popular in docker distributions. Note that we do not store the static muslc build in the repo, so you must compile this yourself, and pass -tags muslc. Please look at the Dockerfile for an example of how we build a static Go binary for muslc. (Or just use this Dockerfile for your production setup).
```

Basically M1 macs must use docker. No Windows support. muslc linux systems have extra steps

**Comment by faddat** [comment]
This is solvable

**Comment by ValarDragon** [comment]
My ideal for v7, is getting on-chain end of Febuary, with the big changes being:
* cosmwasm
* Superfluid Staking v1
* Upgrade to SDK v0.45.x
* IAVL speedups by default
* Mempool filters by default

**Comment by faddat** [comment]
In that case I think it is very likely we can support arm, too.

**Comment by czarcas7ic** [comment]
I finished arm mac support for the installer and am like 50 percent finished with windows. Should I completely scrap the windows deal if there will be no concerted effort to keep it supported?

**Comment by ValarDragon** [comment]
Yeah lets scrap windows from the installer. Sorry, cosmwasm obsoleting windows was nothing something I had remembered as a thing when we talked about it
