### ISSUE TITLE
Review Osmosis Docs

### ISSUE THREAD

**Issue by Amosel** [osmosis-labs/osmosis#8271]
Rationale

[https://docs.osmosis.zone/overview/validate/joining-mainnet/](https://docs.osmosis.zone/overview/validate/joining-mainnet/)<br>[https://docs.osmosis.zone/overview/validate/joining-testnet](https://docs.osmosis.zone/overview/validate/joining-testnet)

Update non working URLs:<br><br>[https://github.com/osmosis-labs/docs](https://github.com/osmosis-labs/docs)

DoD

*

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
