### ISSUE TITLE
PoolAccountInvariant stops for-zero-height export

### ISSUE THREAD

**Issue by Pharaon1993** [osmosis-labs/osmosis#833]
When using ```osmosisd export --for-zero-height --height=-1``` the PoolAccountInvariant is trigged causing this error:

```
panic: invariant broken: gamm: pool-account-balance-equals-expected invariant
    gamm pool id 1
    asset coins: 4300015858680ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,22352934610113uosmo
    account coins: 4300015858680ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,1000000000ibc/9989AD6CCA39D1131523DB0617B50F6442081162294B4795E26746292467B525,22352934610113uosmo


    CRITICAL please submit the following transaction:
         tx crisis invariant-broken gamm pool-account-balance-equals-expected
```

This is caused become somebody sent a LIKE coin to Pool #1 as well as Pool #555 (though that pool isn't even checked at this point). This causes the balance of pool's wallets to not match the assets of the pool.

See balance of pool #1 here:
https://www.mintscan.io/osmosis/account/osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t

The transaction still shows too. Same person sent 1 LIKE to pool #555. Not really sure how to address the issue, I can still use pool 555 to swap.

![Screen Shot 2022-02-08 at 8 40 24 PM](https://user-images.githubusercontent.com/84766250/153105631-4a4ff7be-0df1-45bd-b39f-4e7ffccb46fe.png)

Despite having LIKE as an asset pool 555 doesn't include the "extra" LIKE to its assetes balance.

The TX suggested submitting the invariant-broken to halt the chain, but that seemed excessive so I figured I'd post it here first!

**Comment by Pharaon1993** [comment]
@czarcas7ic

**Comment by ValarDragon** [comment]
Yeah, we need to change the invariant. The invariant itself is bad.

Also plz don't submit that crisis tx to the chain, you'll just lose funds
