### ISSUE TITLE
ExportGenesis / InitGenesis in Incentives does not account for LastGaugeID

### ISSUE THREAD

**Issue by UnityChaos** [osmosis-labs/osmosis#834]
Cause of the v6.2.0 testnet halt.

The export/import genesis process is not handling the LastGaugeID variable, which leads to new gauges starting with gauge ID 1 again.

https://github.com/osmosis-labs/osmosis/blob/main/x/incentives/genesis.go

https://github.com/osmosis-labs/osmosis/blob/main/x/incentives/keeper/store.go#L12

**Comment by mattverse** [comment]
tysm @UnityChaos for investigating on this! Assigning myself for fix on top of v6.x branch

**Comment by ValarDragon** [comment]
Because of all the protobuf changes, I can't easily cherry-pick this onto main. Can we make a second PR to main?
