### ISSUE TITLE
The `release` command builds linux binaries with cross compiling warnings.

### ISSUE THREAD

**Issue by dzmitryhil** [osmosis-labs/osmosis#8381]
## Background

For the binaries `release` the osmosis uses the `ghcr.io/goreleaser/goreleaser-cross` image. But when the linux binaries are building the `goreleaser` prints the warnings:

```
warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
 ```
 
Which, in my understanding, means that the binary still has the dependencies on the installed libs.

Here the example of the output with the `--verbose` flag enabled: https://github.com/dzmitryhil/osmosis/actions/runs/9486549776/job/26141144177#step:3:7672

**Comment by niccoloraspa** [comment]
Thanks for flagging and sharing the logs. 
I will take a look

**Comment by niccoloraspa** [comment]
Sorry, it took me some time as GoReleaser was failing to build for other reasons.

I built the last release with GoReleaser: https://github.com/osmosis-labs/osmosis/releases/tag/v25.2.0.

I have checked the logs with the `--verbose` flag and still see the error you mentioned. However, when checking the released binaries with `ldd`, I get:

```bash
ldd ./osmosisd-25.2.0-linux-arm64
	not a dynamic executable
```

and:

```
ldd ./osmosisd-25.2.0-linux-amd64
	not a dynamic executable
```

This makes me less worried about the warning. To be honest, I'm not sure why this is popping up, but it feels related to Go compiling. Seeing the final binary statically linked convinces me that the end result is correct.

I will close the issue for now. Feel free to reopen it if you think this is not the case or you have more evidence.
