### ISSUE TITLE
[Bug]: Running cosmovisor dockerfile

### ISSUE THREAD

**Issue by amitza** [osmosis-labs/osmosis#8438]
### What happened?

Trying to run osmosis image with cosmovisor didn't work

### Osmosis Version

main

### How to reproduce?

1. from the repo root path run: `docker buildx build -f .\Dockerfile.cosmovisor -t osmosis-cosmovisor .`
2. then run: `docker run osmosis-cosmovisor`
3. the error will be: `exec /bin/cosmovisor: no such file or directory`

docker version:
```
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:54 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.31.1 (153621)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by amitza** [comment]
A potential fix will be to change the base and runner images. I've tested it and it worked, willing to make a PR :)

**Comment by czarcas7ic** [comment]
I think you are good to make the pr unless @alessandrolomanto or @niccoloraspa have any objections, thanks!

**Comment by pablin-10** [comment]
This just exploded in my face :) 

@amitza thanks for reporting!

I think the proposed fix is what you were addressing, let me know
