### ISSUE TITLE
Benchmark impact on SQS ingest time & validate integration test quality on edgenet

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#8441]
Due to Cosmos SDK streaming API changes in v25, we had to make a change that might affect block processing time.

Currently, we have the following dashboard that tracks it:

[https://grafana.osmosis.zone/d/ca8b8a4a-b38c-444c-b74a-4c8150b2b4e1/sqs-osmosis-zone?orgId=1&viewPanel=153](https://grafana.osmosis.zone/d/ca8b8a4a-b38c-444c-b74a-4c8150b2b4e1/sqs-osmosis-zone?orgId=1&viewPanel=153)

<img src="https://uploads.linear.app/0fd52314-016d-4816-853a-95bc296e31fc/f4387cbc-1604-4a70-be10-b811287a22e0/a5ce2e02-2de2-45f7-9719-c82abcbc39e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmZDUyMzE0LTAxNmQtNDgxNi04NTNhLTk1YmMyOTZlMzFmYy9mNDM4N2NiYy0xNjA0LTRhNzAtYmUxMC1iODExMjg3YTIyZTAvYTVjZTJlMDItMmRlMi00NWY3LTk3MTktYzgyYWJjYmMzOWU0IiwiaWF0IjoxNzE5MjUxOTUyLCJleHAiOjMzMjg5ODExOTUyfQ.HcvYr6g4c9ziE6ESudLC--omV0zrCsOmxYba0L94qfU " alt="image.png" width="2574" height="1278" />

## Test Plan

* Create an edgenet with in-place testnet
* Find out a way to track the metric from the above dashboard. Options:
  * Manually querying prometheus metrics
  * Hooking up to Grafana dashboard
  * Prints measuring time (probably easiest but please make sure it is put in the right place (see how the current metric is tracked)
* Run SQS integration tests manually against SQS connected to this testnet and see if any meaningful failures (could point out to a deeper problem)
  * This is how to run: [https://github.com/osmosis-labs/sqs/blob/706a2137ef166044c16a914d908215354dfc9348/Makefile#L185](https://github.com/osmosis-labs/sqs/blob/706a2137ef166044c16a914d908215354dfc9348/Makefile#L185)
  * Please change this to `http://localhost:9092` before running [https://github.com/osmosis-labs/sqs/blob/706a2137ef166044c16a914d908215354dfc9348/tests/sqs_service.py#L3](https://github.com/osmosis-labs/sqs/blob/706a2137ef166044c16a914d908215354dfc9348/tests/sqs_service.py#L3)

## DoD

* Block processing time either did not increased or 10% upper bound
* Raise concerns if any found
* Discuss a plan forward for v26 upgrade with @roman @paddy if meaningful concerns found

**Comment by czarcas7ic** [comment]
Repo created to assist in load testing https://github.com/czarcas7ic/pool-swap-load-testing

**Comment by czarcas7ic** [comment]
Leaving info here for Roman since I am unavailable next week:<br><br>adam-temp-sqs-ingest-testing is a DO node running v26 osmosis (post in place testnet and all). <br><br>This node also has `pool-swap-load-testing` cloned in root, and in `tmux a -t 0` the validator is running<br><br>The only thing that should need to be done at this point is getting sqs to run, and then building and running the binary within pool-swap-load-testing.
