### ISSUE TITLE
Superfluid, remove hardcoded 14 days in many places

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#849]
There are several places where we hardcode times like 14 days or 21 days. We need these to refer to single variables. Its fine for right now for it to just be a constant in types.go until we get time to change it, but it should be consitent & well named variables.

Heres an example: https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/keeper/slash.go#L49

**Comment by mattverse** [comment]
Closed per https://github.com/osmosis-labs/osmosis/pull/880
