### ISSUE TITLE
[Bug]: AppTemplate accessing unexisting field

### ISSUE THREAD

**Issue by najeal** [osmosis-labs/osmosis#8491]
### What happened?

A bug has been introduced in #8487 PR.

New content has been added to the AppTemplate:
```# The topic id to use for publishing pair metadata
pair-topic-id = "{{ .IndexerConfig.PairTopicId }}"
```

When executing the template we provide an Indexer Config with the field `PairTopicID` instead of `PairTopicId`.

The template execution fails and panic because of this.

### Osmosis Version

main

### How to reproduce?

example: run `osmosisd q --help`

**Comment by PaddyMc** [comment]
Ty for submitting an issue and also fixing it, reviewing the PR now
