### ISSUE TITLE
Localrelayer test does not work

### ISSUE THREAD

**Issue by RedBird96** [osmosis-labs/osmosis#8520]
## Background
When I try to run localrelayer with docker-composer it does not work.
It shows some errors:
`ERROR ThreadId(01) foreign_client.create{client=localosmosis-b->localosmosis-a:07-tendermint-0}: failed to create client: error raised while creating client for chain localosmosis-b: failed when building client state: error in underlying transport when making gRPC call: transport error`

How could I fix this error?

Thanks

**Comment by faza** [comment]
Even i faced the same issue. You can add the following in [setup_chain.sh](https://github.com/osmosis-labs/osmosis/blob/main/tests/localrelayer/scripts/setup_chain.sh) to fix it.

```bash
dasel put -t string -f $CONFIG_FOLDER/app.toml -v "0.0.0.0:9090" '.grpc.address'
```
