### ISSUE TITLE
Update swagger endpoints

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis#854]
* Modify `v1beta1` to `v1`
* Modify ibc endpoints from `applications` to `apps`

**Comment by ValarDragon** [comment]
Hrmm, not sure how much this is in our control. As far as I understand, the `v1beta1` is inherited from the SDK proto definitions.

Ditto for ibc endpoints and IBC's definitions.

We can either push for changes in this repos, or update ourselves. The latter may make the composability of tools story harder.

Would be happy if someone else knows better though, the swagger  / GRPC endpoints is generally out of my realm of expertise.
