### ISSUE TITLE
x/lockup: Combine lockups for same duration and jitter amount

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#867]
We want to move to a model where a user has one lockup for a given (denom, duration) pair, can do partial unlocks against that, and superfluid stake sub-components of that. This simplifies logic massively for all front-ends and data integrators.

Issues / constituents that we would like to resolve for this:
- Prior to the v5 upgrade, all locks for the same (owner, denom, duration) triplet created a new lock. (They now add to the existing lockup)
- Until the v4 upgrade, all locks from the front-end would add a jitter to the duration. This is due to a gas bug that existed on-chain. We should combine all the locks from this jitter.
- Reset all accumulation stores (its incorrect for locks created pre the v4 upgrade)

## Achieving this

We want to combine all lockups for the same (owner, denom, duration) triplet, and for durations that are off by a 1hr jitter. So for every (owner, denom) pair, we want to combine all the lockups between 24hrs - 25hrs into a single 24 hr lockup, all the lockups between 7d, 7d1hr into a single 7d lockup, and all the lockups between 14d, 14d1hr into a single 14d lockup

**Comment by mconcat** [comment]
If we will be only using single lock per (user, denom, duration), should we add a reverse reference from that triple to the lock ID?

**Comment by ValarDragon** [comment]
That should already exist via the lockRefs I believe
