### ISSUE TITLE
[Bug]: x/gamm .proto file isn't compiled

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#8692]
### What happened?

The x/gamm .proto file from #8600 hasn't been built.  But when it is built, there is a cycular dependency issue in `main`

### Osmosis Version

main

### How to reproduce?

Make a pull request that triggers the generate protofiles ci job.  You'll then get:

* https://github.com/osmosis-labs/osmosis/pull/8689/commits/a74379b8d8798fb360e62edb22b60536b513af6e

and then a dependency cycle issue is triggered.

### Solution?

I'm not fully sure but maybe we exclude that .proto from building?

* https://github.com/osmosis-labs/osmosis/pull/8689

**Comment by PaddyMc** [comment]
Thanks for the issue, we reverted that PR => https://github.com/osmosis-labs/osmosis/pull/8710

:bow:
