### ISSUE TITLE
[Bug]: Pulling osmosis error

### ISSUE THREAD

**Issue by golnar-mh** [osmosis-labs/osmosis#8716]
### What happened?

I am trying to pull osmosis package with this command:

`go get github.com/osmosis-labs/osmosis/v25`

into my cosmos based blockchain but facing bellow issue:

`go: github.com/gogo/protobuf@v1.3.3: reading github.com/gogo/protobuf/go.mod at revision v1.3.3: unknown revision v1.3.3`

Will you please guide me how I can import osmosis in my app.go?
How I can install/download the osmosis package in my go.mod?

Thank you so much

### Osmosis Version

main, 25

**Comment by PaddyMc** [comment]
Here you need to add the replace directives that are present in the osmosis go.mod, see => https://github.com/osmosis-labs/osmosis/blob/main/go.mod#L273-L302
