### ISSUE TITLE
After the latest version is upgraded,Node running error

### ISSUE THREAD

**Issue by leezijie** [osmosis-labs/osmosis#877]
When I upgraded to 6.3.0, the node ran incorrectly today. The log reports this error after startup:
INF starting ABCI with Tendermint
Error: failed to initialize database: resource temporarily unavailable

command：/data/blockdata/osmo/osmosisd-6.3.0 start --home /data/blockdata/osmo/node

**Comment by leezijie** [comment]
> This usually means that osmosis is already running in that location.
> 
> Maybe check to see if your systemd unit or screen session is still going?
> 
> can also use top/htop/btop to check on things.

Yes, I got up. The midnight node stopped by itself. This is the error log. Do you know why.
![image](https://user-images.githubusercontent.com/32590143/154186750-1a4d6b2d-2ac5-4328-ba5b-6f574c51e481.png)

**Comment by faddat** [comment]
I don't know why but the same thing happened to me yesterday. 

I recommend that you either:

* Restore from snapshot
* State sync and start running again

Hope it helps!

**Comment by leezijie** [comment]
> I don't know why but the same thing happened to me yesterday.
> 
> I recommend that you either:
> 
> * Restore from snapshot
> * State sync and start running again
> 
> Hope it helps!

Thanks a lot
