### ISSUE TITLE
ibc/core/channel/v1beta1/channels/* endpoints give 'Not Implemented'

### ISSUE THREAD

**Issue by gebrits** [osmosis-labs/osmosis#881]
Testing out various endpoints based on the swagger docs. 
Most queries work well, but the `ibc/core/channel/v1beta1/channels/*` collection of endpoints, `GET http://h3:1317/ibc/core/channel/v1beta1/channels/` being one of them return: 

```
{
    "code": 12,
    "message": "Not Implemented",
    "details": []
}
```

Do I have to change something in my app.toml / config.toml or something to enable these, or are they really not supported? 

Use case: I want to try and find all the connected channels from other chains from/to Osmosis

**Comment by ko0f** [comment]
The swagger has many errors, wrongs addresses, etc.

**Comment by gebrits** [comment]
So, are there any ibc-related endpoints that do work?
