### ISSUE TITLE
all cosmos/tx/v1beta1/txs endpoint only return one transaction

### ISSUE THREAD

**Issue by JavHou** [osmosis-labs/osmosis#8835]
Hi team, 

   I need help. all cosmos/tx/v1beta1/txs endpoint in my osmo node can only return one transaction in `tx_response` whatever how many transaction the block have. But it's transaction can query in official client.

network : mainnet
version: 27.0.0

eg.  24284277 block should be 3 transcation, but it return only 1  from api.

```
curl "localhost:1317/cosmos/tx/v1beta1/txs?query=tx.height=24284277" -s  | jq '.tx_responses | length'

cosmovisor/current/bin/osmosisd query  --home /data/osmo-blockchain/ tx --type=hash -height 24284277 B3956B161744348151979952E7130A11C59090339404BCA37C161E3761B1B963
cosmovisor/current/bin/osmosisd query  --home /data/osmo-blockchain/ tx --type=hash --height 24284277 B3956B161744348151979952E7130A11C59090339404BCA37C161E3761B1B963
cosmovisor/current/bin/osmosisd query  --home /data/osmo-blockchain/ tx --type=hash --height 24284277 E253F3308A434C06C933EB0A3A2CE71840BB0C363C294AD1BB1A6A5F5115FBE0
```

**Comment by PaddyMc** [comment]
Thanks for creating an issue.

this is fixed in v27.0.1, please update your node to that version
