### ISSUE TITLE
Write a contributing.md for Osmosis

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#891]
We should write a contributing.md for Osmosis that explains the branching structure, how we use the SDK fork, and how to make / test updates to SDK branches. I've recently explained it 1-1 a couple times, and folks have been left on their own to self-discover what we're doing. Would be ideal to document this.

Things to include:
* How to update dependencies for builds: https://github.com/osmosis-labs/osmosis/issues/456#issuecomment-908860526
* How to change things in vendor for local builds / local testing
* Branch structure of releases on v7, v6, v4, and using the mergify labels for backporting.
* How to build proto files. (`rm -rf vendor/ && make build-reproducible` once docker is installed)

**Comment by faddat** [comment]
@ValarDragon why use make build-reproducible when building proto files?

I've always used make proto-gen -- is make build-reproducible preferable somehow?

**Comment by ValarDragon** [comment]
nope it should've been `make proto-all`, I just typed the wrong thing haha

**Comment by jblbit** [comment]
+1, I'm a newbie trying to contribute to osmosis (also not so familiar with golang) but hardly find any docs to website. Having really a hard time to get started. Something like https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/flinkdev/building/  should be extremely helpful

@ValarDragon any update/progress on this? Happy to partner with you and write this up as I ramp up

**Comment by xBalbinus** [comment]
#1399 Adding this as a place to track work on this issue

**Comment by xBalbinus** [comment]
Closing, as #1399 has been merged.
