### ISSUE TITLE
Synthetic lockups, change the synthetic denom prefixing to always have "synthetic"

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#898]
Currently synthetic denoms have the name decided by the synthetic denom creator. They should all have a common prefix, e.g. "synthetic", and this should be a constant defined in the lockup types folder.

This will clean up a lot of odd constants, and improve the abstractions of various parts of the code.

**Comment by ValarDragon** [comment]
Biggest example: https://github.com/osmosis-labs/osmosis/blob/main/x/lockup/types/lock.go#L45-L54

This can probably be fixed by CTRL+F'ing "superbonding" and "superunbonding" around the code. (And requiring that a synthetic lockup for a denom must start with the prefix, and a native lockup cannot start with the prefix)

We can likely improve the API safety post-v7

**Comment by mattverse** [comment]
What's the reason synthetic lock denoms(what now starts with "superbonding" "superunbonding") have to start with same common prefixes?

Also, are you suggesting that we should make synthetic denoms to "common prefix + superbonding/superunbonding + denom + valAddr")?

**Comment by ValarDragon** [comment]
I think we shouldn't worry about this for now, come back later and delete synthetic lockups for a better lock restriction structure during lockup refactor epics.
