### ISSUE TITLE
WIP: Rename concepts and variable names for superfluid

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#900]
We should go back to some of the names or variables for superfluid so that we ensure everything is named after the right term and is clear. Further discussion is needed for how we want to rename, listing below some of the variables that should change. 

- [ ] EpochOsmoEquivalentTWAP -> EpochOsmoEquivalentSpotPrice
- [ ] SuperfluidAsset -> SuperfluidRegisteredAsset

**Comment by ValarDragon** [comment]
Perhaps OsmoEquivalentPrice? These should be stored in a way that is indexed by epoch.

**Comment by mattverse** [comment]
Oh, are you saying that we should also change logic on how and what we store in state machine for twap?

**Comment by mattverse** [comment]
Srry if im missing something, can you explain why? At every end of epoch, we distribute the rewards and use the most recent  price for updating the delegations, why do we need old twap(or price) for the old epochs?

**Comment by ValarDragon** [comment]
I believe we did this!
