### ISSUE TITLE
Move claims module to its own repository

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#903]
The claims module is a useful module.

Its outlived its need for Osmosis due to the clawback having ended, so we should move it out of repository.

However, we should move the module to its own repository, so other projects can copy, maintain and use it as they need. (The over-arching concern being that if we delete the code from `main`, people will stop using it when its really helpful for their project. IIRC Stargaze re-uses aspects of this module)

**Comment by faddat** [comment]
github.com/osmosis-labs/claims

I'll remove it from v7 tomorrow

**Comment by ValarDragon** [comment]
Thanks!!
